In [1]:
import pandas as pd
import time 
import requests
import json
#other requirements: sqlalchemy, psycopg2
#time & json are in python base 
#install requirements: pip install pandas requests sqlalchemy psycopg2-binary plyer

In [2]:
from DatabaseCreator import DatabaseCreator

In [3]:
start=time.perf_counter()

In [4]:
current_season = 20262027

In [5]:
from Load_Merge_FPL_Data import FPLDataManager
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    manager = FPLDataManager(current_season=current_season)
    df_all_seasons = manager.load_all_seasons()
    print(f"\nTotal records: {len(df_all_seasons)}")

    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    # fpl_engine = db_creator.get_engine_for("fpl_data_analysis") # not needed as we created the engine in the constructor of DatabaseCreator

    #Add a new staging table & data into the database
    playergw = df_all_seasons[['player_name_id','element','value','season','event','fixture','total_points',
                            'minutes','goals_scored','assists','team_elo','opp_team_elo','team_attack_elo', 
                            'opp_team_attack_elo', 'team_defence_elo', 'opp_team_defence_elo','position','bonus','bps',
                            'clean_sheets','goals_conceded','was_home','expected_assists','expected_goal_involvements',
                            'expected_goals','expected_goals_conceded','starts',
                            'cbi','defensive_contribution','recoveries','tackles',
                            'saves','team_name','opp_team_name']]

    table_name = "playergw"
    db_creator.create_staging_table_then_insert_data(table_name, data=playergw)
    playergwdf = db_creator.table_to_df(table_name=table_name)
    print("Final playergw dataframe loaded into psql!")
    print(playergwdf.info())

Loading season 2024-25 (manual merge)...
Loading season 2025-26...
Loading season 20262027 (API)...
Loaded data for element_id: 1/668
Loaded data for element_id: 2/668
Loaded data for element_id: 3/668
Loaded data for element_id: 4/668
Loaded data for element_id: 5/668
Loaded data for element_id: 6/668
Loaded data for element_id: 7/668
Loaded data for element_id: 8/668
Loaded data for element_id: 9/668
Loaded data for element_id: 10/668
Loaded data for element_id: 11/668
Loaded data for element_id: 12/668
Loaded data for element_id: 13/668
Loaded data for element_id: 14/668
Loaded data for element_id: 15/668
Loaded data for element_id: 16/668
Loaded data for element_id: 17/668
Loaded data for element_id: 18/668
Loaded data for element_id: 19/668
Loaded data for element_id: 20/668
Loaded data for element_id: 21/668
Loaded data for element_id: 22/668
Loaded data for element_id: 23/668
Loaded data for element_id: 24/668
Loaded data for element_id: 25/668
Loaded data for element_id: 26/668
Loaded data for element_id: 27/668
Loaded data for element_id: 28/668
Loaded data for element_id: 29/668
Loaded data for element_id: 30/668
Loaded data for element_id: 31/668
Loaded data for element_id: 32/668
Loaded data for element_id: 33/668
Loaded data for element_id: 34/668
Loaded data for element_id: 35/668
Loaded data for element_id: 36/668
Loaded data for element_id: 37/668
Loaded data for element_id: 38/668
Loaded data for element_id: 39/668
Loaded data for element_id: 40/668
Loaded data for element_id: 41/668
Loaded data for element_id: 42/668
Loaded data for element_id: 43/668
Loaded data for element_id: 44/668
Loaded data for element_id: 45/668
Loaded data for element_id: 46/668
Loaded data for element_id: 47/668
Loaded data for element_id: 48/668
Loaded data for element_id: 49/668
Loaded data for element_id: 50/668
Loaded data for element_id: 51/668
Loaded data for element_id: 52/668
Loaded data for element_id: 53/668
Loaded data for element_id: 54/668
Loaded data for element_id: 55/668
Loaded data for element_id: 56/668
Loaded data for element_id: 57/668
Loaded data for element_id: 58/668
Loaded data for element_id: 59/668
Loaded data for element_id: 60/668
Loaded data for element_id: 61/668
Loaded data for element_id: 62/668
Loaded data for element_id: 63/668
Loaded data for element_id: 64/668
Loaded data for element_id: 65/668
Loaded data for element_id: 66/668
Loaded data for element_id: 67/668
Loaded data for element_id: 68/668
Loaded data for element_id: 69/668
Loaded data for element_id: 70/668
Loaded data for element_id: 71/668
Loaded data for element_id: 72/668
Loaded data for element_id: 73/668
Loaded data for element_id: 74/668
Loaded data for element_id: 75/668
Loaded data for element_id: 76/668
Loaded data for element_id: 77/668
Loaded data for element_id: 78/668
Loaded data for element_id: 79/668
Loaded data for element_id: 80/668
Loaded data for element_id: 81/668
Loaded data for element_id: 82/668
Loaded data for element_id: 83/668
Loaded data for element_id: 84/668
Loaded data for element_id: 85/668
Loaded data for element_id: 86/668
Loaded data for element_id: 87/668
Loaded data for element_id: 88/668
Loaded data for element_id: 89/668
Loaded data for element_id: 90/668
Loaded data for element_id: 91/668
Loaded data for element_id: 92/668
Loaded data for element_id: 93/668
Loaded data for element_id: 94/668
Loaded data for element_id: 95/668
Loaded data for element_id: 96/668
Loaded data for element_id: 97/668
Loaded data for element_id: 98/668
Loaded data for element_id: 99/668
Loaded data for element_id: 100/668
Loaded data for element_id: 101/668
Loaded data for element_id: 102/668
Loaded data for element_id: 103/668
Loaded data for element_id: 104/668
Loaded data for element_id: 105/668
Loaded data for element_id: 106/668
Loaded data for element_id: 107/668
Loaded data for element_id: 108/668
Loaded data for element_id: 109/668
Loaded data for element_id: 110/668
Loaded data for element_id: 111/668
Loaded data for element_id: 112/668
Loaded data for element_id: 113/668
Loaded data for element_id: 114/668
Loaded data for element_id: 115/668
Loaded data for element_id: 116/668
Loaded data for element_id: 117/668
Loaded data for element_id: 118/668
Loaded data for element_id: 119/668
Loaded data for element_id: 120/668
Loaded data for element_id: 121/668
Loaded data for element_id: 122/668
Loaded data for element_id: 123/668
Loaded data for element_id: 124/668
Loaded data for element_id: 125/668
Loaded data for element_id: 126/668
Loaded data for element_id: 127/668
Loaded data for element_id: 128/668
Loaded data for element_id: 129/668
Loaded data for element_id: 130/668
Loaded data for element_id: 131/668
Loaded data for element_id: 132/668
Loaded data for element_id: 133/668
Loaded data for element_id: 134/668
Loaded data for element_id: 135/668
Loaded data for element_id: 136/668
Loaded data for element_id: 137/668
Loaded data for element_id: 138/668
Loaded data for element_id: 139/668
Loaded data for element_id: 140/668
Loaded data for element_id: 141/668
Loaded data for element_id: 142/668
Loaded data for element_id: 143/668
Loaded data for element_id: 144/668
Loaded data for element_id: 145/668
Loaded data for element_id: 146/668
Loaded data for element_id: 147/668
Loaded data for element_id: 148/668
Loaded data for element_id: 149/668
Loaded data for element_id: 150/668
Loaded data for element_id: 151/668
Loaded data for element_id: 152/668
Loaded data for element_id: 153/668
Loaded data for element_id: 154/668
Loaded data for element_id: 155/668
Loaded data for element_id: 156/668
Loaded data for element_id: 157/668
Loaded data for element_id: 158/668
Loaded data for element_id: 159/668
Loaded data for element_id: 160/668
Loaded data for element_id: 161/668
Loaded data for element_id: 162/668
Loaded data for element_id: 163/668
Loaded data for element_id: 164/668
Loaded data for element_id: 165/668
Loaded data for element_id: 166/668
Loaded data for element_id: 167/668
Loaded data for element_id: 168/668
Loaded data for element_id: 169/668
Loaded data for element_id: 170/668
Loaded data for element_id: 171/668
Loaded data for element_id: 172/668
Loaded data for element_id: 173/668
Loaded data for element_id: 174/668
Loaded data for element_id: 175/668
Loaded data for element_id: 176/668
Loaded data for element_id: 177/668
Loaded data for element_id: 178/668
Loaded data for element_id: 179/668
Loaded data for element_id: 180/668
Loaded data for element_id: 181/668
Loaded data for element_id: 182/668
Loaded data for element_id: 183/668
Loaded data for element_id: 184/668
Loaded data for element_id: 185/668
Loaded data for element_id: 186/668
Loaded data for element_id: 187/668
Loaded data for element_id: 188/668
Loaded data for element_id: 189/668
Loaded data for element_id: 190/668
Loaded data for element_id: 191/668
Loaded data for element_id: 192/668
Loaded data for element_id: 193/668
Loaded data for element_id: 194/668
Loaded data for element_id: 195/668
Loaded data for element_id: 196/668
Loaded data for element_id: 197/668
Loaded data for element_id: 198/668
Loaded data for element_id: 199/668
Loaded data for element_id: 200/668
Loaded data for element_id: 201/668
Loaded data for element_id: 202/668
Loaded data for element_id: 203/668
Loaded data for element_id: 204/668
Loaded data for element_id: 205/668
Loaded data for element_id: 206/668
Loaded data for element_id: 207/668
Loaded data for element_id: 208/668
Loaded data for element_id: 209/668
Loaded data for element_id: 210/668
Loaded data for element_id: 211/668
Loaded data for element_id: 212/668
Loaded data for element_id: 213/668
Loaded data for element_id: 214/668
Loaded data for element_id: 215/668
Loaded data for element_id: 216/668
Loaded data for element_id: 217/668
Loaded data for element_id: 218/668
Loaded data for element_id: 219/668
Loaded data for element_id: 220/668
Loaded data for element_id: 221/668
Loaded data for element_id: 222/668
Loaded data for element_id: 223/668
Loaded data for element_id: 224/668
Loaded data for element_id: 225/668
Loaded data for element_id: 226/668
Loaded data for element_id: 227/668
Loaded data for element_id: 228/668
Loaded data for element_id: 229/668
Loaded data for element_id: 230/668
Loaded data for element_id: 231/668
Loaded data for element_id: 232/668
Loaded data for element_id: 233/668
Loaded data for element_id: 234/668
Loaded data for element_id: 235/668
Loaded data for element_id: 236/668
Loaded data for element_id: 237/668
Loaded data for element_id: 238/668
Loaded data for element_id: 239/668
Loaded data for element_id: 240/668
Loaded data for element_id: 241/668
Loaded data for element_id: 242/668
Loaded data for element_id: 243/668
Loaded data for element_id: 244/668
Loaded data for element_id: 245/668
Loaded data for element_id: 246/668
Loaded data for element_id: 247/668
Loaded data for element_id: 248/668
Loaded data for element_id: 249/668
Loaded data for element_id: 250/668
Loaded data for element_id: 251/668
Loaded data for element_id: 252/668
Loaded data for element_id: 253/668
Loaded data for element_id: 254/668
Loaded data for element_id: 255/668
Loaded data for element_id: 256/668
Loaded data for element_id: 257/668
Loaded data for element_id: 258/668
Loaded data for element_id: 259/668
Loaded data for element_id: 260/668
Loaded data for element_id: 261/668
Loaded data for element_id: 262/668
Loaded data for element_id: 263/668
Loaded data for element_id: 264/668
Loaded data for element_id: 265/668
Loaded data for element_id: 266/668
Loaded data for element_id: 267/668
Loaded data for element_id: 268/668
Loaded data for element_id: 269/668
Loaded data for element_id: 270/668
Loaded data for element_id: 271/668
Loaded data for element_id: 272/668
Loaded data for element_id: 273/668
Loaded data for element_id: 274/668
Loaded data for element_id: 275/668
Loaded data for element_id: 276/668
Loaded data for element_id: 277/668
Loaded data for element_id: 278/668
Loaded data for element_id: 279/668
Loaded data for element_id: 280/668
Loaded data for element_id: 281/668
Loaded data for element_id: 282/668
Loaded data for element_id: 283/668
Loaded data for element_id: 284/668
Loaded data for element_id: 285/668
Loaded data for element_id: 286/668
Loaded data for element_id: 287/668
Loaded data for element_id: 288/668
Loaded data for element_id: 289/668
Loaded data for element_id: 290/668
Loaded data for element_id: 291/668
Loaded data for element_id: 292/668
Loaded data for element_id: 293/668
Loaded data for element_id: 294/668
Loaded data for element_id: 295/668
Loaded data for element_id: 296/668
Loaded data for element_id: 297/668
Loaded data for element_id: 298/668
Loaded data for element_id: 299/668
Loaded data for element_id: 300/668
Loaded data for element_id: 301/668
Loaded data for element_id: 302/668
Loaded data for element_id: 303/668
Loaded data for element_id: 304/668
Loaded data for element_id: 305/668
Loaded data for element_id: 306/668
Loaded data for element_id: 307/668
Loaded data for element_id: 308/668
Loaded data for element_id: 309/668
Loaded data for element_id: 310/668
Loaded data for element_id: 311/668
Loaded data for element_id: 312/668
Loaded data for element_id: 313/668
Loaded data for element_id: 314/668
Loaded data for element_id: 315/668
Loaded data for element_id: 316/668
Loaded data for element_id: 317/668
Loaded data for element_id: 318/668
Loaded data for element_id: 319/668
Loaded data for element_id: 320/668
Loaded data for element_id: 321/668
Loaded data for element_id: 322/668
Loaded data for element_id: 323/668
Loaded data for element_id: 324/668
Loaded data for element_id: 325/668
Loaded data for element_id: 326/668
Loaded data for element_id: 327/668
Loaded data for element_id: 328/668
Loaded data for element_id: 329/668
Loaded data for element_id: 330/668
Loaded data for element_id: 331/668
Loaded data for element_id: 332/668
Loaded data for element_id: 333/668
Loaded data for element_id: 334/668
Loaded data for element_id: 335/668
Loaded data for element_id: 336/668
Loaded data for element_id: 337/668
Loaded data for element_id: 338/668
Loaded data for element_id: 339/668
Loaded data for element_id: 340/668
Loaded data for element_id: 341/668
Loaded data for element_id: 342/668
Loaded data for element_id: 343/668
Loaded data for element_id: 344/668
Loaded data for element_id: 345/668
Loaded data for element_id: 346/668
Loaded data for element_id: 347/668
Loaded data for element_id: 348/668
Loaded data for element_id: 349/668
Loaded data for element_id: 350/668
Loaded data for element_id: 351/668
Loaded data for element_id: 352/668
Loaded data for element_id: 353/668
Loaded data for element_id: 354/668
Loaded data for element_id: 355/668
Loaded data for element_id: 356/668
Loaded data for element_id: 357/668
Loaded data for element_id: 358/668
Loaded data for element_id: 359/668
Loaded data for element_id: 360/668
Loaded data for element_id: 361/668
Loaded data for element_id: 362/668
Loaded data for element_id: 363/668
Loaded data for element_id: 364/668
Loaded data for element_id: 365/668
Loaded data for element_id: 366/668
Loaded data for element_id: 367/668
Loaded data for element_id: 368/668
Loaded data for element_id: 369/668
Loaded data for element_id: 370/668
Loaded data for element_id: 371/668
Loaded data for element_id: 372/668
Loaded data for element_id: 373/668
Loaded data for element_id: 374/668
Loaded data for element_id: 375/668
Loaded data for element_id: 376/668
Loaded data for element_id: 377/668
Loaded data for element_id: 378/668
Loaded data for element_id: 379/668
Loaded data for element_id: 380/668
Loaded data for element_id: 381/668
Loaded data for element_id: 382/668
Loaded data for element_id: 383/668
Loaded data for element_id: 384/668
Loaded data for element_id: 385/668
Loaded data for element_id: 386/668
Loaded data for element_id: 387/668
Loaded data for element_id: 388/668
Loaded data for element_id: 389/668
Loaded data for element_id: 390/668
Loaded data for element_id: 391/668
Loaded data for element_id: 392/668
Loaded data for element_id: 393/668
Loaded data for element_id: 394/668
Loaded data for element_id: 395/668
Loaded data for element_id: 396/668
Loaded data for element_id: 397/668
Loaded data for element_id: 398/668
Loaded data for element_id: 399/668
Loaded data for element_id: 400/668
Loaded data for element_id: 401/668
Loaded data for element_id: 402/668
Loaded data for element_id: 403/668
Loaded data for element_id: 404/668
Loaded data for element_id: 405/668
Loaded data for element_id: 406/668
Loaded data for element_id: 407/668
Loaded data for element_id: 408/668
Loaded data for element_id: 409/668
Loaded data for element_id: 410/668
Loaded data for element_id: 411/668
Loaded data for element_id: 412/668
Loaded data for element_id: 413/668
Loaded data for element_id: 414/668
Loaded data for element_id: 415/668
Loaded data for element_id: 416/668
Loaded data for element_id: 417/668
Loaded data for element_id: 418/668
Loaded data for element_id: 419/668
Loaded data for element_id: 420/668
Loaded data for element_id: 421/668
Loaded data for element_id: 422/668
Loaded data for element_id: 423/668
Loaded data for element_id: 424/668
Loaded data for element_id: 425/668
Loaded data for element_id: 426/668
Loaded data for element_id: 427/668
Loaded data for element_id: 428/668
Loaded data for element_id: 429/668
Loaded data for element_id: 430/668
Loaded data for element_id: 431/668
Loaded data for element_id: 432/668
Loaded data for element_id: 433/668
Loaded data for element_id: 434/668
Loaded data for element_id: 435/668
Loaded data for element_id: 436/668
Loaded data for element_id: 437/668
Loaded data for element_id: 438/668
Loaded data for element_id: 439/668
Loaded data for element_id: 440/668
Loaded data for element_id: 441/668
Loaded data for element_id: 442/668
Loaded data for element_id: 443/668
Loaded data for element_id: 444/668
Loaded data for element_id: 445/668
Loaded data for element_id: 446/668
Loaded data for element_id: 447/668
Loaded data for element_id: 448/668
Loaded data for element_id: 449/668
Loaded data for element_id: 450/668
Loaded data for element_id: 451/668
Loaded data for element_id: 452/668
Loaded data for element_id: 453/668
Loaded data for element_id: 454/668
Loaded data for element_id: 455/668
Loaded data for element_id: 456/668
Loaded data for element_id: 457/668
Loaded data for element_id: 458/668
Loaded data for element_id: 459/668
Loaded data for element_id: 460/668
Loaded data for element_id: 461/668
Loaded data for element_id: 462/668
Loaded data for element_id: 463/668
Loaded data for element_id: 464/668
Loaded data for element_id: 465/668
Loaded data for element_id: 466/668
Loaded data for element_id: 467/668
Loaded data for element_id: 468/668
Loaded data for element_id: 469/668
Loaded data for element_id: 470/668
Loaded data for element_id: 471/668
Loaded data for element_id: 472/668
Loaded data for element_id: 473/668
Loaded data for element_id: 474/668
Loaded data for element_id: 475/668
Loaded data for element_id: 476/668
Loaded data for element_id: 477/668
Loaded data for element_id: 478/668
Loaded data for element_id: 479/668
Loaded data for element_id: 480/668
Loaded data for element_id: 481/668
Loaded data for element_id: 482/668
Loaded data for element_id: 483/668
Loaded data for element_id: 484/668
Loaded data for element_id: 485/668
Loaded data for element_id: 486/668
Loaded data for element_id: 487/668
Loaded data for element_id: 488/668
Loaded data for element_id: 489/668
Loaded data for element_id: 490/668
Loaded data for element_id: 491/668
Loaded data for element_id: 492/668
Loaded data for element_id: 493/668
Loaded data for element_id: 494/668
Loaded data for element_id: 495/668
Loaded data for element_id: 496/668
Loaded data for element_id: 497/668
Loaded data for element_id: 498/668
Loaded data for element_id: 499/668
Loaded data for element_id: 500/668
Loaded data for element_id: 501/668
Loaded data for element_id: 502/668
Loaded data for element_id: 503/668
Loaded data for element_id: 504/668
Loaded data for element_id: 505/668
Loaded data for element_id: 506/668
Loaded data for element_id: 507/668
Loaded data for element_id: 508/668
Loaded data for element_id: 509/668
Loaded data for element_id: 510/668
Loaded data for element_id: 511/668
Loaded data for element_id: 512/668
Loaded data for element_id: 513/668
Loaded data for element_id: 514/668
Loaded data for element_id: 515/668
Loaded data for element_id: 516/668
Loaded data for element_id: 517/668
Loaded data for element_id: 518/668
Loaded data for element_id: 519/668
Loaded data for element_id: 520/668
Loaded data for element_id: 521/668
Loaded data for element_id: 522/668
Loaded data for element_id: 523/668
Loaded data for element_id: 524/668
Loaded data for element_id: 525/668
Loaded data for element_id: 526/668
Loaded data for element_id: 527/668
Loaded data for element_id: 528/668
Loaded data for element_id: 529/668
Loaded data for element_id: 530/668
Loaded data for element_id: 531/668
Loaded data for element_id: 532/668
Loaded data for element_id: 533/668
Loaded data for element_id: 534/668
Loaded data for element_id: 535/668
Loaded data for element_id: 536/668
Loaded data for element_id: 537/668
Loaded data for element_id: 538/668
Loaded data for element_id: 539/668
Loaded data for element_id: 540/668
Loaded data for element_id: 541/668
Loaded data for element_id: 542/668
Loaded data for element_id: 543/668
Loaded data for element_id: 544/668
Loaded data for element_id: 545/668
Loaded data for element_id: 546/668
Loaded data for element_id: 547/668
Loaded data for element_id: 548/668
Loaded data for element_id: 549/668
Loaded data for element_id: 550/668
Loaded data for element_id: 551/668
Loaded data for element_id: 552/668
Loaded data for element_id: 553/668
Loaded data for element_id: 554/668
Loaded data for element_id: 555/668

In [6]:
filtered = playergwdf['player_name_id'] == "Jordan Pickford"
playergwdf[filtered].pivot_table(index='season',values='expected_goals',aggfunc='count')

            expected_goals
season
20182019.0               0
20192020.0               0
20202021.0               0
20212022.0               0
20222023.0              38
20232024.0              38
20242025.0              38
20252026.0              38
20262027.0               7

In [7]:
filtered = (playergwdf['event']==1) & (playergwdf['player_name_id']=="Jordan Pickford")
playergwdf[filtered].sort_values(by='season')

,player_name_id,element,value,season,event,fixture,total_points,minutes,goals_scored,assists,...,expected_goals,expected_goals_conceded,starts,cbi,defensive_contribution,recoveries,tackles,saves,team_name,opp_team_name
267,Jordan Pickford,154.0,50.0,20182019.0,1.0,10.0,1.0,90.0,0.0,0.0,...,NaN,NaN,NaN,1.0,NaN,9.0,0.0,2.0,Everton,Wolves
22074,Jordan Pickford,148.0,55.0,20192020.0,1.0,4.0,7.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Everton,Crystal Palace
44514,Jordan Pickford,157.0,50.0,20202021.0,1.0,4.0,8.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Everton,Spurs
69153,Jordan Pickford,170.0,50.0,20212022.0,1.0,4.0,2.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Everton,Southampton
94516,Jordan Pickford,182.0,45.0,20222023.0,1.0,3.0,3.0,90.0,0.0,0.0,...,0.0,0.00,0.0,NaN,NaN,NaN,NaN,5.0,Everton,Chelsea
121105,Jordan Pickford,263.0,45.0,20232024.0,1.0,5.0,2.0,90.0,0.0,0.0,...,0.0,1.50,1.0,NaN,NaN,NaN,NaN,1.0,Everton,Fulham
150785,Jordan Pickford,235.0,50.0,20242025.0,1.0,3.0,1.0,90.0,0.0,0.0,...,0.0,1.43,1.0,NaN,NaN,NaN,NaN,2.0,Everton,Brighton
178678,Jordan Pickford,287.0,55.0,20252026.0,1.0,10.0,2.0,90.0,0.0,0.0,...,0.0,2.07,1.0,3.0,0.0,8.0,0.0,2.0,Everton,Leeds
209504,Jordan Pickford,226.0,55.0,20262027.0,1.0,3.0,7.0,90.0,0.0,0.0,...,0.0,1.96,1.0,0.0,0.0,12.0,0.0,4.0,Everton,Crystal Palace

In [8]:
playergwdf.to_csv(r'data/playergwdf.csv',index=False)

# Get FPL Player current status

In [9]:
#Create DF from FPL API Request
headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
get=requests.get("https://fantasy.premierleague.com/api/bootstrap-static/", headers=headers, timeout=5)
data=json.loads(get.text)

#player_raw = Summary stats for each player for the current season
cols=list(data['elements'][0].keys())
player_raw = pd.DataFrame(data['elements'], columns = cols)
player = player_raw[['web_name','id','now_cost','status','news','chance_of_playing_next_round','chance_of_playing_this_round']]
player['season']=current_season
player['datetime_now'] = pd.to_datetime('now')

table_name = "player_status"
if __name__ == "__main__":
    # Replace the existing table entirely on each run
    db_creator.execute_sql(f"DROP TABLE IF EXISTS {table_name};")
    db_creator.create_staging_table_then_insert_data(table_name, data=player)
    player_status = db_creator.table_to_df(table_name=table_name)

In [10]:
view = db_creator.run_sql("""SELECT
player_name_id, 
SUM(expected_goals) AS total_expected_goals FROM playergw
WHERE season = 20262027
    AND expected_goals IS NOT NULL
    GROUP BY player_name_id
ORDER BY total_expected_goals DESC
LIMIT 10
                            """)
view

                     player_name_id  total_expected_goals
0                    Erling Haaland                  5.67
1                     Thierno Barry                  4.70
2                      Bryan Mbeumo                  3.94
3                    Alexander Isak                  3.87
4  Igor Thiago Nascimento Rodrigues                  3.69
5                       Bukayo Saka                  3.63
6             Dominic Calvert-Lewin                  3.60
7                    Gonzalo García                  3.46
8     João Pedro Junqueira de Jesus                  3.05
9                       Yoane Wissa                  2.97

In [11]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
#Finished in 11.91 minute(s)

Finished in 5.09 minute(s)

In [12]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)