In [2]:
import pandas as pd
import time 
import requests
import json
#other requirements: sqlalchemy, pscycopg2

In [3]:
from DatabaseCreator import DatabaseCreator

In [4]:
start=time.perf_counter()

In [5]:
current_season = 20262027

In [6]:
# #get fixtures before changing code
# from Load_Merge_FPL_Data import FPLDataManager 
# import CJDH_local_settings

# #Run Database Creator
# if __name__ == "__main__":
#     manager = FPLDataManager()
#     #FPLAPIDataFetcher: id max = 5 - remove after testing
#     fpl_data, fixtures_with_elo, merged, current_year_players_allfixtures = manager.load_2025_26_season_from_api()

# current_year_players_allfixtures.head()

In [7]:
from Load_Merge_FPL_Data import FPLDataManager
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    manager = FPLDataManager(current_season=current_season)
    df_all_seasons = manager.load_all_seasons()
    print(f"\nTotal records: {len(df_all_seasons)}")

    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

    #Add a new staging table & data into the database
    playergw = df_all_seasons[['player_name_id','element','value','season','event','fixture','total_points',
                            'minutes','goals_scored','assists','team_elo','opp_team_elo','position','bonus','bps',
                            'clean_sheets','goals_conceded','was_home','expected_assists','expected_goal_involvements',
                            'expected_goals','expected_goals_conceded','starts',
                            'cbi','defensive_contribution','recoveries','tackles',
                            'saves','team_name','opp_team_name']]

    table_name = "playergw"
    db_creator.create_staging_table_then_insert_data(table_name, data=playergw)
    playergwdf = db_creator.table_to_df(table_name=table_name)
    print("Final playergw dataframe loaded into psql!")
    print(playergwdf.info())

Loading season 20182019...
Loading season 20192020...
Loading season 20202021...
Loading season 20212022...
Loading season 20222023...
Loading season 20232024...
Loading season 20252026...
Loading season 2024-25 (manual merge)...
Loading season 20262027 (API)...
Loaded data for element_id: 1/584
Loaded data for element_id: 2/584
Loaded data for element_id: 3/584
Loaded data for element_id: 4/584
Loaded data for element_id: 5/584
Loaded data for element_id: 6/584
Loaded data for element_id: 7/584
Loaded data for element_id: 8/584
Loaded data for element_id: 9/584
Loaded data for element_id: 10/584
Loaded data for element_id: 11/584
Loaded data for element_id: 12/584
Loaded data for element_id: 13/584
Loaded data for element_id: 14/584
Loaded data for element_id: 15/584
Loaded data for element_id: 16/584
Loaded data for element_id: 17/584
Loaded data for element_id: 18/584
Loaded data for element_id: 19/584
Loaded data for element_id: 20/584
Loaded data for element_id: 21/584
Loaded data for element_id: 22/584
Loaded data for element_id: 23/584
Loaded data for element_id: 24/584
Loaded data for element_id: 25/584
Loaded data for element_id: 26/584
Loaded data for element_id: 27/584
Loaded data for element_id: 28/584
Loaded data for element_id: 29/584
Loaded data for element_id: 30/584
Loaded data for element_id: 31/584
Loaded data for element_id: 32/584
Loaded data for element_id: 33/584
Loaded data for element_id: 34/584
Loaded data for element_id: 35/584
Loaded data for element_id: 36/584
Loaded data for element_id: 37/584
Loaded data for element_id: 38/584
Loaded data for element_id: 39/584
Loaded data for element_id: 40/584
Loaded data for element_id: 41/584
Loaded data for element_id: 42/584
Loaded data for element_id: 43/584
Loaded data for element_id: 44/584
Loaded data for element_id: 45/584
Loaded data for element_id: 46/584
Loaded data for element_id: 47/584
Loaded data for element_id: 48/584
Loaded data for element_id: 49/584
Loaded data for element_id: 50/584
Loaded data for element_id: 51/584
Loaded data for element_id: 52/584
Loaded data for element_id: 53/584
Loaded data for element_id: 54/584
Loaded data for element_id: 55/584
Loaded data for element_id: 56/584
Loaded data for element_id: 57/584
Loaded data for element_id: 58/584
Loaded data for element_id: 59/584
Loaded data for element_id: 60/584
Loaded data for element_id: 61/584
Loaded data for element_id: 62/584
Loaded data for element_id: 63/584
Loaded data for element_id: 64/584
Loaded data for element_id: 65/584
Loaded data for element_id: 66/584
Loaded data for element_id: 67/584
Loaded data for element_id: 68/584
Loaded data for element_id: 69/584
Loaded data for element_id: 70/584
Loaded data for element_id: 71/584
Loaded data for element_id: 72/584
Loaded data for element_id: 73/584
Loaded data for element_id: 74/584
Loaded data for element_id: 75/584
Loaded data for element_id: 76/584
Loaded data for element_id: 77/584
Loaded data for element_id: 78/584
Loaded data for element_id: 79/584
Loaded data for element_id: 80/584
Loaded data for element_id: 81/584
Loaded data for element_id: 82/584
Loaded data for element_id: 83/584
Loaded data for element_id: 84/584
Loaded data for element_id: 85/584
Loaded data for element_id: 86/584
Loaded data for element_id: 87/584
Loaded data for element_id: 88/584
Loaded data for element_id: 89/584
Loaded data for element_id: 90/584
Loaded data for element_id: 91/584
Loaded data for element_id: 92/584
Loaded data for element_id: 93/584
Loaded data for element_id: 94/584
Loaded data for element_id: 95/584
Loaded data for element_id: 96/584
Loaded data for element_id: 97/584
Loaded data for element_id: 98/584
Loaded data for element_id: 99/584
Loaded data for element_id: 100/584
Loaded data for element_id: 101/584
Loaded data for element_id: 102/584
Loaded data for element_id: 103/584
Loaded data for element_id: 104/584
Loaded data for element_id: 105/584
Loaded data for element_id: 106/584
Loaded data for element_id: 107/584
Loaded data for element_id: 108/584
Loaded data for element_id: 109/584
Loaded data for element_id: 110/584
Loaded data for element_id: 111/584
Loaded data for element_id: 112/584
Loaded data for element_id: 113/584
Loaded data for element_id: 114/584
Loaded data for element_id: 115/584
Loaded data for element_id: 116/584
Loaded data for element_id: 117/584
Loaded data for element_id: 118/584
Loaded data for element_id: 119/584
Loaded data for element_id: 120/584
Loaded data for element_id: 121/584
Loaded data for element_id: 122/584
Loaded data for element_id: 123/584
Loaded data for element_id: 124/584
Loaded data for element_id: 125/584
Loaded data for element_id: 126/584
Loaded data for element_id: 127/584
Loaded data for element_id: 128/584
Loaded data for element_id: 129/584
Loaded data for element_id: 130/584
Loaded data for element_id: 131/584
Loaded data for element_id: 132/584
Loaded data for element_id: 133/584
Loaded data for element_id: 134/584
Loaded data for element_id: 135/584
Loaded data for element_id: 136/584
Loaded data for element_id: 137/584
Loaded data for element_id: 138/584
Loaded data for element_id: 139/584
Loaded data for element_id: 140/584
Loaded data for element_id: 141/584
Loaded data for element_id: 142/584
Loaded data for element_id: 143/584
Loaded data for element_id: 144/584
Loaded data for element_id: 145/584
Loaded data for element_id: 146/584
Loaded data for element_id: 147/584
Loaded data for element_id: 148/584
Loaded data for element_id: 149/584
Loaded data for element_id: 150/584
Loaded data for element_id: 151/584
Loaded data for element_id: 152/584
Loaded data for element_id: 153/584
Loaded data for element_id: 154/584
Loaded data for element_id: 155/584
Loaded data for element_id: 156/584
Loaded data for element_id: 157/584
Loaded data for element_id: 158/584
Loaded data for element_id: 159/584
Loaded data for element_id: 160/584
Loaded data for element_id: 161/584
Loaded data for element_id: 162/584
Loaded data for element_id: 163/584
Loaded data for element_id: 164/584
Loaded data for element_id: 165/584
Loaded data for element_id: 166/584
Loaded data for element_id: 167/584
Loaded data for element_id: 168/584
Loaded data for element_id: 169/584
Loaded data for element_id: 170/584
Loaded data for element_id: 171/584
Loaded data for element_id: 172/584
Loaded data for element_id: 173/584
Loaded data for element_id: 174/584
Loaded data for element_id: 175/584
Loaded data for element_id: 176/584
Loaded data for element_id: 177/584
Loaded data for element_id: 178/584
Loaded data for element_id: 179/584
Loaded data for element_id: 180/584
Loaded data for element_id: 181/584
Loaded data for element_id: 182/584
Loaded data for element_id: 183/584
Loaded data for element_id: 184/584
Loaded data for element_id: 185/584
Loaded data for element_id: 186/584
Loaded data for element_id: 187/584
Loaded data for element_id: 188/584
Loaded data for element_id: 189/584
Loaded data for element_id: 190/584
Loaded data for element_id: 191/584
Loaded data for element_id: 192/584
Loaded data for element_id: 193/584
Loaded data for element_id: 194/584
Loaded data for element_id: 195/584
Loaded data for element_id: 196/584
Loaded data for element_id: 197/584
Loaded data for element_id: 198/584
Loaded data for element_id: 199/584
Loaded data for element_id: 200/584
Loaded data for element_id: 201/584
Loaded data for element_id: 202/584
Loaded data for element_id: 203/584
Loaded data for element_id: 204/584
Loaded data for element_id: 205/584
Loaded data for element_id: 206/584
Loaded data for element_id: 207/584
Loaded data for element_id: 208/584
Loaded data for element_id: 209/584
Loaded data for element_id: 210/584
Loaded data for element_id: 211/584
Loaded data for element_id: 212/584
Loaded data for element_id: 213/584
Loaded data for element_id: 214/584
Loaded data for element_id: 215/584
Loaded data for element_id: 216/584
Loaded data for element_id: 217/584
Loaded data for element_id: 218/584
Loaded data for element_id: 219/584
Loaded data for element_id: 220/584
Loaded data for element_id: 221/584
Loaded data for element_id: 222/584
Loaded data for element_id: 223/584
Loaded data for element_id: 224/584
Loaded data for element_id: 225/584
Loaded data for element_id: 226/584
Loaded data for element_id: 227/584
Loaded data for element_id: 228/584
Loaded data for element_id: 229/584
Loaded data for element_id: 230/584
Loaded data for element_id: 231/584
Loaded data for element_id: 232/584
Loaded data for element_id: 233/584
Loaded data for element_id: 234/584
Loaded data for element_id: 235/584
Loaded data for element_id: 236/584
Loaded data for element_id: 237/584
Loaded data for element_id: 238/584
Loaded data for element_id: 239/584
Loaded data for element_id: 240/584
Loaded data for element_id: 241/584
Loaded data for element_id: 242/584
Loaded data for element_id: 243/584
Loaded data for element_id: 244/584
Loaded data for element_id: 245/584
Loaded data for element_id: 246/584
Loaded data for element_id: 247/584
Loaded data for element_id: 248/584
Loaded data for element_id: 249/584
Loaded data for element_id: 250/584
Loaded data for element_id: 251/584
Loaded data for element_id: 252/584
Loaded data for element_id: 253/584
Loaded data for element_id: 254/584
Loaded data for element_id: 255/584
Loaded data for element_id: 256/584
Loaded data for element_id: 257/584
Loaded data for element_id: 258/584
Loaded data for element_id: 259/584
Loaded data for element_id: 260/584
Loaded data for element_id: 261/584
Loaded data for element_id: 262/584
Loaded data for element_id: 263/584
Loaded data for element_id: 264/584
Loaded data for element_id: 265/584
Loaded data for element_id: 266/584
Loaded data for element_id: 267/584
Loaded data for element_id: 268/584
Loaded data for element_id: 269/584
Loaded data for element_id: 270/584
Loaded data for element_id: 271/584
Loaded data for element_id: 272/584
Loaded data for element_id: 273/584
Loaded data for element_id: 274/584
Loaded data for element_id: 275/584
Loaded data for element_id: 276/584
Loaded data for element_id: 277/584
Loaded data for element_id: 278/584
Loaded data for element_id: 279/584
Loaded data for element_id: 280/584
Loaded data for element_id: 281/584
Loaded data for element_id: 282/584
Loaded data for element_id: 283/584
Loaded data for element_id: 284/584
Loaded data for element_id: 285/584
Loaded data for element_id: 286/584
Loaded data for element_id: 287/584
Loaded data for element_id: 288/584
Loaded data for element_id: 289/584
Loaded data for element_id: 290/584
Loaded data for element_id: 291/584
Loaded data for element_id: 292/584
Loaded data for element_id: 293/584
Loaded data for element_id: 294/584
Loaded data for element_id: 295/584
Loaded data for element_id: 296/584
Loaded data for element_id: 297/584
Loaded data for element_id: 298/584
Loaded data for element_id: 299/584
Loaded data for element_id: 300/584
Loaded data for element_id: 301/584
Loaded data for element_id: 302/584
Loaded data for element_id: 303/584
Loaded data for element_id: 304/584
Loaded data for element_id: 305/584
Loaded data for element_id: 306/584
Loaded data for element_id: 307/584
Loaded data for element_id: 308/584
Loaded data for element_id: 309/584
Loaded data for element_id: 310/584
Loaded data for element_id: 311/584
Loaded data for element_id: 312/584
Loaded data for element_id: 313/584
Loaded data for element_id: 314/584
Loaded data for element_id: 315/584
Loaded data for element_id: 316/584
Loaded data for element_id: 317/584
Loaded data for element_id: 318/584
Loaded data for element_id: 319/584
Loaded data for element_id: 320/584
Loaded data for element_id: 321/584
Loaded data for element_id: 322/584
Loaded data for element_id: 323/584
Loaded data for element_id: 324/584
Loaded data for element_id: 325/584
Loaded data for element_id: 326/584
Loaded data for element_id: 327/584
Loaded data for element_id: 328/584
Loaded data for element_id: 329/584
Loaded data for element_id: 330/584
Loaded data for element_id: 331/584
Loaded data for element_id: 332/584
Loaded data for element_id: 333/584
Loaded data for element_id: 334/584
Loaded data for element_id: 335/584
Loaded data for element_id: 336/584
Loaded data for element_id: 337/584
Loaded data for element_id: 338/584
Loaded data for element_id: 339/584
Loaded data for element_id: 340/584
Loaded data for element_id: 341/584
Loaded data for element_id: 342/584
Loaded data for element_id: 343/584
Loaded data for element_id: 344/584
Loaded data for element_id: 345/584
Loaded data for element_id: 346/584
Loaded data for element_id: 347/584
Loaded data for element_id: 348/584
Loaded data for element_id: 349/584
Loaded data for element_id: 350/584
Loaded data for element_id: 351/584
Loaded data for element_id: 352/584
Loaded data for element_id: 353/584
Loaded data for element_id: 354/584
Loaded data for element_id: 355/584
Loaded data for element_id: 356/584
Loaded data for element_id: 357/584
Loaded data for element_id: 358/584
Loaded data for element_id: 359/584
Loaded data for element_id: 360/584
Loaded data for element_id: 361/584
Loaded data for element_id: 362/584
Loaded data for element_id: 363/584
Loaded data for element_id: 364/584
Loaded data for element_id: 365/584
Loaded data for element_id: 366/584
Loaded data for element_id: 367/584
Loaded data for element_id: 368/584
Loaded data for element_id: 369/584
Loaded data for element_id: 370/584
Loaded data for element_id: 371/584
Loaded data for element_id: 372/584
Loaded data for element_id: 373/584
Loaded data for element_id: 374/584
Loaded data for element_id: 375/584
Loaded data for element_id: 376/584
Loaded data for element_id: 377/584
Loaded data for element_id: 378/584
Loaded data for element_id: 379/584
Loaded data for element_id: 380/584
Loaded data for element_id: 381/584
Loaded data for element_id: 382/584
Loaded data for element_id: 383/584
Loaded data for element_id: 384/584
Loaded data for element_id: 385/584
Loaded data for element_id: 386/584
Loaded data for element_id: 387/584
Loaded data for element_id: 388/584
Loaded data for element_id: 389/584
Loaded data for element_id: 390/584
Loaded data for element_id: 391/584
Loaded data for element_id: 392/584
Loaded data for element_id: 393/584
Loaded data for element_id: 394/584
Loaded data for element_id: 395/584
Loaded data for element_id: 396/584
Loaded data for element_id: 397/584
Loaded data for element_id: 398/584
Loaded data for element_id: 399/584
Loaded data for element_id: 400/584
Loaded data for element_id: 401/584
Loaded data for element_id: 402/584
Loaded data for element_id: 403/584
Loaded data for element_id: 404/584
Loaded data for element_id: 405/584
Loaded data for element_id: 406/584
Loaded data for element_id: 407/584
Loaded data for element_id: 408/584
Loaded data for element_id: 409/584
Loaded data for element_id: 410/584
Loaded data for element_id: 411/584
Loaded data for element_id: 412/584
Loaded data for element_id: 413/584
Loaded data for element_id: 414/584
Loaded data for element_id: 415/584
Loaded data for element_id: 416/584
Loaded data for element_id: 417/584
Loaded data for element_id: 418/584
Loaded data for element_id: 419/584
Loaded data for element_id: 420/584
Loaded data for element_id: 421/584
Loaded data for element_id: 422/584
Loaded data for element_id: 423/584
Loaded data for element_id: 424/584
Loaded data for element_id: 425/584
Loaded data for element_id: 426/584
Loaded data for element_id: 427/584
Loaded data for element_id: 428/584
Loaded data for element_id: 429/584
Loaded data for element_id: 430/584
Loaded data for element_id: 431/584
Loaded data for element_id: 432/584
Loaded data for element_id: 433/584
Loaded data for element_id: 434/584
Loaded data for element_id: 435/584
Loaded data for element_id: 436/584
Loaded data for element_id: 437/584
Loaded data for element_id: 438/584
Loaded data for element_id: 439/584
Loaded data for element_id: 440/584
Loaded data for element_id: 441/584
Loaded data for element_id: 442/584
Loaded data for element_id: 443/584
Loaded data for element_id: 444/584
Loaded data for element_id: 445/584
Loaded data for element_id: 446/584
Loaded data for element_id: 447/584
Loaded data for element_id: 448/584
Loaded data for element_id: 449/584
Loaded data for element_id: 450/584
Loaded data for element_id: 451/584
Loaded data for element_id: 452/584
Loaded data for element_id: 453/584
Loaded data for element_id: 454/584
Loaded data for element_id: 455/584
Loaded data for element_id: 456/584
Loaded data for element_id: 457/584
Loaded data for element_id: 458/584
Loaded data for element_id: 459/584
Loaded data for element_id: 460/584
Loaded data for element_id: 461/584
Loaded data for element_id: 462/584
Loaded data for element_id: 463/584
Loaded data for element_id: 464/584
Loaded data for element_id: 465/584
Loaded data for element_id: 466/584
Loaded data for element_id: 467/584
Loaded data for element_id: 468/584
Loaded data for element_id: 469/584
Loaded data for element_id: 470/584
Loaded data for element_id: 471/584
Loaded data for element_id: 472/584
Loaded data for element_id: 473/584
Loaded data for element_id: 474/584
Loaded data for element_id: 475/584
Loaded data for element_id: 476/584
Loaded data for element_id: 477/584
Loaded data for element_id: 478/584
Loaded data for element_id: 479/584
Loaded data for element_id: 480/584
Loaded data for element_id: 481/584
Loaded data for element_id: 482/584
Loaded data for element_id: 483/584
Loaded data for element_id: 484/584
Loaded data for element_id: 485/584
Loaded data for element_id: 486/584
Loaded data for element_id: 487/584
Loaded data for element_id: 488/584
Loaded data for element_id: 489/584
Loaded data for element_id: 490/584
Loaded data for element_id: 491/584
Loaded data for element_id: 492/584
Loaded data for element_id: 493/584
Loaded data for element_id: 494/584
Loaded data for element_id: 495/584
Loaded data for element_id: 496/584
Loaded data for element_id: 497/584
Loaded data for element_id: 498/584
Loaded data for element_id: 499/584
Loaded data for element_id: 500/584
Loaded data for element_id: 501/584
Loaded data for element_id: 502/584
Loaded data for element_id: 503/584
Loaded data for element_id: 504/584
Loaded data for element_id: 505/584
Loaded data for element_id: 506/584
Loaded data for element_id: 507/584
Loaded data for element_id: 508/584
Loaded data for element_id: 509/584
Loaded data for element_id: 510/584
Loaded data for element_id: 511/584
Loaded data for element_id: 512/584
Loaded data for element_id: 513/584
Loaded data for element_id: 514/584
Loaded data for element_id: 515/584
Loaded data for element_id: 516/584
Loaded data for element_id: 517/584
Loaded data for element_id: 518/584
Loaded data for element_id: 519/584
Loaded data for element_id: 520/584
Loaded data for element_id: 521/584
Loaded data for element_id: 522/584
Loaded data for element_id: 523/584
Loaded data for element_id: 524/584
Loaded data for element_id: 525/584
Loaded data for element_id: 526/584
Loaded data for element_id: 527/584
Loaded data for element_id: 528/584
Loaded data for element_id: 529/584
Loaded data for element_id: 530/584
Loaded data for element_id: 531/584
Loaded data for element_id: 532/584
Loaded data for element_id: 533/584
Loaded data for element_id: 534/584
Loaded data for element_id: 535/584
Loaded data for element_id: 536/584
Loaded data for element_id: 537/584
Loaded data for element_id: 538/584
Loaded data for element_id: 539/584
Loaded data for element_id: 540/584
Loaded data for element_id: 541/584
Loaded data for element_id: 542/584
Loaded data for element_id: 543/584
Loaded data for element_id: 544/584
Loaded data for element_id: 545/584
Loaded data for element_id: 546/584
Loaded data for element_id: 547/584
Loaded data for element_id: 548/584
Loaded data for element_id: 549/584
Loaded data for element_id: 550/584
Loaded data for element_id: 551/584

c:\Users\Chris\OneDrive\Documents\Coding\FPL-Points-Predictor\Load_Merge_FPL_Data.py:294: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_merged = pd.concat(list(self.merged_data.values()), axis=0)
c:\Users\Chris\OneDrive\Documents\Coding\FPL-Points-Predictor\Load_Merge_FPL_Data.py:297: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_rest_of_current_season = pd.concat([all_merged, current_year_players_allfixtures], axis=0)

Total records: 229872
Final playergw dataframe loaded into psql!
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229872 entries, 0 to 229871
Data columns (total 30 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   player_name_id              229872 non-null  object
 1   element                     229872 non-null  float64
 2   value                       207680 non-null  float64
 3   season                      229872 non-null  float64
 4   event                       229872 non-null  float64
 5   fixture                     229872 non-null  float64
 6   total_points                207680 non-null  float64
 7   minutes                     207680 non-null  float64
 8   goals_scored                207680 non-null  float64
 9   assists                     207680 non-null  float64
 10  team_elo                    229872 non-null  float64
 11  opp_team_elo                229872 non-null  float64
 12  position                    185581 non-null  object
 13  bonus                       207680 non-null  float64
 14  bps                         207680 non-null  float64
 15  clean_sheets                207680 non-null  float64
 16  goals_conceded              207680 non-null  float64
 17  was_home                    207680 non-null  object
 18  expected_assists            113580 non-null  float64
 19  expected_goal_involvements  113580 non-null  float64
 20  expected_goals              113580 non-null  float64
 21  expected_goals_conceded     113580 non-null  float64
 22  starts                      113580 non-null  float64
 23  cbi                         51537 non-null   float64
 24  defensive_contribution      29747 non-null   float64
 25  recoveries                  51537 non-null   float64
 26  tackles                     51537 non-null   float64
 27  saves                       207680 non-null  float64
 28  team_name                   229872 non-null  object
 29  opp_team_name               229872 non-null  object
dtypes: float64(25), object(5)
memory usage: 52.6+ MB
None

In [8]:
filtered = playergwdf['player_name_id'] == "Mohamed Salah"
playergwdf[filtered].pivot_table(index='season',values='expected_goals',aggfunc='count')

            expected_goals
season
20182019.0               0
20192020.0               0
20202021.0               0
20212022.0               0
20222023.0              38
20232024.0              38
20242025.0              38
20252026.0              38

In [14]:
filtered = (playergwdf['event']==1) & (playergwdf['player_name_id']=="Jordan Pickford")
playergwdf[filtered].sort_values(by='season')

,player_name_id,element,value,season,event,fixture,total_points,minutes,goals_scored,assists,...,expected_goals,expected_goals_conceded,starts,cbi,defensive_contribution,recoveries,tackles,saves,team_name,opp_team_name
267,Jordan Pickford,154.0,50.0,20182019.0,1.0,10.0,1.0,90.0,0.0,0.0,...,NaN,NaN,NaN,1.0,NaN,9.0,0.0,2.0,Everton,Wolves
22055,Jordan Pickford,148.0,55.0,20192020.0,1.0,4.0,7.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Everton,Crystal Palace
44506,Jordan Pickford,157.0,50.0,20202021.0,1.0,4.0,8.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Everton,Spurs
69153,Jordan Pickford,170.0,50.0,20212022.0,1.0,4.0,2.0,90.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Everton,Southampton
94517,Jordan Pickford,182.0,45.0,20222023.0,1.0,3.0,3.0,90.0,0.0,0.0,...,0.0,0.00,0.0,NaN,NaN,NaN,NaN,5.0,Everton,Chelsea
121108,Jordan Pickford,263.0,45.0,20232024.0,1.0,5.0,2.0,90.0,0.0,0.0,...,0.0,1.50,1.0,NaN,NaN,NaN,NaN,1.0,Everton,Fulham
180518,Jordan Pickford,235.0,50.0,20242025.0,1.0,3.0,1.0,90.0,0.0,0.0,...,0.0,1.43,1.0,NaN,NaN,NaN,NaN,2.0,Everton,Brighton
150955,Jordan Pickford,287.0,55.0,20252026.0,1.0,10.0,2.0,90.0,0.0,0.0,...,0.0,2.07,1.0,3.0,0.0,8.0,0.0,2.0,Everton,Leeds
216800,Jordan Pickford,226.0,NaN,20262027.0,1.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Everton,Crystal Palace

In [10]:
playergwdf.to_csv('playergwdf.csv',index=False)

# Get FPL Player current status

In [11]:
#Create DF from FPL API Request
headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
get=requests.get("https://fantasy.premierleague.com/api/bootstrap-static/", headers=headers, timeout=5)
data=json.loads(get.text)

#player_raw = Summary stats for each player for the current season
cols=list(data['elements'][0].keys())
player_raw = pd.DataFrame(data['elements'], columns = cols)
player = player_raw[['web_name','id','now_cost','status','news','chance_of_playing_next_round','chance_of_playing_this_round']]
player['season']=current_season
player['datetime_now'] = pd.to_datetime('now')

table_name = "player_status"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=player)
    player_status = db_creator.table_to_df(table_name=table_name)

C:\Users\Chris\AppData\Local\Temp\ipykernel_4920\3829675733.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player['season']=current_season
C:\Users\Chris\AppData\Local\Temp\ipykernel_4920\3829675733.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  player['datetime_now'] = pd.to_datetime('now')

In [12]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
#Finished in 6.05 minute(s)

Finished in 11.91 minute(s)

In [13]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)