In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 37 #predictions from gw+1
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  38
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
1557117 Bernard Chalk GW 28 Pick 1
1557117 Bernard Chalk GW 28 Pick 2
1557117 Bernard Chalk GW 28 Pick 3
1557117 Bernard Chalk GW 28 Pick 4
1557117 Bernard Chalk GW 28 Pick 5
1557117 Bernard Chalk GW 28 Pick 6
1557117 Bernard Chalk GW 28 Pick 7
1557117 Bernard Chalk GW 28 Pick 8
1557117 Bernard Chalk GW 28 Pick 9
1557117 Bernard Chalk GW 28 Pick 10
1557117 Bernard Chalk GW 28 Pick 11
1557117 Bernard Chalk GW 28 Pick 12
1557117 Bernard Chalk GW 28 Pick 13
1557117 Bernard Chalk GW 28 Pick 14
1557117 Bernard Chalk GW 28 Pick 15
1557117 Bernard Chalk GW 29 Pick 1
1557117 Bernard Chalk GW 29 Pick 2
1557117 Bernard Chalk GW 29 Pick 3
1557117 Bernard Chalk GW 29 Pick 4
1557117 Bernard Chalk GW 29 Pick 5
1557117 Bernard Chalk GW 29 Pick 6
1557117 Bernard Chalk GW 29 Pick 7
1557117 Bernard Chalk GW 29 Pick 8
1557117 Bernard Chalk GW 29 Pick 9
1557117 Bernard Chalk GW 29 Pick 10
1557117 Bernard Chalk GW 29 Pick 11
1557117 Bernard Chalk GW 29 Pick 12
1557117 Bernard Chalk GW 29 Pick 13
1557117 Bernard Chalk GW 29 Pick 14
1557117 Bernard Chalk GW 29 Pick 15
1557117 Bernard Chalk GW 30 Pick 1
1557117 Bernard Chalk GW 30 Pick 2
1557117 Bernard Chalk GW 30 Pick 3
1557117 Bernard Chalk GW 30 Pick 4
1557117 Bernard Chalk GW 30 Pick 5
1557117 Bernard Chalk GW 30 Pick 6
1557117 Bernard Chalk GW 30 Pick 7
1557117 Bernard Chalk GW 30 Pick 8
1557117 Bernard Chalk GW 30 Pick 9
1557117 Bernard Chalk GW 30 Pick 10
1557117 Bernard Chalk GW 30 Pick 11
1557117 Bernard Chalk GW 30 Pick 12
1557117 Bernard Chalk GW 30 Pick 13
1557117 Bernard Chalk GW 30 Pick 14
1557117 Bernard Chalk GW 30 Pick 15
1557117 Bernard Chalk GW 31 Pick 1
1557117 Bernard Chalk GW 31 Pick 2
1557117 Bernard Chalk GW 31 Pick 3
1557117 Bernard Chalk GW 31 Pick 4
1557117 Bernard Chalk GW 31 Pick 5
1557117 Bernard Chalk GW 31 Pick 6
1557117 Bernard Chalk GW 31 Pick 7
1557117 Bernard Chalk GW 31 Pick 8
1557117 Bernard Chalk GW 31 Pick 9
1557117 Bernard Chalk GW 31 Pick 10
1557117 Bernard Chalk GW 31 Pick 11
1557117 Bernard Chalk GW 31 Pick 12
1557117 Bernard Chalk GW 31 Pick 13
1557117 Bernard Chalk GW 31 Pick 14
1557117 Bernard Chalk GW 31 Pick 15
1557117 Bernard Chalk GW 32 Pick 1
1557117 Bernard Chalk GW 32 Pick 2
1557117 Bernard Chalk GW 32 Pick 3
1557117 Bernard Chalk GW 32 Pick 4
1557117 Bernard Chalk GW 32 Pick 5
1557117 Bernard Chalk GW 32 Pick 6
1557117 Bernard Chalk GW 32 Pick 7
1557117 Bernard Chalk GW 32 Pick 8
1557117 Bernard Chalk GW 32 Pick 9
1557117 Bernard Chalk GW 32 Pick 10
1557117 Bernard Chalk GW 32 Pick 11
1557117 Bernard Chalk GW 32 Pick 12
1557117 Bernard Chalk GW 32 Pick 13
1557117 Bernard Chalk GW 32 Pick 14
1557117 Bernard Chalk GW 32 Pick 15
1557117 Bernard Chalk GW 33 Pick 1
1557117 Bernard Chalk GW 33 Pick 2
1557117 Bernard Chalk GW 33 Pick 3
1557117 Bernard Chalk GW 33 Pick 4
1557117 Bernard Chalk GW 33 Pick 5
1557117 Bernard Chalk GW 33 Pick 6
1557117 Bernard Chalk GW 33 Pick 7
1557117 Bernard Chalk GW 33 Pick 8
1557117 Bernard Chalk GW 33 Pick 9
1557117 Bernard Chalk GW 33 Pick 10
1557117 Bernard Chalk GW 33 Pick 11
1557117 Bernard Chalk GW 33 Pick 12
1557117 Bernard Chalk GW 33 Pick 13
1557117 Bernard Chalk GW 33 Pick 14
1557117 Bernard Chalk GW 33 Pick 15
1557117 Bernard Chalk GW 34 Pick 1
1557117 Bernard Chalk GW 34 Pick 2
1557117 Bernard Chalk GW 34 Pick 3
1557117 Bernard Chalk GW 34 Pick 4
1557117 Bernard Chalk GW 34 Pick 5
1557117 Bernard Chalk GW 34 Pick 6
1557117 Bernard Chalk GW 34 Pick 7
1557117 Bernard Chalk GW 34 Pick 8
1557117 Bernard Chalk GW 34 Pick 9
1557117 Bernard Chalk GW 34 Pick 10
1557117 Bernard Chalk GW 34 Pick 11
1557117 Bernard Chalk GW 34 Pick 12
1557117 Bernard Chalk GW 34 Pick 13
1557117 Bernard Chalk GW 34 Pick 14
1557117 Bernard Chalk GW 34 Pick 15
1557117 Bernard Chalk GW 35 Pick 1
1557117 Bernard Chalk GW 35 Pick 2
1557117 Bernard Chalk GW 35 Pick 3
1557117 Bernard Chalk GW 35 Pick 4
1557117 Bernard Chalk GW 35 Pick 5
1557117 Bernard Chalk GW 35 Pick 6
1557117 Bernard Chalk GW 35 Pick 7
1557117 Bernard Chalk GW 35 Pick 8
1557117 Bernard Chalk GW 35 Pick 9
1557117 Bernard Chalk GW 35 Pick 10
1557117 Bernard Chalk GW 35 Pick 11
1557117 Bernard Chalk GW 35 Pick 12
1557117 Bernard Chalk GW 35 Pick 13
1557117 Bernard Chalk GW 35 Pick 14
1557117 Bernard Chalk GW 35 Pick 15
1557117 Bernard Chalk GW 36 Pick 1
1557117 Bernard Chalk GW 36 Pick 2
1557117 Bernard Chalk GW 36 Pick 3
1557117 Bernard Chalk GW 36 Pick 4
1557117 Bernard Chalk GW 36 Pick 5
1557117 Bernard Chalk GW 36 Pick 6
1557117 Bernard Chalk GW 36 Pick 7
1557117 Bernard Chalk GW 36 Pick 8
1557117 Bernard Chalk GW 36 Pick 9
1557117 Bernard Chalk GW 36 Pick 10
1557117 Bernard Chalk GW 36 Pick 11
1557117 Bernard Chalk GW 36 Pick 12

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW38 to GW42

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Erling Haaland,a,0,FWD,Man City,1115.3,2.02,77.4,0.586,0.547,1.322
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1037.7,1.79,84.6,0.136,0.104,0.874
2,Jurriën Timber,d,0,DEF,Arsenal,1037.7,1.76,62.6,0.222,0.260,0.970
3,Declan Rice,a,0,MID,Arsenal,1037.7,1.75,78.6,0.288,0.269,0.841
4,Leandro Trossard,a,0,MID,Arsenal,1037.7,1.72,75.1,0.271,0.330,0.891
5,Bruno Borges Fernandes,a,1,MID,Man Utd,1085.1,1.66,84.4,0.216,0.310,1.416
6,Bryan Mbeumo,a,0,MID,Man Utd,1085.1,1.62,70.8,0.453,0.103,1.362
7,Riccardo Calafiori,a,0,DEF,Arsenal,1037.7,1.62,69.5,0.143,0.102,0.935
8,Anthony Gordon,a,0,MID,Newcastle,1037.9,1.57,53.2,0.434,0.492,1.396
9,William Saliba,a,0,DEF,Arsenal,1037.7,1.56,86.2,0.049,0.058,0.911
10,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1111.6,1.54,67.0,0.310,0.328,1.958
11,Bukayo Saka,a,0,MID,Arsenal,1037.7,1.54,69.9,0.230,0.241,0.768
12,Nico O'Reilly,a,0,DEF,Man City,1115.3,1.54,83.1,0.156,0.045,1.212
13,William Osula,a,0,FWD,Newcastle,1037.9,1.53,69.9,0.508,0.149,1.441
14,Dominic Calvert-Lewin,a,0,FWD,Leeds,989.4,1.53,86.5,0.404,0.162,1.062
15,Eberechi Eze,a,0,MID,Arsenal,1037.7,1.53,70.6,0.270,0.163,0.829
16,Cole Palmer,a,0,MID,Chelsea,1040.6,1.51,85.5,0.243,0.116,1.337
17,Antoine Semenyo,a,0,MID,Man City,1115.3,1.51,66.2,0.307,0.260,1.209
18,Mathias Jensen,a,0,MID,Brentford,1147.6,1.49,76.0,0.294,0.101,1.319
19,Bruno Guimarães Rodriguez Moura,a,1,MID,Newcastle,1037.9,1.49,81.5,0.239,0.135,1.325
20,Marcus Tavernier,a,0,MID,Bournemouth,1042.2,1.48,82.2,0.206,0.141,1.210
21,Morgan Rogers,a,0,MID,Aston Villa,1247.2,1.47,86.1,0.190,0.240,2.644
22,Ladislav Krejcí,a,0,DEF,Wolves,870.1,1.46,79.5,0.048,0.048,0.955
23,Enzo Fernández,a,0,MID,Chelsea,1040.6,1.46,86.2,0.187,0.132,1.258
24,Nathan Patterson,a,0,DEF,Everton,972.1,1.45,54.1,0.122,0.351,1.206
25,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1085.1,1.45,85.5,0.197,0.130,1.383
26,Karl Darlow,a,0,GK,Leeds,989.4,1.45,89.9,NaN,NaN,0.918
27,Dominik Szoboszlai,a,1,MID,Liverpool,1065.8,1.45,86.0,0.171,0.166,1.426
28,James Tarkowski,a,0,DEF,Everton,972.1,1.44,86.8,0.065,0.042,1.165
29,James Justin,a,0,DEF,Leeds,989.4,1.44,87.2,0.034,0.047,1.051
30,Michael Keane,a,0,DEF,Everton,972.1,1.43,83.6,0.062,0.039,1.140
31,Jake O'Brien,a,0,DEF,Everton,972.1,1.42,83.0,0.050,0.038,1.093
32,Vitalii Mykolenko,a,0,DEF,Everton,972.1,1.42,84.9,0.054,0.038,1.102
33,Jaka Bijol,a,0,DEF,Leeds,989.4,1.42,80.8,0.033,0.053,1.015
34,Santiago Ignacio Bueno,a,0,DEF,Wolves,870.1,1.42,87.0,0.044,0.047,1.055
35,Dango Ouattara,a,0,MID,Brentford,1147.6,1.41,75.4,0.209,0.159,1.435
36,Adrien Truffert,a,0,DEF,Bournemouth,1042.2,1.40,86.9,0.058,0.077,1.244
37,Marc Guéhi,a,0,DEF,Man City,1115.3,1.40,86.1,0.051,0.053,1.240
38,Yankuba Minteh,a,0,MID,Brighton,1134.2,1.40,84.8,0.184,0.114,1.305
39,Ollie Watkins,a,0,FWD,Aston Villa,1247.2,1.40,78.7,0.349,0.226,1.786
40,João Pedro Junqueira de Jesus,d,0,FWD,Chelsea,1040.6,1.39,82.3,0.405,0.048,1.388
41,Mohamed Salah,a,0,MID,Liverpool,1065.8,1.39,55.6,0.411,0.219,1.353
42,Piero Hincapié,a,0,DEF,Arsenal,1037.7,1.39,57.1,0.051,0.089,0.896
43,Phil Foden,a,0,MID,Man City,1115.3,1.37,58.3,0.351,0.173,1.247
44,Anton Stach,d,0,MID,Leeds,989.4,1.37,81.0,0.167,0.114,1.108
45,Jérémy Doku,a,0,MID,Man City,1115.3,1.37,71.0,0.179,0.191,1.213
46,Marcos Senesi Barón,a,0,DEF,Bournemouth,1042.2,1.37,86.0,0.044,0.068,1.242
47,Joe Rodon,a,0,DEF,Leeds,989.4,1.37,84.0,0.033,0.026,1.087
48,Crysencio Summerville,a,0,MID,West Ham,1026.2,1.37,85.0,0.173,0.084,1.250
49,Toti Gomes,a,0,DEF,Wolves,870.1,1.36,79.4,0.040,0.027,1.057

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
        -- AND team_name = 'Crystal Palace'
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 38 and 42:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Erling Haaland,a,FWD,Man City,14.7,1115.3,6.17,77.4,0.586,0.547,1.322
1,Gabriel dos Santos Magalhães,a,DEF,Arsenal,7.3,1037.7,5.47,84.6,0.136,0.104,0.874
2,Jurriën Timber,d,DEF,Arsenal,6.0,1037.7,5.38,62.6,0.222,0.260,0.970
3,Declan Rice,a,MID,Arsenal,7.2,1037.7,5.35,78.6,0.288,0.269,0.841
4,Leandro Trossard,a,MID,Arsenal,6.5,1037.7,5.24,75.1,0.271,0.330,0.891
5,Bruno Borges Fernandes,a,MID,Man Utd,10.4,1085.1,5.05,84.4,0.216,0.310,1.416
6,Bryan Mbeumo,a,MID,Man Utd,8.3,1085.1,4.94,70.8,0.453,0.103,1.362
7,Riccardo Calafiori,a,DEF,Arsenal,5.6,1037.7,4.93,69.5,0.143,0.102,0.935
8,Anthony Gordon,a,MID,Newcastle,7.3,1037.9,4.80,53.2,0.434,0.492,1.396
9,William Saliba,a,DEF,Arsenal,6.2,1037.7,4.76,86.2,0.049,0.058,0.911
10,Nico O'Reilly,a,DEF,Man City,5.3,1115.3,4.71,83.1,0.156,0.045,1.212
11,Bukayo Saka,a,MID,Arsenal,10.0,1037.7,4.71,69.9,0.230,0.241,0.768
12,Morgan Gibbs-White,a,MID,Nott'm Forest,7.5,1111.6,4.71,67.0,0.310,0.328,1.958
13,William Osula,a,FWD,Newcastle,5.4,1037.9,4.68,69.9,0.508,0.149,1.441
14,Dominic Calvert-Lewin,a,FWD,Leeds,5.8,989.4,4.67,86.5,0.404,0.162,1.062
15,Eberechi Eze,a,MID,Arsenal,7.3,1037.7,4.66,70.6,0.270,0.163,0.829
16,Antoine Semenyo,a,MID,Man City,8.1,1115.3,4.61,66.2,0.307,0.260,1.209
17,Cole Palmer,a,MID,Chelsea,10.3,1040.6,4.60,85.5,0.243,0.116,1.337
18,Bruno Guimarães Rodriguez Moura,a,MID,Newcastle,6.9,1037.9,4.55,81.5,0.239,0.135,1.325
19,Mathias Jensen,a,MID,Brentford,4.9,1147.6,4.55,76.0,0.294,0.101,1.319

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        2184.0
1                 Ryan Boyce  5398818.0        2140.0
2                 Rhys Birdy  5810139.0        2117.0
3               Tommy Davies  7845816.0        2106.0
4               Samia Shelim  6506490.0        2102.0
5          William Partridge  6588565.0        2099.0
6         Christopher Harris    28660.0        2096.0
7         Christopher Harris   145486.0        2066.0
8               Jack Carroll  4438260.0        2032.0
9              Ollie Carroll  5181285.0        2020.0
10             Rizwan Shelim  3058994.0        1995.0
11            Conner Harling  3421093.0        1921.0
12               Nafi Shelim  4776281.0        1917.0
13             Tajwar Shelim  4773459.0        1899.0
14  Christakis Christodoulou  7474864.0        1864.0
15              Will Hossack  4792527.0        1713.0
16              Tahmid Haque  6394829.0        1708.0
17               Simon Meech  6764382.0        1696.0
18            Charlie Garner  9432680.0        1624.0
19              Holly Stower  7367977.0        1579.0
20            Rachel Aumayer  9763056.0        1392.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW38 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
134,1,6.0,William Saliba,a,6.2,DEF,Arsenal,4.762813,0.0,4.762813,0.000000,4.762813,0.0,4.762813,4.762813,4.762813
272,1,691.0,Dominic Calvert-Lewin,a,5.8,FWD,Leeds,4.670707,0.0,4.670707,0.000000,4.670707,0.0,4.670707,4.670707,4.670707
401,1,237.0,Enzo Fernández,a,6.4,MID,Chelsea,4.442219,0.0,4.442219,0.000000,4.442219,0.0,4.442219,4.442219,4.442219
179,1,341.0,Karl Darlow,a,4.0,GK,Leeds,4.437189,0.0,4.437189,0.000000,4.437189,0.0,4.437189,4.437189,4.437189
211,1,21.0,Declan Rice,a,7.2,MID,Arsenal,5.351649,20.0,4.281319,-1.070330,4.281319,0.0,3.210989,4.281319,4.281319
363,1,694.0,Nordi Mukiele,a,4.6,DEF,Sunderland,3.810733,0.0,3.810733,0.000000,3.810733,0.0,3.810733,3.810733,3.810733
147,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,3.048074,0.0,3.048074,0.000000,3.048074,0.0,3.048074,3.048074,3.048074
282,1,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,2.684234,0.0,2.684234,0.000000,2.684234,0.0,2.684234,2.684234,2.684234
16,1,5.0,Gabriel dos Santos Magalhães,a,7.3,DEF,Arsenal,5.467884,60.0,2.187154,-3.280731,2.187154,0.0,-1.093577,2.187154,2.187154
210,1,417.0,Rayan Cherki,a,6.6,MID,Man City,3.606663,40.0,2.163998,-1.442665,2.163998,0.0,0.721333,2.163998,2.163998
251,1,411.0,Nico O'Reilly,a,5.3,DEF,Man City,4.709168,60.0,1.883667,-2.825501,1.883667,0.0,-0.941834,1.883667,1.883667
283,1,329.0,Harry Wilson,a,5.9,MID,Fulham,3.635176,60.0,1.454070,-2.181105,1.454070,0.0,-0.727035,1.454070,1.454070
39,1,136.0,Igor Thiago Nascimento Rodrigues,a,7.3,FWD,Brentford,4.022171,80.0,0.804434,-3.217737,0.804434,0.0,-2.413303,0.804434,0.804434
83,1,449.0,Bruno Borges Fernandes,a,10.4,MID,Man Utd,5.051865,120.0,-1.010373,-6.062238,-1.010373,0.0,-7.072610,-1.010373,-1.010373
325,1,430.0,Erling Haaland,a,14.7,FWD,Man City,6.167373,160.0,-3.700424,-9.867796,-3.700424,0.0,-13.568220,-3.700424,-3.700424

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW38 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
325,1,430.0,Erling Haaland,a,14.7,FWD,Man City,6.167373,160.0,-3.700424,-9.867796,-3.700424,0.000000,-13.568220,-3.700424,-3.700424
38,0,82.0,Antoine Semenyo,a,8.1,MID,Man City,4.611863,60.0,1.844745,-2.767118,0.000000,-2.767118,-0.922373,-2.767118,1.844745
49,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,3.552236,60.0,1.420894,-2.131341,0.000000,-2.131341,-0.710447,-2.131341,1.420894
344,0,387.0,Dominik Szoboszlai,a,7.0,MID,Liverpool,4.436372,40.0,2.661823,-1.774549,0.000000,-1.774549,0.887274,-1.774549,2.661823
351,0,10.0,Myles Lewis-Skelly,a,5.0,DEF,Arsenal,4.142422,40.0,2.485453,-1.656969,0.000000,-1.656969,0.828484,-1.656969,2.485453
53,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,3.888375,40.0,2.333025,-1.555350,0.000000,-1.555350,0.777675,-1.555350,2.333025
390,0,139.0,Bart Verbruggen,a,4.6,GK,Brighton,3.721434,40.0,2.232861,-1.488574,0.000000,-1.488574,0.744287,-1.488574,2.232861
83,1,449.0,Bruno Borges Fernandes,a,10.4,MID,Man Utd,5.051865,120.0,-1.010373,-6.062238,-1.010373,0.000000,-7.072610,-1.010373,-1.010373
89,0,16.0,Bukayo Saka,a,10.0,MID,Arsenal,4.705610,20.0,3.764488,-0.941122,0.000000,-0.941122,2.823366,-0.941122,3.764488
252,0,84.0,Marcus Tavernier,a,5.4,MID,Bournemouth,4.506082,20.0,3.604865,-0.901216,0.000000,-0.901216,2.703649,-0.901216,3.604865
429,0,47.0,Morgan Rogers,a,7.4,MID,Aston Villa,4.478890,20.0,3.583112,-0.895778,0.000000,-0.895778,2.687334,-0.895778,3.583112
8,0,291.0,James Tarkowski,a,5.7,DEF,Everton,4.392628,20.0,3.514102,-0.878526,0.000000,-0.878526,2.635577,-0.878526,3.514102
77,0,295.0,Michael Keane,a,4.5,DEF,Everton,4.349392,20.0,3.479514,-0.869878,0.000000,-0.869878,2.609635,-0.869878,3.479514
153,0,74.0,Adrien Truffert,a,4.7,DEF,Bournemouth,4.278391,20.0,3.422713,-0.855678,0.000000,-0.855678,2.567035,-0.855678,3.422713
208,0,260.0,Marc Guéhi,a,5.1,DEF,Man City,4.263226,20.0,3.410581,-0.852645,0.000000,-0.852645,2.557936,-0.852645,3.410581
428,0,615.0,Crysencio Summerville,a,5.4,MID,West Ham,4.170294,20.0,3.336235,-0.834059,0.000000,-0.834059,2.502176,-0.834059,3.336235
103,0,242.0,Kiernan Dewsbury-Hall,a,5.3,MID,Everton,4.044851,20.0,3.235881,-0.808970,0.000000,-0.808970,2.426911,-0.808970,3.235881
389,0,373.0,Virgil van Dijk,a,6.1,DEF,Liverpool,4.020772,20.0,3.216618,-0.804154,0.000000,-0.804154,2.412463,-0.804154,3.216618
405,0,151.0,Jan Paul van Hecke,a,4.7,DEF,Brighton,3.859833,20.0,3.087866,-0.771967,0.000000,-0.771967,2.315900,-0.771967,3.087866
123,0,624.0,Jarrod Bowen,a,7.7,FWD,West Ham,3.816217,20.0,3.052974,-0.763243,0.000000,-0.763243,2.289730,-0.763243,3.052974

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW38 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
206,0,8.0,Jurriën Timber,d,6.0,DEF,Arsenal,5.383644,0.0,5.383644,0.0,0.0,0.0,5.383644,0.0,5.383644
217,0,20.0,Leandro Trossard,a,6.5,MID,Arsenal,5.240438,0.0,5.240438,0.0,0.0,0.0,5.240438,0.0,5.240438
340,0,119.0,Bryan Mbeumo,a,8.3,MID,Man Utd,4.937632,0.0,4.937632,0.0,0.0,0.0,4.937632,0.0,4.937632
273,0,7.0,Riccardo Calafiori,a,5.6,DEF,Arsenal,4.928109,0.0,4.928109,0.0,0.0,0.0,4.928109,0.0,4.928109
326,0,485.0,Anthony Gordon,a,7.3,MID,Newcastle,4.798455,0.0,4.798455,0.0,0.0,0.0,4.798455,0.0,4.798455
20,0,515.0,Morgan Gibbs-White,a,7.5,MID,Nott'm Forest,4.705208,0.0,4.705208,0.0,0.0,0.0,4.705208,0.0,4.705208
346,0,500.0,William Osula,a,5.4,FWD,Newcastle,4.682303,0.0,4.682303,0.0,0.0,0.0,4.682303,0.0,4.682303
398,0,266.0,Eberechi Eze,a,7.3,MID,Arsenal,4.662571,0.0,4.662571,0.0,0.0,0.0,4.662571,0.0,4.662571
130,0,235.0,Cole Palmer,a,10.3,MID,Chelsea,4.603128,0.0,4.603128,0.0,0.0,0.0,4.603128,0.0,4.603128
139,0,488.0,Bruno Guimarães Rodriguez Moura,a,6.9,MID,Newcastle,4.550595,0.0,4.550595,0.0,0.0,0.0,4.550595,0.0,4.550595
212,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,4.547680,0.0,4.547680,0.0,0.0,0.0,4.547680,0.0,4.547680
338,0,709.0,Ladislav Krejcí,a,4.5,DEF,Wolves,4.446666,0.0,4.446666,0.0,0.0,0.0,4.446666,0.0,4.446666
331,0,296.0,Nathan Patterson,a,4.4,DEF,Everton,4.435246,0.0,4.435246,0.0,0.0,0.0,4.435246,0.0,4.435246
404,0,450.0,Matheus Santos Carneiro da Cunha,a,8.1,MID,Man Utd,4.434773,0.0,4.434773,0.0,0.0,0.0,4.434773,0.0,4.434773
224,0,706.0,James Justin,a,4.0,DEF,Leeds,4.380545,0.0,4.380545,0.0,0.0,0.0,4.380545,0.0,4.380545
446,0,292.0,Vitalii Mykolenko,a,4.9,DEF,Everton,4.342099,0.0,4.342099,0.0,0.0,0.0,4.342099,0.0,4.342099
294,0,293.0,Jake O'Brien,a,4.9,DEF,Everton,4.326746,0.0,4.326746,0.0,0.0,0.0,4.326746,0.0,4.326746
215,0,344.0,Jaka Bijol,a,3.9,DEF,Leeds,4.319318,0.0,4.319318,0.0,0.0,0.0,4.319318,0.0,4.319318
244,0,636.0,Santiago Ignacio Bueno,a,4.4,DEF,Wolves,4.317324,0.0,4.317324,0.0,0.0,0.0,4.317324,0.0,4.317324
25,0,83.0,Dango Ouattara,a,5.7,MID,Brentford,4.296500,0.0,4.296500,0.0,0.0,0.0,4.296500,0.0,4.296500

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £102.3m / £102.4m
Total Weighted Expected Points: 57.44
Remaining Budget: £0.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Đorđe Petrović                 Bournemouth  £4.6     3.87
 ✅        Karl Darlow                    Leeds        £4.0     4.44

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ladislav Krejcí                Wolves       £4.5     4.45
 🪑        James Justin                   Leeds        £4.0     4.38
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.3     5.47
 ✅        Jurriën Timber                 Arsenal      £6.0     5.38
 ✅        Nico O'Reilly                  Man City     £5.3     4.71

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Declan Rice                    Arsenal      £7.2     5.35
 ✅        Bruno Borges Fernandes         Man Utd      £10.4    5.05
 ✅        Bryan Mbeumo                   Man Utd      £8.3     4.94
 ✅        Anthony Gordon                 Newcastle    £7.3     4.80
 ✅        Morgan Gibbs-White             Nott'm Forest £7.5     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.8     4.67
 ✅        Erling Haaland                 Man City     £14.7    6.17
 ✅        William Osula                  Newcastle    £5.4     4.68

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £93.9m / £102.4m
Total Weighted Expected Points: 54.53
Remaining Budget: £8.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Jordan Pickford                Everton      £5.6     3.91
 ✅        Karl Darlow                    Leeds        £4.0     4.44

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        James Justin                   Leeds        £4.0     4.38
 🪑        Nathan Patterson               Everton      £4.4     4.44
 ✅        Jurriën Timber                 Arsenal      £6.0     5.38
 ✅        Riccardo Calafiori             Arsenal      £5.6     4.93
 ✅        Ladislav Krejcí                Wolves       £4.5     4.45

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Morgan Gibbs-White             Nott'm Forest £7.5     4.71
 ✅        Cole Palmer                    Chelsea      £10.3    4.60
 ✅        Leandro Trossard               Arsenal      £6.5     5.24
 ✅        Anthony Gordon                 Newcastle    £7.3     4.80
 ✅        Bryan Mbeumo                   Man Utd      £8.3     4.94

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ollie Watkins                  Aston Villa  £8.7     4.28
 ✅        Dominic Calvert-Lewin          Leeds        £5.8     4.67
 ✅        William Osula                  Newcastle    £5.4     4.68

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,38.0,Erling Haaland,a,FWD,Man City,Aston Villa,14.7,6.167373
1,38.0,Gabriel dos Santos Magalhães,a,DEF,Arsenal,Crystal Palace,7.3,5.467884
2,38.0,Jurriën Timber,d,DEF,Arsenal,Crystal Palace,6.0,5.383644
3,38.0,Declan Rice,a,MID,Arsenal,Crystal Palace,7.2,5.351649
4,38.0,Leandro Trossard,a,MID,Arsenal,Crystal Palace,6.5,5.240438
5,38.0,Bruno Borges Fernandes,a,MID,Man Utd,Brighton,10.4,5.051865
6,38.0,Bryan Mbeumo,a,MID,Man Utd,Brighton,8.3,4.937632
7,38.0,Riccardo Calafiori,a,DEF,Arsenal,Crystal Palace,5.6,4.928109
8,38.0,Anthony Gordon,a,MID,Newcastle,Fulham,7.3,4.798455
9,38.0,William Saliba,a,DEF,Arsenal,Crystal Palace,6.2,4.762813

In [17]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW38 to GW38...

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £102.3m / £102.4m
Total Weighted Expected Points: 57.43
Remaining Budget: £0.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Đorđe Petrović                 Bournemouth  £4.6     3.87
 ✅        Karl Darlow                    Leeds        £4.0     4.44

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ladislav Krejcí                Wolves       £4.5     4.45
 🪑        James Justin                   Leeds        £4.0     4.38
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.3     5.47
 ✅        Jurriën Timber                 Arsenal      £6.0     5.38
 ✅        Nico O'Reilly                  Man City     £5.3     4.71

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Declan Rice                    Arsenal      £7.2     5.35
 ✅        Bruno Borges Fernandes         Man Utd      £10.4    5.05
 ✅        Bryan Mbeumo                   Man Utd      £8.3     4.94
 ✅        Anthony Gordon                 Newcastle    £7.3     4.80
 ✅        Morgan Gibbs-White             Nott'm Forest £7.5     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.8     4.67
 ✅        Erling Haaland                 Man City     £14.7    6.17
 ✅        William Osula                  Newcastle    £5.4     4.68

================================================================================
Optimization Status: Optimal

In [18]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 38

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
3,38,Declan Rice,a,MID,Arsenal,Crystal Palace,7.2,5.351649
4,38,Bruno Borges Fernandes,a,MID,Man Utd,Brighton,10.4,5.051865
5,38,Bryan Mbeumo,a,MID,Man Utd,Brighton,8.3,4.937632
6,38,Anthony Gordon,a,MID,Newcastle,Fulham,7.3,4.798455
8,38,Morgan Gibbs-White,a,MID,Nott'm Forest,Bournemouth,7.5,4.705208
10,38,Karl Darlow,a,GK,Leeds,West Ham,4.0,4.437189
0,38,Erling Haaland,a,FWD,Man City,Aston Villa,14.7,6.167373
9,38,William Osula,a,FWD,Newcastle,Fulham,5.4,4.682303
1,38,Gabriel dos Santos Magalhães,a,DEF,Arsenal,Crystal Palace,7.3,5.467884
2,38,Jurriën Timber,d,DEF,Arsenal,Crystal Palace,6.0,5.383644
7,38,Nico O'Reilly,a,DEF,Man City,Aston Villa,5.3,4.709168

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)