In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 32
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  33
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
1557117 Bernard Chalk GW 28 Pick 1
1557117 Bernard Chalk GW 28 Pick 2
1557117 Bernard Chalk GW 28 Pick 3
1557117 Bernard Chalk GW 28 Pick 4
1557117 Bernard Chalk GW 28 Pick 5
1557117 Bernard Chalk GW 28 Pick 6
1557117 Bernard Chalk GW 28 Pick 7
1557117 Bernard Chalk GW 28 Pick 8
1557117 Bernard Chalk GW 28 Pick 9
1557117 Bernard Chalk GW 28 Pick 10
1557117 Bernard Chalk GW 28 Pick 11
1557117 Bernard Chalk GW 28 Pick 12
1557117 Bernard Chalk GW 28 Pick 13
1557117 Bernard Chalk GW 28 Pick 14
1557117 Bernard Chalk GW 28 Pick 15
1557117 Bernard Chalk GW 29 Pick 1
1557117 Bernard Chalk GW 29 Pick 2
1557117 Bernard Chalk GW 29 Pick 3
1557117 Bernard Chalk GW 29 Pick 4
1557117 Bernard Chalk GW 29 Pick 5
1557117 Bernard Chalk GW 29 Pick 6
1557117 Bernard Chalk GW 29 Pick 7
1557117 Bernard Chalk GW 29 Pick 8
1557117 Bernard Chalk GW 29 Pick 9
1557117 Bernard Chalk GW 29 Pick 10
1557117 Bernard Chalk GW 29 Pick 11
1557117 Bernard Chalk GW 29 Pick 12
1557117 Bernard Chalk GW 29 Pick 13
1557117 Bernard Chalk GW 29 Pick 14
1557117 Bernard Chalk GW 29 Pick 15
1557117 Bernard Chalk GW 30 Pick 1
1557117 Bernard Chalk GW 30 Pick 2
1557117 Bernard Chalk GW 30 Pick 3
1557117 Bernard Chalk GW 30 Pick 4
1557117 Bernard Chalk GW 30 Pick 5
1557117 Bernard Chalk GW 30 Pick 6
1557117 Bernard Chalk GW 30 Pick 7
1557117 Bernard Chalk GW 30 Pick 8
1557117 Bernard Chalk GW 30 Pick 9
1557117 Bernard Chalk GW 30 Pick 10
1557117 Bernard Chalk GW 30 Pick 11
1557117 Bernard Chalk GW 30 Pick 12
1557117 Bernard Chalk GW 30 Pick 13
1557117 Bernard Chalk GW 30 Pick 14
1557117 Bernard Chalk GW 30 Pick 15
1557117 Bernard Chalk GW 31 Pick 1
1557117 Bernard Chalk GW 31 Pick 2
1557117 Bernard Chalk GW 31 Pick 3
1557117 Bernard Chalk GW 31 Pick 4
1557117 Bernard Chalk GW 31 Pick 5
1557117 Bernard Chalk GW 31 Pick 6
1557117 Bernard Chalk GW 31 Pick 7
1557117 Bernard Chalk GW 31 Pick 8
1557117 Bernard Chalk GW 31 Pick 9
1557117 Bernard Chalk GW 31 Pick 10
1557117 Bernard Chalk GW 31 Pick 11
1557117 Bernard Chalk GW 31 Pick 12
1557117 Bernard Chalk GW 31 Pick 13
1557117 Bernard Chalk GW 31 Pick 14
1557117 Bernard Chalk GW 31 Pick 15
1557117 Bernard Chalk GW 32 Pick 1
1557117 Bernard Chalk GW 32 Pick 2
1557117 Bernard Chalk GW 32 Pick 3
1557117 Bernard Chalk GW 32 Pick 4
1557117 Bernard Chalk GW 32 Pick 5
1557117 Bernard Chalk GW 32 Pick 6
1557117 Bernard Chalk GW 32 Pick 7
1557117 Bernard Chalk GW 32 Pick 8
1557117 Bernard Chalk GW 32 Pick 9
1557117 Bernard Chalk GW 32 Pick 10
1557117 Bernard Chalk GW 32 Pick 11
1557117 Bernard Chalk GW 32 Pick 12
1557117 Bernard Chalk GW 32 Pick 13
1557117 Bernard Chalk GW 32 Pick 14
1557117 Bernard Chalk GW 32 Pick 15
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW33 to GW37

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,John Stones,d,0,DEF,Man City,1073.5,6.91,72.7,0.773,0.063,1.444
1,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,6.22,100.1,0.152,0.719,1.220
2,Antoine Semenyo,a,0,MID,Man City,1073.5,6.08,102.8,0.385,0.234,1.242
3,Matheus Nunes,a,1,DEF,Man City,1073.5,5.86,108.0,0.048,0.305,1.092
4,Bukayo Saka,d,0,MID,Arsenal,1043.9,5.47,77.2,0.352,0.308,0.878
5,Nico O'Reilly,d,0,DEF,Man City,1073.5,5.46,83.7,0.157,0.070,1.035
6,Mats Wieffer,a,0,MID,Brighton,1007.7,5.45,104.0,0.172,0.407,1.279
7,Erling Haaland,a,0,FWD,Man City,1073.5,5.42,100.8,0.481,0.189,1.345
8,Marc Guéhi,a,0,DEF,Man City,1073.5,5.32,105.2,0.059,0.105,1.036
9,Dominic Calvert-Lewin,a,0,FWD,Leeds,984.7,5.29,94.3,0.580,0.153,1.179
10,Jarrod Bowen,a,0,FWD,West Ham,1103.7,5.28,80.3,0.512,0.317,1.733
11,Harry Wilson,a,0,MID,Fulham,1093.3,5.23,84.1,0.293,0.292,1.513
12,Danny Welbeck,a,0,FWD,Brighton,1007.7,5.19,92.5,0.493,0.238,1.305
13,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1043.9,5.17,83.3,0.073,0.142,0.821
14,Max Alleyne,a,0,DEF,Man City,1073.5,5.10,78.1,0.298,0.061,1.401
15,Declan Rice,a,0,MID,Arsenal,1043.9,5.05,84.7,0.225,0.262,0.901
16,Harvey Barnes,a,0,MID,Newcastle,1088.5,5.00,56.3,0.639,0.275,1.634
17,Cole Palmer,a,0,MID,Chelsea,1057.3,4.96,102.3,0.243,0.169,1.533
18,Mohamed Salah,a,0,MID,Liverpool,1093.4,4.96,67.3,0.423,0.234,1.617
19,Mason Mount,a,0,MID,Man Utd,1081.6,4.89,21.2,1.953,0.678,1.576
20,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,4.89,104.4,0.048,0.031,1.126
21,Morgan Rogers,a,0,MID,Aston Villa,1015.9,4.86,83.2,0.210,0.267,1.251
22,Rico Lewis,a,0,DEF,Man City,1073.5,4.84,75.1,0.287,0.107,1.531
23,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1040.1,4.82,83.8,0.209,0.220,1.337
24,Marcus Tavernier,a,0,MID,Bournemouth,1091.6,4.80,100.2,0.178,0.218,1.407
25,James Ward-Prowse,a,0,MID,Burnley,1124.6,4.79,90.2,0.278,0.211,2.155
26,Bruno Borges Fernandes,a,1,MID,Man Utd,1081.6,4.73,80.3,0.226,0.224,1.409
27,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1040.1,4.71,77.5,0.279,0.145,1.342
28,Pascal Groß,a,0,MID,Brighton,1007.7,4.69,107.7,0.137,0.162,1.247
29,Anthony Gordon,a,0,MID,Newcastle,1088.5,4.58,83.4,0.209,0.212,1.494
30,Pascal Struijk,a,0,DEF,Leeds,984.7,4.57,108.5,0.079,0.045,1.271
31,Ollie Watkins,a,0,FWD,Aston Villa,1015.9,4.53,71.3,0.451,0.273,1.189
32,Mathias Jensen,a,0,MID,Brentford,1085.7,4.52,84.8,0.234,0.101,1.532
33,Jayden Bogle,a,0,DEF,Leeds,984.7,4.51,97.0,0.074,0.066,1.250
34,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1081.6,4.50,83.0,0.230,0.125,1.432
35,Zian Flemming,a,1,FWD,Burnley,1124.6,4.49,89.7,0.524,0.046,1.752
36,William Saliba,a,0,DEF,Arsenal,1043.9,4.49,85.0,0.047,0.033,0.909
37,Alex Iwobi,a,0,MID,Fulham,1093.3,4.48,86.3,0.197,0.145,1.494
38,Francisco Evanilson de Lima Barbosa,a,0,FWD,Bournemouth,1091.6,4.48,99.6,0.337,0.154,1.609
39,Kiernan Dewsbury-Hall,a,0,MID,Everton,1099.0,4.46,82.9,0.210,0.131,1.403
40,Pedro Lomba Neto,a,0,MID,Chelsea,1057.3,4.43,86.2,0.176,0.269,1.525
41,Rayan Cherki,a,0,MID,Man City,1073.5,4.43,76.6,0.233,0.181,1.182
42,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1057.3,4.43,96.4,0.410,0.074,1.421
43,Cody Gakpo,a,0,MID,Liverpool,1093.4,4.42,81.0,0.232,0.117,1.546
44,James Justin,a,0,DEF,Leeds,984.7,4.42,107.5,0.042,0.058,1.245
45,Jack Hinshelwood,a,0,MID,Brighton,1007.7,4.41,89.9,0.157,0.190,1.280
46,Alex Scott,a,0,MID,Bournemouth,1091.6,4.40,102.5,0.144,0.093,1.416
47,Lucas Digne,a,0,DEF,Aston Villa,1015.9,4.40,76.1,0.054,0.197,1.267
48,Dwight McNeil,a,0,MID,Everton,1099.0,4.40,71.6,0.266,0.183,1.401
49,Enzo Fernández,a,0,MID,Chelsea,1057.3,4.39,91.0,0.183,0.145,1.450

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 33 and 37:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,John Stones,d,DEF,Man City,5.4,1073.5,31.18,72.7,0.773,0.063,1.444
1,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,6.2,1073.5,28.85,100.1,0.152,0.719,1.220
2,Bukayo Saka,d,MID,Arsenal,9.8,1043.9,28.09,77.2,0.352,0.308,0.878
3,Antoine Semenyo,a,MID,Man City,8.2,1073.5,27.97,102.8,0.385,0.234,1.242
4,Gabriel dos Santos Magalhães,a,DEF,Arsenal,7.2,1043.9,27.25,83.3,0.073,0.142,0.821
5,Matheus Nunes,a,DEF,Man City,5.3,1073.5,26.58,108.0,0.048,0.305,1.092
6,Harry Wilson,a,MID,Fulham,6.1,1093.3,26.37,84.1,0.293,0.292,1.513
7,Jarrod Bowen,a,FWD,West Ham,7.6,1103.7,26.33,80.3,0.512,0.317,1.733
8,Declan Rice,a,MID,Arsenal,7.3,1043.9,25.86,84.7,0.225,0.262,0.901
9,Mats Wieffer,a,MID,Brighton,4.9,1007.7,25.46,104.0,0.172,0.407,1.279
10,Harvey Barnes,a,MID,Newcastle,6.1,1088.5,25.24,56.3,0.639,0.275,1.634
11,Erling Haaland,a,FWD,Man City,14.4,1073.5,24.97,100.8,0.481,0.189,1.345
12,Mohamed Salah,a,MID,Liverpool,14.0,1093.4,24.61,67.3,0.423,0.234,1.617
13,Morgan Rogers,a,MID,Aston Villa,7.4,1015.9,24.61,83.2,0.210,0.267,1.251
14,Nico O'Reilly,d,DEF,Man City,5.0,1073.5,24.58,83.7,0.157,0.070,1.035
15,Mason Mount,a,MID,Man Utd,5.9,1081.6,24.51,21.2,1.953,0.678,1.576
16,Marc Guéhi,a,DEF,Man City,5.1,1073.5,24.38,105.2,0.059,0.105,1.036
17,Dominic Calvert-Lewin,a,FWD,Leeds,5.6,984.7,24.25,94.3,0.580,0.153,1.179
18,Bruno Borges Fernandes,a,MID,Man Utd,10.3,1081.6,23.94,80.3,0.226,0.224,1.409
19,Danny Welbeck,a,FWD,Brighton,6.2,1007.7,23.92,92.5,0.493,0.238,1.305

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        1847.0
1                 Ryan Boyce  5398818.0        1838.0
2               Samia Shelim  6506490.0        1773.0
3         Christopher Harris    28660.0        1772.0
4          William Partridge  6588565.0        1768.0
5               Jack Carroll  4438260.0        1739.0
6               Tommy Davies  7845816.0        1731.0
7              Rizwan Shelim  3058994.0        1715.0
8         Christopher Harris   145486.0        1710.0
9                 Rhys Birdy  5810139.0        1705.0
10             Ollie Carroll  5181285.0        1683.0
11               Nafi Shelim  4776281.0        1664.0
12            Conner Harling  3421093.0        1652.0
13             Tajwar Shelim  4773459.0        1620.0
14  Christakis Christodoulou  7474864.0        1582.0
15              Tahmid Haque  6394829.0        1495.0
16            Charlie Garner  9432680.0        1485.0
17               Simon Meech  6764382.0        1477.0
18              Will Hossack  4792527.0        1468.0
19              Holly Stower  7367977.0        1379.0
20            Rachel Aumayer  9763056.0        1221.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW33 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
244,1,16.0,Bukayo Saka,d,9.8,MID,Arsenal,34.063114,0.0,34.063114,0.000000,34.063114,0.0,34.063114,34.063114,34.063114
179,1,691.0,Dominic Calvert-Lewin,a,5.6,FWD,Leeds,29.392832,0.0,29.392832,0.000000,29.392832,0.0,29.392832,29.392832,29.392832
180,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,27.820365,0.0,27.820365,0.000000,27.820365,0.0,27.820365,27.820365,27.820365
406,1,8.0,Jurriën Timber,d,6.3,DEF,Arsenal,27.551137,0.0,27.551137,0.000000,27.551137,0.0,27.551137,27.551137,27.551137
420,1,237.0,Enzo Fernández,a,6.5,MID,Chelsea,24.167945,0.0,24.167945,0.000000,24.167945,0.0,24.167945,24.167945,24.167945
285,1,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,23.748638,0.0,23.748638,0.000000,23.748638,0.0,23.748638,23.748638,23.748638
35,1,341.0,Karl Darlow,a,3.9,GK,Leeds,22.449229,0.0,22.449229,0.000000,22.449229,0.0,22.449229,22.449229,22.449229
353,1,32.0,Emiliano Martínez Romero,d,5.1,GK,Aston Villa,21.996967,0.0,21.996967,0.000000,21.996967,0.0,21.996967,21.996967,21.996967
329,1,694.0,Nordi Mukiele,a,4.5,DEF,Sunderland,21.614627,20.0,17.291702,-4.322925,17.291702,0.0,12.968776,17.291702,17.291702
7,1,337.0,Raúl Jiménez Rodríguez,a,6.2,FWD,Fulham,16.189696,0.0,16.189696,0.000000,16.189696,0.0,16.189696,16.189696,16.189696
134,1,661.0,Hugo Ekitiké,a,9.3,FWD,Liverpool,14.976256,0.0,14.976256,0.000000,14.976256,0.0,14.976256,14.976256,14.976256
128,1,373.0,Virgil van Dijk,a,6.3,DEF,Liverpool,22.508112,40.0,13.504867,-9.003245,13.504867,0.0,4.501622,13.504867,13.504867
208,1,5.0,Gabriel dos Santos Magalhães,a,7.2,DEF,Arsenal,32.427781,80.0,6.485556,-25.942225,6.485556,0.0,-19.456669,6.485556,6.485556
199,1,329.0,Harry Wilson,a,6.1,MID,Fulham,31.716328,80.0,6.343266,-25.373063,6.343266,0.0,-19.029797,6.343266,6.343266
403,1,449.0,Bruno Borges Fernandes,a,10.3,MID,Man Utd,28.897436,120.0,-5.779487,-34.676924,-5.779487,0.0,-40.456411,-5.779487,-5.779487

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW33 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
230,0,430.0,Erling Haaland,a,14.4,FWD,Man City,29.932591,120.0,-5.986518,-35.919109,0.000000,-35.919109,-41.905627,-35.919109,-5.986518
372,0,82.0,Antoine Semenyo,a,8.2,MID,Man City,33.391303,60.0,13.356521,-20.034782,0.000000,-20.034782,-6.678261,-20.034782,13.356521
118,0,249.0,João Pedro Junqueira de Jesus,a,7.8,FWD,Chelsea,24.704432,80.0,4.940886,-19.763546,0.000000,-19.763546,-14.822659,-19.763546,4.940886
116,0,21.0,Declan Rice,a,7.3,MID,Arsenal,30.937554,60.0,12.375021,-18.562532,0.000000,-18.562532,-6.187511,-18.562532,12.375021
186,0,411.0,Nico O'Reilly,d,5.0,DEF,Man City,28.569716,40.0,17.141830,-11.427886,0.000000,-11.427886,5.713943,-11.427886,17.141830
432,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.3,FWD,Brentford,26.002273,40.0,15.601364,-10.400909,0.000000,-10.400909,5.200455,-10.400909,15.601364
233,0,119.0,Bryan Mbeumo,a,8.6,MID,Man Utd,25.412800,40.0,15.247680,-10.165120,0.000000,-10.165120,5.082560,-10.165120,15.247680
13,0,72.0,Marcos Senesi Barón,a,5.1,DEF,Bournemouth,23.090716,40.0,13.854430,-9.236286,0.000000,-9.236286,4.618143,-9.236286,13.854430
108,0,684.0,Malick Thiaw,a,5.1,DEF,Newcastle,21.135669,40.0,12.681401,-8.454267,0.000000,-8.454267,4.227134,-8.454267,12.681401
133,0,624.0,Jarrod Bowen,a,7.6,FWD,West Ham,32.296355,20.0,25.837084,-6.459271,0.000000,-6.459271,19.377813,-6.459271,25.837084
403,1,449.0,Bruno Borges Fernandes,a,10.3,MID,Man Utd,28.897436,120.0,-5.779487,-34.676924,-5.779487,0.000000,-40.456411,-5.779487,-5.779487
407,0,260.0,Marc Guéhi,a,5.1,DEF,Man City,28.631714,20.0,22.905372,-5.726343,0.000000,-5.726343,17.179029,-5.726343,22.905372
18,0,485.0,Anthony Gordon,a,7.4,MID,Newcastle,27.776934,20.0,22.221547,-5.555387,0.000000,-5.555387,16.666161,-5.555387,22.221547
38,0,242.0,Kiernan Dewsbury-Hall,a,5.1,MID,Everton,27.048575,20.0,21.638860,-5.409715,0.000000,-5.409715,16.229145,-5.409715,21.638860
25,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,25.719021,20.0,20.575217,-5.143804,0.000000,-5.143804,15.431412,-5.143804,20.575217
325,0,457.0,Carlos Henrique Casimiro,a,5.7,MID,Man Utd,24.701684,20.0,19.761348,-4.940337,0.000000,-4.940337,14.821011,-4.940337,19.761348
347,0,26.0,Martín Zubimendi Ibáñez,a,5.1,MID,Arsenal,24.556485,20.0,19.645188,-4.911297,0.000000,-4.911297,14.733891,-4.911297,19.645188
207,0,1.0,David Raya Martín,a,6.0,GK,Arsenal,24.385172,20.0,19.508138,-4.877034,0.000000,-4.877034,14.631103,-4.877034,19.508138
39,0,683.0,Omar Alderete,a,4.1,DEF,Sunderland,22.489785,20.0,17.991828,-4.497957,0.000000,-4.497957,13.493871,-4.497957,17.991828
102,0,517.0,Elliot Anderson,a,5.5,MID,Nott'm Forest,22.475322,20.0,17.980257,-4.495064,0.000000,-4.495064,13.485193,-4.495064,17.980257

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW33 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
395,0,409.0,John Stones,d,5.4,DEF,Man City,36.847294,0.0,36.847294,0.0,0.0,0.0,36.847294,0.0,36.847294
139,0,416.0,Bernardo Mota Veiga de Carvalho e Silva,a,6.2,MID,Man City,34.094976,0.0,34.094976,0.0,0.0,0.0,34.094976,0.0,34.094976
205,0,407.0,Matheus Nunes,a,5.3,DEF,Man City,31.342411,0.0,31.342411,0.0,0.0,0.0,31.342411,0.0,31.342411
294,0,173.0,Mats Wieffer,a,4.9,MID,Brighton,30.512306,0.0,30.512306,0.0,0.0,0.0,30.512306,0.0,30.512306
115,0,487.0,Harvey Barnes,a,6.1,MID,Newcastle,30.352195,0.0,30.352195,0.0,0.0,0.0,30.352195,0.0,30.352195
400,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,29.963362,0.0,29.963362,0.0,0.0,0.0,29.963362,0.0,29.963362
363,0,455.0,Mason Mount,a,5.9,MID,Man Utd,29.409683,0.0,29.409683,0.0,0.0,0.0,29.409683,0.0,29.409683
98,0,47.0,Morgan Rogers,a,7.4,MID,Aston Villa,29.168041,0.0,29.168041,0.0,0.0,0.0,29.168041,0.0,29.168041
5,0,178.0,Danny Welbeck,a,6.2,FWD,Brighton,28.464591,0.0,28.464591,0.0,0.0,0.0,28.464591,0.0,28.464591
6,0,515.0,Morgan Gibbs-White,a,7.4,MID,Nott'm Forest,28.352544,0.0,28.352544,0.0,0.0,0.0,28.352544,0.0,28.352544
261,0,6.0,William Saliba,a,6.1,DEF,Arsenal,28.271055,0.0,28.271055,0.0,0.0,0.0,28.271055,0.0,28.271055
361,0,516.0,Callum Hudson-Odoi,a,5.7,MID,Nott'm Forest,27.451304,0.0,27.451304,0.0,0.0,0.0,27.451304,0.0,27.451304
281,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,27.207351,0.0,27.207351,0.0,0.0,0.0,27.207351,0.0,27.207351
271,0,64.0,Ollie Watkins,a,8.5,FWD,Aston Villa,27.172654,0.0,27.172654,0.0,0.0,0.0,27.172654,0.0,27.172654
253,0,794.0,Max Alleyne,a,3.9,DEF,Man City,27.128217,0.0,27.128217,0.0,0.0,0.0,27.128217,0.0,27.128217
104,0,324.0,Alex Iwobi,a,6.4,MID,Fulham,27.070704,0.0,27.070704,0.0,0.0,0.0,27.070704,0.0,27.070704
276,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,26.946107,0.0,26.946107,0.0,0.0,0.0,26.946107,0.0,26.946107
0,0,300.0,Dwight McNeil,a,5.5,MID,Everton,26.776009,0.0,26.776009,0.0,0.0,0.0,26.776009,0.0,26.776009
286,0,384.0,Cody Gakpo,a,7.3,MID,Liverpool,26.629875,0.0,26.629875,0.0,0.0,0.0,26.629875,0.0,26.629875
26,0,84.0,Marcus Tavernier,a,5.4,MID,Bournemouth,26.621384,0.0,26.621384,0.0,0.0,0.0,26.621384,0.0,26.621384

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £89.2m / £102.4m
Total Weighted Expected Points: 298.63
Remaining Budget: £13.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0    19.26
 ✅        David Raya Martín              Arsenal      £6.0    20.39

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lucas Digne                    Aston Villa  £4.5    22.11
 🪑        Pascal Struijk                 Leeds        £4.3    21.10
 ✅        John Stones                    Man City     £5.4    31.18
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2    27.25
 ✅        Matheus Nunes                  Man City     £5.3    26.58

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    28.85
 ✅        Bukayo Saka                    Arsenal      £9.8    28.09
 ✅        Harry Wilson                   Fulham       £6.1    26.37
 ✅        Mats Wieffer                   Brighton     £4.9    25.46
 ✅        Harvey Barnes                  Newcastle    £6.1    25.24

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.2    23.92
 ✅        Jarrod Bowen                   West Ham     £7.6    26.33
 ✅        Dominic Calvert-Lewin          Leeds        £5.6    24.25

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £97.2m / £102.4m
Total Weighted Expected Points: 346.70
Remaining Budget: £5.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mads Hermansen                 West Ham     £4.2    22.56
 ✅        Melker Ellborg                 Sunderland   £4.0    23.12

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Michael Keane                  Everton      £4.6    25.51
 🪑        Jurriën Timber                 Arsenal      £6.3    27.55
 ✅        Matheus Nunes                  Man City     £5.3    31.34
 ✅        William Saliba                 Arsenal      £6.1    28.27
 ✅        John Stones                    Man City     £5.4    36.85

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Harvey Barnes                  Newcastle    £6.1    30.35
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    34.09
 ✅        Bukayo Saka                    Arsenal      £9.8    34.06
 ✅        Mats Wieffer                   Brighton     £4.9    30.51
 ✅        Mohamed Salah                  Liverpool    £14.0   29.96

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ollie Watkins                  Aston Villa  £8.5    27.17
 ✅        Danny Welbeck                  Brighton     £6.2    28.46
 ✅        Dominic Calvert-Lewin          Leeds        £5.6    29.39

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,33.0,John Stones,d,DEF,Man City,Arsenal; Burnley,5.4,13.343035
1,33.0,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,Arsenal; Burnley,6.2,11.409083
2,33.0,Antoine Semenyo,a,MID,Man City,Arsenal; Burnley,8.2,11.346016
3,33.0,Matheus Nunes,a,DEF,Man City,Arsenal; Burnley,5.3,11.206146
4,33.0,Nico O'Reilly,d,DEF,Man City,Arsenal; Burnley,5.0,10.589679
5,33.0,Erling Haaland,a,FWD,Man City,Arsenal; Burnley,14.4,10.077303
6,33.0,Marc Guéhi,a,DEF,Man City,Arsenal; Burnley,5.1,9.970913
7,33.0,Mats Wieffer,a,MID,Brighton,Spurs; Chelsea,4.9,9.951311
8,33.0,Dominic Calvert-Lewin,a,FWD,Leeds,Wolves; Bournemouth,5.6,9.938662
9,33.0,Max Alleyne,a,DEF,Man City,Arsenal; Burnley,3.9,9.751276

In [17]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW33 to GW38...

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £83.0m / £102.4m
Total Weighted Expected Points: 111.56
Remaining Budget: £19.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5     7.25
 ✅        Karl Darlow                    Leeds        £3.9     7.60

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Adrien Truffert                Bournemouth  £4.7     8.13
 🪑        Marcos Senesi Barón            Bournemouth  £5.1     8.09
 ✅        John Stones                    Man City     £5.4    13.34
 ✅        Matheus Nunes                  Man City     £5.3    11.21
 ✅        Pascal Struijk                 Leeds        £4.3     8.37

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    11.41
 ✅        Mats Wieffer                   Brighton     £4.9     9.95
 ✅        Cole Palmer                    Chelsea      £10.6    9.06
 ✅        James Ward-Prowse              Burnley      £5.6     8.93
 ✅        Marcus Tavernier               Bournemouth  £5.4     8.92

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Zian Flemming                  Burnley      £5.3     8.24
 ✅        Dominic Calvert-Lewin          Leeds        £5.6     9.94
 ✅        Danny Welbeck                  Brighton     £6.2     9.66

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.3m / £102.4m
Total Weighted Expected Points: 55.09
Remaining Budget: £2.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.79
 ✅        Mads Hermansen                 West Ham     £4.2     3.89

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Konstantinos Mavropanos        West Ham     £4.4     4.27
 🪑        Lucas Digne                    Aston Villa  £4.5     4.21
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.24
 ✅        Michael Keane                  Everton      £4.6     4.68
 ✅        William Saliba                 Arsenal      £6.1     4.43

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bukayo Saka                    Arsenal      £9.8     5.54
 ✅        Harry Wilson                   Fulham       £6.1     5.17
 ✅        Mohamed Salah                  Liverpool    £14.0    5.03
 ✅        Mason Mount                    Man Utd      £5.9     4.88
 ✅        Harvey Barnes                  Newcastle    £6.1     4.86

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.38
 ✅        Jarrod Bowen                   West Ham     £7.6     5.28
 ✅        Ollie Watkins                  Aston Villa  £8.5     4.43

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £93.9m / £102.4m
Total Weighted Expected Points: 59.29
Remaining Budget: £8.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mads Hermansen                 West Ham     £4.2     3.87
 ✅        Emiliano Martínez Romero       Aston Villa  £5.1     4.11

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Struijk                 Leeds        £4.3     4.48
 🪑        Nathan Collins                 Brentford    £4.9     4.43
 ✅        John Stones                    Man City     £5.4     5.96
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.27
 ✅        Lucas Digne                    Aston Villa  £4.5     4.88

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     5.82
 ✅        Bukayo Saka                    Arsenal      £9.8     5.64
 ✅        Antoine Semenyo                Man City     £8.2     5.56
 ✅        Declan Rice                    Arsenal      £7.3     5.17
 ✅        Morgan Rogers                  Aston Villa  £7.4     5.12

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.2     4.50
 ✅        Jarrod Bowen                   West Ham     £7.6     5.28
 ✅        Dominic Calvert-Lewin          Leeds        £5.6     4.75

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £92.1m / £102.4m
Total Weighted Expected Points: 61.96
Remaining Budget: £10.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.94
 ✅        David Raya Martín              Arsenal      £6.0     4.53

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matty Cash                     Aston Villa  £4.7     4.75
 🪑        Ferdi Kadıoğlu                 Brighton     £4.4     4.18
 ✅        John Stones                    Man City     £5.4     5.95
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.81
 ✅        Lucas Digne                    Aston Villa  £4.5     5.21

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bukayo Saka                    Arsenal      £9.8     5.85
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     5.77
 ✅        Morgan Rogers                  Aston Villa  £7.4     5.72
 ✅        Antoine Semenyo                Man City     £8.2     5.52
 ✅        Mats Wieffer                   Brighton     £4.9     5.51

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.6     4.91
 ✅        Danny Welbeck                  Brighton     £6.2     5.16
 ✅        Jarrod Bowen                   West Ham     £7.6     5.15

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £93.8m / £102.4m
Total Weighted Expected Points: 62.61
Remaining Budget: £8.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.84
 ✅        Mads Hermansen                 West Ham     £4.2     3.86

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Timothy Castagne               Fulham       £4.3     4.33
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     6.59
 ✅        John Stones                    Man City     £5.4     5.93
 ✅        William Saliba                 Arsenal      £6.1     5.89
 ✅        Jurriën Timber                 Arsenal      £6.3     5.74

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     5.85
 ✅        Harry Wilson                   Fulham       £6.1     5.71
 ✅        Antoine Semenyo                Man City     £8.2     5.54
 ✅        Harvey Barnes                  Newcastle    £6.1     5.27
 ✅        Bruno Borges Fernandes         Man Utd      £10.3    5.20

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.6     4.65
 🪑        Danny Welbeck                  Brighton     £6.2     4.60
 ✅        Jarrod Bowen                   West Ham     £7.6     5.29

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.4m / £102.4m
Total Weighted Expected Points: 59.69
Remaining Budget: £2.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.86
 ✅        Mads Hermansen                 West Ham     £4.2     4.01

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Michael Keane                  Everton      £4.6     4.66
 🪑        William Saliba                 Arsenal      £6.1     4.43
 ✅        John Stones                    Man City     £5.4     5.67
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.18
 ✅        Matheus Nunes                  Man City     £5.3     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bukayo Saka                    Arsenal      £9.8     5.98
 ✅        Antoine Semenyo                Man City     £8.2     5.42
 ✅        Mohamed Salah                  Liverpool    £14.0    5.35
 ✅        Harry Wilson                   Fulham       £6.1     5.35
 ✅        Harvey Barnes                  Newcastle    £6.1     5.12

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.2     4.54
 ✅        Jarrod Bowen                   West Ham     £7.6     5.97
 ✅        Dominic Calvert-Lewin          Leeds        £5.6     5.14

================================================================================
Optimization Status: Optimal

In [18]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 33

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
1,33,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,Arsenal; Burnley,6.2,11.409083
3,33,Mats Wieffer,a,MID,Brighton,Spurs; Chelsea,4.9,9.951311
6,33,Cole Palmer,a,MID,Chelsea,Man Utd; Brighton,10.6,9.061341
7,33,James Ward-Prowse,a,MID,Burnley,Nott'm Forest; Man City,5.6,8.925260
8,33,Marcus Tavernier,a,MID,Bournemouth,Newcastle; Leeds,5.4,8.923564
10,33,Karl Darlow,a,GK,Leeds,Wolves; Bournemouth,3.9,7.599889
4,33,Dominic Calvert-Lewin,a,FWD,Leeds,Wolves; Bournemouth,5.6,9.938662
5,33,Danny Welbeck,a,FWD,Brighton,Spurs; Chelsea,6.2,9.660943
0,33,John Stones,d,DEF,Man City,Arsenal; Burnley,5.4,13.343035
2,33,Matheus Nunes,a,DEF,Man City,Arsenal; Burnley,5.3,11.206146
9,33,Pascal Struijk,a,DEF,Leeds,Wolves; Bournemouth,4.3,8.369896

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)