In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 27
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  28
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4
5398818 Ryan Boyce GW 5 Pick 5
5398818 Ryan Boyce GW 5 Pick 6
5398818 Ryan Boyce GW 5 Pick 7
5398818 Ryan Boyce GW 5 Pick 8
5398818 Ryan Boyce GW 5 Pick 9
5398818 Ryan Boyce GW 5 Pick 10
5398818 Ryan Boyce GW 5 Pick 11
5398818 Ryan Boyce GW 5 Pick 12
5398818 Ryan Boyce GW 5 Pick 13
5398818 Ryan Boyce GW 5 Pick 14
5398818 Ryan Boyce GW 5 Pick 15
5398818 Ryan Boyce GW 6 Pick 1
5398818 Ryan Boyce GW 6 Pick 2
5398818 Ryan Boyce GW 6 Pick 3
5398818 Ryan Boyce GW 6 Pick 4
5398818 Ryan Boyce GW 6 Pick 5
5398818 Ryan Boyce GW 6 Pick 6
5398818 Ryan Boyce GW 6 Pick 7
5398818 Ryan Boyce GW 6 Pick 8
5398818 Ryan Boyce GW 6 Pick 9
5398818 Ryan Boyce GW 6 Pick 10
5398818 Ryan Boyce GW 6 Pick 11
5398818 Ryan Boyce GW 6 Pick 12
5398818 Ryan Boyce GW 6 Pick 13
5398818 Ryan Boyce GW 6 Pick 14
5398818 Ryan Boyce GW 6 Pick 15
5398818 Ryan Boyce GW 7 Pick 1
5398818 Ryan Boyce GW 7 Pick 2
5398818 Ryan Boyce GW 7 Pick 3
5398818 Ryan Boyce GW 7 Pick 4
5398818 Ryan Boyce GW 7 Pick 5
5398818 Ryan Boyce GW 7 Pick 6
5398818 Ryan Boyce GW 7 Pick 7
5398818 Ryan Boyce GW 7 Pick 8
5398818 Ryan Boyce GW 7 Pick 9
5398818 Ryan Boyce GW 7 Pick 10
5398818 Ryan Boyce GW 7 Pick 11
5398818 Ryan Boyce GW 7 Pick 12
5398818 Ryan Boyce GW 7 Pick 13
5398818 Ryan Boyce GW 7 Pick 14
5398818 Ryan Boyce GW 7 Pick 15
5398818 Ryan Boyce GW 8 Pick 1
5398818 Ryan Boyce GW 8 Pick 2
5398818 Ryan Boyce GW 8 Pick 3
5398818 Ryan Boyce GW 8 Pick 4
5398818 Ryan Boyce GW 8 Pick 5
5398818 Ryan Boyce GW 8 Pick 6
5398818 Ryan Boyce GW 8 Pick 7
5398818 Ryan Boyce GW 8 Pick 8
5398818 Ryan Boyce GW 8 Pick 9
5398818 Ryan Boyce GW 8 Pick 10
5398818 Ryan Boyce GW 8 Pick 11
5398818 Ryan Boyce GW 8 Pick 12
5398818 Ryan Boyce GW 8 Pick 13
5398818 Ryan Boyce GW 8 Pick 14
5398818 Ryan Boyce GW 8 Pick 15
5398818 Ryan Boyce GW 9 Pick 1
5398818 Ryan Boyce GW 9 Pick 2
5398818 Ryan Boyce GW 9 Pick 3
5398818 Ryan Boyce GW 9 Pick 4
5398818 Ryan Boyce GW 9 Pick 5
5398818 Ryan Boyce GW 9 Pick 6
5398818 Ryan Boyce GW 9 Pick 7
5398818 Ryan Boyce GW 9 Pick 8
5398818 Ryan Boyce GW 9 Pick 9
5398818 Ryan Boyce GW 9 Pick 10
5398818 Ryan Boyce GW 9 Pick 11
5398818 Ryan Boyce GW 9 Pick 12
5398818 Ryan Boyce GW 9 Pick 13
5398818 Ryan Boyce GW 9 Pick 14
5398818 Ryan Boyce GW 9 Pick 15
5398818 Ryan Boyce GW 10 Pick 1
5398818 Ryan Boyce GW 10 Pick 2
5398818 Ryan Boyce GW 10 Pick 3
5398818 Ryan Boyce GW 10 Pick 4
5398818 Ryan Boyce GW 10 Pick 5
5398818 Ryan Boyce GW 10 Pick 6
5398818 Ryan Boyce GW 10 Pick 7
5398818 Ryan Boyce GW 10 Pick 8
5398818 Ryan Boyce GW 10 Pick 9
5398818 Ryan Boyce GW 10 Pick 10
5398818 Ryan Boyce GW 10 Pick 11
5398818 Ryan Boyce GW 10 Pick 12
5398818 Ryan Boyce GW 10 Pick 13

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW28 to GW32

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Mohamed Salah,a,0,MID,Liverpool,996.8,4.89,78.4,0.264,0.162,1.009
1,Ibrahima Konaté,a,1,DEF,Liverpool,996.8,4.84,86.9,0.042,0.048,0.918
2,Alexis Mac Allister,a,0,MID,Liverpool,996.8,4.83,79.3,0.227,0.177,0.996
3,Enzo Fernández,a,0,MID,Chelsea,1154.0,4.82,84.4,0.239,0.203,1.717
4,Florian Wirtz,d,0,MID,Liverpool,996.8,4.78,81.9,0.182,0.199,0.998
5,Bruno Borges Fernandes,a,1,MID,Man Utd,1071.4,4.78,84.3,0.215,0.195,1.387
6,Virgil van Dijk,a,0,DEF,Liverpool,996.8,4.72,79.7,0.051,0.050,0.947
7,Milos Kerkez,a,0,DEF,Liverpool,996.8,4.71,77.0,0.043,0.052,0.960
8,Dominik Szoboszlai,a,1,MID,Liverpool,996.8,4.70,83.6,0.162,0.189,1.039
9,Tyrone Mings,a,1,DEF,Aston Villa,1027.8,4.68,83.4,0.040,0.052,0.917
10,Harry Wilson,a,0,MID,Fulham,1009.4,4.67,82.3,0.207,0.159,1.184
11,Andrew Robertson,a,0,DEF,Liverpool,996.8,4.61,60.2,0.039,0.072,0.794
12,Morgan Rogers,a,0,MID,Aston Villa,1027.8,4.60,86.0,0.167,0.147,1.068
13,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,1027.8,4.59,87.0,0.042,0.045,0.988
14,Nico O'Reilly,a,0,DEF,Man City,1029.2,4.57,81.8,0.082,0.066,0.843
15,Cole Palmer,a,0,MID,Chelsea,1154.0,4.56,70.4,0.276,0.197,1.619
16,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,984.9,4.56,84.2,0.448,0.070,1.206
17,Ian Maatsen,a,1,DEF,Aston Villa,1027.8,4.55,76.1,0.038,0.055,0.927
18,Mathias Jensen,a,0,MID,Brentford,984.9,4.53,79.9,0.166,0.165,1.078
19,Viktor Gyökeres,a,0,FWD,Arsenal,1081.5,4.53,78.8,0.625,0.146,1.137
20,Jeremie Frimpong,d,0,DEF,Liverpool,996.8,4.52,64.5,0.087,0.053,1.048
21,Antoine Semenyo,a,0,MID,Man City,1029.2,4.51,85.5,0.259,0.187,0.939
22,Matty Cash,a,0,DEF,Aston Villa,1027.8,4.50,85.4,0.041,0.045,1.029
23,Dango Ouattara,a,0,MID,Brentford,984.9,4.47,76.4,0.216,0.141,1.099
24,Alex Iwobi,a,0,MID,Fulham,1009.4,4.47,84.1,0.176,0.155,1.254
25,Vitaly Janelt,a,0,MID,Brentford,984.9,4.45,78.4,0.165,0.163,1.083
26,Iliman Ndiaye,a,0,MID,Everton,1084.7,4.44,84.5,0.193,0.137,1.378
27,Lamare Bogarde,a,0,DEF,Aston Villa,1027.8,4.44,65.3,0.037,0.058,0.872
28,Enzo Le Fée,a,0,MID,Sunderland,1037.9,4.43,85.7,0.144,0.186,1.341
29,Matheus Nunes,a,1,DEF,Man City,1029.2,4.43,81.9,0.040,0.065,0.818
30,Alex Scott,a,0,MID,Bournemouth,1069.2,4.41,84.4,0.172,0.131,1.356
31,Emiliano Martínez Romero,a,1,GK,Aston Villa,1027.8,4.39,89.9,NaN,NaN,0.969
32,Pau Torres,a,0,DEF,Aston Villa,1027.8,4.38,66.5,0.086,0.047,1.019
33,Abdukodir Khusanov,a,0,DEF,Man City,1029.2,4.35,74.3,0.041,0.053,0.766
34,Michael Kayode,d,0,DEF,Brentford,984.9,4.35,85.4,0.040,0.048,1.135
35,Sepp van den Berg,a,0,DEF,Brentford,984.9,4.32,84.4,0.044,0.044,1.143
36,Carlos Henrique Casimiro,a,0,MID,Man Utd,1071.4,4.32,84.2,0.147,0.157,1.378
37,Keane Lewis-Potter,a,0,DEF,Brentford,984.9,4.31,76.3,0.057,0.058,1.146
38,Cody Gakpo,a,0,MID,Liverpool,996.8,4.31,74.4,0.165,0.143,1.027
39,Bryan Mbeumo,a,0,MID,Man Utd,1071.4,4.30,82.9,0.179,0.137,1.366
40,Rico Henry,a,0,DEF,Brentford,984.9,4.30,79.5,0.058,0.052,1.137
41,Max Alleyne,d,0,DEF,Man City,1029.2,4.28,63.0,0.149,0.053,0.917
42,Marc Guéhi,a,0,DEF,Man City,1029.2,4.27,85.2,0.043,0.052,0.900
43,Joachim Andersen,a,0,DEF,Fulham,1009.4,4.26,86.9,0.041,0.043,1.175
44,Moisés Caicedo Corozo,a,0,MID,Chelsea,1154.0,4.26,84.4,0.123,0.201,1.598
45,Alisson Becker,a,0,GK,Liverpool,996.8,4.25,90.0,NaN,NaN,0.978
46,Crysencio Summerville,a,0,MID,West Ham,1107.3,4.25,85.6,0.179,0.109,1.514
47,Ethan Pinnock,a,0,DEF,Brentford,984.9,4.25,60.9,0.210,0.060,1.316
48,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1154.0,4.23,76.8,0.405,0.093,1.330
49,Kenny Tete,a,0,DEF,Fulham,1009.4,4.23,77.7,0.041,0.051,1.179

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 28 and 32:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Enzo Fernández,a,MID,Chelsea,6.9,1154.0,24.21,84.4,0.239,0.203,1.717
1,Mohamed Salah,a,MID,Liverpool,14.0,996.8,24.20,78.4,0.264,0.162,1.009
2,Ibrahima Konaté,a,DEF,Liverpool,5.4,996.8,24.03,86.9,0.042,0.048,0.918
3,Bruno Borges Fernandes,a,MID,Man Utd,9.8,1071.4,23.98,84.3,0.215,0.195,1.387
4,Alexis Mac Allister,a,MID,Liverpool,6.2,996.8,23.96,79.3,0.227,0.177,0.996
5,Florian Wirtz,d,MID,Liverpool,8.4,996.8,23.70,81.9,0.182,0.199,0.998
6,Virgil van Dijk,a,DEF,Liverpool,5.9,996.8,23.58,79.7,0.051,0.050,0.947
7,Tyrone Mings,a,DEF,Aston Villa,4.3,1027.8,23.35,83.4,0.040,0.052,0.917
8,Harry Wilson,a,MID,Fulham,5.9,1009.4,23.30,82.3,0.207,0.159,1.184
9,Dominik Szoboszlai,a,MID,Liverpool,6.7,996.8,23.29,83.6,0.162,0.189,1.039
10,Milos Kerkez,a,DEF,Liverpool,5.6,996.8,22.97,77.0,0.043,0.052,0.960
11,Andrew Robertson,a,DEF,Liverpool,5.7,996.8,22.90,60.2,0.039,0.072,0.794
12,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,1027.8,22.88,87.0,0.042,0.045,0.988
13,Cole Palmer,a,MID,Chelsea,10.6,1154.0,22.86,70.4,0.276,0.197,1.619
14,Igor Thiago Nascimento Rodrigues,a,FWD,Brentford,7.0,984.9,22.77,84.2,0.448,0.070,1.206
15,Morgan Rogers,a,MID,Aston Villa,7.7,1027.8,22.76,86.0,0.167,0.147,1.068
16,Ian Maatsen,a,DEF,Aston Villa,4.2,1027.8,22.69,76.1,0.038,0.055,0.927
17,Mathias Jensen,a,MID,Brentford,4.9,984.9,22.49,79.9,0.166,0.165,1.078
18,Matty Cash,a,DEF,Aston Villa,4.9,1027.8,22.39,85.4,0.041,0.045,1.029
19,Alex Iwobi,a,MID,Fulham,6.3,1009.4,22.23,84.1,0.176,0.155,1.254

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        1513.0
1                 Ryan Boyce  5398818.0        1505.0
2               Jack Carroll  4438260.0        1496.0
3          William Partridge  6588565.0        1459.0
4         Christopher Harris    28660.0        1448.0
5                 Rhys Birdy  5810139.0        1438.0
6               Tommy Davies  7845816.0        1437.0
7               Samia Shelim  6506490.0        1433.0
8              Rizwan Shelim  3058994.0        1405.0
9             Conner Harling  3421093.0        1401.0
10        Christopher Harris   145486.0        1400.0
11  Christakis Christodoulou  7474864.0        1386.0
12             Ollie Carroll  5181285.0        1377.0
13               Nafi Shelim  4776281.0        1371.0
14             Tajwar Shelim  4773459.0        1370.0
15              Will Hossack  4792527.0        1314.0
16               Simon Meech  6764382.0        1267.0
17            Charlie Garner  9432680.0        1259.0
18              Tahmid Haque  6394829.0        1246.0
19              Holly Stower  7367977.0        1182.0
20            Rachel Aumayer  9763056.0        1029.0

In [ ]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
166,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,50.700260,0.0,50.700260,0.000000,50.700260,0.0,50.700260,50.700260,50.700260
136,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,47.659333,0.0,47.659333,0.000000,47.659333,0.0,47.659333,47.659333,47.659333
350,1,32.0,Emiliano Martínez Romero,a,5.0,GK,Aston Villa,47.303717,0.0,47.303717,0.000000,47.303717,0.0,47.303717,47.303717,47.303717
353,1,337.0,Raúl Jiménez Rodríguez,a,6.1,FWD,Fulham,43.270610,0.0,43.270610,0.000000,43.270610,0.0,43.270610,43.270610,43.270610
215,1,691.0,Dominic Calvert-Lewin,a,5.8,FWD,Leeds,39.510209,0.0,39.510209,0.000000,39.510209,0.0,39.510209,39.510209,39.510209
33,1,341.0,Karl Darlow,a,3.9,GK,Leeds,39.018140,0.0,39.018140,0.000000,39.018140,0.0,39.018140,39.018140,39.018140
326,1,8.0,Jurriën Timber,a,6.4,DEF,Arsenal,47.564097,40.0,28.538458,-19.025639,28.538458,0.0,9.512819,28.538458,28.538458
284,1,237.0,Enzo Fernández,a,6.9,MID,Chelsea,54.322334,60.0,21.728933,-32.593400,21.728933,0.0,-10.864467,21.728933,21.728933
186,1,449.0,Bruno Borges Fernandes,a,9.8,MID,Man Utd,52.665733,60.0,21.066293,-31.599440,21.066293,0.0,-10.533147,21.066293,21.066293
40,1,5.0,Gabriel dos Santos Magalhães,a,7.1,DEF,Arsenal,49.173881,60.0,19.669552,-29.504329,19.669552,0.0,-9.834776,19.669552,19.669552
140,1,694.0,Nordi Mukiele,d,4.6,DEF,Sunderland,46.024615,60.0,18.409846,-27.614769,18.409846,0.0,-9.204923,18.409846,18.409846
90,1,661.0,Hugo Ekitiké,a,8.9,FWD,Liverpool,44.355635,60.0,17.742254,-26.613381,17.742254,0.0,-8.871127,17.742254,17.742254
111,1,21.0,Declan Rice,a,7.6,MID,Arsenal,46.042957,100.0,0.000000,-46.042957,0.000000,0.0,-46.042957,0.000000,0.000000

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value
304,0,430.0,Erling Haaland,a,14.8,FWD,Man City,45.785889,140.0,-18.314355,-64.100244,0.0,-64.100244,-82.414600,-64.100244
285,0,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,47.432876,120.0,-9.486575,-56.919451,0.0,-56.919451,-66.406026,-56.919451
118,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,46.542299,80.0,9.308460,-37.233839,0.0,-37.233839,-27.925379,-37.233839
107,0,226.0,Trevoh Chalobah,a,5.8,DEF,Chelsea,37.717306,80.0,7.543461,-30.173845,0.0,-30.173845,-22.630384,-30.173845
142,0,47.0,Morgan Rogers,a,7.7,MID,Aston Villa,49.680935,60.0,19.872374,-29.808561,0.0,-29.808561,-9.936187,-29.808561
337,0,36.0,Matty Cash,a,4.9,DEF,Aston Villa,48.764477,60.0,19.505791,-29.258686,0.0,-29.258686,-9.752895,-29.258686
52,0,82.0,Antoine Semenyo,a,8.0,MID,Man City,51.387995,40.0,30.832797,-20.555198,0.0,-20.555198,10.277599,-20.555198
401,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.0,FWD,Brentford,49.811435,40.0,29.886861,-19.924574,0.0,-19.924574,9.962287,-19.924574
174,0,736.0,Gianluigi Donnarumma,a,5.6,GK,Man City,41.908127,40.0,25.144876,-16.763251,0.0,-16.763251,8.381625,-16.763251
194,0,1.0,David Raya Martín,a,6.0,GK,Arsenal,40.205709,40.0,24.123425,-16.082284,0.0,-16.082284,8.041142,-16.082284
167,0,329.0,Harry Wilson,a,5.9,MID,Fulham,50.282335,20.0,40.225868,-10.056467,0.0,-10.056467,30.169401,-10.056467
66,0,457.0,Carlos Henrique Casimiro,a,5.6,MID,Man Utd,47.419650,20.0,37.935720,-9.483930,0.0,-9.483930,28.451790,-9.483930
381,0,26.0,Martín Zubimendi Ibáñez,a,5.3,MID,Arsenal,45.376680,20.0,36.301344,-9.075336,0.0,-9.075336,27.226008,-9.075336
388,0,390.0,Ryan Gravenberch,a,5.5,MID,Liverpool,44.095413,20.0,35.276330,-8.819083,0.0,-8.819083,26.457248,-8.819083
18,0,220.0,Robert Lynch Sánchez,a,4.9,GK,Chelsea,43.166574,20.0,34.533259,-8.633315,0.0,-8.633315,25.899944,-8.633315
333,0,242.0,Kiernan Dewsbury-Hall,a,4.9,MID,Everton,42.853947,20.0,34.283157,-8.570789,0.0,-8.570789,25.712368,-8.570789
42,0,470.0,Martin Dúbravka,a,4.0,GK,Burnley,35.380616,20.0,28.304492,-7.076123,0.0,-7.076123,21.228369,-7.076123
417,0,50.0,Emiliano Buendía Stati,a,5.3,MID,Aston Villa,43.186401,0.0,43.186401,0.000000,0.0,0.000000,43.186401,0.000000
400,0,167.0,Carlos Baleba,a,4.5,MID,Brighton,32.655588,0.0,32.655588,0.000000,0.0,0.000000,32.655588,0.000000
402,0,100.0,Junior Kroupi,a,4.7,FWD,Bournemouth,35.436105,0.0,35.436105,0.000000,0.0,0.000000,35.436105,0.000000

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value
113,0,666.0,Viktor Gyökeres,a,8.8,FWD,Arsenal,53.301476,0.0,53.301476,0.0,0.0,0.0,53.301476,0.0
390,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,51.718366,0.0,51.718366,0.0,0.0,0.0,51.718366,0.0
92,0,374.0,Ibrahima Konaté,a,5.4,DEF,Liverpool,51.713973,0.0,51.713973,0.0,0.0,0.0,51.713973,0.0
325,0,386.0,Alexis Mac Allister,a,6.2,MID,Liverpool,51.331075,0.0,51.331075,0.0,0.0,0.0,51.331075,0.0
190,0,373.0,Virgil van Dijk,a,5.9,DEF,Liverpool,51.172772,0.0,51.172772,0.0,0.0,0.0,51.172772,0.0
298,0,40.0,Tyrone Mings,a,4.3,DEF,Aston Villa,51.065326,0.0,51.065326,0.0,0.0,0.0,51.065326,0.0
71,0,382.0,Florian Wirtz,d,8.4,MID,Liverpool,50.756918,0.0,50.756918,0.0,0.0,0.0,50.756918,0.0
295,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,50.340682,0.0,50.340682,0.0,0.0,0.0,50.340682,0.0
195,0,411.0,Nico O'Reilly,a,4.9,DEF,Man City,49.903274,0.0,49.903274,0.0,0.0,0.0,49.903274,0.0
143,0,387.0,Dominik Szoboszlai,a,6.7,MID,Liverpool,49.763967,0.0,49.763967,0.0,0.0,0.0,49.763967,0.0
127,0,39.0,Ian Maatsen,a,4.2,DEF,Aston Villa,49.738341,0.0,49.738341,0.0,0.0,0.0,49.738341,0.0
89,0,372.0,Andrew Robertson,a,5.7,DEF,Liverpool,48.990083,0.0,48.990083,0.0,0.0,0.0,48.990083,0.0
180,0,44.0,Lamare Bogarde,a,4.0,DEF,Aston Villa,48.770239,0.0,48.770239,0.0,0.0,0.0,48.770239,0.0
307,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,48.585147,0.0,48.585147,0.0,0.0,0.0,48.585147,0.0
147,0,547.0,Enzo Le Fée,a,4.9,MID,Sunderland,48.561891,0.0,48.561891,0.0,0.0,0.0,48.561891,0.0
126,0,324.0,Alex Iwobi,a,6.3,MID,Fulham,47.941027,0.0,47.941027,0.0,0.0,0.0,47.941027,0.0
125,0,90.0,Alex Scott,a,5.0,MID,Bournemouth,47.867018,0.0,47.867018,0.0,0.0,0.0,47.867018,0.0
266,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,47.748782,0.0,47.748782,0.0,0.0,0.0,47.748782,0.0
303,0,371.0,Milos Kerkez,a,5.6,DEF,Liverpool,47.632482,0.0,47.632482,0.0,0.0,0.0,47.632482,0.0
100,0,615.0,Crysencio Summerville,a,5.6,MID,West Ham,47.499429,0.0,47.499429,0.0,0.0,0.0,47.499429,0.0

In [ ]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
113,0,666.0,Viktor Gyökeres,a,8.8,FWD,Arsenal,53.301476,0.0,53.301476,0.0,0.000000,0.0,53.301476,0.000000,53.301476
390,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,51.718366,0.0,51.718366,0.0,0.000000,0.0,51.718366,0.000000,51.718366
92,0,374.0,Ibrahima Konaté,a,5.4,DEF,Liverpool,51.713973,0.0,51.713973,0.0,0.000000,0.0,51.713973,0.000000,51.713973
325,0,386.0,Alexis Mac Allister,a,6.2,MID,Liverpool,51.331075,0.0,51.331075,0.0,0.000000,0.0,51.331075,0.000000,51.331075
190,0,373.0,Virgil van Dijk,a,5.9,DEF,Liverpool,51.172772,0.0,51.172772,0.0,0.000000,0.0,51.172772,0.000000,51.172772
298,0,40.0,Tyrone Mings,a,4.3,DEF,Aston Villa,51.065326,0.0,51.065326,0.0,0.000000,0.0,51.065326,0.000000,51.065326
71,0,382.0,Florian Wirtz,d,8.4,MID,Liverpool,50.756918,0.0,50.756918,0.0,0.000000,0.0,50.756918,0.000000,50.756918
166,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,50.700260,0.0,50.700260,0.0,50.700260,0.0,50.700260,50.700260,50.700260
295,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,50.340682,0.0,50.340682,0.0,0.000000,0.0,50.340682,0.000000,50.340682
195,0,411.0,Nico O'Reilly,a,4.9,DEF,Man City,49.903274,0.0,49.903274,0.0,0.000000,0.0,49.903274,0.000000,49.903274
143,0,387.0,Dominik Szoboszlai,a,6.7,MID,Liverpool,49.763967,0.0,49.763967,0.0,0.000000,0.0,49.763967,0.000000,49.763967
127,0,39.0,Ian Maatsen,a,4.2,DEF,Aston Villa,49.738341,0.0,49.738341,0.0,0.000000,0.0,49.738341,0.000000,49.738341
89,0,372.0,Andrew Robertson,a,5.7,DEF,Liverpool,48.990083,0.0,48.990083,0.0,0.000000,0.0,48.990083,0.000000,48.990083
180,0,44.0,Lamare Bogarde,a,4.0,DEF,Aston Villa,48.770239,0.0,48.770239,0.0,0.000000,0.0,48.770239,0.000000,48.770239
307,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,48.585147,0.0,48.585147,0.0,0.000000,0.0,48.585147,0.000000,48.585147
147,0,547.0,Enzo Le Fée,a,4.9,MID,Sunderland,48.561891,0.0,48.561891,0.0,0.000000,0.0,48.561891,0.000000,48.561891
126,0,324.0,Alex Iwobi,a,6.3,MID,Fulham,47.941027,0.0,47.941027,0.0,0.000000,0.0,47.941027,0.000000,47.941027
125,0,90.0,Alex Scott,a,5.0,MID,Bournemouth,47.867018,0.0,47.867018,0.0,0.000000,0.0,47.867018,0.000000,47.867018
266,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,47.748782,0.0,47.748782,0.0,0.000000,0.0,47.748782,0.000000,47.748782
136,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,47.659333,0.0,47.659333,0.0,47.659333,0.0,47.659333,47.659333,47.659333

In [12]:
from FPL_Optimizer import FPLOptimizer

In [13]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £101.5m / £102.4m
Total Weighted Expected Points: 265.34
Remaining Budget: £0.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Caoimhín Kelleher              Brentford    £4.6    19.92
 ✅        Emiliano Martínez Romero       Aston Villa  £5.0    21.84

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Michael Kayode                 Brentford    £4.5    21.37
 ✅        Ibrahima Konaté                Liverpool    £5.4    24.03
 ✅        Virgil van Dijk                Liverpool    £5.9    23.58
 ✅        Tyrone Mings                   Aston Villa  £4.3    23.35
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    22.88

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Enzo Fernández                 Chelsea      £6.9    24.21
 ✅        Mohamed Salah                  Liverpool    £14.0   24.20
 ✅        Bruno Borges Fernandes         Man Utd      £9.8    23.98
 ✅        Harry Wilson                   Fulham       £5.9    23.30
 ✅        Cole Palmer                    Chelsea      £10.6   22.86

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7    21.14
 🪑        Brian Brobbey                  Sunderland   £5.5    21.01
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.0    22.77

================================================================================
Optimization Status: Optimal

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £94.4m / £102.4m
Total Weighted Expected Points: 572.54
Remaining Budget: £8.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Caoimhín Kelleher              Brentford    £4.6    42.47
 ✅        Emiliano Martínez Romero       Aston Villa  £5.0    47.30

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus Nunes                  Man City     £5.4    47.66
 ✅        Ibrahima Konaté                Liverpool    £5.4    51.71
 ✅        Nico O'Reilly                  Man City     £4.9    49.90
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    50.34
 ✅        Tyrone Mings                   Aston Villa  £4.3    51.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Enzo Le Fée                    Sunderland   £4.9    48.56
 ✅        Cole Palmer                    Chelsea      £10.6   50.70
 ✅        Iliman Ndiaye                  Everton      £6.2    48.59
 ✅        Alexis Mac Allister            Liverpool    £6.2    51.33
 ✅        Mohamed Salah                  Liverpool    £14.0   51.72

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brian Brobbey                  Sunderland   £5.5    46.04
 🪑        Marc Guiu Paz                  Chelsea      £4.2    44.00
 ✅        Viktor Gyökeres                Arsenal      £8.8    53.30

================================================================================
Optimization Status: Optimal

In [15]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [16]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)