In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 30
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  31
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4
5398818 Ryan Boyce GW 5 Pick 5
5398818 Ryan Boyce GW 5 Pick 6
5398818 Ryan Boyce GW 5 Pick 7
5398818 Ryan Boyce GW 5 Pick 8
5398818 Ryan Boyce GW 5 Pick 9
5398818 Ryan Boyce GW 5 Pick 10
5398818 Ryan Boyce GW 5 Pick 11
5398818 Ryan Boyce GW 5 Pick 12
5398818 Ryan Boyce GW 5 Pick 13
5398818 Ryan Boyce GW 5 Pick 14
5398818 Ryan Boyce GW 5 Pick 15
5398818 Ryan Boyce GW 6 Pick 1
5398818 Ryan Boyce GW 6 Pick 2
5398818 Ryan Boyce GW 6 Pick 3
5398818 Ryan Boyce GW 6 Pick 4
5398818 Ryan Boyce GW 6 Pick 5
5398818 Ryan Boyce GW 6 Pick 6
5398818 Ryan Boyce GW 6 Pick 7
5398818 Ryan Boyce GW 6 Pick 8
5398818 Ryan Boyce GW 6 Pick 9
5398818 Ryan Boyce GW 6 Pick 10
5398818 Ryan Boyce GW 6 Pick 11
5398818 Ryan Boyce GW 6 Pick 12
5398818 Ryan Boyce GW 6 Pick 13
5398818 Ryan Boyce GW 6 Pick 14
5398818 Ryan Boyce GW 6 Pick 15
5398818 Ryan Boyce GW 7 Pick 1
5398818 Ryan Boyce GW 7 Pick 2
5398818 Ryan Boyce GW 7 Pick 3
5398818 Ryan Boyce GW 7 Pick 4
5398818 Ryan Boyce GW 7 Pick 5
5398818 Ryan Boyce GW 7 Pick 6
5398818 Ryan Boyce GW 7 Pick 7
5398818 Ryan Boyce GW 7 Pick 8
5398818 Ryan Boyce GW 7 Pick 9
5398818 Ryan Boyce GW 7 Pick 10
5398818 Ryan Boyce GW 7 Pick 11
5398818 Ryan Boyce GW 7 Pick 12
5398818 Ryan Boyce GW 7 Pick 13
5398818 Ryan Boyce GW 7 Pick 14
5398818 Ryan Boyce GW 7 Pick 15
5398818 Ryan Boyce GW 8 Pick 1
5398818 Ryan Boyce GW 8 Pick 2
5398818 Ryan Boyce GW 8 Pick 3
5398818 Ryan Boyce GW 8 Pick 4
5398818 Ryan Boyce GW 8 Pick 5
5398818 Ryan Boyce GW 8 Pick 6
5398818 Ryan Boyce GW 8 Pick 7
5398818 Ryan Boyce GW 8 Pick 8
5398818 Ryan Boyce GW 8 Pick 9
5398818 Ryan Boyce GW 8 Pick 10
5398818 Ryan Boyce GW 8 Pick 11
5398818 Ryan Boyce GW 8 Pick 12
5398818 Ryan Boyce GW 8 Pick 13
5398818 Ryan Boyce GW 8 Pick 14
5398818 Ryan Boyce GW 8 Pick 15
5398818 Ryan Boyce GW 9 Pick 1
5398818 Ryan Boyce GW 9 Pick 2
5398818 Ryan Boyce GW 9 Pick 3
5398818 Ryan Boyce GW 9 Pick 4
5398818 Ryan Boyce GW 9 Pick 5
5398818 Ryan Boyce GW 9 Pick 6
5398818 Ryan Boyce GW 9 Pick 7
5398818 Ryan Boyce GW 9 Pick 8
5398818 Ryan Boyce GW 9 Pick 9
5398818 Ryan Boyce GW 9 Pick 10
5398818 Ryan Boyce GW 9 Pick 11
5398818 Ryan Boyce GW 9 Pick 12
5398818 Ryan Boyce GW 9 Pick 13
5398818 Ryan Boyce GW 9 Pick 14
5398818 Ryan Boyce GW 9 Pick 15
5398818 Ryan Boyce GW 10 Pick 1
5398818 Ryan Boyce GW 10 Pick 2
5398818 Ryan Boyce GW 10 Pick 3
5398818 Ryan Boyce GW 10 Pick 4
5398818 Ryan Boyce GW 10 Pick 5
5398818 Ryan Boyce GW 10 Pick 6
5398818 Ryan Boyce GW 10 Pick 7
5398818 Ryan Boyce GW 10 Pick 8
5398818 Ryan Boyce GW 10 Pick 9
5398818 Ryan Boyce GW 10 Pick 10
5398818 Ryan Boyce GW 10 Pick 11
5398818 Ryan Boyce GW 10 Pick 12
5398818 Ryan Boyce GW 10 Pick 13
5398818 Ryan Boyce GW 10 Pick 14
5398818 Ryan Boyce GW 10 Pick 15
5398818 Ryan Boyce GW 11 Pick 1
5398818 Ryan Boyce GW 11 Pick 2
5398818 Ryan Boyce GW 11 Pick 3
5398818 Ryan Boyce GW 11 Pick 4
5398818 Ryan Boyce GW 11 Pick 5
5398818 Ryan Boyce GW 11 Pick 6
5398818 Ryan Boyce GW 11 Pick 7
5398818 Ryan Boyce GW 11 Pick 8
5398818 Ryan Boyce GW 11 Pick 9
5398818 Ryan Boyce GW 11 Pick 10
5398818 Ryan Boyce GW 11 Pick 11
5398818 Ryan Boyce GW 11 Pick 12
5398818 Ryan Boyce GW 11 Pick 13
5398818 Ryan Boyce GW 11 Pick 14
5398818 Ryan Boyce GW 11 Pick 15
5398818 Ryan Boyce GW 12 Pick 1
5398818 Ryan Boyce GW 12 Pick 2
5398818 Ryan Boyce GW 12 Pick 3
5398818 Ryan Boyce GW 12 Pick 4
5398818 Ryan Boyce GW 12 Pick 5
5398818 Ryan Boyce GW 12 Pick 6
5398818 Ryan Boyce GW 12 Pick 7
5398818 Ryan Boyce GW 12 Pick 8
5398818 Ryan Boyce GW 12 Pick 9
5398818 Ryan Boyce GW 12 Pick 10
5398818 Ryan Boyce GW 12 Pick 11
5398818 Ryan Boyce GW 12 Pick 12
5398818 Ryan Boyce GW 12 Pick 13
5398818 Ryan Boyce GW 12 Pick 14
5398818 Ryan Boyce GW 12 Pick 15
5398818 Ryan Boyce GW 13 Pick 1
5398818 Ryan Boyce GW 13 Pick 2
5398818 Ryan Boyce GW 13 Pick 3
5398818 Ryan Boyce GW 13 Pick 4
5398818 Ryan Boyce GW 13 Pick 5
5398818 Ryan Boyce GW 13 Pick 6
5398818 Ryan Boyce GW 13 Pick 7
5398818 Ryan Boyce GW 13 Pick 8
5398818 Ryan Boyce GW 13 Pick 9
5398818 Ryan Boyce GW 13 Pick 10
5398818 Ryan Boyce GW 13 Pick 11
5398818 Ryan Boyce GW 13 Pick 12
5398818 Ryan Boyce GW 13 Pick 13
5398818 Ryan Boyce GW 13 Pick 14
5398818 Ryan Boyce GW 13 Pick 15
5398818 Ryan Boyce GW 14 Pick 1
5398818 Ryan Boyce GW 14 Pick 2
5398818 Ryan Boyce GW 14 Pick 3
5398818 Ryan Boyce GW 14 Pick 4
5398818 Ryan Boyce GW 14 Pick 5
5398818 Ryan Boyce GW 14 Pick 6
5398818 Ryan Boyce GW 14 Pick 7
5398818 Ryan Boyce GW 14 Pick 8
5398818 Ryan Boyce GW 14 Pick 9
5398818 Ryan Boyce GW 14 Pick 10
5398818 Ryan Boyce GW 14 Pick 11
5398818 Ryan Boyce GW 14 Pick 12
5398818 Ryan Boyce GW 14 Pick 13
5398818 Ryan Boyce GW 14 Pick 14
5398818 Ryan Boyce GW 14 Pick 15
5398818 Ryan Boyce GW 15 Pick 1
5398818 Ryan Boyce GW 15 Pick 2
5398818 Ryan Boyce GW 15 Pick 3
5398818 Ryan Boyce GW 15 Pick 4
5398818 Ryan Boyce GW 15 Pick 5
5398818 Ryan Boyce GW 15 Pick 6
5398818 Ryan Boyce GW 15 Pick 7
5398818 Ryan Boyce GW 15 Pick 8
5398818 Ryan Boyce GW 15 Pick 9
5398818 Ryan Boyce GW 15 Pick 10
5398818 Ryan Boyce GW 15 Pick 11
5398818 Ryan Boyce GW 15 Pick 12
5398818 Ryan Boyce GW 15 Pick 13
5398818 Ryan Boyce GW 15 Pick 14
5398818 Ryan Boyce GW 15 Pick 15
5398818 Ryan Boyce GW 16 Pick 1
5398818 Ryan Boyce GW 16 Pick 2
5398818 Ryan Boyce GW 16 Pick 3
5398818 Ryan Boyce GW 16 Pick 4
5398818 Ryan Boyce GW 16 Pick 5
5398818 Ryan Boyce GW 16 Pick 6
5398818 Ryan Boyce GW 16 Pick 7
5398818 Ryan Boyce GW 16 Pick 8
5398818 Ryan Boyce GW 16 Pick 9
5398818 Ryan Boyce GW 16 Pick 10
5398818 Ryan Boyce GW 16 Pick 11
5398818 Ryan Boyce GW 16 Pick 12
5398818 Ryan Boyce GW 16 Pick 13
5398818 Ryan Boyce GW 16 Pick 14
5398818 Ryan Boyce GW 16 Pick 15
5398818 Ryan Boyce GW 17 Pick 1
5398818 Ryan Boyce GW 17 Pick 2
5398818 Ryan Boyce GW 17 Pick 3
5398818 Ryan Boyce GW 17 Pick 4
5398818 Ryan Boyce GW 17 Pick 5
5398818 Ryan Boyce GW 17 Pick 6
5398818 Ryan Boyce GW 17 Pick 7
5398818 Ryan Boyce GW 17 Pick 8
5398818 Ryan Boyce GW 17 Pick 9
5398818 Ryan Boyce GW 17 Pick 10
5398818 Ryan Boyce GW 17 Pick 11
5398818 Ryan Boyce GW 17 Pick 12
5398818 Ryan Boyce GW 17 Pick 13
5398818 Ryan Boyce GW 17 Pick 14
5398818 Ryan Boyce GW 17 Pick 15
5398818 Ryan Boyce GW 18 Pick 1
5398818 Ryan Boyce GW 18 Pick 2
5398818 Ryan Boyce GW 18 Pick 3
5398818 Ryan Boyce GW 18 Pick 4
5398818 Ryan Boyce GW 18 Pick 5
5398818 Ryan Boyce GW 18 Pick 6
5398818 Ryan Boyce GW 18 Pick 7
5398818 Ryan Boyce GW 18 Pick 8
5398818 Ryan Boyce GW 18 Pick 9
5398818 Ryan Boyce GW 18 Pick 10
5398818 Ryan Boyce GW 18 Pick 11
5398818 Ryan Boyce GW 18 Pick 12
5398818 Ryan Boyce GW 18 Pick 13
5398818 Ryan Boyce GW 18 Pick 14
5398818 Ryan Boyce GW 18 Pick 15
5398818 Ryan Boyce GW 19 Pick 1
5398818 Ryan Boyce GW 19 Pick 2
5398818 Ryan Boyce GW 19 Pick 3
5398818 Ryan Boyce GW 19 Pick 4
5398818 Ryan Boyce GW 19 Pick 5
5398818 Ryan Boyce GW 19 Pick 6
5398818 Ryan Boyce GW 19 Pick 7
5398818 Ryan Boyce GW 19 Pick 8
5398818 Ryan Boyce GW 19 Pick 9
5398818 Ryan Boyce GW 19 Pick 10
5398818 Ryan Boyce GW 19 Pick 11
5398818 Ryan Boyce GW 19 Pick 12
5398818 Ryan Boyce GW 19 Pick 13
5398818 Ryan Boyce GW 19 Pick 14
5398818 Ryan Boyce GW 19 Pick 15
5398818 Ryan Boyce GW 20 Pick 1
5398818 Ryan Boyce GW 20 Pick 2
5398818 Ryan Boyce GW 20 Pick 3
5398818 Ryan Boyce GW 20 Pick 4
5398818 Ryan Boyce GW 20 Pick 5
5398818 Ryan Boyce GW 20 Pick 6
5398818 Ryan Boyce GW 20 Pick 7
5398818 Ryan Boyce GW 20 Pick 8
5398818 Ryan Boyce GW 20 Pick 9
5398818 Ryan Boyce GW 20 Pick 10
5398818 Ryan Boyce GW 20 Pick 11
5398818 Ryan Boyce GW 20 Pick 12
5398818 Ryan Boyce GW 20 Pick 13
5398818 Ryan Boyce GW 20 Pick 14
5398818 Ryan Boyce GW 20 Pick 15
5398818 Ryan Boyce GW 21 Pick 1
5398818 Ryan Boyce GW 21 Pick 2
5398818 Ryan Boyce GW 21 Pick 3
5398818 Ryan Boyce GW 21 Pick 4
5398818 Ryan Boyce GW 21 Pick 5
5398818 Ryan Boyce GW 21 Pick 6
5398818 Ryan Boyce GW 21 Pick 7
5398818 Ryan Boyce GW 21 Pick 8
5398818 Ryan Boyce GW 21 Pick 9
5398818 Ryan Boyce GW 21 Pick 10
5398818 Ryan Boyce GW 21 Pick 11
5398818 Ryan Boyce GW 21 Pick 12
5398818 Ryan Boyce GW 21 Pick 13
5398818 Ryan Boyce GW 21 Pick 14
5398818 Ryan Boyce GW 21 Pick 15
5398818 Ryan Boyce GW 22 Pick 1
5398818 Ryan Boyce GW 22 Pick 2
5398818 Ryan Boyce GW 22 Pick 3
5398818 Ryan Boyce GW 22 Pick 4
5398818 Ryan Boyce GW 22 Pick 5
5398818 Ryan Boyce GW 22 Pick 6
5398818 Ryan Boyce GW 22 Pick 7
5398818 Ryan Boyce GW 22 Pick 8
5398818 Ryan Boyce GW 22 Pick 9
5398818 Ryan Boyce GW 22 Pick 10
5398818 Ryan Boyce GW 22 Pick 11
5398818 Ryan Boyce GW 22 Pick 12
5398818 Ryan Boyce GW 22 Pick 13
5398818 Ryan Boyce GW 22 Pick 14
5398818 Ryan Boyce GW 22 Pick 15
5398818 Ryan Boyce GW 23 Pick 1
5398818 Ryan Boyce GW 23 Pick 2
5398818 Ryan Boyce GW 23 Pick 3
5398818 Ryan Boyce GW 23 Pick 4
5398818 Ryan Boyce GW 23 Pick 5
5398818 Ryan Boyce GW 23 Pick 6
5398818 Ryan Boyce GW 23 Pick 7
5398818 Ryan Boyce GW 23 Pick 8
5398818 Ryan Boyce GW 23 Pick 9
5398818 Ryan Boyce GW 23 Pick 10
5398818 Ryan Boyce GW 23 Pick 11
5398818 Ryan Boyce GW 23 Pick 12
5398818 Ryan Boyce GW 23 Pick 13
5398818 Ryan Boyce GW 23 Pick 14
5398818 Ryan Boyce GW 23 Pick 15
5398818 Ryan Boyce GW 24 Pick 1
5398818 Ryan Boyce GW 24 Pick 2
5398818 Ryan Boyce GW 24 Pick 3
5398818 Ryan Boyce GW 24 Pick 4
5398818 Ryan Boyce GW 24 Pick 5
5398818 Ryan Boyce GW 24 Pick 6
5398818 Ryan Boyce GW 24 Pick 7
5398818 Ryan Boyce GW 24 Pick 8
5398818 Ryan Boyce GW 24 Pick 9
5398818 Ryan Boyce GW 24 Pick 10
5398818 Ryan Boyce GW 24 Pick 11
5398818 Ryan Boyce GW 24 Pick 12
5398818 Ryan Boyce GW 24 Pick 13
5398818 Ryan Boyce GW 24 Pick 14
5398818 Ryan Boyce GW 24 Pick 15
5398818 Ryan Boyce GW 25 Pick 1
5398818 Ryan Boyce GW 25 Pick 2
5398818 Ryan Boyce GW 25 Pick 3
5398818 Ryan Boyce GW 25 Pick 4
5398818 Ryan Boyce GW 25 Pick 5
5398818 Ryan Boyce GW 25 Pick 6
5398818 Ryan Boyce GW 25 Pick 7
5398818 Ryan Boyce GW 25 Pick 8
5398818 Ryan Boyce GW 25 Pick 9
5398818 Ryan Boyce GW 25 Pick 10
5398818 Ryan Boyce GW 25 Pick 11
5398818 Ryan Boyce GW 25 Pick 12
5398818 Ryan Boyce GW 25 Pick 13
5398818 Ryan Boyce GW 25 Pick 14
5398818 Ryan Boyce GW 25 Pick 15
5398818 Ryan Boyce GW 26 Pick 1
5398818 Ryan Boyce GW 26 Pick 2
5398818 Ryan Boyce GW 26 Pick 3
5398818 Ryan Boyce GW 26 Pick 4
5398818 Ryan Boyce GW 26 Pick 5
5398818 Ryan Boyce GW 26 Pick 6
5398818 Ryan Boyce GW 26 Pick 7
5398818 Ryan Boyce GW 26 Pick 8
5398818 Ryan Boyce GW 26 Pick 9
5398818 Ryan Boyce GW 26 Pick 10
5398818 Ryan Boyce GW 26 Pick 11
5398818 Ryan Boyce GW 26 Pick 12
5398818 Ryan Boyce GW 26 Pick 13
5398818 Ryan Boyce GW 26 Pick 14
5398818 Ryan Boyce GW 26 Pick 15
5398818 Ryan Boyce GW 27 Pick 1
5398818 Ryan Boyce GW 27 Pick 2
5398818 Ryan Boyce GW 27 Pick 3
5398818 Ryan Boyce GW 27 Pick 4
5398818 Ryan Boyce GW 27 Pick 5
5398818 Ryan Boyce GW 27 Pick 6
5398818 Ryan Boyce GW 27 Pick 7
5398818 Ryan Boyce GW 27 Pick 8
5398818 Ryan Boyce GW 27 Pick 9
5398818 Ryan Boyce GW 27 Pick 10
5398818 Ryan Boyce GW 27 Pick 11
5398818 Ryan Boyce GW 27 Pick 12
5398818 Ryan Boyce GW 27 Pick 13
5398818 Ryan Boyce GW 27 Pick 14
5398818 Ryan Boyce GW 27 Pick 15
5398818 Ryan Boyce GW 28 Pick 1
5398818 Ryan Boyce GW 28 Pick 2
5398818 Ryan Boyce GW 28 Pick 3
5398818 Ryan Boyce GW 28 Pick 4
5398818 Ryan Boyce GW 28 Pick 5
5398818 Ryan Boyce GW 28 Pick 6
5398818 Ryan Boyce GW 28 Pick 7
5398818 Ryan Boyce GW 28 Pick 8
5398818 Ryan Boyce GW 28 Pick 9
5398818 Ryan Boyce GW 28 Pick 10
5398818 Ryan Boyce GW 28 Pick 11
5398818 Ryan Boyce GW 28 Pick 12
5398818 Ryan Boyce GW 28 Pick 13
5398818 Ryan Boyce GW 28 Pick 14
5398818 Ryan Boyce GW 28 Pick 15
5398818 Ryan Boyce GW 29 Pick 1
5398818 Ryan Boyce GW 29 Pick 2
5398818 Ryan Boyce GW 29 Pick 3
5398818 Ryan Boyce GW 29 Pick 4
5398818 Ryan Boyce GW 29 Pick 5
5398818 Ryan Boyce GW 29 Pick 6
5398818 Ryan Boyce GW 29 Pick 7
5398818 Ryan Boyce GW 29 Pick 8
5398818 Ryan Boyce GW 29 Pick 9
5398818 Ryan Boyce GW 29 Pick 10
5398818 Ryan Boyce GW 29 Pick 11
5398818 Ryan Boyce GW 29 Pick 12
5398818 Ryan Boyce GW 29 Pick 13
5398818 Ryan Boyce GW 29 Pick 14
5398818 Ryan Boyce GW 29 Pick 15
5398818 Ryan Boyce GW 30 Pick 1
5398818 Ryan Boyce GW 30 Pick 2
5398818 Ryan Boyce GW 30 Pick 3
5398818 Ryan Boyce GW 30 Pick 4
5398818 Ryan Boyce GW 30 Pick 5
5398818 Ryan Boyce GW 30 Pick 6
5398818 Ryan Boyce GW 30 Pick 7
5398818 Ryan Boyce GW 30 Pick 8
5398818 Ryan Boyce GW 30 Pick 9
5398818 Ryan Boyce GW 30 Pick 10
5398818 Ryan Boyce GW 30 Pick 11
5398818 Ryan Boyce GW 30 Pick 12
5398818 Ryan Boyce GW 30 Pick 13
5398818 Ryan Boyce GW 30 Pick 14
5398818 Ryan Boyce GW 30 Pick 15
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW31 to GW35

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1082.6,5.05,80.9,0.206,0.266,1.342
1,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,1008.4,4.85,80.7,0.052,0.050,0.902
2,Alexis Mac Allister,a,1,MID,Liverpool,1069.5,4.83,84.6,0.224,0.172,1.351
3,Lucas Digne,a,0,DEF,Aston Villa,1008.4,4.74,73.5,0.050,0.077,0.907
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1027.5,4.70,81.6,0.228,0.156,1.221
5,Dominik Szoboszlai,a,1,MID,Liverpool,1069.5,4.67,86.4,0.183,0.190,1.490
6,Matty Cash,d,0,DEF,Aston Villa,1008.4,4.64,78.9,0.040,0.059,0.950
7,Lamare Bogarde,a,0,DEF,Aston Villa,1008.4,4.60,63.6,0.038,0.058,0.796
8,Cole Palmer,a,0,MID,Chelsea,1098.7,4.60,79.5,0.213,0.179,1.375
9,Tyrone Mings,a,1,DEF,Aston Villa,1008.4,4.56,77.2,0.045,0.068,1.030
10,Morgan Rogers,a,0,MID,Aston Villa,1008.4,4.56,81.2,0.171,0.186,1.182
11,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1082.6,4.54,84.9,0.198,0.125,1.285
12,Mohamed Salah,a,0,MID,Liverpool,1069.5,4.53,68.3,0.311,0.155,1.393
13,Cody Gakpo,a,0,MID,Liverpool,1069.5,4.53,76.0,0.210,0.147,1.170
14,Harry Wilson,a,0,MID,Fulham,1103.2,4.50,83.6,0.177,0.142,1.391
15,Dango Ouattara,a,0,MID,Brentford,1039.0,4.42,78.8,0.201,0.136,1.352
16,Pau Torres,a,0,DEF,Aston Villa,1008.4,4.41,77.4,0.039,0.043,1.048
17,Alex Iwobi,a,0,MID,Fulham,1103.2,4.41,86.3,0.144,0.143,1.386
18,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1098.7,4.40,82.2,0.391,0.060,1.319
19,Anton Stach,a,0,MID,Leeds,1018.7,4.38,85.5,0.154,0.177,1.229
20,Enzo Fernández,a,0,MID,Chelsea,1098.7,4.37,78.6,0.170,0.181,1.372
21,Anthony Gordon,a,0,MID,Newcastle,1096.5,4.37,83.4,0.193,0.123,1.382
22,Amadou Onana,a,0,MID,Aston Villa,1008.4,4.37,81.5,0.165,0.152,1.155
23,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,4.35,80.0,0.196,0.110,1.145
24,Bryan Mbeumo,a,0,MID,Man Utd,1082.6,4.33,79.2,0.189,0.127,1.241
25,Mathias Jensen,a,1,MID,Brentford,1039.0,4.31,83.1,0.157,0.138,1.398
26,Carlos Henrique Casimiro,a,0,MID,Man Utd,1082.6,4.31,82.7,0.160,0.136,1.288
27,Nikola Milenković,a,0,DEF,Nott'm Forest,1027.5,4.28,85.8,0.047,0.042,1.168
28,Marc Guiu Paz,a,0,FWD,Chelsea,1098.7,4.27,46.5,0.860,0.241,1.575
29,Lewis Dunk,a,0,DEF,Brighton,1047.4,4.27,86.5,0.042,0.043,1.166
30,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,4.25,86.6,0.039,0.047,1.158
31,Ola Aina,a,0,DEF,Nott'm Forest,1027.5,4.25,86.7,0.037,0.042,1.151
32,Nico O'Reilly,a,0,DEF,Man City,1084.5,4.25,79.4,0.358,0.067,0.942
33,Pascal Groß,a,0,MID,Brighton,1047.4,4.25,86.0,0.103,0.159,1.104
34,Habib Diarra,a,0,MID,Sunderland,1027.8,4.24,85.0,0.163,0.103,1.091
35,Iliman Ndiaye,a,0,MID,Everton,1117.0,4.24,86.0,0.158,0.120,1.407
36,Florian Wirtz,a,0,MID,Liverpool,1069.5,4.24,59.7,0.260,0.227,1.144
37,Ethan Pinnock,a,0,DEF,Brentford,1039.0,4.23,66.3,0.225,0.052,1.479
38,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,1039.0,4.23,82.5,0.316,0.076,1.305
39,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,4.21,84.9,0.041,0.048,1.185
40,Tomáš Souček,a,0,MID,West Ham,1051.8,4.20,82.7,0.146,0.138,1.299
41,Pascal Struijk,a,0,DEF,Leeds,1018.7,4.20,86.3,0.048,0.048,1.144
42,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1051.8,4.19,84.8,0.121,0.132,1.291
43,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1027.5,4.19,86.5,0.036,0.041,1.185
44,Ibrahima Konaté,a,1,DEF,Liverpool,1069.5,4.18,84.5,0.042,0.045,1.207
45,Aaron Wan-Bissaka,a,0,DEF,West Ham,1051.8,4.10,86.4,0.036,0.042,1.177
46,Virgil van Dijk,a,0,DEF,Liverpool,1069.5,4.10,62.3,0.104,0.049,1.207
47,Alex Scott,a,0,MID,Bournemouth,1098.3,4.10,81.9,0.143,0.110,1.233
48,Joe Rodon,a,0,DEF,Leeds,1018.7,4.09,86.3,0.039,0.045,1.183
49,James Hill,a,0,DEF,Bournemouth,1098.3,4.09,83.6,0.063,0.071,1.309

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 31 and 35:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Nico O'Reilly,a,DEF,Man City,5.1,1084.5,25.57,79.4,0.358,0.067,0.942
1,Bruno Borges Fernandes,a,MID,Man Utd,10.1,1082.6,25.03,80.9,0.206,0.266,1.342
2,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,1008.4,24.11,80.7,0.052,0.050,0.902
3,Alexis Mac Allister,a,MID,Liverpool,6.3,1069.5,24.06,84.6,0.224,0.172,1.351
4,Lucas Digne,a,DEF,Aston Villa,4.5,1008.4,23.59,73.5,0.050,0.077,0.907
5,Morgan Gibbs-White,a,MID,Nott'm Forest,7.3,1027.5,23.43,81.6,0.228,0.156,1.221
6,Dominik Szoboszlai,a,MID,Liverpool,6.9,1069.5,23.29,86.4,0.183,0.190,1.490
7,Cole Palmer,a,MID,Chelsea,10.6,1098.7,23.09,79.5,0.213,0.179,1.375
8,Matty Cash,d,DEF,Aston Villa,4.8,1008.4,23.04,78.9,0.040,0.059,0.950
9,Lamare Bogarde,a,DEF,Aston Villa,4.0,1008.4,22.97,63.6,0.038,0.058,0.796
10,Morgan Rogers,a,MID,Aston Villa,7.5,1008.4,22.75,81.2,0.171,0.186,1.182
11,Tyrone Mings,a,DEF,Aston Villa,4.3,1008.4,22.71,77.2,0.045,0.068,1.030
12,Mohamed Salah,a,MID,Liverpool,14.0,1069.5,22.59,68.3,0.311,0.155,1.393
13,Matheus Santos Carneiro da Cunha,a,MID,Man Utd,8.0,1082.6,22.59,84.9,0.198,0.125,1.285
14,Cody Gakpo,a,MID,Liverpool,7.3,1069.5,22.57,76.0,0.210,0.147,1.170
15,Anton Stach,a,MID,Leeds,4.7,1018.7,22.19,85.5,0.154,0.177,1.229
16,Harry Wilson,a,MID,Fulham,6.0,1103.2,22.07,83.6,0.177,0.142,1.391
17,João Pedro Junqueira de Jesus,a,FWD,Chelsea,7.7,1098.7,22.04,82.2,0.391,0.060,1.319
18,Dango Ouattara,a,MID,Brentford,6.0,1039.0,22.02,78.8,0.201,0.136,1.352
19,Enzo Fernández,a,MID,Chelsea,6.6,1098.7,21.95,78.6,0.170,0.181,1.372

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0                 Ryan Boyce  5398818.0        1715.0
1              Bernard Chalk  1557117.0        1695.0
2               Jack Carroll  4438260.0        1648.0
3         Christopher Harris    28660.0        1644.0
4          William Partridge  6588565.0        1643.0
5               Samia Shelim  6506490.0        1610.0
6               Tommy Davies  7845816.0        1601.0
7         Christopher Harris   145486.0        1594.0
8                 Rhys Birdy  5810139.0        1581.0
9              Ollie Carroll  5181285.0        1579.0
10             Rizwan Shelim  3058994.0        1577.0
11            Conner Harling  3421093.0        1576.0
12               Nafi Shelim  4776281.0        1562.0
13             Tajwar Shelim  4773459.0        1519.0
14  Christakis Christodoulou  7474864.0        1478.0
15              Will Hossack  4792527.0        1417.0
16               Simon Meech  6764382.0        1400.0
17              Tahmid Haque  6394829.0        1398.0
18            Charlie Garner  9432680.0        1395.0
19              Holly Stower  7367977.0        1325.0
20            Rachel Aumayer  9763056.0        1151.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
199,1,8.0,Jurriën Timber,a,6.3,DEF,Arsenal,37.597384,0.0,37.597384,0.000000,37.597384,0.0,37.597384,37.597384,37.597384
178,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,37.226894,0.0,37.226894,0.000000,37.226894,0.0,37.226894,37.226894,37.226894
432,1,384.0,Cody Gakpo,a,7.3,MID,Liverpool,35.679565,0.0,35.679565,0.000000,35.679565,0.0,35.679565,35.679565,35.679565
25,1,237.0,Enzo Fernández,a,6.6,MID,Chelsea,35.256824,0.0,35.256824,0.000000,35.256824,0.0,35.256824,35.256824,35.256824
142,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,32.403976,0.0,32.403976,0.000000,32.403976,0.0,32.403976,32.403976,32.403976
377,1,691.0,Dominic Calvert-Lewin,a,5.7,FWD,Leeds,30.837463,0.0,30.837463,0.000000,30.837463,0.0,30.837463,30.837463,30.837463
338,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,30.364658,0.0,30.364658,0.000000,30.364658,0.0,30.364658,30.364658,30.364658
43,1,341.0,Karl Darlow,a,3.9,GK,Leeds,29.091274,0.0,29.091274,0.000000,29.091274,0.0,29.091274,29.091274,29.091274
158,1,694.0,Nordi Mukiele,d,4.5,DEF,Sunderland,28.424033,0.0,28.424033,0.000000,28.424033,0.0,28.424033,28.424033,28.424033
6,1,337.0,Raúl Jiménez Rodríguez,a,6.2,FWD,Fulham,27.114394,0.0,27.114394,0.000000,27.114394,0.0,27.114394,27.114394,27.114394
212,1,661.0,Hugo Ekitiké,a,9.2,FWD,Liverpool,28.094772,40.0,16.856863,-11.237909,16.856863,0.0,5.618954,16.856863,16.856863
163,1,373.0,Virgil van Dijk,a,6.2,DEF,Liverpool,32.220507,60.0,12.888203,-19.332304,12.888203,0.0,-6.444101,12.888203,12.888203
206,1,5.0,Gabriel dos Santos Magalhães,a,7.2,DEF,Arsenal,35.683747,80.0,7.136749,-28.546998,7.136749,0.0,-21.410248,7.136749,7.136749
374,1,329.0,Harry Wilson,a,6.0,MID,Fulham,35.629599,80.0,7.125920,-28.503679,7.125920,0.0,-21.377759,7.125920,7.125920
190,1,449.0,Bruno Borges Fernandes,a,10.1,MID,Man Utd,40.319599,100.0,0.000000,-40.319599,0.000000,0.0,-40.319599,0.000000,0.000000

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
303,0,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,35.423708,100.0,0.000000,-35.423708,0.0,-35.423708,-35.423708,-35.423708,0.000000
188,0,430.0,Erling Haaland,a,14.6,FWD,Man City,29.370476,120.0,-5.874095,-35.244572,0.0,-35.244572,-41.118667,-35.244572,-5.874095
416,0,82.0,Antoine Semenyo,a,8.3,MID,Man City,34.238118,80.0,6.847624,-27.390494,0.0,-27.390494,-20.542871,-27.390494,6.847624
405,0,21.0,Declan Rice,a,7.4,MID,Arsenal,32.291999,60.0,12.916800,-19.375199,0.0,-19.375199,-6.458400,-19.375199,12.916800
151,0,119.0,Bryan Mbeumo,a,8.7,MID,Man Utd,34.788082,40.0,20.872849,-13.915233,0.0,-13.915233,6.957616,-13.915233,20.872849
40,0,72.0,Marcos Senesi Barón,a,5.0,DEF,Bournemouth,32.578219,40.0,19.546932,-13.031288,0.0,-13.031288,6.515644,-13.031288,19.546932
9,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,27.543988,40.0,16.526393,-11.017595,0.0,-11.017595,5.508798,-11.017595,16.526393
35,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,44.297582,20.0,35.438066,-8.859516,0.0,-8.859516,26.578549,-8.859516,35.438066
31,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,35.892553,20.0,28.714043,-7.178511,0.0,-7.178511,21.535532,-7.178511,28.714043
74,0,457.0,Carlos Henrique Casimiro,a,5.6,MID,Man Utd,34.608218,20.0,27.686574,-6.921644,0.0,-6.921644,20.764931,-6.921644,27.686574
311,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.2,FWD,Brentford,33.667326,20.0,26.933861,-6.733465,0.0,-6.733465,20.200396,-6.733465,26.933861
334,0,382.0,Florian Wirtz,a,8.3,MID,Liverpool,33.585273,20.0,26.868219,-6.717055,0.0,-6.717055,20.151164,-6.717055,26.868219
262,0,16.0,Bukayo Saka,a,9.8,MID,Arsenal,32.445118,20.0,25.956095,-6.489024,0.0,-6.489024,19.467071,-6.489024,25.956095
124,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,32.270716,20.0,25.816573,-6.454143,0.0,-6.454143,19.362429,-6.454143,25.816573
226,0,74.0,Adrien Truffert,a,4.6,DEF,Bournemouth,32.255258,20.0,25.804206,-6.451052,0.0,-6.451052,19.353155,-6.451052,25.804206
46,0,683.0,Omar Alderete,a,4.1,DEF,Sunderland,32.093224,20.0,25.674579,-6.418645,0.0,-6.418645,19.255934,-6.418645,25.674579
110,0,517.0,Elliot Anderson,a,5.5,MID,Nott'm Forest,31.128721,20.0,24.902977,-6.225744,0.0,-6.225744,18.677233,-6.225744,24.902977
47,0,624.0,Jarrod Bowen,a,7.5,FWD,West Ham,30.549324,20.0,24.439459,-6.109865,0.0,-6.109865,18.329594,-6.109865,24.439459
399,0,390.0,Ryan Gravenberch,a,5.5,MID,Liverpool,29.937375,20.0,23.949900,-5.987475,0.0,-5.987475,17.962425,-5.987475,23.949900
205,0,681.0,Benjamin Sesko,a,7.3,FWD,Man Utd,29.683361,20.0,23.746689,-5.936672,0.0,-5.936672,17.810017,-5.936672,23.746689

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
168,0,386.0,Alexis Mac Allister,a,6.3,MID,Liverpool,37.962521,0.0,37.962521,0.0,0.0,0.0,37.962521,0.0,37.962521
150,0,515.0,Morgan Gibbs-White,a,7.3,MID,Nott'm Forest,37.165626,0.0,37.165626,0.0,0.0,0.0,37.165626,0.0,37.165626
257,0,387.0,Dominik Szoboszlai,a,6.9,MID,Liverpool,36.768504,0.0,36.768504,0.0,0.0,0.0,36.768504,0.0,36.768504
291,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,36.419172,0.0,36.419172,0.0,0.0,0.0,36.419172,0.0,36.419172
317,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,36.391254,0.0,36.391254,0.0,0.0,0.0,36.391254,0.0,36.391254
20,0,47.0,Morgan Rogers,a,7.5,MID,Aston Villa,35.750525,0.0,35.750525,0.0,0.0,0.0,35.750525,0.0,35.750525
401,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,35.705847,0.0,35.705847,0.0,0.0,0.0,35.705847,0.0,35.705847
227,0,660.0,Anton Stach,a,4.7,MID,Leeds,35.365025,0.0,35.365025,0.0,0.0,0.0,35.365025,0.0,35.365025
195,0,485.0,Anthony Gordon,a,7.2,MID,Newcastle,35.331511,0.0,35.331511,0.0,0.0,0.0,35.331511,0.0,35.331511
421,0,169.0,Diego Gómez Amarilla,a,4.9,MID,Brighton,34.961262,0.0,34.961262,0.0,0.0,0.0,34.961262,0.0,34.961262
21,0,36.0,Matty Cash,d,4.8,DEF,Aston Villa,34.923271,0.0,34.923271,0.0,0.0,0.0,34.923271,0.0,34.923271
193,0,44.0,Lamare Bogarde,a,4.0,DEF,Aston Villa,34.900149,0.0,34.900149,0.0,0.0,0.0,34.900149,0.0,34.900149
111,0,324.0,Alex Iwobi,a,6.4,MID,Fulham,34.890757,0.0,34.890757,0.0,0.0,0.0,34.890757,0.0,34.890757
323,0,40.0,Tyrone Mings,a,4.3,DEF,Aston Villa,34.639457,0.0,34.639457,0.0,0.0,0.0,34.639457,0.0,34.639457
155,0,252.0,Marc Guiu Paz,a,4.1,FWD,Chelsea,34.540276,0.0,34.540276,0.0,0.0,0.0,34.540276,0.0,34.540276
341,0,343.0,Pascal Struijk,a,4.3,DEF,Leeds,34.537183,0.0,34.537183,0.0,0.0,0.0,34.537183,0.0,34.537183
329,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,34.517522,0.0,34.517522,0.0,0.0,0.0,34.517522,0.0,34.517522
81,0,83.0,Dango Ouattara,a,6.0,MID,Brentford,34.437151,0.0,34.437151,0.0,0.0,0.0,34.437151,0.0,34.437151
138,0,59.0,Amadou Onana,a,4.8,MID,Aston Villa,34.348535,0.0,34.348535,0.0,0.0,0.0,34.348535,0.0,34.348535
82,0,146.0,Lewis Dunk,a,4.5,DEF,Brighton,34.296234,0.0,34.296234,0.0,0.0,0.0,34.296234,0.0,34.296234

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £91.7m / £102.4m
Total Weighted Expected Points: 264.91
Remaining Budget: £10.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Hákon Rafn Valdimarsson        Brentford    £3.9    19.05
 ✅        Bart Verbruggen                Brighton     £4.5    19.35

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Struijk                 Leeds        £4.3    21.41
 ✅        Nico O'Reilly                  Man City     £5.1    25.57
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    24.11
 ✅        Lucas Digne                    Aston Villa  £4.5    23.59
 ✅        Matty Cash                     Aston Villa  £4.8    23.04

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bruno Borges Fernandes         Man Utd      £10.1   25.03
 ✅        Alexis Mac Allister            Liverpool    £6.3    24.06
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3    23.43
 ✅        Dominik Szoboszlai             Liverpool    £6.9    23.29
 ✅        Cole Palmer                    Chelsea      £10.6   23.09

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Marc Guiu Paz                  Chelsea      £4.1    21.49
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2    21.13
 ✅        João Pedro Junqueira de Jesus  Chelsea      £7.7    22.04

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £88.2m / £102.4m
Total Weighted Expected Points: 407.72
Remaining Budget: £14.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5    31.03
 ✅        Hákon Rafn Valdimarsson        Brentford    £3.9    31.06

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Struijk                 Leeds        £4.3    34.54
 ✅        Matty Cash                     Aston Villa  £4.8    34.92
 ✅        Lamare Bogarde                 Aston Villa  £4.0    34.90
 ✅        Jurriën Timber                 Arsenal      £6.3    37.60
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    36.39

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3    37.17
 ✅        Alexis Mac Allister            Liverpool    £6.3    37.96
 ✅        Cole Palmer                    Chelsea      £10.6   37.23
 ✅        Dominik Szoboszlai             Liverpool    £6.9    36.77
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0    36.42

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Zian Flemming                  Burnley      £5.3    31.13
 🪑        Jean-Philippe Mateta           Crystal Palace £7.5    30.89
 ✅        Marc Guiu Paz                  Chelsea      £4.1    34.54

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,34.0,Nico O'Reilly,a,DEF,Man City,Burnley,5.1,7.249984
1,37.0,Nico O'Reilly,a,DEF,Man City,Bournemouth,5.1,6.291337
2,35.0,Nico O'Reilly,a,DEF,Man City,Everton,5.1,6.287559
3,36.0,Nico O'Reilly,a,DEF,Man City,Brentford,5.1,6.252823
4,38.0,Nico O'Reilly,a,DEF,Man City,Aston Villa,5.1,6.188091
5,32.0,Nico O'Reilly,a,DEF,Man City,Chelsea,5.1,6.186537
6,37.0,Jurriën Timber,a,DEF,Arsenal,Burnley,6.3,6.061429
7,33.0,Nico O'Reilly,a,DEF,Man City,Arsenal,5.1,5.841250
8,37.0,Gabriel dos Santos Magalhães,a,DEF,Arsenal,Burnley,7.2,5.811869
9,36.0,Jurriën Timber,a,DEF,Arsenal,West Ham,6.3,5.791601

In [17]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW31 to GW38...

Optimizing team selection for GW31...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £88.2m / £102.4m
Total Weighted Expected Points: 54.34
Remaining Budget: £14.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.99
 ✅        Bernd Leno                     Fulham       £4.9     4.20

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Nikola Milenković              Nott'm Forest £5.1     4.53
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4     5.04
 ✅        Lucas Digne                    Aston Villa  £4.5     5.01
 ✅        Matty Cash                     Aston Villa  £4.8     4.95
 ✅        Joachim Andersen               Fulham       £4.5     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    5.08
 ✅        Alex Iwobi                     Fulham       £6.4     4.92
 ✅        Alexis Mac Allister            Liverpool    £6.3     4.83
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3     4.76
 ✅        Dominik Szoboszlai             Liverpool    £6.9     4.67

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Marc Guiu Paz                  Chelsea      £4.1     4.36
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2     4.23
 ✅        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.42

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW32...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.5m / £102.4m
Total Weighted Expected Points: 56.18
Remaining Budget: £4.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        David Raya Martín              Arsenal      £6.0     4.08
 ✅        Bart Verbruggen                Brighton     £4.5     4.20

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     6.19
 ✅        Jurriën Timber                 Arsenal      £6.3     5.22
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     4.98
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4     4.90
 ✅        Lamare Bogarde                 Aston Villa  £4.0     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Diego Gómez Amarilla           Brighton     £4.9     4.73
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    5.35
 ✅        Alexis Mac Allister            Liverpool    £6.3     4.88
 ✅        Antoine Semenyo                Man City     £8.3     4.79
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.74

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.32
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2     4.22
 ✅        Jean-Philippe Mateta           Crystal Palace £7.5     4.43

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £96.1m / £102.4m
Total Weighted Expected Points: 54.50
Remaining Budget: £6.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     4.01
 ✅        Dean Henderson                 Crystal Palace £5.0     4.01

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gabriel dos Santos Magalhães   Arsenal      £7.2     4.63
 ✅        Nico O'Reilly                  Man City     £5.1     5.84
 ✅        Jurriën Timber                 Arsenal      £6.3     4.96
 ✅        Nikola Milenković              Nott'm Forest £5.1     4.86
 ✅        Murillo Costa dos Santos       Nott'm Forest £5.2     4.70

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Alexis Mac Allister            Liverpool    £6.3     4.84
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3     4.83
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    4.79
 ✅        Antoine Semenyo                Man City     £8.3     4.71
 ✅        Dominik Szoboszlai             Liverpool    £6.9     4.68

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.41
 🪑        Marc Guiu Paz                  Chelsea      £4.1     4.24
 ✅        Jean-Philippe Mateta           Crystal Palace £7.5     4.55

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.4m / £102.4m
Total Weighted Expected Points: 57.95
Remaining Budget: £5.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Đorđe Petrović                 Bournemouth  £4.5     3.90
 ✅        David Raya Martín              Arsenal      £6.0     4.00

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     7.25
 ✅        Matheus Nunes                  Man City     £5.4     5.56
 ✅        Jurriën Timber                 Arsenal      £6.3     5.19
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     4.95
 ✅        Marcos Senesi Barón            Bournemouth  £5.0     4.79

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Morgan Gibbs-White             Nott'm Forest £7.3     4.64
 ✅        Antoine Semenyo                Man City     £8.3     5.51
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    4.98
 ✅        Alexis Mac Allister            Liverpool    £6.3     4.87
 ✅        Dominik Szoboszlai             Liverpool    £6.9     4.70

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Marc Guiu Paz                  Chelsea      £4.1     4.34
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2     4.23
 ✅        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.42

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £93.2m / £102.4m
Total Weighted Expected Points: 56.64
Remaining Budget: £9.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Hákon Rafn Valdimarsson        Brentford    £3.9     3.94
 ✅        David Raya Martín              Arsenal      £6.0     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     6.29
 ✅        Jurriën Timber                 Arsenal      £6.3     5.20
 ✅        Lucas Digne                    Aston Villa  £4.5     5.18
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4     5.14
 ✅        Matty Cash                     Aston Villa  £4.8     5.08

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martín Zubimendi Ibáñez        Arsenal      £5.2     4.70
 ✅        Anton Stach                    Leeds        £4.7     4.87
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    4.83
 ✅        Antoine Semenyo                Man City     £8.3     4.81
 ✅        Cole Palmer                    Chelsea      £10.6    4.80

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.47
 🪑        Jean-Philippe Mateta           Crystal Palace £7.5     4.47
 ✅        Marc Guiu Paz                  Chelsea      £4.1     4.55

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £97.2m / £102.4m
Total Weighted Expected Points: 58.81
Remaining Budget: £5.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Hákon Rafn Valdimarsson        Brentford    £3.9     4.37
 ✅        David Raya Martín              Arsenal      £6.0     4.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     6.25
 ✅        Jurriën Timber                 Arsenal      £6.3     5.79
 ✅        Lucas Digne                    Aston Villa  £4.5     5.50
 ✅        William Saliba                 Arsenal      £6.1     5.45
 ✅        Matty Cash                     Aston Villa  £4.8     5.38

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Morgan Gibbs-White             Nott'm Forest £7.3     4.58
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    5.15
 ✅        Morgan Rogers                  Aston Villa  £7.5     4.94
 ✅        Antoine Semenyo                Man City     £8.3     4.82
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.67

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.35
 🪑        Marc Guiu Paz                  Chelsea      £4.1     4.17
 ✅        Jean-Philippe Mateta           Crystal Palace £7.5     4.48

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £101.8m / £102.4m
Total Weighted Expected Points: 58.69
Remaining Budget: £0.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5     3.98
 ✅        Filip Jörgensen                Chelsea      £4.3     4.03

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lewis Dunk                     Brighton     £4.5     4.59
 ✅        Nico O'Reilly                  Man City     £5.1     6.29
 ✅        Jurriën Timber                 Arsenal      £6.3     6.06
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.81
 ✅        William Saliba                 Arsenal      £6.1     5.77

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bruno Borges Fernandes         Man Utd      £10.1    5.20
 ✅        Cole Palmer                    Chelsea      £10.6    4.86
 ✅        Antoine Semenyo                Man City     £8.3     4.82
 ✅        Alex Iwobi                     Fulham       £6.4     4.77
 ✅        Harry Wilson                   Fulham       £6.0     4.74

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Jean-Philippe Mateta           Crystal Palace £7.5     4.47
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2     4.22
 ✅        João Pedro Junqueira de Jesus  Chelsea      £7.7     4.62

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £100.8m / £102.4m
Total Weighted Expected Points: 55.08
Remaining Budget: £1.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     4.01
 ✅        David Raya Martín              Arsenal      £6.0     4.10

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts

In [18]:

freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 36

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
60,36,Bruno Borges Fernandes,a,MID,Man Utd,Sunderland,10.1,5.145511
61,36,Morgan Rogers,a,MID,Aston Villa,Burnley,7.5,4.943150
62,36,Antoine Semenyo,a,MID,Man City,Brentford,8.3,4.817868
63,36,Matheus Santos Carneiro da Cunha,a,MID,Man Utd,Sunderland,8.0,4.666701
64,36,David Raya Martín,a,GK,Arsenal,West Ham,6.0,4.644463
65,36,Jean-Philippe Mateta,a,FWD,Crystal Palace,Everton,7.5,4.479865
55,36,Nico O'Reilly,a,DEF,Man City,Brentford,5.1,6.252823
56,36,Jurriën Timber,a,DEF,Arsenal,West Ham,6.3,5.791601
57,36,Lucas Digne,a,DEF,Aston Villa,Burnley,4.5,5.499873
58,36,William Saliba,a,DEF,Arsenal,West Ham,6.1,5.445882
59,36,Matty Cash,d,DEF,Aston Villa,Burnley,4.8,5.375478

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)