In [6]:
import pandas as pd
import time
#other requirements: pulp

In [7]:
start=time.perf_counter()

In [8]:
#add this info to a settings dict?
current_gw = 27
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [9]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [ ]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  28
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
4438260 Jack Carroll GW 1 Pick 1
4438260 Jack Carroll GW 1 Pick 2
4438260 Jack Carroll GW 1 Pick 3
4438260 Jack Carroll GW 1 Pick 4
4438260 Jack Carroll GW 1 Pick 5
4438260 Jack Carroll GW 1 Pick 6
4438260 Jack Carroll GW 1 Pick 7
4438260 Jack Carroll GW 1 Pick 8
4438260 Jack Carroll GW 1 Pick 9
4438260 Jack Carroll GW 1 Pick 10
4438260 Jack Carroll GW 1 Pick 11
4438260 Jack Carroll GW 1 Pick 12
4438260 Jack Carroll GW 1 Pick 13
4438260 Jack Carroll GW 1 Pick 14
4438260 Jack Carroll GW 1 Pick 15
4438260 Jack Carroll GW 2 Pick 1
4438260 Jack Carroll GW 2 Pick 2
4438260 Jack Carroll GW 2 Pick 3
4438260 Jack Carroll GW 2 Pick 4
4438260 Jack Carroll GW 2 Pick 5
4438260 Jack Carroll GW 2 Pick 6
4438260 Jack Carroll GW 2 Pick 7
4438260 Jack Carroll GW 2 Pick 8
4438260 Jack Carroll GW 2 Pick 9
4438260 Jack Carroll GW 2 Pick 10
4438260 Jack Carroll GW 2 Pick 11
4438260 Jack Carroll GW 2 Pick 12
4438260 Jack Carroll GW 2 Pick 13
4438260 Jack Carroll GW 2 Pick 14
4438260 Jack Carroll GW 2 Pick 15
4438260 Jack Carroll GW 3 Pick 1
4438260 Jack Carroll GW 3 Pick 2
4438260 Jack Carroll GW 3 Pick 3
4438260 Jack Carroll GW 3 Pick 4
4438260 Jack Carroll GW 3 Pick 5
4438260 Jack Carroll GW 3 Pick 6
4438260 Jack Carroll GW 3 Pick 7
4438260 Jack Carroll GW 3 Pick 8
4438260 Jack Carroll GW 3 Pick 9
4438260 Jack Carroll GW 3 Pick 10
4438260 Jack Carroll GW 3 Pick 11
4438260 Jack Carroll GW 3 Pick 12
4438260 Jack Carroll GW 3 Pick 13
4438260 Jack Carroll GW 3 Pick 14
4438260 Jack Carroll GW 3 Pick 15
4438260 Jack Carroll GW 4 Pick 1
4438260 Jack Carroll GW 4 Pick 2
4438260 Jack Carroll GW 4 Pick 3
4438260 Jack Carroll GW 4 Pick 4
4438260 Jack Carroll GW 4 Pick 5
4438260 Jack Carroll GW 4 Pick 6
4438260 Jack Carroll GW 4 Pick 7
4438260 Jack Carroll GW 4 Pick 8
4438260 Jack Carroll GW 4 Pick 9
4438260 Jack Carroll GW 4 Pick 10
4438260 Jack Carroll GW 4 Pick 11
4438260 Jack Carroll GW 4 Pick 12
4438260 Jack Carroll GW 4 Pick 13
4438260 Jack Carroll GW 4 Pick 14
4438260 Jack Carroll GW 4 Pick 15
4438260 Jack Carroll GW 5 Pick 1
4438260 Jack Carroll GW 5 Pick 2
4438260 Jack Carroll GW 5 Pick 3
4438260 Jack Carroll GW 5 Pick 4
4438260 Jack Carroll GW 5 Pick 5
4438260 Jack Carroll GW 5 Pick 6
4438260 Jack Carroll GW 5 Pick 7
4438260 Jack Carroll GW 5 Pick 8
4438260 Jack Carroll GW 5 Pick 9
4438260 Jack Carroll GW 5 Pick 10
4438260 Jack Carroll GW 5 Pick 11
4438260 Jack Carroll GW 5 Pick 12
4438260 Jack Carroll GW 5 Pick 13
4438260 Jack Carroll GW 5 Pick 14
4438260 Jack Carroll GW 5 Pick 15
4438260 Jack Carroll GW 6 Pick 1
4438260 Jack Carroll GW 6 Pick 2
4438260 Jack Carroll GW 6 Pick 3
4438260 Jack Carroll GW 6 Pick 4
4438260 Jack Carroll GW 6 Pick 5
4438260 Jack Carroll GW 6 Pick 6
4438260 Jack Carroll GW 6 Pick 7
4438260 Jack Carroll GW 6 Pick 8
4438260 Jack Carroll GW 6 Pick 9
4438260 Jack Carroll GW 6 Pick 10
4438260 Jack Carroll GW 6 Pick 11
4438260 Jack Carroll GW 6 Pick 12
4438260 Jack Carroll GW 6 Pick 13
4438260 Jack Carroll GW 6 Pick 14
4438260 Jack Carroll GW 6 Pick 15
4438260 Jack Carroll GW 7 Pick 1
4438260 Jack Carroll GW 7 Pick 2
4438260 Jack Carroll GW 7 Pick 3
4438260 Jack Carroll GW 7 Pick 4
4438260 Jack Carroll GW 7 Pick 5
4438260 Jack Carroll GW 7 Pick 6
4438260 Jack Carroll GW 7 Pick 7
4438260 Jack Carroll GW 7 Pick 8
4438260 Jack Carroll GW 7 Pick 9
4438260 Jack Carroll GW 7 Pick 10
4438260 Jack Carroll GW 7 Pick 11
4438260 Jack Carroll GW 7 Pick 12
4438260 Jack Carroll GW 7 Pick 13
4438260 Jack Carroll GW 7 Pick 14
4438260 Jack Carroll GW 7 Pick 15
4438260 Jack Carroll GW 8 Pick 1
4438260 Jack Carroll GW 8 Pick 2
4438260 Jack Carroll GW 8 Pick 3
4438260 Jack Carroll GW 8 Pick 4
4438260 Jack Carroll GW 8 Pick 5
4438260 Jack Carroll GW 8 Pick 6
4438260 Jack Carroll GW 8 Pick 7
4438260 Jack Carroll GW 8 Pick 8
4438260 Jack Carroll GW 8 Pick 9
4438260 Jack Carroll GW 8 Pick 10
4438260 Jack Carroll GW 8 Pick 11
4438260 Jack Carroll GW 8 Pick 12
4438260 Jack Carroll GW 8 Pick 13
4438260 Jack Carroll GW 8 Pick 14
4438260 Jack Carroll GW 8 Pick 15
4438260 Jack Carroll GW 9 Pick 1
4438260 Jack Carroll GW 9 Pick 2
4438260 Jack Carroll GW 9 Pick 3
4438260 Jack Carroll GW 9 Pick 4
4438260 Jack Carroll GW 9 Pick 5
4438260 Jack Carroll GW 9 Pick 6
4438260 Jack Carroll GW 9 Pick 7
4438260 Jack Carroll GW 9 Pick 8
4438260 Jack Carroll GW 9 Pick 9
4438260 Jack Carroll GW 9 Pick 10
4438260 Jack Carroll GW 9 Pick 11
4438260 Jack Carroll GW 9 Pick 12
4438260 Jack Carroll GW 9 Pick 13
4438260 Jack Carroll GW 9 Pick 14
4438260 Jack Carroll GW 9 Pick 15
4438260 Jack Carroll GW 10 Pick 1
4438260 Jack Carroll GW 10 Pick 2
4438260 Jack Carroll GW 10 Pick 3
4438260 Jack Carroll GW 10 Pick 4
4438260 Jack Carroll GW 10 Pick 5

In [39]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW28 to GW32

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Virgil van Dijk,a,0,DEF,Liverpool,996.9,4.95,83.0,0.051,0.045,0.883
1,Ibrahima Konaté,a,1,DEF,Liverpool,996.9,4.92,86.5,0.049,0.044,0.893
2,Florian Wirtz,a,0,MID,Liverpool,996.9,4.84,83.6,0.190,0.204,0.964
3,Enzo Fernández,a,0,MID,Chelsea,1155.0,4.75,85.1,0.229,0.201,1.687
4,Lamare Bogarde,a,0,DEF,Aston Villa,1028.4,4.71,67.1,0.037,0.054,0.780
5,Cole Palmer,a,0,MID,Chelsea,1155.0,4.70,74.1,0.248,0.207,1.494
6,Ethan Pinnock,a,0,DEF,Brentford,987.9,4.68,66.0,0.243,0.072,1.282
7,Andrew Robertson,a,0,DEF,Liverpool,996.9,4.66,69.8,0.038,0.060,0.885
8,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,1028.4,4.64,86.9,0.037,0.046,0.941
9,Tyrone Mings,a,1,DEF,Aston Villa,1028.4,4.59,82.3,0.036,0.047,0.943
10,Ian Maatsen,a,1,DEF,Aston Villa,1028.4,4.59,76.2,0.037,0.056,0.912
11,Bruno Borges Fernandes,a,1,MID,Man Utd,1070.1,4.59,83.5,0.178,0.209,1.429
12,Matty Cash,a,0,DEF,Aston Villa,1028.4,4.58,85.3,0.039,0.054,0.976
13,Mathias Jensen,a,0,MID,Brentford,987.9,4.57,83.4,0.149,0.171,1.091
14,Milos Kerkez,a,0,DEF,Liverpool,996.9,4.56,72.7,0.044,0.050,1.002
15,Morgan Rogers,a,0,MID,Aston Villa,1028.4,4.54,85.4,0.173,0.136,1.071
16,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,987.9,4.54,85.2,0.446,0.057,1.221
17,Nico O'Reilly,a,0,DEF,Man City,1030.6,4.51,73.9,0.103,0.057,0.865
18,Mohamed Salah,a,0,MID,Liverpool,996.9,4.50,75.4,0.217,0.148,1.050
19,Antoine Semenyo,a,0,MID,Man City,1030.6,4.49,86.1,0.249,0.204,0.951
20,Max Alleyne,d,0,DEF,Man City,1030.6,4.47,68.0,0.218,0.062,1.052
21,Vitaly Janelt,a,0,MID,Brentford,987.9,4.44,79.3,0.158,0.166,1.089
22,Dominik Szoboszlai,a,1,MID,Liverpool,996.9,4.43,72.2,0.169,0.213,1.042
23,Harry Wilson,a,0,MID,Fulham,1010.2,4.39,76.8,0.177,0.157,1.183
24,Kristoffer Ajer,a,0,DEF,Brentford,987.9,4.39,82.4,0.040,0.060,1.095
25,Sepp van den Berg,a,0,DEF,Brentford,987.9,4.35,84.1,0.045,0.049,1.118
26,Alex Scott,a,0,MID,Bournemouth,1068.7,4.35,85.4,0.156,0.120,1.297
27,Rico Henry,a,0,DEF,Brentford,987.9,4.35,81.5,0.047,0.055,1.125
28,Matthijs de Ligt,d,0,DEF,Man Utd,1070.1,4.34,66.7,0.296,0.065,1.578
29,Dango Ouattara,a,0,MID,Brentford,987.9,4.33,75.5,0.197,0.136,1.126
30,Michael Kayode,d,0,DEF,Brentford,987.9,4.32,86.0,0.037,0.050,1.125
31,Matheus Nunes,a,1,DEF,Man City,1030.6,4.32,81.5,0.040,0.105,0.926
32,Keane Lewis-Potter,a,0,DEF,Brentford,987.9,4.31,74.9,0.051,0.060,1.122
33,Lucas Digne,a,0,DEF,Aston Villa,1028.4,4.29,59.5,0.051,0.057,0.901
34,Crysencio Summerville,a,0,MID,West Ham,1105.5,4.28,84.5,0.185,0.124,1.499
35,Rico Lewis,a,0,DEF,Man City,1030.6,4.27,66.0,0.218,0.051,1.134
36,Moisés Caicedo Corozo,a,0,MID,Chelsea,1155.0,4.25,85.6,0.120,0.203,1.618
37,Rúben dos Santos Gato Alves Dias,a,0,DEF,Man City,1030.6,4.24,75.9,0.041,0.047,0.886
38,Marc Guéhi,a,0,DEF,Man City,1030.6,4.24,80.3,0.044,0.041,0.895
39,Iliman Ndiaye,a,0,MID,Everton,1084.0,4.23,82.5,0.176,0.123,1.460
40,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1155.0,4.21,72.1,0.411,0.120,1.494
41,Joachim Andersen,a,0,DEF,Fulham,1010.2,4.18,86.5,0.038,0.046,1.224
42,Pau Torres,a,0,DEF,Aston Villa,1028.4,4.18,66.1,0.036,0.048,1.006
43,Alex Iwobi,a,0,MID,Fulham,1010.2,4.16,80.4,0.137,0.147,1.270
44,Nordi Mukiele,a,0,DEF,Sunderland,1038.6,4.15,86.0,0.039,0.052,1.183
45,Carlos Henrique Casimiro,a,0,MID,Man Utd,1070.1,4.15,83.6,0.123,0.152,1.394
46,Bryan Mbeumo,a,0,MID,Man Utd,1070.1,4.13,81.1,0.167,0.120,1.463
47,Amine Adli,a,0,MID,Bournemouth,1068.7,4.12,75.8,0.173,0.110,1.292
48,Marc Guiu Paz,a,0,FWD,Chelsea,1155.0,4.12,45.8,0.740,0.318,1.597
49,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1028.4,4.11,74.1,0.136,0.132,1.058

In [42]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 28 and 32:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Virgil van Dijk,a,DEF,Liverpool,5.9,996.9,24.44,83.0,0.051,0.045,0.883
1,Ibrahima Konaté,a,DEF,Liverpool,5.4,996.9,24.29,86.5,0.049,0.044,0.893
2,Florian Wirtz,a,MID,Liverpool,8.4,996.9,23.97,83.6,0.190,0.204,0.964
3,Enzo Fernández,a,MID,Chelsea,6.9,1155.0,23.91,85.1,0.229,0.201,1.687
4,Cole Palmer,a,MID,Chelsea,10.6,1155.0,23.58,74.1,0.248,0.207,1.494
5,Lamare Bogarde,a,DEF,Aston Villa,4.0,1028.4,23.52,67.1,0.037,0.054,0.780
6,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,1028.4,23.22,86.9,0.037,0.046,0.941
7,Ethan Pinnock,a,DEF,Brentford,4.2,987.9,23.19,66.0,0.243,0.072,1.282
8,Bruno Borges Fernandes,a,MID,Man Utd,9.8,1070.1,23.07,83.5,0.178,0.209,1.429
9,Andrew Robertson,a,DEF,Liverpool,5.7,996.9,22.99,69.8,0.038,0.060,0.885
10,Tyrone Mings,a,DEF,Aston Villa,4.3,1028.4,22.89,82.3,0.036,0.047,0.943
11,Matty Cash,a,DEF,Aston Villa,4.9,1028.4,22.87,85.3,0.039,0.054,0.976
12,Ian Maatsen,a,DEF,Aston Villa,4.2,1028.4,22.82,76.2,0.037,0.056,0.912
13,Mathias Jensen,a,MID,Brentford,4.9,987.9,22.74,83.4,0.149,0.171,1.091
14,Morgan Rogers,a,MID,Aston Villa,7.7,1028.4,22.63,85.4,0.173,0.136,1.071
15,Igor Thiago Nascimento Rodrigues,a,FWD,Brentford,7.0,987.9,22.59,85.2,0.446,0.057,1.221
16,Mohamed Salah,a,MID,Liverpool,14.0,996.9,22.34,75.4,0.217,0.148,1.050
17,Milos Kerkez,a,DEF,Liverpool,5.6,996.9,22.17,72.7,0.044,0.050,1.002
18,Vitaly Janelt,a,MID,Brentford,4.9,987.9,22.12,79.3,0.158,0.166,1.089
19,Dominik Szoboszlai,a,MID,Liverpool,6.7,996.9,22.01,72.2,0.169,0.213,1.042

In [28]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        1499.0
1               Jack Carroll  4438260.0        1486.0
2                 Ryan Boyce  5398818.0        1477.0
3          William Partridge  6588565.0        1443.0
4                 Rhys Birdy  5810139.0        1424.0
5         Christopher Harris    28660.0        1422.0
6               Tommy Davies  7845816.0        1420.0
7               Samia Shelim  6506490.0        1416.0
8              Rizwan Shelim  3058994.0        1385.0
9             Conner Harling  3421093.0        1383.0
10  Christakis Christodoulou  7474864.0        1371.0
11        Christopher Harris   145486.0        1363.0
12             Ollie Carroll  5181285.0        1356.0
13               Nafi Shelim  4776281.0        1351.0
14             Tajwar Shelim  4773459.0        1316.0
15              Will Hossack  4792527.0        1291.0
16               Simon Meech  6764382.0        1244.0
17            Charlie Garner  9432680.0        1234.0
18              Tahmid Haque  6394829.0        1233.0
19              Holly Stower  7367977.0        1156.0
20            Rachel Aumayer  9763056.0        1012.0

In [ ]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value
        -- {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value
161,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,52.262578,0.0,52.262578,0.000000,52.262578,0.0,52.262578,52.262578
131,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,46.540835,0.0,46.540835,0.000000,46.540835,0.0,46.540835,46.540835
344,1,32.0,Emiliano Martínez Romero,a,5.0,GK,Aston Villa,43.204006,0.0,43.204006,0.000000,43.204006,0.0,43.204006,43.204006
347,1,337.0,Raúl Jiménez Rodríguez,a,6.1,FWD,Fulham,40.302420,0.0,40.302420,0.000000,40.302420,0.0,40.302420,40.302420
210,1,691.0,Dominic Calvert-Lewin,a,5.8,FWD,Leeds,39.516834,0.0,39.516834,0.000000,39.516834,0.0,39.516834,39.516834
31,1,341.0,Karl Darlow,a,3.9,GK,Leeds,38.481846,0.0,38.481846,0.000000,38.481846,0.0,38.481846,38.481846
319,1,8.0,Jurriën Timber,a,6.4,DEF,Arsenal,47.906760,40.0,28.744056,-19.162704,28.744056,0.0,9.581352,28.744056
281,1,237.0,Enzo Fernández,a,6.9,MID,Chelsea,53.591124,60.0,21.436450,-32.154675,21.436450,0.0,-10.718225,21.436450
180,1,449.0,Bruno Borges Fernandes,a,9.8,MID,Man Utd,50.541752,60.0,20.216701,-30.325051,20.216701,0.0,-10.108350,20.216701
37,1,5.0,Gabriel dos Santos Magalhães,a,7.1,DEF,Arsenal,46.792198,60.0,18.716879,-28.075319,18.716879,0.0,-9.358440,18.716879
280,1,694.0,Nordi Mukiele,a,4.6,DEF,Sunderland,44.726699,60.0,17.890680,-26.836019,17.890680,0.0,-8.945340,17.890680
86,1,661.0,Hugo Ekitiké,a,8.9,FWD,Liverpool,43.918297,60.0,17.567319,-26.350978,17.567319,0.0,-8.783659,17.567319
107,1,21.0,Declan Rice,a,7.6,MID,Arsenal,46.677841,100.0,0.000000,-46.677841,0.000000,0.0,-46.677841,0.000000

In [103]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value
301,0,430.0,Erling Haaland,a,14.8,FWD,Man City,46.093081,140.0,-18.437233,-64.530314,0.0,-64.530314,-82.967547,-64.530314
282,0,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,47.280894,120.0,-9.456179,-56.737072,0.0,-56.737072,-66.193251,-56.737072
113,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,45.881983,80.0,9.176397,-36.705586,0.0,-36.705586,-27.529190,-36.705586
103,0,226.0,Trevoh Chalobah,a,5.8,DEF,Chelsea,37.391602,80.0,7.478320,-29.913282,0.0,-29.913282,-22.434961,-29.913282
135,0,47.0,Morgan Rogers,a,7.7,MID,Aston Villa,49.449072,60.0,19.779629,-29.669443,0.0,-29.669443,-9.889814,-29.669443
330,0,36.0,Matty Cash,a,4.9,DEF,Aston Villa,49.379401,60.0,19.751761,-29.627641,0.0,-29.627641,-9.875880,-29.627641
49,0,82.0,Antoine Semenyo,a,8.0,MID,Man City,51.338873,40.0,30.803324,-20.535549,0.0,-20.535549,10.267775,-20.535549
394,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.0,FWD,Brentford,48.957544,40.0,29.374526,-19.583018,0.0,-19.583018,9.791509,-19.583018
188,0,1.0,David Raya Martín,a,6.0,GK,Arsenal,42.269445,40.0,25.361667,-16.907778,0.0,-16.907778,8.453889,-16.907778
168,0,736.0,Gianluigi Donnarumma,a,5.6,GK,Man City,41.831173,40.0,25.098704,-16.732469,0.0,-16.732469,8.366235,-16.732469
162,0,329.0,Harry Wilson,a,5.9,MID,Fulham,46.491039,20.0,37.192831,-9.298208,0.0,-9.298208,27.894624,-9.298208
374,0,26.0,Martín Zubimendi Ibáñez,a,5.3,MID,Arsenal,45.774432,20.0,36.619545,-9.154886,0.0,-9.154886,27.464659,-9.154886
63,0,457.0,Carlos Henrique Casimiro,a,5.6,MID,Man Utd,45.706924,20.0,36.565539,-9.141385,0.0,-9.141385,27.424154,-9.141385
381,0,390.0,Ryan Gravenberch,a,5.5,MID,Liverpool,43.715606,20.0,34.972485,-8.743121,0.0,-8.743121,26.229364,-8.743121
326,0,242.0,Kiernan Dewsbury-Hall,a,4.9,MID,Everton,41.771901,20.0,33.417521,-8.354380,0.0,-8.354380,25.063141,-8.354380
17,0,220.0,Robert Lynch Sánchez,a,4.9,GK,Chelsea,38.969125,20.0,31.175300,-7.793825,0.0,-7.793825,23.381475,-7.793825
39,0,470.0,Martin Dúbravka,a,4.0,GK,Burnley,32.182132,20.0,25.745705,-6.436426,0.0,-6.436426,19.309279,-6.436426
0,0,414.0,Phil Foden,a,8.2,MID,Man City,33.394911,0.0,33.394911,0.000000,0.0,0.000000,33.394911,0.000000
384,0,18.0,Noni Madueke,a,6.8,MID,Arsenal,37.059843,0.0,37.059843,0.000000,0.0,0.000000,37.059843,0.000000
385,0,814.0,Luca Netz,a,4.5,DEF,Nott'm Forest,34.956772,0.0,34.956772,0.000000,0.0,0.000000,34.956772,0.000000

In [104]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW28 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value
88,0,374.0,Ibrahima Konaté,a,5.4,DEF,Liverpool,51.543295,0.0,51.543295,0.0,0.0,0.0,51.543295,0.0
308,0,382.0,Florian Wirtz,a,8.4,MID,Liverpool,51.308830,0.0,51.308830,0.0,0.0,0.0,51.308830,0.0
184,0,373.0,Virgil van Dijk,a,5.9,DEF,Liverpool,51.140158,0.0,51.140158,0.0,0.0,0.0,51.140158,0.0
174,0,44.0,Lamare Bogarde,a,4.0,DEF,Aston Villa,51.058830,0.0,51.058830,0.0,0.0,0.0,51.058830,0.0
292,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,50.806878,0.0,50.806878,0.0,0.0,0.0,50.806878,0.0
356,0,111.0,Ethan Pinnock,a,4.2,DEF,Brentford,49.966480,0.0,49.966480,0.0,0.0,0.0,49.966480,0.0
295,0,40.0,Tyrone Mings,a,4.3,DEF,Aston Villa,49.848077,0.0,49.848077,0.0,0.0,0.0,49.848077,0.0
120,0,39.0,Ian Maatsen,a,4.2,DEF,Aston Villa,49.822040,0.0,49.822040,0.0,0.0,0.0,49.822040,0.0
261,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,48.756098,0.0,48.756098,0.0,0.0,0.0,48.756098,0.0
145,0,794.0,Max Alleyne,d,4.1,DEF,Man City,48.755816,0.0,48.755816,0.0,0.0,0.0,48.755816,0.0
85,0,372.0,Andrew Robertson,a,5.7,DEF,Liverpool,48.323877,0.0,48.323877,0.0,0.0,0.0,48.323877,0.0
224,0,436.0,Matthijs de Ligt,d,4.9,DEF,Man Utd,48.309855,0.0,48.309855,0.0,0.0,0.0,48.309855,0.0
383,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,48.156778,0.0,48.156778,0.0,0.0,0.0,48.156778,0.0
96,0,615.0,Crysencio Summerville,a,5.6,MID,West Ham,47.966059,0.0,47.966059,0.0,0.0,0.0,47.966059,0.0
189,0,411.0,Nico O'Reilly,a,4.9,DEF,Man City,47.946533,0.0,47.946533,0.0,0.0,0.0,47.946533,0.0
207,0,125.0,Vitaly Janelt,a,4.9,MID,Brentford,47.852946,0.0,47.852946,0.0,0.0,0.0,47.852946,0.0
36,0,241.0,Moisés Caicedo Corozo,a,5.7,MID,Chelsea,47.813373,0.0,47.813373,0.0,0.0,0.0,47.813373,0.0
118,0,90.0,Alex Scott,a,5.0,MID,Bournemouth,47.522426,0.0,47.522426,0.0,0.0,0.0,47.522426,0.0
137,0,387.0,Dominik Szoboszlai,a,6.7,MID,Liverpool,47.118242,0.0,47.118242,0.0,0.0,0.0,47.118242,0.0
304,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,46.481180,0.0,46.481180,0.0,0.0,0.0,46.481180,0.0

In [105]:
from FPL_Optimizer import FPLOptimizer

In [106]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £94.6m / £102.4m
Total Weighted Expected Points: 263.75
Remaining Budget: £7.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bernd Leno                     Fulham       £4.9    19.40
 ✅        Emiliano Martínez Romero       Aston Villa  £5.0    19.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Virgil van Dijk                Liverpool    £5.9    24.44
 ✅        Ibrahima Konaté                Liverpool    £5.4    24.29
 ✅        Lamare Bogarde                 Aston Villa  £4.0    23.52
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    23.22
 ✅        Ethan Pinnock                  Brentford    £4.2    23.19

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mathias Jensen                 Brentford    £4.9    22.74
 ✅        Florian Wirtz                  Liverpool    £8.4    23.97
 ✅        Enzo Fernández                 Chelsea      £6.9    23.91
 ✅        Cole Palmer                    Chelsea      £10.6   23.58
 ✅        Bruno Borges Fernandes         Man Utd      £9.8    23.07

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7    21.11
 🪑        Brian Brobbey                  Sunderland   £5.5    18.82
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.0    22.59

================================================================================
Optimization Status: Optimal

In [107]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £88.6m / £102.4m
Total Weighted Expected Points: 561.58
Remaining Budget: £13.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Stefan Ortega Moreno           Nott'm Forest £4.7    42.46
 ✅        Emiliano Martínez Romero       Aston Villa  £5.0    43.20

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Ibrahima Konaté                Liverpool    £5.4    51.54
 ✅        Lamare Bogarde                 Aston Villa  £4.0    51.06
 ✅        Virgil van Dijk                Liverpool    £5.9    51.14
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    50.81
 ✅        Ethan Pinnock                  Brentford    £4.2    49.97

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Vitaly Janelt                  Brentford    £4.9    47.85
 ✅        Crysencio Summerville          West Ham     £5.6    47.97
 ✅        Cole Palmer                    Chelsea      £10.6   52.26
 ✅        Mathias Jensen                 Brentford    £4.9    48.76
 ✅        Florian Wirtz                  Liverpool    £8.4    51.31

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Viktor Gyökeres                Arsenal      £8.8    43.61
 🪑        Jarrod Bowen                   West Ham     £7.6    41.45
 ✅        Marc Guiu Paz                  Chelsea      £4.2    46.04

================================================================================
Optimization Status: Optimal

In [108]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [109]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)