In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 29
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  30
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4
5398818 Ryan Boyce GW 5 Pick 5
5398818 Ryan Boyce GW 5 Pick 6
5398818 Ryan Boyce GW 5 Pick 7
5398818 Ryan Boyce GW 5 Pick 8
5398818 Ryan Boyce GW 5 Pick 9
5398818 Ryan Boyce GW 5 Pick 10
5398818 Ryan Boyce GW 5 Pick 11
5398818 Ryan Boyce GW 5 Pick 12
5398818 Ryan Boyce GW 5 Pick 13
5398818 Ryan Boyce GW 5 Pick 14
5398818 Ryan Boyce GW 5 Pick 15
5398818 Ryan Boyce GW 6 Pick 1
5398818 Ryan Boyce GW 6 Pick 2
5398818 Ryan Boyce GW 6 Pick 3
5398818 Ryan Boyce GW 6 Pick 4
5398818 Ryan Boyce GW 6 Pick 5
5398818 Ryan Boyce GW 6 Pick 6
5398818 Ryan Boyce GW 6 Pick 7
5398818 Ryan Boyce GW 6 Pick 8
5398818 Ryan Boyce GW 6 Pick 9
5398818 Ryan Boyce GW 6 Pick 10
5398818 Ryan Boyce GW 6 Pick 11
5398818 Ryan Boyce GW 6 Pick 12
5398818 Ryan Boyce GW 6 Pick 13
5398818 Ryan Boyce GW 6 Pick 14
5398818 Ryan Boyce GW 6 Pick 15
5398818 Ryan Boyce GW 7 Pick 1
5398818 Ryan Boyce GW 7 Pick 2
5398818 Ryan Boyce GW 7 Pick 3
5398818 Ryan Boyce GW 7 Pick 4
5398818 Ryan Boyce GW 7 Pick 5
5398818 Ryan Boyce GW 7 Pick 6
5398818 Ryan Boyce GW 7 Pick 7
5398818 Ryan Boyce GW 7 Pick 8
5398818 Ryan Boyce GW 7 Pick 9
5398818 Ryan Boyce GW 7 Pick 10
5398818 Ryan Boyce GW 7 Pick 11
5398818 Ryan Boyce GW 7 Pick 12
5398818 Ryan Boyce GW 7 Pick 13
5398818 Ryan Boyce GW 7 Pick 14
5398818 Ryan Boyce GW 7 Pick 15
5398818 Ryan Boyce GW 8 Pick 1
5398818 Ryan Boyce GW 8 Pick 2
5398818 Ryan Boyce GW 8 Pick 3
5398818 Ryan Boyce GW 8 Pick 4
5398818 Ryan Boyce GW 8 Pick 5
5398818 Ryan Boyce GW 8 Pick 6
5398818 Ryan Boyce GW 8 Pick 7
5398818 Ryan Boyce GW 8 Pick 8
5398818 Ryan Boyce GW 8 Pick 9
5398818 Ryan Boyce GW 8 Pick 10
5398818 Ryan Boyce GW 8 Pick 11
5398818 Ryan Boyce GW 8 Pick 12
5398818 Ryan Boyce GW 8 Pick 13
5398818 Ryan Boyce GW 8 Pick 14
5398818 Ryan Boyce GW 8 Pick 15
5398818 Ryan Boyce GW 9 Pick 1
5398818 Ryan Boyce GW 9 Pick 2
5398818 Ryan Boyce GW 9 Pick 3
5398818 Ryan Boyce GW 9 Pick 4
5398818 Ryan Boyce GW 9 Pick 5
5398818 Ryan Boyce GW 9 Pick 6
5398818 Ryan Boyce GW 9 Pick 7
5398818 Ryan Boyce GW 9 Pick 8
5398818 Ryan Boyce GW 9 Pick 9
5398818 Ryan Boyce GW 9 Pick 10
5398818 Ryan Boyce GW 9 Pick 11
5398818 Ryan Boyce GW 9 Pick 12
5398818 Ryan Boyce GW 9 Pick 13
5398818 Ryan Boyce GW 9 Pick 14
5398818 Ryan Boyce GW 9 Pick 15
5398818 Ryan Boyce GW 10 Pick 1
5398818 Ryan Boyce GW 10 Pick 2
5398818 Ryan Boyce GW 10 Pick 3
5398818 Ryan Boyce GW 10 Pick 4
5398818 Ryan Boyce GW 10 Pick 5
5398818 Ryan Boyce GW 10 Pick 6
5398818 Ryan Boyce GW 10 Pick 7
5398818 Ryan Boyce GW 10 Pick 8
5398818 Ryan Boyce GW 10 Pick 9
5398818 Ryan Boyce GW 10 Pick 10
5398818 Ryan Boyce GW 10 Pick 11
5398818 Ryan Boyce GW 10 Pick 12
5398818 Ryan Boyce GW 10 Pick 13
5398818 Ryan Boyce GW 10 Pick 14
5398818 Ryan Boyce GW 10 Pick 15
5398818 Ryan Boyce GW 11 Pick 1
5398818 Ryan Boyce GW 11 Pick 2
5398818 Ryan Boyce GW 11 Pick 3
5398818 Ryan Boyce GW 11 Pick 4
5398818 Ryan Boyce GW 11 Pick 5
5398818 Ryan Boyce GW 11 Pick 6
5398818 Ryan Boyce GW 11 Pick 7
5398818 Ryan Boyce GW 11 Pick 8
5398818 Ryan Boyce GW 11 Pick 9
5398818 Ryan Boyce GW 11 Pick 10
5398818 Ryan Boyce GW 11 Pick 11
5398818 Ryan Boyce GW 11 Pick 12
5398818 Ryan Boyce GW 11 Pick 13
5398818 Ryan Boyce GW 11 Pick 14
5398818 Ryan Boyce GW 11 Pick 15
5398818 Ryan Boyce GW 12 Pick 1
5398818 Ryan Boyce GW 12 Pick 2
5398818 Ryan Boyce GW 12 Pick 3
5398818 Ryan Boyce GW 12 Pick 4
5398818 Ryan Boyce GW 12 Pick 5
5398818 Ryan Boyce GW 12 Pick 6
5398818 Ryan Boyce GW 12 Pick 7
5398818 Ryan Boyce GW 12 Pick 8
5398818 Ryan Boyce GW 12 Pick 9
5398818 Ryan Boyce GW 12 Pick 10
5398818 Ryan Boyce GW 12 Pick 11
5398818 Ryan Boyce GW 12 Pick 12
5398818 Ryan Boyce GW 12 Pick 13
5398818 Ryan Boyce GW 12 Pick 14
5398818 Ryan Boyce GW 12 Pick 15
5398818 Ryan Boyce GW 13 Pick 1
5398818 Ryan Boyce GW 13 Pick 2
5398818 Ryan Boyce GW 13 Pick 3
5398818 Ryan Boyce GW 13 Pick 4
5398818 Ryan Boyce GW 13 Pick 5
5398818 Ryan Boyce GW 13 Pick 6
5398818 Ryan Boyce GW 13 Pick 7
5398818 Ryan Boyce GW 13 Pick 8
5398818 Ryan Boyce GW 13 Pick 9
5398818 Ryan Boyce GW 13 Pick 10
5398818 Ryan Boyce GW 13 Pick 11
5398818 Ryan Boyce GW 13 Pick 12
5398818 Ryan Boyce GW 13 Pick 13
5398818 Ryan Boyce GW 13 Pick 14
5398818 Ryan Boyce GW 13 Pick 15
5398818 Ryan Boyce GW 14 Pick 1
5398818 Ryan Boyce GW 14 Pick 2
5398818 Ryan Boyce GW 14 Pick 3
5398818 Ryan Boyce GW 14 Pick 4
5398818 Ryan Boyce GW 14 Pick 5
5398818 Ryan Boyce GW 14 Pick 6
5398818 Ryan Boyce GW 14 Pick 7
5398818 Ryan Boyce GW 14 Pick 8
5398818 Ryan Boyce GW 14 Pick 9
5398818 Ryan Boyce GW 14 Pick 10
5398818 Ryan Boyce GW 14 Pick 11
5398818 Ryan Boyce GW 14 Pick 12
5398818 Ryan Boyce GW 14 Pick 13
5398818 Ryan Boyce GW 14 Pick 14
5398818 Ryan Boyce GW 14 Pick 15
5398818 Ryan Boyce GW 15 Pick 1
5398818 Ryan Boyce GW 15 Pick 2
5398818 Ryan Boyce GW 15 Pick 3
5398818 Ryan Boyce GW 15 Pick 4
5398818 Ryan Boyce GW 15 Pick 5
5398818 Ryan Boyce GW 15 Pick 6
5398818 Ryan Boyce GW 15 Pick 7
5398818 Ryan Boyce GW 15 Pick 8
5398818 Ryan Boyce GW 15 Pick 9
5398818 Ryan Boyce GW 15 Pick 10
5398818 Ryan Boyce GW 15 Pick 11
5398818 Ryan Boyce GW 15 Pick 12
5398818 Ryan Boyce GW 15 Pick 13
5398818 Ryan Boyce GW 15 Pick 14
5398818 Ryan Boyce GW 15 Pick 15
5398818 Ryan Boyce GW 16 Pick 1
5398818 Ryan Boyce GW 16 Pick 2
5398818 Ryan Boyce GW 16 Pick 3
5398818 Ryan Boyce GW 16 Pick 4
5398818 Ryan Boyce GW 16 Pick 5
5398818 Ryan Boyce GW 16 Pick 6
5398818 Ryan Boyce GW 16 Pick 7
5398818 Ryan Boyce GW 16 Pick 8
5398818 Ryan Boyce GW 16 Pick 9
5398818 Ryan Boyce GW 16 Pick 10
5398818 Ryan Boyce GW 16 Pick 11
5398818 Ryan Boyce GW 16 Pick 12
5398818 Ryan Boyce GW 16 Pick 13
5398818 Ryan Boyce GW 16 Pick 14
5398818 Ryan Boyce GW 16 Pick 15
5398818 Ryan Boyce GW 17 Pick 1
5398818 Ryan Boyce GW 17 Pick 2
5398818 Ryan Boyce GW 17 Pick 3
5398818 Ryan Boyce GW 17 Pick 4
5398818 Ryan Boyce GW 17 Pick 5
5398818 Ryan Boyce GW 17 Pick 6
5398818 Ryan Boyce GW 17 Pick 7
5398818 Ryan Boyce GW 17 Pick 8
5398818 Ryan Boyce GW 17 Pick 9
5398818 Ryan Boyce GW 17 Pick 10
5398818 Ryan Boyce GW 17 Pick 11
5398818 Ryan Boyce GW 17 Pick 12
5398818 Ryan Boyce GW 17 Pick 13
5398818 Ryan Boyce GW 17 Pick 14
5398818 Ryan Boyce GW 17 Pick 15
5398818 Ryan Boyce GW 18 Pick 1
5398818 Ryan Boyce GW 18 Pick 2
5398818 Ryan Boyce GW 18 Pick 3
5398818 Ryan Boyce GW 18 Pick 4
5398818 Ryan Boyce GW 18 Pick 5
5398818 Ryan Boyce GW 18 Pick 6
5398818 Ryan Boyce GW 18 Pick 7
5398818 Ryan Boyce GW 18 Pick 8
5398818 Ryan Boyce GW 18 Pick 9
5398818 Ryan Boyce GW 18 Pick 10
5398818 Ryan Boyce GW 18 Pick 11
5398818 Ryan Boyce GW 18 Pick 12
5398818 Ryan Boyce GW 18 Pick 13
5398818 Ryan Boyce GW 18 Pick 14
5398818 Ryan Boyce GW 18 Pick 15
5398818 Ryan Boyce GW 19 Pick 1
5398818 Ryan Boyce GW 19 Pick 2
5398818 Ryan Boyce GW 19 Pick 3
5398818 Ryan Boyce GW 19 Pick 4
5398818 Ryan Boyce GW 19 Pick 5
5398818 Ryan Boyce GW 19 Pick 6
5398818 Ryan Boyce GW 19 Pick 7
5398818 Ryan Boyce GW 19 Pick 8
5398818 Ryan Boyce GW 19 Pick 9
5398818 Ryan Boyce GW 19 Pick 10
5398818 Ryan Boyce GW 19 Pick 11
5398818 Ryan Boyce GW 19 Pick 12
5398818 Ryan Boyce GW 19 Pick 13
5398818 Ryan Boyce GW 19 Pick 14
5398818 Ryan Boyce GW 19 Pick 15
5398818 Ryan Boyce GW 20 Pick 1
5398818 Ryan Boyce GW 20 Pick 2
5398818 Ryan Boyce GW 20 Pick 3
5398818 Ryan Boyce GW 20 Pick 4
5398818 Ryan Boyce GW 20 Pick 5
5398818 Ryan Boyce GW 20 Pick 6
5398818 Ryan Boyce GW 20 Pick 7
5398818 Ryan Boyce GW 20 Pick 8
5398818 Ryan Boyce GW 20 Pick 9
5398818 Ryan Boyce GW 20 Pick 10
5398818 Ryan Boyce GW 20 Pick 11
5398818 Ryan Boyce GW 20 Pick 12
5398818 Ryan Boyce GW 20 Pick 13
5398818 Ryan Boyce GW 20 Pick 14
5398818 Ryan Boyce GW 20 Pick 15
5398818 Ryan Boyce GW 21 Pick 1
5398818 Ryan Boyce GW 21 Pick 2
5398818 Ryan Boyce GW 21 Pick 3
5398818 Ryan Boyce GW 21 Pick 4
5398818 Ryan Boyce GW 21 Pick 5
5398818 Ryan Boyce GW 21 Pick 6
5398818 Ryan Boyce GW 21 Pick 7
5398818 Ryan Boyce GW 21 Pick 8
5398818 Ryan Boyce GW 21 Pick 9
5398818 Ryan Boyce GW 21 Pick 10
5398818 Ryan Boyce GW 21 Pick 11
5398818 Ryan Boyce GW 21 Pick 12
5398818 Ryan Boyce GW 21 Pick 13
5398818 Ryan Boyce GW 21 Pick 14
5398818 Ryan Boyce GW 21 Pick 15
5398818 Ryan Boyce GW 22 Pick 1
5398818 Ryan Boyce GW 22 Pick 2
5398818 Ryan Boyce GW 22 Pick 3
5398818 Ryan Boyce GW 22 Pick 4
5398818 Ryan Boyce GW 22 Pick 5
5398818 Ryan Boyce GW 22 Pick 6
5398818 Ryan Boyce GW 22 Pick 7
5398818 Ryan Boyce GW 22 Pick 8
5398818 Ryan Boyce GW 22 Pick 9
5398818 Ryan Boyce GW 22 Pick 10
5398818 Ryan Boyce GW 22 Pick 11
5398818 Ryan Boyce GW 22 Pick 12
5398818 Ryan Boyce GW 22 Pick 13
5398818 Ryan Boyce GW 22 Pick 14
5398818 Ryan Boyce GW 22 Pick 15
5398818 Ryan Boyce GW 23 Pick 1
5398818 Ryan Boyce GW 23 Pick 2
5398818 Ryan Boyce GW 23 Pick 3
5398818 Ryan Boyce GW 23 Pick 4
5398818 Ryan Boyce GW 23 Pick 5
5398818 Ryan Boyce GW 23 Pick 6
5398818 Ryan Boyce GW 23 Pick 7
5398818 Ryan Boyce GW 23 Pick 8
5398818 Ryan Boyce GW 23 Pick 9
5398818 Ryan Boyce GW 23 Pick 10
5398818 Ryan Boyce GW 23 Pick 11
5398818 Ryan Boyce GW 23 Pick 12
5398818 Ryan Boyce GW 23 Pick 13
5398818 Ryan Boyce GW 23 Pick 14
5398818 Ryan Boyce GW 23 Pick 15
5398818 Ryan Boyce GW 24 Pick 1
5398818 Ryan Boyce GW 24 Pick 2
5398818 Ryan Boyce GW 24 Pick 3
5398818 Ryan Boyce GW 24 Pick 4
5398818 Ryan Boyce GW 24 Pick 5
5398818 Ryan Boyce GW 24 Pick 6
5398818 Ryan Boyce GW 24 Pick 7
5398818 Ryan Boyce GW 24 Pick 8
5398818 Ryan Boyce GW 24 Pick 9
5398818 Ryan Boyce GW 24 Pick 10
5398818 Ryan Boyce GW 24 Pick 11
5398818 Ryan Boyce GW 24 Pick 12
5398818 Ryan Boyce GW 24 Pick 13
5398818 Ryan Boyce GW 24 Pick 14
5398818 Ryan Boyce GW 24 Pick 15
5398818 Ryan Boyce GW 25 Pick 1
5398818 Ryan Boyce GW 25 Pick 2
5398818 Ryan Boyce GW 25 Pick 3
5398818 Ryan Boyce GW 25 Pick 4
5398818 Ryan Boyce GW 25 Pick 5
5398818 Ryan Boyce GW 25 Pick 6
5398818 Ryan Boyce GW 25 Pick 7
5398818 Ryan Boyce GW 25 Pick 8
5398818 Ryan Boyce GW 25 Pick 9
5398818 Ryan Boyce GW 25 Pick 10
5398818 Ryan Boyce GW 25 Pick 11
5398818 Ryan Boyce GW 25 Pick 12
5398818 Ryan Boyce GW 25 Pick 13
5398818 Ryan Boyce GW 25 Pick 14
5398818 Ryan Boyce GW 25 Pick 15
5398818 Ryan Boyce GW 26 Pick 1
5398818 Ryan Boyce GW 26 Pick 2
5398818 Ryan Boyce GW 26 Pick 3
5398818 Ryan Boyce GW 26 Pick 4
5398818 Ryan Boyce GW 26 Pick 5
5398818 Ryan Boyce GW 26 Pick 6
5398818 Ryan Boyce GW 26 Pick 7
5398818 Ryan Boyce GW 26 Pick 8
5398818 Ryan Boyce GW 26 Pick 9
5398818 Ryan Boyce GW 26 Pick 10
5398818 Ryan Boyce GW 26 Pick 11
5398818 Ryan Boyce GW 26 Pick 12
5398818 Ryan Boyce GW 26 Pick 13
5398818 Ryan Boyce GW 26 Pick 14
5398818 Ryan Boyce GW 26 Pick 15
5398818 Ryan Boyce GW 27 Pick 1
5398818 Ryan Boyce GW 27 Pick 2
5398818 Ryan Boyce GW 27 Pick 3
5398818 Ryan Boyce GW 27 Pick 4
5398818 Ryan Boyce GW 27 Pick 5
5398818 Ryan Boyce GW 27 Pick 6
5398818 Ryan Boyce GW 27 Pick 7
5398818 Ryan Boyce GW 27 Pick 8
5398818 Ryan Boyce GW 27 Pick 9
5398818 Ryan Boyce GW 27 Pick 10
5398818 Ryan Boyce GW 27 Pick 11
5398818 Ryan Boyce GW 27 Pick 12
5398818 Ryan Boyce GW 27 Pick 13
5398818 Ryan Boyce GW 27 Pick 14
5398818 Ryan Boyce GW 27 Pick 15
5398818 Ryan Boyce GW 28 Pick 1
5398818 Ryan Boyce GW 28 Pick 2
5398818 Ryan Boyce GW 28 Pick 3
5398818 Ryan Boyce GW 28 Pick 4
5398818 Ryan Boyce GW 28 Pick 5
5398818 Ryan Boyce GW 28 Pick 6
5398818 Ryan Boyce GW 28 Pick 7
5398818 Ryan Boyce GW 28 Pick 8
5398818 Ryan Boyce GW 28 Pick 9
5398818 Ryan Boyce GW 28 Pick 10
5398818 Ryan Boyce GW 28 Pick 11
5398818 Ryan Boyce GW 28 Pick 12
5398818 Ryan Boyce GW 28 Pick 13
5398818 Ryan Boyce GW 28 Pick 14
5398818 Ryan Boyce GW 28 Pick 15
5398818 Ryan Boyce GW 29 Pick 1
5398818 Ryan Boyce GW 29 Pick 2
5398818 Ryan Boyce GW 29 Pick 3
5398818 Ryan Boyce GW 29 Pick 4
5398818 Ryan Boyce GW 29 Pick 5
5398818 Ryan Boyce GW 29 Pick 6
5398818 Ryan Boyce GW 29 Pick 7
5398818 Ryan Boyce GW 29 Pick 8
5398818 Ryan Boyce GW 29 Pick 9
5398818 Ryan Boyce GW 29 Pick 10
5398818 Ryan Boyce GW 29 Pick 11
5398818 Ryan Boyce GW 29 Pick 12
5398818 Ryan Boyce GW 29 Pick 13
5398818 Ryan Boyce GW 29 Pick 14
5398818 Ryan Boyce GW 29 Pick 15
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW30 to GW34

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Cody Gakpo,a,0,MID,Liverpool,1039.1,4.92,74.7,0.277,0.209,1.086
1,Mohamed Salah,a,0,MID,Liverpool,1039.1,4.73,79.9,0.241,0.167,1.182
2,Alexis Mac Allister,a,1,MID,Liverpool,1039.1,4.72,83.1,0.213,0.159,1.173
3,Cole Palmer,a,0,MID,Chelsea,1110.6,4.67,76.9,0.205,0.192,1.435
4,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.9,4.67,77.1,0.205,0.230,1.324
5,Milos Kerkez,a,0,DEF,Liverpool,1039.1,4.62,83.7,0.039,0.057,1.030
6,Dominik Szoboszlai,a,1,MID,Liverpool,1039.1,4.61,85.6,0.157,0.176,1.190
7,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1080.9,4.55,83.9,0.201,0.141,1.316
8,Ibrahima Konaté,a,1,DEF,Liverpool,1039.1,4.54,86.6,0.041,0.048,1.096
9,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1013.3,4.54,82.3,0.184,0.167,1.215
10,Alex Iwobi,a,0,MID,Fulham,1056.2,4.53,85.4,0.167,0.167,1.358
11,Hugo Ekitiké,a,0,FWD,Liverpool,1039.1,4.50,83.8,0.380,0.100,1.308
12,Harry Wilson,d,0,MID,Fulham,1056.2,4.50,81.5,0.185,0.154,1.345
13,Morgan Rogers,a,0,MID,Aston Villa,1036.0,4.48,84.6,0.180,0.157,1.296
14,Virgil van Dijk,a,0,DEF,Liverpool,1039.1,4.45,66.9,0.069,0.049,1.039
15,Enzo Fernández,a,0,MID,Chelsea,1110.6,4.42,80.8,0.164,0.197,1.459
16,Alex Scott,a,0,MID,Bournemouth,1060.1,4.41,85.8,0.159,0.126,1.254
17,Dango Ouattara,a,0,MID,Brentford,1027.3,4.41,82.5,0.181,0.131,1.379
18,Crysencio Summerville,a,0,MID,West Ham,1086.0,4.39,86.3,0.182,0.137,1.458
19,Bryan Mbeumo,a,0,MID,Man Utd,1080.9,4.39,81.1,0.196,0.133,1.288
20,Mathias Jensen,a,0,MID,Brentford,1027.3,4.37,81.2,0.149,0.165,1.379
21,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,1036.0,4.36,86.7,0.043,0.049,1.110
22,Jeremie Frimpong,a,0,DEF,Liverpool,1039.1,4.33,62.5,0.052,0.059,0.957
23,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1060.1,4.33,77.5,0.189,0.126,1.182
24,Diego Gómez Amarilla,a,0,MID,Brighton,1038.3,4.32,80.2,0.184,0.121,1.148
25,Iliman Ndiaye,a,0,MID,Everton,1125.4,4.30,85.3,0.186,0.112,1.403
26,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,1027.3,4.29,85.4,0.334,0.074,1.379
27,Marc Guiu Paz,a,0,FWD,Chelsea,1110.6,4.27,47.3,0.777,0.297,1.607
28,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1038.3,4.26,65.2,0.297,0.056,1.562
29,Carlos Henrique Casimiro,a,0,MID,Man Utd,1080.9,4.26,81.8,0.154,0.136,1.307
30,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1027.3,4.24,88.5,NaN,NaN,1.147
31,Matty Cash,d,0,DEF,Aston Villa,1036.0,4.22,80.3,0.047,0.048,1.158
32,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1110.6,4.22,82.6,0.352,0.071,1.213
33,Florian Wirtz,a,0,MID,Liverpool,1039.1,4.21,55.0,0.238,0.316,1.226
34,Ferdi Kadıoğlu,a,0,DEF,Brighton,1038.3,4.18,86.3,0.046,0.048,1.179
35,Anton Stach,a,0,MID,Leeds,1049.1,4.17,82.9,0.140,0.146,1.300
36,Jan Paul van Hecke,a,0,DEF,Brighton,1038.3,4.16,86.1,0.037,0.051,1.156
37,Daniel Ballard,a,0,DEF,Sunderland,1051.4,4.15,83.6,0.045,0.048,1.153
38,Enzo Le Fée,a,0,MID,Sunderland,1051.4,4.12,85.8,0.105,0.130,1.234
39,Tyrone Mings,a,1,DEF,Aston Villa,1036.0,4.12,78.6,0.040,0.041,1.167
40,Anthony Gordon,a,0,MID,Newcastle,1109.8,4.12,77.3,0.173,0.117,1.392
41,Pascal Groß,a,0,MID,Brighton,1038.3,4.11,84.7,0.099,0.138,1.140
42,Pau Torres,a,0,DEF,Aston Villa,1036.0,4.09,77.3,0.042,0.037,1.195
43,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1036.0,4.09,75.8,0.145,0.141,1.206
44,Moisés Caicedo Corozo,a,0,MID,Chelsea,1110.6,4.08,85.2,0.097,0.159,1.462
45,Habib Diarra,a,0,MID,Sunderland,1051.4,4.08,81.4,0.138,0.101,1.160
46,Reiss Nelson,d,0,MID,Brentford,1027.3,4.08,38.8,0.600,0.269,1.721
47,Brian Brobbey,d,1,FWD,Sunderland,1051.4,4.08,62.1,0.471,0.194,1.265
48,Alisson Becker,a,0,GK,Liverpool,1039.1,4.07,89.9,NaN,NaN,1.065
49,Lewis Dunk,a,0,DEF,Brighton,1038.3,4.06,86.4,0.039,0.047,1.215

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 30 and 34:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Cody Gakpo,a,MID,Liverpool,7.3,1039.1,24.41,74.7,0.277,0.209,1.086
1,Mohamed Salah,a,MID,Liverpool,14.0,1039.1,23.55,79.9,0.241,0.167,1.182
2,Alexis Mac Allister,a,MID,Liverpool,6.2,1039.1,23.47,83.1,0.213,0.159,1.173
3,Bruno Borges Fernandes,a,MID,Man Utd,10.0,1080.9,23.45,77.1,0.205,0.230,1.324
4,Cole Palmer,a,MID,Chelsea,10.6,1110.6,23.30,76.9,0.205,0.192,1.435
5,Dominik Szoboszlai,a,MID,Liverpool,6.9,1039.1,22.91,85.6,0.157,0.176,1.190
6,Matheus Santos Carneiro da Cunha,a,MID,Man Utd,8.0,1080.9,22.76,83.9,0.201,0.141,1.316
7,Morgan Gibbs-White,a,MID,Nott'm Forest,7.3,1013.3,22.75,82.3,0.184,0.167,1.215
8,Milos Kerkez,a,DEF,Liverpool,5.6,1039.1,22.72,83.7,0.039,0.057,1.030
9,Morgan Rogers,a,MID,Aston Villa,7.6,1036.0,22.46,84.6,0.180,0.157,1.296
10,Alex Iwobi,a,MID,Fulham,6.3,1056.2,22.46,85.4,0.167,0.167,1.358
11,Hugo Ekitiké,a,FWD,Liverpool,9.1,1039.1,22.43,83.8,0.380,0.100,1.308
12,Harry Wilson,d,MID,Fulham,6.0,1056.2,22.28,81.5,0.185,0.154,1.345
13,Crysencio Summerville,a,MID,West Ham,5.7,1086.0,22.20,86.3,0.182,0.137,1.458
14,Ibrahima Konaté,a,DEF,Liverpool,5.5,1039.1,22.19,86.6,0.041,0.048,1.096
15,Enzo Fernández,a,MID,Chelsea,6.7,1110.6,22.12,80.8,0.164,0.197,1.459
16,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,1036.0,22.07,86.7,0.043,0.049,1.110
17,Bryan Mbeumo,a,MID,Man Utd,8.7,1080.9,21.98,81.1,0.196,0.133,1.288
18,Virgil van Dijk,a,DEF,Liverpool,6.1,1039.1,21.87,66.9,0.069,0.049,1.039
19,Alex Scott,a,MID,Bournemouth,5.1,1060.1,21.79,85.8,0.159,0.126,1.254

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0                 Ryan Boyce  5398818.0        1668.0
1              Bernard Chalk  1557117.0        1637.0
2               Jack Carroll  4438260.0        1614.0
3         Christopher Harris    28660.0        1597.0
4          William Partridge  6588565.0        1579.0
5               Samia Shelim  6506490.0        1567.0
6               Tommy Davies  7845816.0        1551.0
7                 Rhys Birdy  5810139.0        1548.0
8             Conner Harling  3421093.0        1535.0
9              Ollie Carroll  5181285.0        1534.0
10        Christopher Harris   145486.0        1525.0
11             Rizwan Shelim  3058994.0        1521.0
12               Nafi Shelim  4776281.0        1515.0
13             Tajwar Shelim  4773459.0        1467.0
14  Christakis Christodoulou  7474864.0        1446.0
15              Will Hossack  4792527.0        1379.0
16            Charlie Garner  9432680.0        1361.0
17               Simon Meech  6764382.0        1358.0
18              Tahmid Haque  6394829.0        1351.0
19              Holly Stower  7367977.0        1306.0
20            Rachel Aumayer  9763056.0        1116.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW30 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
173,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,42.485203,0.0,42.485203,0.000000,42.485203,0.0,42.485203,42.485203,42.485203
192,1,8.0,Jurriën Timber,a,6.3,DEF,Arsenal,40.370654,0.0,40.370654,0.000000,40.370654,0.0,40.370654,40.370654,40.370654
237,1,237.0,Enzo Fernández,a,6.7,MID,Chelsea,40.305984,0.0,40.305984,0.000000,40.305984,0.0,40.305984,40.305984,40.305984
130,1,329.0,Harry Wilson,d,6.0,MID,Fulham,39.917469,0.0,39.917469,0.000000,39.917469,0.0,39.917469,39.917469,39.917469
141,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,37.922711,0.0,37.922711,0.000000,37.922711,0.0,37.922711,37.922711,37.922711
376,1,691.0,Dominic Calvert-Lewin,a,5.7,FWD,Leeds,35.211773,0.0,35.211773,0.000000,35.211773,0.0,35.211773,35.211773,35.211773
153,1,694.0,Nordi Mukiele,d,4.5,DEF,Sunderland,33.332491,0.0,33.332491,0.000000,33.332491,0.0,33.332491,33.332491,33.332491
363,1,337.0,Raúl Jiménez Rodríguez,a,6.1,FWD,Fulham,32.218152,0.0,32.218152,0.000000,32.218152,0.0,32.218152,32.218152,32.218152
39,1,341.0,Karl Darlow,a,3.9,GK,Leeds,30.821268,0.0,30.821268,0.000000,30.821268,0.0,30.821268,30.821268,30.821268
333,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,33.007940,20.0,26.406352,-6.601588,26.406352,0.0,19.804764,26.406352,26.406352
108,1,661.0,Hugo Ekitiké,a,9.1,FWD,Liverpool,40.101681,40.0,24.061008,-16.040672,24.061008,0.0,8.020336,24.061008,24.061008
322,1,373.0,Virgil van Dijk,a,6.1,DEF,Liverpool,38.039303,40.0,22.823582,-15.215721,22.823582,0.0,7.607861,22.823582,22.823582
129,1,449.0,Bruno Borges Fernandes,a,10.0,MID,Man Utd,42.433014,60.0,16.973206,-25.459809,16.973206,0.0,-8.486603,16.973206,16.973206
138,1,21.0,Declan Rice,a,7.5,MID,Arsenal,36.894330,60.0,14.757732,-22.136598,14.757732,0.0,-7.378866,14.757732,14.757732
47,1,5.0,Gabriel dos Santos Magalhães,a,7.1,DEF,Arsenal,39.949630,80.0,7.989926,-31.959704,7.989926,0.0,-23.969778,7.989926,7.989926

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW30 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
389,0,430.0,Erling Haaland,a,14.7,FWD,Man City,36.047238,200.0,-36.047238,-72.094475,0.0,-72.094475,-108.141713,-72.094475,-36.047238
371,0,82.0,Antoine Semenyo,a,8.2,MID,Man City,41.612819,80.0,8.322564,-33.290255,0.0,-33.290255,-24.967691,-33.290255,8.322564
328,0,249.0,João Pedro Junqueira de Jesus,a,7.6,FWD,Chelsea,38.181991,60.0,15.272796,-22.909195,0.0,-22.909195,-7.636398,-22.909195,15.272796
148,0,119.0,Bryan Mbeumo,a,8.7,MID,Man Utd,39.517237,40.0,23.710342,-15.806895,0.0,-15.806895,7.903447,-15.806895,23.710342
305,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.2,FWD,Brentford,37.983953,40.0,22.790372,-15.193581,0.0,-15.193581,7.596791,-15.193581,22.790372
117,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,37.604770,40.0,22.562862,-15.041908,0.0,-15.041908,7.520954,-15.041908,22.562862
25,0,226.0,Trevoh Chalobah,a,5.6,DEF,Chelsea,33.648496,40.0,20.189097,-13.459398,0.0,-13.459398,6.729699,-13.459398,20.189097
62,0,101.0,Caoimhín Kelleher,a,4.7,GK,Brentford,32.474856,40.0,19.484914,-12.989942,0.0,-12.989942,6.494971,-12.989942,19.484914
331,0,47.0,Morgan Rogers,a,7.6,MID,Aston Villa,40.759172,20.0,32.607337,-8.151834,0.0,-8.151834,24.455503,-8.151834,32.607337
70,0,457.0,Carlos Henrique Casimiro,a,5.6,MID,Man Utd,38.494674,20.0,30.795739,-7.698935,0.0,-7.698935,23.096804,-7.698935,30.795739
88,0,348.0,Joe Rodon,a,3.9,DEF,Leeds,36.076911,20.0,28.861529,-7.215382,0.0,-7.215382,21.646147,-7.215382,28.861529
380,0,26.0,Martín Zubimendi Ibáñez,a,5.2,MID,Arsenal,36.063945,20.0,28.851156,-7.212789,0.0,-7.212789,21.638367,-7.212789,28.851156
325,0,517.0,Elliot Anderson,a,5.4,MID,Nott'm Forest,35.803647,20.0,28.642917,-7.160729,0.0,-7.160729,21.482188,-7.160729,28.642917
250,0,242.0,Kiernan Dewsbury-Hall,a,5.0,MID,Everton,35.784932,20.0,28.627945,-7.156986,0.0,-7.156986,21.470959,-7.156986,28.627945
220,0,74.0,Adrien Truffert,a,4.6,DEF,Bournemouth,35.373367,20.0,28.298694,-7.074673,0.0,-7.074673,21.224020,-7.074673,28.298694
171,0,72.0,Marcos Senesi Barón,a,4.9,DEF,Bournemouth,35.288897,20.0,28.231118,-7.057779,0.0,-7.057779,21.173338,-7.057779,28.231118
259,0,16.0,Bukayo Saka,a,9.8,MID,Arsenal,35.006000,20.0,28.004800,-7.001200,0.0,-7.001200,21.003600,-7.001200,28.004800
52,0,291.0,James Tarkowski,a,5.7,DEF,Everton,34.464800,20.0,27.571840,-6.892960,0.0,-6.892960,20.678880,-6.892960,27.571840
396,0,390.0,Ryan Gravenberch,a,5.5,MID,Liverpool,33.799624,20.0,27.039700,-6.759925,0.0,-6.759925,20.279775,-6.759925,27.039700
42,0,624.0,Jarrod Bowen,a,7.5,FWD,West Ham,33.290770,20.0,26.632616,-6.658154,0.0,-6.658154,19.974462,-6.658154,26.632616

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW30 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
288,0,384.0,Cody Gakpo,a,7.3,MID,Liverpool,43.195998,0.0,43.195998,0.0,0.0,0.0,43.195998,0.0,43.195998
398,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,41.990132,0.0,41.990132,0.0,0.0,0.0,41.990132,0.0,41.990132
339,0,386.0,Alexis Mac Allister,a,6.2,MID,Liverpool,41.827660,0.0,41.827660,0.0,0.0,0.0,41.827660,0.0,41.827660
284,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,41.003456,0.0,41.003456,0.0,0.0,0.0,41.003456,0.0,41.003456
253,0,387.0,Dominik Szoboszlai,a,6.9,MID,Liverpool,40.559442,0.0,40.559442,0.0,0.0,0.0,40.559442,0.0,40.559442
147,0,515.0,Morgan Gibbs-White,a,7.3,MID,Nott'm Forest,40.294042,0.0,40.294042,0.0,0.0,0.0,40.294042,0.0,40.294042
127,0,324.0,Alex Iwobi,a,6.3,MID,Fulham,40.072836,0.0,40.072836,0.0,0.0,0.0,40.072836,0.0,40.072836
218,0,615.0,Crysencio Summerville,a,5.7,MID,West Ham,39.924782,0.0,39.924782,0.0,0.0,0.0,39.924782,0.0,39.924782
318,0,371.0,Milos Kerkez,a,5.6,DEF,Liverpool,39.479700,0.0,39.479700,0.0,0.0,0.0,39.479700,0.0,39.479700
309,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,39.467181,0.0,39.467181,0.0,0.0,0.0,39.467181,0.0,39.467181
321,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,39.401566,0.0,39.401566,0.0,0.0,0.0,39.401566,0.0,39.401566
32,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,39.125293,0.0,39.125293,0.0,0.0,0.0,39.125293,0.0,39.125293
417,0,169.0,Diego Gómez Amarilla,a,4.9,MID,Brighton,39.093935,0.0,39.093935,0.0,0.0,0.0,39.093935,0.0,39.093935
291,0,90.0,Alex Scott,a,5.1,MID,Bournemouth,38.820658,0.0,38.820658,0.0,0.0,0.0,38.820658,0.0,38.820658
221,0,660.0,Anton Stach,a,4.7,MID,Leeds,38.735757,0.0,38.735757,0.0,0.0,0.0,38.735757,0.0,38.735757
126,0,374.0,Ibrahima Konaté,a,5.5,DEF,Liverpool,38.723873,0.0,38.723873,0.0,0.0,0.0,38.723873,0.0,38.723873
82,0,149.0,Igor Julio dos Santos de Paulo,a,4.5,DEF,Brighton,38.636034,0.0,38.636034,0.0,0.0,0.0,38.636034,0.0,38.636034
276,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,38.489427,0.0,38.489427,0.0,0.0,0.0,38.489427,0.0,38.489427
336,0,343.0,Pascal Struijk,a,4.3,DEF,Leeds,38.481461,0.0,38.481461,0.0,0.0,0.0,38.481461,0.0,38.481461
187,0,807.0,Rayan Vitor Simplício Rocha,a,5.6,MID,Bournemouth,38.479289,0.0,38.479289,0.0,0.0,0.0,38.479289,0.0,38.479289

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 255.76
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5    19.37
 ✅        Hákon Rafn Valdimarsson        Brentford    £3.9    20.85

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matty Cash                     Aston Villa  £4.8    21.32
 🪑        Ferdi Kadıoğlu                 Brighton     £4.4    21.05
 ✅        Milos Kerkez                   Liverpool    £5.6    22.72
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    22.07
 ✅        Igor Julio dos Santos de Paulo Brighton     £4.5    21.37

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Cody Gakpo                     Liverpool    £7.3    24.41
 ✅        Bruno Borges Fernandes         Man Utd      £10.0   23.45
 ✅        Cole Palmer                    Chelsea      £10.6   23.30
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0    22.76
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3    22.75

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2    21.32
 ✅        Hugo Ekitiké                   Liverpool    £9.1    22.43
 ✅        Marc Guiu Paz                  Chelsea      £4.1    21.34

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.2m / £102.4m
Total Weighted Expected Points: 458.57
Remaining Budget: £5.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5    34.90
 ✅        Hákon Rafn Valdimarsson        Brentford    £3.9    37.37

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Struijk                 Leeds        £4.3    38.48
 ✅        Nico O'Reilly                  Man City     £5.1    39.13
 ✅        Igor Julio dos Santos de Paulo Brighton     £4.5    38.64
 ✅        Jurriën Timber                 Arsenal      £6.3    40.37
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    39.47

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Cole Palmer                    Chelsea      £10.6   42.49
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0    41.00
 ✅        Cody Gakpo                     Liverpool    £7.3    43.20
 ✅        Alexis Mac Allister            Liverpool    £6.2    41.83
 ✅        Mohamed Salah                  Liverpool    £14.0   41.99

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brian Brobbey                  Sunderland   £5.4    36.57
 🪑        Ollie Watkins                  Aston Villa  £8.6    36.47
 ✅        Marc Guiu Paz                  Chelsea      £4.1    38.45

================================================================================
Optimization Status: Optimal

In [16]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [17]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)