In [21]:
import pandas as pd
import time
#other requirements: pulp

In [22]:
start=time.perf_counter()

In [23]:
#add this info to a settings dict?
current_gw = 34
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [24]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [25]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  35
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
1557117 Bernard Chalk GW 28 Pick 1
1557117 Bernard Chalk GW 28 Pick 2
1557117 Bernard Chalk GW 28 Pick 3
1557117 Bernard Chalk GW 28 Pick 4
1557117 Bernard Chalk GW 28 Pick 5
1557117 Bernard Chalk GW 28 Pick 6
1557117 Bernard Chalk GW 28 Pick 7
1557117 Bernard Chalk GW 28 Pick 8
1557117 Bernard Chalk GW 28 Pick 9
1557117 Bernard Chalk GW 28 Pick 10
1557117 Bernard Chalk GW 28 Pick 11
1557117 Bernard Chalk GW 28 Pick 12
1557117 Bernard Chalk GW 28 Pick 13
1557117 Bernard Chalk GW 28 Pick 14
1557117 Bernard Chalk GW 28 Pick 15
1557117 Bernard Chalk GW 29 Pick 1
1557117 Bernard Chalk GW 29 Pick 2
1557117 Bernard Chalk GW 29 Pick 3
1557117 Bernard Chalk GW 29 Pick 4
1557117 Bernard Chalk GW 29 Pick 5
1557117 Bernard Chalk GW 29 Pick 6
1557117 Bernard Chalk GW 29 Pick 7
1557117 Bernard Chalk GW 29 Pick 8
1557117 Bernard Chalk GW 29 Pick 9
1557117 Bernard Chalk GW 29 Pick 10
1557117 Bernard Chalk GW 29 Pick 11
1557117 Bernard Chalk GW 29 Pick 12
1557117 Bernard Chalk GW 29 Pick 13
1557117 Bernard Chalk GW 29 Pick 14
1557117 Bernard Chalk GW 29 Pick 15
1557117 Bernard Chalk GW 30 Pick 1
1557117 Bernard Chalk GW 30 Pick 2
1557117 Bernard Chalk GW 30 Pick 3
1557117 Bernard Chalk GW 30 Pick 4
1557117 Bernard Chalk GW 30 Pick 5
1557117 Bernard Chalk GW 30 Pick 6
1557117 Bernard Chalk GW 30 Pick 7
1557117 Bernard Chalk GW 30 Pick 8
1557117 Bernard Chalk GW 30 Pick 9
1557117 Bernard Chalk GW 30 Pick 10
1557117 Bernard Chalk GW 30 Pick 11
1557117 Bernard Chalk GW 30 Pick 12
1557117 Bernard Chalk GW 30 Pick 13
1557117 Bernard Chalk GW 30 Pick 14
1557117 Bernard Chalk GW 30 Pick 15
1557117 Bernard Chalk GW 31 Pick 1
1557117 Bernard Chalk GW 31 Pick 2
1557117 Bernard Chalk GW 31 Pick 3
1557117 Bernard Chalk GW 31 Pick 4
1557117 Bernard Chalk GW 31 Pick 5
1557117 Bernard Chalk GW 31 Pick 6
1557117 Bernard Chalk GW 31 Pick 7
1557117 Bernard Chalk GW 31 Pick 8
1557117 Bernard Chalk GW 31 Pick 9
1557117 Bernard Chalk GW 31 Pick 10
1557117 Bernard Chalk GW 31 Pick 11
1557117 Bernard Chalk GW 31 Pick 12
1557117 Bernard Chalk GW 31 Pick 13
1557117 Bernard Chalk GW 31 Pick 14
1557117 Bernard Chalk GW 31 Pick 15
1557117 Bernard Chalk GW 32 Pick 1
1557117 Bernard Chalk GW 32 Pick 2
1557117 Bernard Chalk GW 32 Pick 3
1557117 Bernard Chalk GW 32 Pick 4
1557117 Bernard Chalk GW 32 Pick 5
1557117 Bernard Chalk GW 32 Pick 6
1557117 Bernard Chalk GW 32 Pick 7
1557117 Bernard Chalk GW 32 Pick 8
1557117 Bernard Chalk GW 32 Pick 9
1557117 Bernard Chalk GW 32 Pick 10
1557117 Bernard Chalk GW 32 Pick 11
1557117 Bernard Chalk GW 32 Pick 12
1557117 Bernard Chalk GW 32 Pick 13
1557117 Bernard Chalk GW 32 Pick 14
1557117 Bernard Chalk GW 32 Pick 15
1557117 Bernard Chalk GW 33 Pick 1
1557117 Bernard Chalk GW 33 Pick 2
1557117 Bernard Chalk GW 33 Pick 3
1557117 Bernard Chalk GW 33 Pick 4
1557117 Bernard Chalk GW 33 Pick 5
1557117 Bernard Chalk GW 33 Pick 6
1557117 Bernard Chalk GW 33 Pick 7
1557117 Bernard Chalk GW 33 Pick 8
1557117 Bernard Chalk GW 33 Pick 9
1557117 Bernard Chalk GW 33 Pick 10
1557117 Bernard Chalk GW 33 Pick 11
1557117 Bernard Chalk GW 33 Pick 12
1557117 Bernard Chalk GW 33 Pick 13
1557117 Bernard Chalk GW 33 Pick 14
1557117 Bernard Chalk GW 33 Pick 15
1557117 Bernard Chalk GW 34 Pick 1
1557117 Bernard Chalk GW 34 Pick 2
1557117 Bernard Chalk GW 34 Pick 3
1557117 Bernard Chalk GW 34 Pick 4
1557117 Bernard Chalk GW 34 Pick 5
1557117 Bernard Chalk GW 34 Pick 6
1557117 Bernard Chalk GW 34 Pick 7
1557117 Bernard Chalk GW 34 Pick 8
1557117 Bernard Chalk GW 34 Pick 9
1557117 Bernard Chalk GW 34 Pick 10
1557117 Bernard Chalk GW 34 Pick 11
1557117 Bernard Chalk GW 34 Pick 12
1557117 Bernard Chalk GW 34 Pick 13
1557117 Bernard Chalk GW 34 Pick 14
1557117 Bernard Chalk GW 34 Pick 15
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15

In [26]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW35 to GW39

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1081.6,9.23,103.9,0.582,0.734,1.003
1,John Stones,a,0,DEF,Man City,1081.6,8.21,74.2,0.954,0.043,1.286
2,Nico O'Reilly,a,0,DEF,Man City,1081.6,6.28,99.4,0.197,0.072,1.009
3,Antoine Semenyo,a,0,MID,Man City,1081.6,6.28,99.8,0.344,0.251,0.979
4,Erling Haaland,a,0,FWD,Man City,1081.6,5.99,104.6,0.593,0.152,1.056
5,Matheus Nunes,a,1,DEF,Man City,1081.6,5.83,107.0,0.043,0.246,1.044
6,Marc Guéhi,a,0,DEF,Man City,1081.6,5.38,108.4,0.058,0.074,1.071
7,Rayan Cherki,a,0,MID,Man City,1081.6,5.35,92.1,0.245,0.171,0.993
8,Abdukodir Khusanov,a,0,DEF,Man City,1081.6,5.21,102.5,0.042,0.031,0.974
9,Max Alleyne,a,0,DEF,Man City,1081.6,5.04,77.8,0.238,0.035,1.327
10,Declan Rice,a,0,MID,Arsenal,996.8,4.98,83.9,0.295,0.293,0.757
11,Jarrod Bowen,a,0,FWD,West Ham,1090.9,4.90,75.4,0.469,0.521,1.426
12,Mohamed Salah,d,0,MID,Liverpool,1097.8,4.90,76.8,0.403,0.274,1.272
13,James Ward-Prowse,a,0,MID,Burnley,1072.8,4.90,78.1,0.455,0.236,2.062
14,Jérémy Doku,a,0,MID,Man City,1081.6,4.85,95.5,0.133,0.161,0.989
15,Mathias Jensen,a,0,MID,Brentford,1119.7,4.84,84.8,0.362,0.184,1.434
16,Rico Lewis,a,0,DEF,Man City,1081.6,4.79,70.4,0.248,0.096,1.365
17,Rayan Aït-Nouri,a,0,DEF,Man City,1081.6,4.76,72.4,0.041,0.077,0.991
18,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,996.8,4.68,86.8,0.065,0.075,0.784
19,Ollie Watkins,a,0,FWD,Aston Villa,1063.9,4.68,78.9,0.493,0.343,1.468
20,Youri Tielemans,a,0,MID,Aston Villa,1063.9,4.51,73.2,0.271,0.345,1.466
21,Gianluigi Donnarumma,a,0,GK,Man City,1081.6,4.50,112.4,NaN,NaN,1.030
22,Piero Hincapié,a,0,DEF,Arsenal,996.8,4.46,76.0,0.070,0.069,0.831
23,Bruno Borges Fernandes,a,1,MID,Man Utd,1086.2,4.43,84.3,0.221,0.235,1.297
24,William Saliba,a,0,DEF,Arsenal,996.8,4.43,86.7,0.042,0.035,0.794
25,Morgan Rogers,a,0,MID,Aston Villa,1063.9,4.43,84.9,0.216,0.257,1.505
26,Benjamin White,a,0,DEF,Arsenal,996.8,4.41,80.9,0.043,0.070,0.805
27,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1086.5,4.38,84.4,0.219,0.286,1.378
28,Rodrigo 'Rodri' Hernandez Cascante,d,0,MID,Man City,1081.6,4.25,99.9,0.059,0.084,1.022
29,Harry Wilson,a,0,MID,Fulham,1075.3,4.22,83.8,0.190,0.264,1.319
30,Cole Palmer,a,0,MID,Chelsea,1051.4,4.19,82.6,0.246,0.150,1.247
31,Kiernan Dewsbury-Hall,a,0,MID,Everton,1072.4,4.15,85.1,0.181,0.232,1.355
32,Jefferson Lerma Solís,a,0,MID,Crystal Palace,1135.9,4.14,99.9,0.081,0.100,1.492
33,Reece James,d,0,DEF,Chelsea,1051.4,4.11,61.6,0.177,0.529,1.580
34,Walter Benítez,a,0,GK,Crystal Palace,1135.9,4.10,109.2,NaN,NaN,1.695
35,Marcus Tavernier,a,0,MID,Bournemouth,1097.3,4.10,84.4,0.210,0.165,1.323
36,Eberechi Eze,d,0,MID,Arsenal,996.8,4.09,59.2,0.320,0.290,0.784
37,Ismaïla Sarr,a,0,MID,Crystal Palace,1135.9,4.09,88.5,0.152,0.065,1.409
38,Pascal Struijk,a,0,DEF,Leeds,987.5,4.07,86.6,0.057,0.036,1.061
39,John McGinn,a,0,MID,Aston Villa,1063.9,4.05,79.5,0.144,0.272,1.376
40,James Trafford,a,0,GK,Man City,1081.6,4.02,110.0,NaN,NaN,1.486
41,Granit Xhaka,a,0,MID,Sunderland,1044.6,4.02,84.4,0.177,0.193,1.628
42,Mats Wieffer,a,0,MID,Brighton,1024.6,4.01,76.6,0.110,0.332,1.129
43,Brennan Johnson,a,0,MID,Crystal Palace,1135.9,4.01,71.2,0.159,0.255,1.439
44,Chris Richards,a,0,DEF,Crystal Palace,1135.9,3.98,108.2,0.042,0.029,1.536
45,Dwight McNeil,a,0,MID,Everton,1072.4,3.97,66.5,0.294,0.224,1.269
46,Pedro Lomba Neto,a,0,MID,Chelsea,1051.4,3.96,77.7,0.179,0.226,1.267
47,Pascal Groß,a,0,MID,Brighton,1024.6,3.96,85.5,0.126,0.191,1.131
48,Leandro Trossard,a,0,MID,Arsenal,996.8,3.95,44.8,0.497,0.393,0.819
49,Tyrick Mitchell,a,0,DEF,Crystal Palace,1135.9,3.94,103.8,0.041,0.076,1.619

In [42]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
        -- AND team_name = 'Crystal Palace'
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 35 and 39:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,6.2,1081.6,40.20,103.9,0.582,0.734,1.003
1,John Stones,a,DEF,Man City,5.4,1081.6,35.84,74.2,0.954,0.043,1.286
2,Nico O'Reilly,a,DEF,Man City,5.1,1081.6,27.37,99.4,0.197,0.072,1.009
3,Antoine Semenyo,a,MID,Man City,8.2,1081.6,27.32,99.8,0.344,0.251,0.979
4,Erling Haaland,a,FWD,Man City,14.5,1081.6,26.23,104.6,0.593,0.152,1.056
5,Matheus Nunes,a,DEF,Man City,5.3,1081.6,25.46,107.0,0.043,0.246,1.044
6,Marc Guéhi,a,DEF,Man City,5.1,1081.6,23.44,108.4,0.058,0.074,1.071
7,Rayan Cherki,a,MID,Man City,6.4,1081.6,23.25,92.1,0.245,0.171,0.993
8,Abdukodir Khusanov,a,DEF,Man City,5.4,1081.6,22.75,102.5,0.042,0.031,0.974
9,Declan Rice,a,MID,Arsenal,7.2,996.8,22.47,83.9,0.295,0.293,0.757
10,Mohamed Salah,d,MID,Liverpool,14.0,1097.8,21.93,76.8,0.403,0.274,1.272
11,James Ward-Prowse,a,MID,Burnley,5.6,1072.8,21.90,78.1,0.455,0.236,2.062
12,Jarrod Bowen,a,FWD,West Ham,7.7,1090.9,21.89,75.4,0.469,0.521,1.426
13,Max Alleyne,a,DEF,Man City,3.9,1081.6,21.86,77.8,0.238,0.035,1.327
14,Mathias Jensen,a,MID,Brentford,4.9,1119.7,21.54,84.8,0.362,0.184,1.434
15,Jérémy Doku,a,MID,Man City,6.4,1081.6,21.13,95.5,0.133,0.161,0.989
16,Gabriel dos Santos Magalhães,a,DEF,Arsenal,7.1,996.8,21.04,86.8,0.065,0.075,0.784
17,Rico Lewis,a,DEF,Man City,4.6,1081.6,20.86,70.4,0.248,0.096,1.365
18,Ollie Watkins,a,FWD,Aston Villa,8.7,1063.9,20.69,78.9,0.493,0.343,1.468
19,Rayan Aït-Nouri,a,DEF,Man City,5.7,1081.6,20.58,72.4,0.041,0.077,0.991

In [28]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        1992.0
1                 Ryan Boyce  5398818.0        1958.0
2               Tommy Davies  7845816.0        1910.0
3                 Rhys Birdy  5810139.0        1907.0
4         Christopher Harris    28660.0        1897.0
5               Samia Shelim  6506490.0        1880.0
6         Christopher Harris   145486.0        1876.0
7          William Partridge  6588565.0        1874.0
8               Jack Carroll  4438260.0        1855.0
9              Rizwan Shelim  3058994.0        1812.0
10             Ollie Carroll  5181285.0        1796.0
11             Tajwar Shelim  4773459.0        1770.0
12               Nafi Shelim  4776281.0        1746.0
13            Conner Harling  3421093.0        1726.0
14  Christakis Christodoulou  7474864.0        1653.0
15              Tahmid Haque  6394829.0        1600.0
16              Will Hossack  4792527.0        1581.0
17               Simon Meech  6764382.0        1549.0
18            Charlie Garner  9432680.0        1547.0
19              Holly Stower  7367977.0        1466.0
20            Rachel Aumayer  9763056.0        1277.0

In [29]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW35 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
289,1,235.0,Cole Palmer,a,10.5,MID,Chelsea,18.778837,0.0,18.778837,0.000000,18.778837,0.0,18.778837,18.778837,18.778837
151,1,21.0,Declan Rice,a,7.2,MID,Arsenal,22.474524,20.0,17.979619,-4.494905,17.979619,0.0,13.484714,17.979619,17.979619
390,1,691.0,Dominic Calvert-Lewin,a,5.6,FWD,Leeds,16.649343,0.0,16.649343,0.000000,16.649343,0.0,16.649343,16.649343,16.649343
415,1,237.0,Enzo Fernández,a,6.5,MID,Chelsea,16.449293,0.0,16.449293,0.000000,16.449293,0.0,16.449293,16.449293,16.449293
73,1,341.0,Karl Darlow,a,3.9,GK,Leeds,16.065154,0.0,16.065154,0.000000,16.065154,0.0,16.065154,16.065154,16.065154
170,1,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,15.630136,0.0,15.630136,0.000000,15.630136,0.0,15.630136,15.630136,15.630136
264,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,15.133231,0.0,15.133231,0.000000,15.133231,0.0,15.133231,15.133231,15.133231
196,1,694.0,Nordi Mukiele,a,4.6,DEF,Sunderland,16.433276,20.0,13.146621,-3.286655,13.146621,0.0,9.859966,13.146621,13.146621
318,1,337.0,Raúl Jiménez Rodríguez,a,6.1,FWD,Fulham,9.769791,0.0,9.769791,0.000000,9.769791,0.0,9.769791,9.769791,9.769791
358,1,136.0,Igor Thiago Nascimento Rodrigues,a,7.4,FWD,Brentford,16.182087,40.0,9.709252,-6.472835,9.709252,0.0,3.236417,9.709252,9.709252
361,1,373.0,Virgil van Dijk,a,6.2,DEF,Liverpool,16.381578,60.0,6.552631,-9.828947,6.552631,0.0,-3.276316,6.552631,6.552631
333,1,329.0,Harry Wilson,a,6.0,MID,Fulham,19.008493,80.0,3.801699,-15.206794,3.801699,0.0,-11.405096,3.801699,3.801699
90,1,5.0,Gabriel dos Santos Magalhães,a,7.1,DEF,Arsenal,21.044445,100.0,0.000000,-21.044445,0.000000,0.0,-21.044445,0.000000,0.000000
391,1,449.0,Bruno Borges Fernandes,a,10.3,MID,Man Utd,19.772621,200.0,-19.772621,-39.545242,-19.772621,0.0,-59.317863,-19.772621,-19.772621

In [30]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW35 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
391,1,449.0,Bruno Borges Fernandes,a,10.3,MID,Man Utd,19.772621,200.0,-19.772621,-39.545242,-19.772621,0.000000,-59.317863,-19.772621,-19.772621
376,0,624.0,Jarrod Bowen,a,7.7,FWD,West Ham,21.893188,60.0,8.757275,-13.135913,0.000000,-13.135913,-4.378638,-13.135913,8.757275
26,0,430.0,Erling Haaland,a,14.5,FWD,Man City,26.230204,40.0,15.738122,-10.492081,0.000000,-10.492081,5.246041,-10.492081,15.738122
7,0,1.0,David Raya Martín,a,6.0,GK,Arsenal,17.455111,60.0,6.982044,-10.473066,0.000000,-10.473066,-3.491022,-10.473066,6.982044
401,0,64.0,Ollie Watkins,a,8.7,FWD,Aston Villa,20.686125,40.0,12.411675,-8.274450,0.000000,-8.274450,4.137225,-8.274450,12.411675
108,0,515.0,Morgan Gibbs-White,a,7.5,MID,Nott'm Forest,19.537635,40.0,11.722581,-7.815054,0.000000,-7.815054,3.907527,-7.815054,11.722581
213,0,47.0,Morgan Rogers,a,7.4,MID,Aston Villa,19.421857,40.0,11.653114,-7.768743,0.000000,-7.768743,3.884371,-7.768743,11.653114
386,0,387.0,Dominik Szoboszlai,a,7.1,MID,Liverpool,16.995629,40.0,10.197377,-6.798252,0.000000,-6.798252,3.399126,-6.798252,10.197377
10,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,14.585560,40.0,8.751336,-5.834224,0.000000,-5.834224,2.917112,-5.834224,8.751336
141,0,568.0,Pedro Porro Sauceda,a,5.1,DEF,Spurs,13.293812,40.0,7.976287,-5.317525,0.000000,-5.317525,2.658762,-5.317525,7.976287
76,0,242.0,Kiernan Dewsbury-Hall,a,5.1,MID,Everton,18.701334,20.0,14.961068,-3.740267,0.000000,-3.740267,11.220801,-3.740267,14.961068
81,0,615.0,Crysencio Summerville,a,5.5,MID,West Ham,17.542566,20.0,14.034053,-3.508513,0.000000,-3.508513,10.525540,-3.508513,14.034053
366,0,119.0,Bryan Mbeumo,a,8.5,MID,Man Utd,17.508167,20.0,14.006533,-3.501633,0.000000,-3.501633,10.504900,-3.501633,14.006533
121,0,16.0,Bukayo Saka,a,9.8,MID,Arsenal,16.793489,20.0,13.434791,-3.358698,0.000000,-3.358698,10.076093,-3.358698,13.434791
47,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,16.581930,20.0,13.265544,-3.316386,0.000000,-3.316386,9.949158,-3.316386,13.265544
237,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,16.135986,20.0,12.908789,-3.227197,0.000000,-3.227197,9.681591,-3.227197,12.908789
105,0,291.0,James Tarkowski,a,5.7,DEF,Everton,15.846539,20.0,12.677231,-3.169308,0.000000,-3.169308,9.507923,-3.169308,12.677231
197,0,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,15.277428,20.0,12.221942,-3.055486,0.000000,-3.055486,9.166457,-3.055486,12.221942
78,0,683.0,Omar Alderete,a,4.1,DEF,Sunderland,15.059647,20.0,12.047718,-3.011929,0.000000,-3.011929,9.035788,-3.011929,12.047718
236,0,684.0,Malick Thiaw,a,5.1,DEF,Newcastle,14.910070,20.0,11.928056,-2.982014,0.000000,-2.982014,8.946042,-2.982014,11.928056

In [31]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW35 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
301,0,416.0,Bernardo Mota Veiga de Carvalho e Silva,a,6.2,MID,Man City,40.196846,0.0,40.196846,0.0,0.0,0.0,40.196846,0.0,40.196846
357,0,409.0,John Stones,a,5.4,DEF,Man City,35.844522,0.0,35.844522,0.0,0.0,0.0,35.844522,0.0,35.844522
56,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,27.373760,0.0,27.373760,0.0,0.0,0.0,27.373760,0.0,27.373760
330,0,82.0,Antoine Semenyo,a,8.2,MID,Man City,27.324231,0.0,27.324231,0.0,0.0,0.0,27.324231,0.0,27.324231
5,0,407.0,Matheus Nunes,a,5.3,DEF,Man City,25.455021,0.0,25.455021,0.0,0.0,0.0,25.455021,0.0,25.455021
395,0,260.0,Marc Guéhi,a,5.1,DEF,Man City,23.435082,0.0,23.435082,0.0,0.0,0.0,23.435082,0.0,23.435082
332,0,417.0,Rayan Cherki,a,6.4,MID,Man City,23.247394,0.0,23.247394,0.0,0.0,0.0,23.247394,0.0,23.247394
434,0,406.0,Abdukodir Khusanov,a,5.4,DEF,Man City,22.749777,0.0,22.749777,0.0,0.0,0.0,22.749777,0.0,22.749777
77,0,381.0,Mohamed Salah,d,14.0,MID,Liverpool,21.929594,0.0,21.929594,0.0,0.0,0.0,21.929594,0.0,21.929594
142,0,614.0,James Ward-Prowse,a,5.6,MID,Burnley,21.896873,0.0,21.896873,0.0,0.0,0.0,21.896873,0.0,21.896873
104,0,794.0,Max Alleyne,a,3.9,DEF,Man City,21.858516,0.0,21.858516,0.0,0.0,0.0,21.858516,0.0,21.858516
152,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,21.535886,0.0,21.535886,0.0,0.0,0.0,21.535886,0.0,21.535886
284,0,418.0,Jérémy Doku,a,6.4,MID,Man City,21.134434,0.0,21.134434,0.0,0.0,0.0,21.134434,0.0,21.134434
230,0,410.0,Rico Lewis,a,4.6,DEF,Man City,20.860255,0.0,20.860255,0.0,0.0,0.0,20.860255,0.0,20.860255
354,0,402.0,Rayan Aït-Nouri,a,5.7,DEF,Man City,20.575257,0.0,20.575257,0.0,0.0,0.0,20.575257,0.0,20.575257
176,0,725.0,Piero Hincapié,a,5.1,DEF,Arsenal,20.099481,0.0,20.099481,0.0,0.0,0.0,20.099481,0.0,20.099481
130,0,6.0,William Saliba,a,6.1,DEF,Arsenal,19.932929,0.0,19.932929,0.0,0.0,0.0,19.932929,0.0,19.932929
346,0,11.0,Benjamin White,a,5.1,DEF,Arsenal,19.812546,0.0,19.812546,0.0,0.0,0.0,19.812546,0.0,19.812546
100,0,48.0,Youri Tielemans,a,5.9,MID,Aston Villa,19.667022,0.0,19.667022,0.0,0.0,0.0,19.667022,0.0,19.667022
410,0,736.0,Gianluigi Donnarumma,a,5.6,GK,Man City,19.539935,0.0,19.539935,0.0,0.0,0.0,19.539935,0.0,19.539935

In [32]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [33]:
from FPL_Optimizer import FPLOptimizer

In [34]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £97.1m / £102.4m
Total Weighted Expected Points: 279.95
Remaining Budget: £5.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Karl Darlow                    Leeds        £3.9    16.07
 ✅        Walter Benítez                 Crystal Palace £3.9    17.90

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Piero Hincapié                 Arsenal      £5.1    20.10
 🪑        Reece James                    Chelsea      £5.6    18.46
 ✅        John Stones                    Man City     £5.4    35.84
 ✅        Nico O'Reilly                  Man City     £5.1    27.37
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1    21.04

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    40.20
 ✅        Declan Rice                    Arsenal      £7.2    22.47
 ✅        Mohamed Salah                  Liverpool    £14.0   21.93
 ✅        James Ward-Prowse              Burnley      £5.6    21.90
 ✅        Mathias Jensen                 Brentford    £4.9    21.54

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Francisco Evanilson de Lima Barbosa Bournemouth  £6.7    17.16
 ✅        Jarrod Bowen                   West Ham     £7.7    21.89
 ✅        Ollie Watkins                  Aston Villa  £8.7    20.69

================================================================================
Optimization Status: Optimal

In [35]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £88.8m / £102.4m
Total Weighted Expected Points: 270.53
Remaining Budget: £13.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Karl Darlow                    Leeds        £3.9    16.07
 ✅        Walter Benítez                 Crystal Palace £3.9    17.90

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1    27.37
 ✅        William Saliba                 Arsenal      £6.1    19.93
 ✅        Piero Hincapié                 Arsenal      £5.1    20.10
 ✅        Benjamin White                 Arsenal      £5.1    19.81
 ✅        John Stones                    Man City     £5.4    35.84

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Youri Tielemans                Aston Villa  £5.9    19.67
 ✅        Mohamed Salah                  Liverpool    £14.0   21.93
 ✅        James Ward-Prowse              Burnley      £5.6    21.90
 ✅        Mathias Jensen                 Brentford    £4.9    21.54
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    40.20

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brian Brobbey                  Sunderland   £5.3    16.10
 🪑        Dominic Calvert-Lewin          Leeds        £5.6    16.65
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.7    17.16

================================================================================
Optimization Status: Optimal

In [36]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,36.0,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,Crystal Palace; Brentford,6.2,16.336383
1,36.0,John Stones,a,DEF,Man City,Crystal Palace; Brentford,5.4,14.424153
2,36.0,Antoine Semenyo,a,MID,Man City,Crystal Palace; Brentford,8.2,11.148245
3,36.0,Nico O'Reilly,a,DEF,Man City,Crystal Palace; Brentford,5.1,11.081057
4,36.0,Erling Haaland,a,FWD,Man City,Crystal Palace; Brentford,14.5,10.469812
5,36.0,Matheus Nunes,a,DEF,Man City,Crystal Palace; Brentford,5.3,10.247069
6,36.0,Marc Guéhi,a,DEF,Man City,Crystal Palace; Brentford,5.1,9.508743
7,36.0,Rayan Cherki,a,MID,Man City,Crystal Palace; Brentford,6.4,9.488923
8,36.0,Abdukodir Khusanov,a,DEF,Man City,Crystal Palace; Brentford,5.4,9.192356
9,36.0,Max Alleyne,a,DEF,Man City,Crystal Palace; Brentford,3.9,8.965704

In [37]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW35 to GW38...

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £96.3m / £102.4m
Total Weighted Expected Points: 64.22
Remaining Budget: £6.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emiliano Martínez Romero       Aston Villa  £5.1     4.08
 ✅        Caoimhín Kelleher              Brentford    £4.8     4.09

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Struijk                 Leeds        £4.3     4.85
 🪑        Gabriel dos Santos Magalhães   Arsenal      £7.1     4.75
 ✅        John Stones                    Man City     £5.4     7.25
 ✅        Nico O'Reilly                  Man City     £5.1     5.56
 ✅        Nordi Mukiele                  Sunderland   £4.6     4.99

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     8.15
 ✅        James Ward-Prowse              Burnley      £5.6     5.54
 ✅        Mathias Jensen                 Brentford    £4.9     5.51
 ✅        Mohamed Salah                  Liverpool    £14.0    5.41
 ✅        Declan Rice                    Arsenal      £7.2     5.21

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.6     4.51
 ✅        Jarrod Bowen                   West Ham     £7.7     5.47
 ✅        Ollie Watkins                  Aston Villa  £8.7     5.20

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £97.5m / £102.4m
Total Weighted Expected Points: 93.05
Remaining Budget: £4.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        David Raya Martín              Arsenal      £6.0     4.57
 ✅        Walter Benítez                 Crystal Palace £3.9     7.12

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lucas Digne                    Aston Villa  £4.5     5.27
 🪑        Piero Hincapié                 Arsenal      £5.1     5.23
 ✅        John Stones                    Man City     £5.4    14.42
 ✅        Nico O'Reilly                  Man City     £5.1    11.08
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     5.50

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2    16.34
 ✅        Jefferson Lerma Solís          Crystal Palace £4.9     7.23
 ✅        Ismaïla Sarr                   Crystal Palace £6.3     7.17
 ✅        Youri Tielemans                Aston Villa  £5.9     5.64
 ✅        Mohamed Salah                  Liverpool    £14.0    5.54

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Francisco Evanilson de Lima Barbosa Bournemouth  £6.7     4.30
 ✅        Ollie Watkins                  Aston Villa  £8.7     5.65
 ✅        Jarrod Bowen                   West Ham     £7.7     5.43

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £98.6m / £102.4m
Total Weighted Expected Points: 66.87
Remaining Budget: £3.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lucas Estella Perri            Leeds        £4.4     3.98
 ✅        Bernd Leno                     Fulham       £4.9     4.38

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Reece James                    Chelsea      £5.6     5.04
 ✅        John Stones                    Man City     £5.4     7.18
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     6.01
 ✅        Piero Hincapié                 Arsenal      £5.1     5.81
 ✅        Nico O'Reilly                  Man City     £5.1     5.36

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     8.02
 ✅        Declan Rice                    Arsenal      £7.2     6.65
 ✅        Mathias Jensen                 Brentford    £4.9     5.44
 ✅        Mohamed Salah                  Liverpool    £14.0    5.39
 ✅        James Ward-Prowse              Burnley      £5.6     5.33

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ollie Watkins                  Aston Villa  £8.7     4.96
 🪑        Francisco Evanilson de Lima Barbosa Bournemouth  £6.7     4.25
 ✅        Jarrod Bowen                   West Ham     £7.7     5.48

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £96.8m / £102.4m
Total Weighted Expected Points: 62.93
Remaining Budget: £5.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Karl Darlow                    Leeds        £3.9     4.09
 ✅        David Raya Martín              Arsenal      £6.0     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Kyle Walker-Peters             West Ham     £4.2     4.74
 🪑        El Hadji Malick Diouf          West Ham     £4.1     4.72
 ✅        John Stones                    Man City     £5.4     6.99
 ✅        Nico O'Reilly                  Man City     £5.1     5.38
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     4.78

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     7.69
 ✅        James Ward-Prowse              Burnley      £5.6     5.67
 ✅        Mohamed Salah                  Liverpool    £14.0    5.59
 ✅        Mathias Jensen                 Brentford    £4.9     5.32
 ✅        Declan Rice                    Arsenal      £7.2     5.21

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Francisco Evanilson de Lima Barbosa Bournemouth  £6.7     4.31
 ✅        Jarrod Bowen                   West Ham     £7.7     5.52
 ✅        Ollie Watkins                  Aston Villa  £8.7     4.87

================================================================================
Optimization Status: Optimal

In [38]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 36

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
11,36,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,Crystal Palace; Brentford,6.2,16.336383
14,36,Jefferson Lerma Solís,a,MID,Crystal Palace,Man City; Everton,4.9,7.233696
15,36,Ismaïla Sarr,a,MID,Crystal Palace,Man City; Everton,6.3,7.169695
18,36,Youri Tielemans,a,MID,Aston Villa,Burnley,5.9,5.637862
19,36,Mohamed Salah,d,MID,Liverpool,Chelsea,14.0,5.537146
16,36,Walter Benítez,a,GK,Crystal Palace,Man City; Everton,3.9,7.121028
17,36,Ollie Watkins,a,FWD,Aston Villa,Burnley,8.7,5.647241
21,36,Jarrod Bowen,a,FWD,West Ham,Arsenal,7.7,5.427437
12,36,John Stones,a,DEF,Man City,Crystal Palace; Brentford,5.4,14.424153
13,36,Nico O'Reilly,a,DEF,Man City,Crystal Palace; Brentford,5.1,11.081057
20,36,Gabriel dos Santos Magalhães,a,DEF,Arsenal,West Ham,7.1,5.500517

In [39]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [40]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)