In [11]:
import pandas as pd
import time
#other requirements: pulp

In [12]:
start=time.perf_counter()

In [13]:
#add this info to a settings dict?
current_gw = 30
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [14]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [15]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  31
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4
5398818 Ryan Boyce GW 5 Pick 5
5398818 Ryan Boyce GW 5 Pick 6
5398818 Ryan Boyce GW 5 Pick 7
5398818 Ryan Boyce GW 5 Pick 8
5398818 Ryan Boyce GW 5 Pick 9
5398818 Ryan Boyce GW 5 Pick 10
5398818 Ryan Boyce GW 5 Pick 11
5398818 Ryan Boyce GW 5 Pick 12
5398818 Ryan Boyce GW 5 Pick 13
5398818 Ryan Boyce GW 5 Pick 14
5398818 Ryan Boyce GW 5 Pick 15
5398818 Ryan Boyce GW 6 Pick 1
5398818 Ryan Boyce GW 6 Pick 2
5398818 Ryan Boyce GW 6 Pick 3
5398818 Ryan Boyce GW 6 Pick 4
5398818 Ryan Boyce GW 6 Pick 5
5398818 Ryan Boyce GW 6 Pick 6
5398818 Ryan Boyce GW 6 Pick 7
5398818 Ryan Boyce GW 6 Pick 8
5398818 Ryan Boyce GW 6 Pick 9
5398818 Ryan Boyce GW 6 Pick 10
5398818 Ryan Boyce GW 6 Pick 11
5398818 Ryan Boyce GW 6 Pick 12
5398818 Ryan Boyce GW 6 Pick 13
5398818 Ryan Boyce GW 6 Pick 14
5398818 Ryan Boyce GW 6 Pick 15
5398818 Ryan Boyce GW 7 Pick 1
5398818 Ryan Boyce GW 7 Pick 2
5398818 Ryan Boyce GW 7 Pick 3
5398818 Ryan Boyce GW 7 Pick 4
5398818 Ryan Boyce GW 7 Pick 5
5398818 Ryan Boyce GW 7 Pick 6
5398818 Ryan Boyce GW 7 Pick 7
5398818 Ryan Boyce GW 7 Pick 8
5398818 Ryan Boyce GW 7 Pick 9
5398818 Ryan Boyce GW 7 Pick 10
5398818 Ryan Boyce GW 7 Pick 11
5398818 Ryan Boyce GW 7 Pick 12
5398818 Ryan Boyce GW 7 Pick 13
5398818 Ryan Boyce GW 7 Pick 14
5398818 Ryan Boyce GW 7 Pick 15
5398818 Ryan Boyce GW 8 Pick 1
5398818 Ryan Boyce GW 8 Pick 2
5398818 Ryan Boyce GW 8 Pick 3
5398818 Ryan Boyce GW 8 Pick 4
5398818 Ryan Boyce GW 8 Pick 5
5398818 Ryan Boyce GW 8 Pick 6
5398818 Ryan Boyce GW 8 Pick 7
5398818 Ryan Boyce GW 8 Pick 8
5398818 Ryan Boyce GW 8 Pick 9
5398818 Ryan Boyce GW 8 Pick 10
5398818 Ryan Boyce GW 8 Pick 11
5398818 Ryan Boyce GW 8 Pick 12
5398818 Ryan Boyce GW 8 Pick 13
5398818 Ryan Boyce GW 8 Pick 14
5398818 Ryan Boyce GW 8 Pick 15
5398818 Ryan Boyce GW 9 Pick 1
5398818 Ryan Boyce GW 9 Pick 2
5398818 Ryan Boyce GW 9 Pick 3
5398818 Ryan Boyce GW 9 Pick 4
5398818 Ryan Boyce GW 9 Pick 5
5398818 Ryan Boyce GW 9 Pick 6
5398818 Ryan Boyce GW 9 Pick 7
5398818 Ryan Boyce GW 9 Pick 8
5398818 Ryan Boyce GW 9 Pick 9
5398818 Ryan Boyce GW 9 Pick 10
5398818 Ryan Boyce GW 9 Pick 11
5398818 Ryan Boyce GW 9 Pick 12
5398818 Ryan Boyce GW 9 Pick 13
5398818 Ryan Boyce GW 9 Pick 14
5398818 Ryan Boyce GW 9 Pick 15
5398818 Ryan Boyce GW 10 Pick 1
5398818 Ryan Boyce GW 10 Pick 2
5398818 Ryan Boyce GW 10 Pick 3
5398818 Ryan Boyce GW 10 Pick 4
5398818 Ryan Boyce GW 10 Pick 5
5398818 Ryan Boyce GW 10 Pick 6
5398818 Ryan Boyce GW 10 Pick 7
5398818 Ryan Boyce GW 10 Pick 8
5398818 Ryan Boyce GW 10 Pick 9
5398818 Ryan Boyce GW 10 Pick 10
5398818 Ryan Boyce GW 10 Pick 11
5398818 Ryan Boyce GW 10 Pick 12
5398818 Ryan Boyce GW 10 Pick 13
5398818 Ryan Boyce GW 10 Pick 14
5398818 Ryan Boyce GW 10 Pick 15
5398818 Ryan Boyce GW 11 Pick 1
5398818 Ryan Boyce GW 11 Pick 2
5398818 Ryan Boyce GW 11 Pick 3
5398818 Ryan Boyce GW 11 Pick 4
5398818 Ryan Boyce GW 11 Pick 5
5398818 Ryan Boyce GW 11 Pick 6
5398818 Ryan Boyce GW 11 Pick 7
5398818 Ryan Boyce GW 11 Pick 8
5398818 Ryan Boyce GW 11 Pick 9
5398818 Ryan Boyce GW 11 Pick 10
5398818 Ryan Boyce GW 11 Pick 11
5398818 Ryan Boyce GW 11 Pick 12
5398818 Ryan Boyce GW 11 Pick 13
5398818 Ryan Boyce GW 11 Pick 14
5398818 Ryan Boyce GW 11 Pick 15
5398818 Ryan Boyce GW 12 Pick 1
5398818 Ryan Boyce GW 12 Pick 2
5398818 Ryan Boyce GW 12 Pick 3
5398818 Ryan Boyce GW 12 Pick 4
5398818 Ryan Boyce GW 12 Pick 5
5398818 Ryan Boyce GW 12 Pick 6
5398818 Ryan Boyce GW 12 Pick 7
5398818 Ryan Boyce GW 12 Pick 8
5398818 Ryan Boyce GW 12 Pick 9
5398818 Ryan Boyce GW 12 Pick 10
5398818 Ryan Boyce GW 12 Pick 11
5398818 Ryan Boyce GW 12 Pick 12
5398818 Ryan Boyce GW 12 Pick 13
5398818 Ryan Boyce GW 12 Pick 14
5398818 Ryan Boyce GW 12 Pick 15
5398818 Ryan Boyce GW 13 Pick 1
5398818 Ryan Boyce GW 13 Pick 2
5398818 Ryan Boyce GW 13 Pick 3
5398818 Ryan Boyce GW 13 Pick 4
5398818 Ryan Boyce GW 13 Pick 5
5398818 Ryan Boyce GW 13 Pick 6
5398818 Ryan Boyce GW 13 Pick 7
5398818 Ryan Boyce GW 13 Pick 8
5398818 Ryan Boyce GW 13 Pick 9
5398818 Ryan Boyce GW 13 Pick 10
5398818 Ryan Boyce GW 13 Pick 11
5398818 Ryan Boyce GW 13 Pick 12
5398818 Ryan Boyce GW 13 Pick 13
5398818 Ryan Boyce GW 13 Pick 14
5398818 Ryan Boyce GW 13 Pick 15
5398818 Ryan Boyce GW 14 Pick 1
5398818 Ryan Boyce GW 14 Pick 2
5398818 Ryan Boyce GW 14 Pick 3
5398818 Ryan Boyce GW 14 Pick 4
5398818 Ryan Boyce GW 14 Pick 5
5398818 Ryan Boyce GW 14 Pick 6
5398818 Ryan Boyce GW 14 Pick 7
5398818 Ryan Boyce GW 14 Pick 8
5398818 Ryan Boyce GW 14 Pick 9
5398818 Ryan Boyce GW 14 Pick 10
5398818 Ryan Boyce GW 14 Pick 11
5398818 Ryan Boyce GW 14 Pick 12
5398818 Ryan Boyce GW 14 Pick 13
5398818 Ryan Boyce GW 14 Pick 14
5398818 Ryan Boyce GW 14 Pick 15
5398818 Ryan Boyce GW 15 Pick 1
5398818 Ryan Boyce GW 15 Pick 2
5398818 Ryan Boyce GW 15 Pick 3
5398818 Ryan Boyce GW 15 Pick 4
5398818 Ryan Boyce GW 15 Pick 5
5398818 Ryan Boyce GW 15 Pick 6
5398818 Ryan Boyce GW 15 Pick 7
5398818 Ryan Boyce GW 15 Pick 8
5398818 Ryan Boyce GW 15 Pick 9
5398818 Ryan Boyce GW 15 Pick 10
5398818 Ryan Boyce GW 15 Pick 11
5398818 Ryan Boyce GW 15 Pick 12
5398818 Ryan Boyce GW 15 Pick 13
5398818 Ryan Boyce GW 15 Pick 14
5398818 Ryan Boyce GW 15 Pick 15
5398818 Ryan Boyce GW 16 Pick 1
5398818 Ryan Boyce GW 16 Pick 2
5398818 Ryan Boyce GW 16 Pick 3
5398818 Ryan Boyce GW 16 Pick 4
5398818 Ryan Boyce GW 16 Pick 5
5398818 Ryan Boyce GW 16 Pick 6
5398818 Ryan Boyce GW 16 Pick 7
5398818 Ryan Boyce GW 16 Pick 8
5398818 Ryan Boyce GW 16 Pick 9
5398818 Ryan Boyce GW 16 Pick 10
5398818 Ryan Boyce GW 16 Pick 11
5398818 Ryan Boyce GW 16 Pick 12
5398818 Ryan Boyce GW 16 Pick 13
5398818 Ryan Boyce GW 16 Pick 14
5398818 Ryan Boyce GW 16 Pick 15
5398818 Ryan Boyce GW 17 Pick 1
5398818 Ryan Boyce GW 17 Pick 2
5398818 Ryan Boyce GW 17 Pick 3
5398818 Ryan Boyce GW 17 Pick 4
5398818 Ryan Boyce GW 17 Pick 5
5398818 Ryan Boyce GW 17 Pick 6
5398818 Ryan Boyce GW 17 Pick 7
5398818 Ryan Boyce GW 17 Pick 8
5398818 Ryan Boyce GW 17 Pick 9
5398818 Ryan Boyce GW 17 Pick 10
5398818 Ryan Boyce GW 17 Pick 11
5398818 Ryan Boyce GW 17 Pick 12
5398818 Ryan Boyce GW 17 Pick 13
5398818 Ryan Boyce GW 17 Pick 14
5398818 Ryan Boyce GW 17 Pick 15
5398818 Ryan Boyce GW 18 Pick 1
5398818 Ryan Boyce GW 18 Pick 2
5398818 Ryan Boyce GW 18 Pick 3
5398818 Ryan Boyce GW 18 Pick 4
5398818 Ryan Boyce GW 18 Pick 5
5398818 Ryan Boyce GW 18 Pick 6
5398818 Ryan Boyce GW 18 Pick 7
5398818 Ryan Boyce GW 18 Pick 8
5398818 Ryan Boyce GW 18 Pick 9
5398818 Ryan Boyce GW 18 Pick 10
5398818 Ryan Boyce GW 18 Pick 11
5398818 Ryan Boyce GW 18 Pick 12
5398818 Ryan Boyce GW 18 Pick 13
5398818 Ryan Boyce GW 18 Pick 14
5398818 Ryan Boyce GW 18 Pick 15
5398818 Ryan Boyce GW 19 Pick 1
5398818 Ryan Boyce GW 19 Pick 2
5398818 Ryan Boyce GW 19 Pick 3
5398818 Ryan Boyce GW 19 Pick 4
5398818 Ryan Boyce GW 19 Pick 5
5398818 Ryan Boyce GW 19 Pick 6
5398818 Ryan Boyce GW 19 Pick 7
5398818 Ryan Boyce GW 19 Pick 8
5398818 Ryan Boyce GW 19 Pick 9
5398818 Ryan Boyce GW 19 Pick 10
5398818 Ryan Boyce GW 19 Pick 11
5398818 Ryan Boyce GW 19 Pick 12
5398818 Ryan Boyce GW 19 Pick 13
5398818 Ryan Boyce GW 19 Pick 14
5398818 Ryan Boyce GW 19 Pick 15
5398818 Ryan Boyce GW 20 Pick 1
5398818 Ryan Boyce GW 20 Pick 2
5398818 Ryan Boyce GW 20 Pick 3
5398818 Ryan Boyce GW 20 Pick 4
5398818 Ryan Boyce GW 20 Pick 5
5398818 Ryan Boyce GW 20 Pick 6
5398818 Ryan Boyce GW 20 Pick 7
5398818 Ryan Boyce GW 20 Pick 8
5398818 Ryan Boyce GW 20 Pick 9
5398818 Ryan Boyce GW 20 Pick 10
5398818 Ryan Boyce GW 20 Pick 11
5398818 Ryan Boyce GW 20 Pick 12
5398818 Ryan Boyce GW 20 Pick 13
5398818 Ryan Boyce GW 20 Pick 14
5398818 Ryan Boyce GW 20 Pick 15
5398818 Ryan Boyce GW 21 Pick 1
5398818 Ryan Boyce GW 21 Pick 2
5398818 Ryan Boyce GW 21 Pick 3
5398818 Ryan Boyce GW 21 Pick 4
5398818 Ryan Boyce GW 21 Pick 5
5398818 Ryan Boyce GW 21 Pick 6
5398818 Ryan Boyce GW 21 Pick 7
5398818 Ryan Boyce GW 21 Pick 8
5398818 Ryan Boyce GW 21 Pick 9
5398818 Ryan Boyce GW 21 Pick 10
5398818 Ryan Boyce GW 21 Pick 11
5398818 Ryan Boyce GW 21 Pick 12
5398818 Ryan Boyce GW 21 Pick 13
5398818 Ryan Boyce GW 21 Pick 14
5398818 Ryan Boyce GW 21 Pick 15
5398818 Ryan Boyce GW 22 Pick 1
5398818 Ryan Boyce GW 22 Pick 2
5398818 Ryan Boyce GW 22 Pick 3
5398818 Ryan Boyce GW 22 Pick 4
5398818 Ryan Boyce GW 22 Pick 5
5398818 Ryan Boyce GW 22 Pick 6
5398818 Ryan Boyce GW 22 Pick 7
5398818 Ryan Boyce GW 22 Pick 8
5398818 Ryan Boyce GW 22 Pick 9
5398818 Ryan Boyce GW 22 Pick 10
5398818 Ryan Boyce GW 22 Pick 11
5398818 Ryan Boyce GW 22 Pick 12
5398818 Ryan Boyce GW 22 Pick 13
5398818 Ryan Boyce GW 22 Pick 14
5398818 Ryan Boyce GW 22 Pick 15
5398818 Ryan Boyce GW 23 Pick 1
5398818 Ryan Boyce GW 23 Pick 2
5398818 Ryan Boyce GW 23 Pick 3
5398818 Ryan Boyce GW 23 Pick 4
5398818 Ryan Boyce GW 23 Pick 5
5398818 Ryan Boyce GW 23 Pick 6
5398818 Ryan Boyce GW 23 Pick 7
5398818 Ryan Boyce GW 23 Pick 8
5398818 Ryan Boyce GW 23 Pick 9
5398818 Ryan Boyce GW 23 Pick 10
5398818 Ryan Boyce GW 23 Pick 11
5398818 Ryan Boyce GW 23 Pick 12
5398818 Ryan Boyce GW 23 Pick 13
5398818 Ryan Boyce GW 23 Pick 14
5398818 Ryan Boyce GW 23 Pick 15
5398818 Ryan Boyce GW 24 Pick 1
5398818 Ryan Boyce GW 24 Pick 2
5398818 Ryan Boyce GW 24 Pick 3
5398818 Ryan Boyce GW 24 Pick 4
5398818 Ryan Boyce GW 24 Pick 5
5398818 Ryan Boyce GW 24 Pick 6
5398818 Ryan Boyce GW 24 Pick 7
5398818 Ryan Boyce GW 24 Pick 8
5398818 Ryan Boyce GW 24 Pick 9
5398818 Ryan Boyce GW 24 Pick 10
5398818 Ryan Boyce GW 24 Pick 11
5398818 Ryan Boyce GW 24 Pick 12
5398818 Ryan Boyce GW 24 Pick 13
5398818 Ryan Boyce GW 24 Pick 14
5398818 Ryan Boyce GW 24 Pick 15
5398818 Ryan Boyce GW 25 Pick 1
5398818 Ryan Boyce GW 25 Pick 2
5398818 Ryan Boyce GW 25 Pick 3
5398818 Ryan Boyce GW 25 Pick 4
5398818 Ryan Boyce GW 25 Pick 5
5398818 Ryan Boyce GW 25 Pick 6
5398818 Ryan Boyce GW 25 Pick 7
5398818 Ryan Boyce GW 25 Pick 8
5398818 Ryan Boyce GW 25 Pick 9
5398818 Ryan Boyce GW 25 Pick 10
5398818 Ryan Boyce GW 25 Pick 11
5398818 Ryan Boyce GW 25 Pick 12
5398818 Ryan Boyce GW 25 Pick 13
5398818 Ryan Boyce GW 25 Pick 14
5398818 Ryan Boyce GW 25 Pick 15
5398818 Ryan Boyce GW 26 Pick 1
5398818 Ryan Boyce GW 26 Pick 2
5398818 Ryan Boyce GW 26 Pick 3
5398818 Ryan Boyce GW 26 Pick 4
5398818 Ryan Boyce GW 26 Pick 5
5398818 Ryan Boyce GW 26 Pick 6
5398818 Ryan Boyce GW 26 Pick 7
5398818 Ryan Boyce GW 26 Pick 8
5398818 Ryan Boyce GW 26 Pick 9
5398818 Ryan Boyce GW 26 Pick 10
5398818 Ryan Boyce GW 26 Pick 11
5398818 Ryan Boyce GW 26 Pick 12
5398818 Ryan Boyce GW 26 Pick 13
5398818 Ryan Boyce GW 26 Pick 14
5398818 Ryan Boyce GW 26 Pick 15
5398818 Ryan Boyce GW 27 Pick 1
5398818 Ryan Boyce GW 27 Pick 2
5398818 Ryan Boyce GW 27 Pick 3
5398818 Ryan Boyce GW 27 Pick 4
5398818 Ryan Boyce GW 27 Pick 5
5398818 Ryan Boyce GW 27 Pick 6
5398818 Ryan Boyce GW 27 Pick 7
5398818 Ryan Boyce GW 27 Pick 8
5398818 Ryan Boyce GW 27 Pick 9
5398818 Ryan Boyce GW 27 Pick 10
5398818 Ryan Boyce GW 27 Pick 11
5398818 Ryan Boyce GW 27 Pick 12
5398818 Ryan Boyce GW 27 Pick 13
5398818 Ryan Boyce GW 27 Pick 14
5398818 Ryan Boyce GW 27 Pick 15
5398818 Ryan Boyce GW 28 Pick 1
5398818 Ryan Boyce GW 28 Pick 2
5398818 Ryan Boyce GW 28 Pick 3
5398818 Ryan Boyce GW 28 Pick 4
5398818 Ryan Boyce GW 28 Pick 5
5398818 Ryan Boyce GW 28 Pick 6
5398818 Ryan Boyce GW 28 Pick 7
5398818 Ryan Boyce GW 28 Pick 8
5398818 Ryan Boyce GW 28 Pick 9
5398818 Ryan Boyce GW 28 Pick 10
5398818 Ryan Boyce GW 28 Pick 11
5398818 Ryan Boyce GW 28 Pick 12
5398818 Ryan Boyce GW 28 Pick 13
5398818 Ryan Boyce GW 28 Pick 14
5398818 Ryan Boyce GW 28 Pick 15
5398818 Ryan Boyce GW 29 Pick 1
5398818 Ryan Boyce GW 29 Pick 2
5398818 Ryan Boyce GW 29 Pick 3
5398818 Ryan Boyce GW 29 Pick 4
5398818 Ryan Boyce GW 29 Pick 5
5398818 Ryan Boyce GW 29 Pick 6
5398818 Ryan Boyce GW 29 Pick 7
5398818 Ryan Boyce GW 29 Pick 8
5398818 Ryan Boyce GW 29 Pick 9
5398818 Ryan Boyce GW 29 Pick 10
5398818 Ryan Boyce GW 29 Pick 11
5398818 Ryan Boyce GW 29 Pick 12
5398818 Ryan Boyce GW 29 Pick 13
5398818 Ryan Boyce GW 29 Pick 14
5398818 Ryan Boyce GW 29 Pick 15
5398818 Ryan Boyce GW 30 Pick 1
5398818 Ryan Boyce GW 30 Pick 2
5398818 Ryan Boyce GW 30 Pick 3
5398818 Ryan Boyce GW 30 Pick 4
5398818 Ryan Boyce GW 30 Pick 5
5398818 Ryan Boyce GW 30 Pick 6
5398818 Ryan Boyce GW 30 Pick 7
5398818 Ryan Boyce GW 30 Pick 8
5398818 Ryan Boyce GW 30 Pick 9
5398818 Ryan Boyce GW 30 Pick 10
5398818 Ryan Boyce GW 30 Pick 11
5398818 Ryan Boyce GW 30 Pick 12
5398818 Ryan Boyce GW 30 Pick 13
5398818 Ryan Boyce GW 30 Pick 14
5398818 Ryan Boyce GW 30 Pick 15
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9

In [16]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW31 to GW35

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1028.6,4.80,85.2,0.232,0.140,1.182
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1084.0,4.76,76.7,0.216,0.240,1.367
2,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,1007.4,4.66,86.8,0.046,0.045,0.989
3,Mohamed Salah,a,0,MID,Liverpool,1067.9,4.60,75.8,0.249,0.159,1.234
4,Dominik Szoboszlai,a,1,MID,Liverpool,1067.9,4.60,83.5,0.180,0.192,1.321
5,Cole Palmer,a,0,MID,Chelsea,1096.3,4.60,81.1,0.217,0.190,1.435
6,Matty Cash,d,0,DEF,Aston Villa,1007.4,4.50,76.6,0.048,0.052,1.016
7,Alex Iwobi,a,0,MID,Fulham,1107.2,4.44,85.0,0.157,0.139,1.418
8,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1084.0,4.39,81.0,0.175,0.127,1.340
9,Alexis Mac Allister,a,1,MID,Liverpool,1067.9,4.37,77.8,0.179,0.158,1.231
10,Ibrahima Konaté,a,1,DEF,Liverpool,1067.9,4.37,82.1,0.042,0.042,1.074
11,Cody Gakpo,a,0,MID,Liverpool,1067.9,4.36,71.0,0.195,0.177,1.104
12,Morgan Rogers,a,0,MID,Aston Villa,1007.4,4.35,79.9,0.159,0.158,1.164
13,Pau Torres,a,0,DEF,Aston Villa,1007.4,4.35,78.4,0.043,0.041,1.062
14,Anton Stach,a,0,MID,Leeds,1016.5,4.34,81.0,0.172,0.170,1.235
15,Lucas Digne,a,0,DEF,Aston Villa,1007.4,4.33,71.4,0.049,0.071,1.063
16,Pascal Groß,a,0,MID,Brighton,1047.4,4.31,85.8,0.099,0.186,1.116
17,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,4.31,85.5,0.041,0.051,1.113
18,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,4.31,87.1,0.042,0.044,1.126
19,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1054.4,4.30,85.5,0.117,0.147,1.308
20,Jeremie Frimpong,a,0,DEF,Liverpool,1067.9,4.30,62.5,0.040,0.067,0.936
21,Anthony Gordon,a,0,MID,Newcastle,1096.9,4.29,83.0,0.170,0.122,1.307
22,Jaidon Anthony,a,0,MID,Burnley,1067.9,4.29,80.5,0.224,0.116,1.768
23,Lewis Dunk,a,0,DEF,Brighton,1047.4,4.28,86.5,0.049,0.049,1.184
24,Bryan Mbeumo,a,0,MID,Man Utd,1084.0,4.27,79.9,0.179,0.129,1.307
25,Iliman Ndiaye,a,0,MID,Everton,1118.8,4.27,85.1,0.165,0.116,1.373
26,Mathias Jensen,a,1,MID,Brentford,1036.6,4.27,78.2,0.167,0.128,1.311
27,Alex Scott,a,0,MID,Bournemouth,1096.1,4.26,85.7,0.157,0.117,1.263
28,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,4.25,80.8,0.167,0.114,1.096
29,Tomáš Souček,a,0,MID,West Ham,1054.4,4.25,82.2,0.160,0.134,1.271
30,Enzo Fernández,a,0,MID,Chelsea,1096.3,4.25,79.3,0.151,0.176,1.389
31,Tyrone Mings,a,1,DEF,Aston Villa,1007.4,4.25,69.3,0.052,0.069,1.077
32,Carlos Henrique Casimiro,a,0,MID,Man Utd,1084.0,4.24,81.4,0.159,0.138,1.325
33,Amadou Onana,a,0,MID,Aston Villa,1007.4,4.19,73.8,0.159,0.159,1.064
34,Marc Guiu Paz,a,0,FWD,Chelsea,1096.3,4.18,46.4,0.800,0.294,1.619
35,Habib Diarra,a,0,MID,Sunderland,1027.9,4.16,83.2,0.153,0.103,1.106
36,Ola Aina,a,0,DEF,Nott'm Forest,1028.6,4.16,86.4,0.033,0.045,1.195
37,Nikola Milenković,a,0,DEF,Nott'm Forest,1028.6,4.14,86.8,0.039,0.041,1.227
38,João Pedro Junqueira de Jesus,a,0,FWD,Chelsea,1096.3,4.12,83.3,0.348,0.062,1.228
39,Lamare Bogarde,a,0,DEF,Aston Villa,1007.4,4.12,58.9,0.039,0.058,0.947
40,Dango Ouattara,a,0,MID,Brentford,1036.6,4.11,74.0,0.175,0.123,1.279
41,Rayan Vitor Simplício Rocha,a,0,MID,Bournemouth,1096.1,4.11,76.1,0.157,0.140,1.156
42,Estêvão Almeida de Oliveira Gonçalves,d,0,MID,Chelsea,1096.3,4.11,53.3,0.406,0.217,1.746
43,Aaron Wan-Bissaka,a,0,DEF,West Ham,1054.4,4.11,87.4,0.040,0.042,1.203
44,Enzo Le Fée,d,0,MID,Sunderland,1027.9,4.11,84.8,0.124,0.110,1.143
45,Axel Disasi,a,0,DEF,West Ham,1054.4,4.10,87.3,0.037,0.042,1.189
46,Omar Alderete,a,0,DEF,Sunderland,1027.9,4.10,87.2,0.041,0.041,1.149
47,Ian Maatsen,a,1,DEF,Aston Villa,1007.4,4.10,65.9,0.041,0.063,1.095
48,Florian Wirtz,a,0,MID,Liverpool,1067.9,4.06,57.0,0.263,0.245,1.360
49,Marcus Tavernier,a,0,MID,Bournemouth,1096.1,4.06,79.4,0.154,0.117,1.328

In [17]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 31 and 35:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Morgan Gibbs-White,a,MID,Nott'm Forest,7.3,1028.6,23.93,85.2,0.232,0.140,1.182
1,Bruno Borges Fernandes,a,MID,Man Utd,10.1,1084.0,23.59,76.7,0.216,0.240,1.367
2,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,1007.4,23.26,86.8,0.046,0.045,0.989
3,Cole Palmer,a,MID,Chelsea,10.6,1096.3,23.19,81.1,0.217,0.190,1.435
4,Dominik Szoboszlai,a,MID,Liverpool,6.9,1067.9,23.00,83.5,0.180,0.192,1.321
5,Mohamed Salah,a,MID,Liverpool,14.0,1067.9,22.97,75.8,0.249,0.159,1.234
6,Matty Cash,d,DEF,Aston Villa,4.8,1007.4,22.43,76.6,0.048,0.052,1.016
7,Anton Stach,a,MID,Leeds,4.7,1016.5,22.02,81.0,0.172,0.170,1.235
8,Alexis Mac Allister,a,MID,Liverpool,6.3,1067.9,21.87,77.8,0.179,0.158,1.231
9,Ibrahima Konaté,a,DEF,Liverpool,5.5,1067.9,21.86,82.1,0.042,0.042,1.074
10,Matheus Santos Carneiro da Cunha,a,MID,Man Utd,8.0,1084.0,21.83,81.0,0.175,0.127,1.340
11,Morgan Rogers,a,MID,Aston Villa,7.5,1007.4,21.78,79.9,0.159,0.158,1.164
12,Cody Gakpo,a,MID,Liverpool,7.3,1067.9,21.76,71.0,0.195,0.177,1.104
13,Pau Torres,a,DEF,Aston Villa,4.3,1007.4,21.73,78.4,0.043,0.041,1.062
14,Lucas Digne,a,DEF,Aston Villa,4.5,1007.4,21.65,71.4,0.049,0.071,1.063
15,Ferdi Kadıoğlu,a,DEF,Brighton,4.4,1047.4,21.52,87.1,0.042,0.044,1.126
16,Jeremie Frimpong,a,DEF,Liverpool,5.7,1067.9,21.52,62.5,0.040,0.067,0.936
17,Alex Iwobi,a,MID,Fulham,6.4,1107.2,21.50,85.0,0.157,0.139,1.418
18,Jaidon Anthony,a,MID,Burnley,5.0,1067.9,21.49,80.5,0.224,0.116,1.768
19,Mateus Gonçalo Espanha Fernandes,a,MID,West Ham,5.5,1054.4,21.48,85.5,0.117,0.147,1.308

In [18]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0                 Ryan Boyce  5398818.0        1698.0
1              Bernard Chalk  1557117.0        1654.0
2               Jack Carroll  4438260.0        1640.0
3          William Partridge  6588565.0        1620.0
4         Christopher Harris    28660.0        1613.0
5               Samia Shelim  6506490.0        1588.0
6               Tommy Davies  7845816.0        1580.0
7             Conner Harling  3421093.0        1566.0
8                 Rhys Birdy  5810139.0        1557.0
9              Ollie Carroll  5181285.0        1553.0
10        Christopher Harris   145486.0        1543.0
11             Rizwan Shelim  3058994.0        1538.0
12               Nafi Shelim  4776281.0        1534.0
13             Tajwar Shelim  4773459.0        1496.0
14  Christakis Christodoulou  7474864.0        1470.0
15              Will Hossack  4792527.0        1397.0
16               Simon Meech  6764382.0        1390.0
17              Tahmid Haque  6394829.0        1374.0
18            Charlie Garner  9432680.0        1373.0
19              Holly Stower  7367977.0        1316.0
20            Rachel Aumayer  9763056.0        1121.0

In [19]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
178,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,37.337122,0.0,37.337122,0.000000,37.337122,0.0,37.337122,37.337122,37.337122
198,1,8.0,Jurriën Timber,a,6.3,DEF,Arsenal,36.851097,0.0,36.851097,0.000000,36.851097,0.0,36.851097,36.851097,36.851097
24,1,237.0,Enzo Fernández,a,6.6,MID,Chelsea,34.388604,0.0,34.388604,0.000000,34.388604,0.0,34.388604,34.388604,34.388604
428,1,384.0,Cody Gakpo,a,7.3,MID,Liverpool,34.239439,0.0,34.239439,0.000000,34.239439,0.0,34.239439,34.239439,34.239439
142,1,407.0,Matheus Nunes,a,5.4,DEF,Man City,32.480280,0.0,32.480280,0.000000,32.480280,0.0,32.480280,32.480280,32.480280
337,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,30.530883,0.0,30.530883,0.000000,30.530883,0.0,30.530883,30.530883,30.530883
204,1,691.0,Dominic Calvert-Lewin,d,5.7,FWD,Leeds,30.070883,0.0,30.070883,0.000000,30.070883,0.0,30.070883,30.070883,30.070883
158,1,694.0,Nordi Mukiele,d,4.5,DEF,Sunderland,29.663293,0.0,29.663293,0.000000,29.663293,0.0,29.663293,29.663293,29.663293
43,1,341.0,Karl Darlow,a,3.9,GK,Leeds,27.608677,0.0,27.608677,0.000000,27.608677,0.0,27.608677,27.608677,27.608677
5,1,337.0,Raúl Jiménez Rodríguez,a,6.2,FWD,Fulham,27.283192,0.0,27.283192,0.000000,27.283192,0.0,27.283192,27.283192,27.283192
214,1,661.0,Hugo Ekitiké,a,9.2,FWD,Liverpool,26.878892,40.0,16.127335,-10.751557,16.127335,0.0,5.375778,16.127335,16.127335
163,1,373.0,Virgil van Dijk,a,6.2,DEF,Liverpool,28.626817,60.0,11.450727,-17.176090,11.450727,0.0,-5.725363,11.450727,11.450727
208,1,5.0,Gabriel dos Santos Magalhães,a,7.2,DEF,Arsenal,35.032720,80.0,7.006544,-28.026176,7.006544,0.0,-21.019632,7.006544,7.006544
132,1,329.0,Harry Wilson,d,6.0,MID,Fulham,30.102353,80.0,6.020471,-24.081883,6.020471,0.0,-18.061412,6.020471,6.020471
189,1,449.0,Bruno Borges Fernandes,a,10.1,MID,Man Utd,38.339460,100.0,0.000000,-38.339460,0.000000,0.0,-38.339460,0.000000,0.000000

In [20]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
187,0,430.0,Erling Haaland,a,14.6,FWD,Man City,28.665765,120.0,-5.733153,-34.398918,0.0,-34.398918,-40.132071,-34.398918,-5.733153
303,0,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,33.291751,100.0,0.000000,-33.291751,0.0,-33.291751,-33.291751,-33.291751,0.000000
412,0,82.0,Antoine Semenyo,a,8.3,MID,Man City,35.045605,80.0,7.009121,-28.036484,0.0,-28.036484,-21.027363,-28.036484,7.009121
402,0,21.0,Declan Rice,a,7.4,MID,Arsenal,32.679811,60.0,13.071925,-19.607887,0.0,-19.607887,-6.535962,-19.607887,13.071925
151,0,119.0,Bryan Mbeumo,a,8.7,MID,Man Utd,34.338737,40.0,20.603242,-13.735495,0.0,-13.735495,6.867747,-13.735495,20.603242
40,0,72.0,Marcos Senesi Barón,a,5.0,DEF,Bournemouth,32.922330,40.0,19.753398,-13.168932,0.0,-13.168932,6.584466,-13.168932,19.753398
8,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,28.214846,40.0,16.928908,-11.285939,0.0,-11.285939,5.642969,-11.285939,16.928908
34,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,34.513755,20.0,27.611004,-6.902751,0.0,-6.902751,20.708253,-6.902751,27.611004
74,0,457.0,Carlos Henrique Casimiro,a,5.6,MID,Man Utd,34.063525,20.0,27.250820,-6.812705,0.0,-6.812705,20.438115,-6.812705,27.250820
30,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,33.632127,20.0,26.905702,-6.726425,0.0,-6.726425,20.179276,-6.726425,26.905702
123,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,32.948079,20.0,26.358464,-6.589616,0.0,-6.589616,19.768848,-6.589616,26.358464
230,0,74.0,Adrien Truffert,a,4.6,DEF,Bournemouth,32.851338,20.0,26.281070,-6.570268,0.0,-6.570268,19.710803,-6.570268,26.281070
265,0,16.0,Bukayo Saka,a,9.8,MID,Arsenal,32.601222,20.0,26.080978,-6.520244,0.0,-6.520244,19.560733,-6.520244,26.080978
333,0,382.0,Florian Wirtz,a,8.3,MID,Liverpool,32.326305,20.0,25.861044,-6.465261,0.0,-6.465261,19.395783,-6.465261,25.861044
46,0,683.0,Omar Alderete,a,4.1,DEF,Sunderland,32.133935,20.0,25.707148,-6.426787,0.0,-6.426787,19.280361,-6.426787,25.707148
109,0,517.0,Elliot Anderson,a,5.5,MID,Nott'm Forest,31.711388,20.0,25.369110,-6.342278,0.0,-6.342278,19.026833,-6.342278,25.369110
310,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.2,FWD,Brentford,31.396544,20.0,25.117235,-6.279309,0.0,-6.279309,18.837927,-6.279309,25.117235
26,0,226.0,Trevoh Chalobah,a,5.6,DEF,Chelsea,30.018859,20.0,24.015088,-6.003772,0.0,-6.003772,18.011316,-6.003772,24.015088
245,0,220.0,Robert Lynch Sánchez,a,4.8,GK,Chelsea,29.401609,20.0,23.521287,-5.880322,0.0,-5.880322,17.640965,-5.880322,23.521287
15,0,317.0,Joachim Andersen,a,4.5,DEF,Fulham,29.135304,20.0,23.308243,-5.827061,0.0,-5.827061,17.481183,-5.827061,23.308243

In [21]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW31 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
150,0,515.0,Morgan Gibbs-White,a,7.3,MID,Nott'm Forest,38.040371,0.0,38.040371,0.0,0.0,0.0,38.040371,0.0,38.040371
397,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,36.557251,0.0,36.557251,0.0,0.0,0.0,36.557251,0.0,36.557251
260,0,387.0,Dominik Szoboszlai,a,6.9,MID,Liverpool,36.374851,0.0,36.374851,0.0,0.0,0.0,36.374851,0.0,36.374851
316,0,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,35.661950,0.0,35.661950,0.0,0.0,0.0,35.661950,0.0,35.661950
231,0,660.0,Anton Stach,a,4.7,MID,Leeds,35.334725,0.0,35.334725,0.0,0.0,0.0,35.334725,0.0,35.334725
292,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,35.090870,0.0,35.090870,0.0,0.0,0.0,35.090870,0.0,35.090870
145,0,151.0,Jan Paul van Hecke,a,4.4,DEF,Brighton,34.836375,0.0,34.836375,0.0,0.0,0.0,34.836375,0.0,34.836375
143,0,148.0,Ferdi Kadıoğlu,a,4.4,DEF,Brighton,34.790779,0.0,34.790779,0.0,0.0,0.0,34.790779,0.0,34.790779
110,0,324.0,Alex Iwobi,a,6.4,MID,Fulham,34.623250,0.0,34.623250,0.0,0.0,0.0,34.623250,0.0,34.623250
19,0,47.0,Morgan Rogers,a,7.5,MID,Aston Villa,34.590089,0.0,34.590089,0.0,0.0,0.0,34.590089,0.0,34.590089
194,0,485.0,Anthony Gordon,a,7.2,MID,Newcastle,34.575979,0.0,34.575979,0.0,0.0,0.0,34.575979,0.0,34.575979
82,0,146.0,Lewis Dunk,a,4.5,DEF,Brighton,34.573072,0.0,34.573072,0.0,0.0,0.0,34.573072,0.0,34.573072
167,0,386.0,Alexis Mac Allister,a,6.3,MID,Liverpool,34.560097,0.0,34.560097,0.0,0.0,0.0,34.560097,0.0,34.560097
328,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,34.524660,0.0,34.524660,0.0,0.0,0.0,34.524660,0.0,34.524660
388,0,783.0,Pascal Groß,a,5.5,MID,Brighton,34.490668,0.0,34.490668,0.0,0.0,0.0,34.490668,0.0,34.490668
20,0,36.0,Matty Cash,d,4.8,DEF,Aston Villa,34.368846,0.0,34.368846,0.0,0.0,0.0,34.368846,0.0,34.368846
307,0,200.0,Jaidon Anthony,a,5.0,MID,Burnley,34.273175,0.0,34.273175,0.0,0.0,0.0,34.273175,0.0,34.273175
299,0,90.0,Alex Scott,a,5.1,MID,Bournemouth,34.272085,0.0,34.272085,0.0,0.0,0.0,34.272085,0.0,34.272085
129,0,374.0,Ibrahima Konaté,a,5.5,DEF,Liverpool,34.246388,0.0,34.246388,0.0,0.0,0.0,34.246388,0.0,34.246388
268,0,708.0,Mateus Gonçalo Espanha Fernandes,a,5.5,MID,West Ham,34.223526,0.0,34.223526,0.0,0.0,0.0,34.223526,0.0,34.223526

In [22]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [23]:
from FPL_Optimizer import FPLOptimizer

In [24]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £99.2m / £102.4m
Total Weighted Expected Points: 254.83
Remaining Budget: £3.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0    19.56
 ✅        Hákon Rafn Valdimarsson        Brentford    £3.9    19.83

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Ferdi Kadıoğlu                 Brighton     £4.4    21.52
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    23.26
 ✅        Matty Cash                     Aston Villa  £4.8    22.43
 ✅        Ibrahima Konaté                Liverpool    £5.5    21.86
 ✅        Pau Torres                     Aston Villa  £4.3    21.73

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3    23.93
 ✅        Bruno Borges Fernandes         Man Utd      £10.1   23.59
 ✅        Cole Palmer                    Chelsea      £10.6   23.19
 ✅        Dominik Szoboszlai             Liverpool    £6.9    23.00
 ✅        Mohamed Salah                  Liverpool    £14.0   22.97

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.7    20.64
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.2    19.74
 ✅        Marc Guiu Paz                  Chelsea      £4.1    20.89

================================================================================
Optimization Status: Optimal

In [25]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £94.1m / £102.4m
Total Weighted Expected Points: 403.08
Remaining Budget: £8.3m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Alisson Becker                 Liverpool    £5.4    31.11
 ✅        Hákon Rafn Valdimarsson        Brentford    £3.9    31.51

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lewis Dunk                     Brighton     £4.5    34.57
 ✅        Ferdi Kadıoğlu                 Brighton     £4.4    34.79
 ✅        Jan Paul van Hecke             Brighton     £4.4    34.84
 ✅        Jurriën Timber                 Arsenal      £6.3    36.85
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4    35.66

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Morgan Gibbs-White             Nott'm Forest £7.3    38.04
 ✅        Cole Palmer                    Chelsea      £10.6   37.34
 ✅        Anton Stach                    Leeds        £4.7    35.33
 ✅        Dominik Szoboszlai             Liverpool    £6.9    36.37
 ✅        Mohamed Salah                  Liverpool    £14.0   36.56

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.7    30.07
 🪑        Jean-Philippe Mateta           Crystal Palace £7.5    29.14
 ✅        Marc Guiu Paz                  Chelsea      £4.1    33.29

================================================================================
Optimization Status: Optimal

In [26]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [27]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)