In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 31
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  32
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2
5398818 Ryan Boyce GW 4 Pick 3
5398818 Ryan Boyce GW 4 Pick 4
5398818 Ryan Boyce GW 4 Pick 5
5398818 Ryan Boyce GW 4 Pick 6
5398818 Ryan Boyce GW 4 Pick 7
5398818 Ryan Boyce GW 4 Pick 8
5398818 Ryan Boyce GW 4 Pick 9
5398818 Ryan Boyce GW 4 Pick 10
5398818 Ryan Boyce GW 4 Pick 11
5398818 Ryan Boyce GW 4 Pick 12
5398818 Ryan Boyce GW 4 Pick 13
5398818 Ryan Boyce GW 4 Pick 14
5398818 Ryan Boyce GW 4 Pick 15
5398818 Ryan Boyce GW 5 Pick 1
5398818 Ryan Boyce GW 5 Pick 2
5398818 Ryan Boyce GW 5 Pick 3
5398818 Ryan Boyce GW 5 Pick 4
5398818 Ryan Boyce GW 5 Pick 5
5398818 Ryan Boyce GW 5 Pick 6
5398818 Ryan Boyce GW 5 Pick 7
5398818 Ryan Boyce GW 5 Pick 8
5398818 Ryan Boyce GW 5 Pick 9
5398818 Ryan Boyce GW 5 Pick 10
5398818 Ryan Boyce GW 5 Pick 11
5398818 Ryan Boyce GW 5 Pick 12
5398818 Ryan Boyce GW 5 Pick 13
5398818 Ryan Boyce GW 5 Pick 14
5398818 Ryan Boyce GW 5 Pick 15
5398818 Ryan Boyce GW 6 Pick 1
5398818 Ryan Boyce GW 6 Pick 2
5398818 Ryan Boyce GW 6 Pick 3
5398818 Ryan Boyce GW 6 Pick 4
5398818 Ryan Boyce GW 6 Pick 5
5398818 Ryan Boyce GW 6 Pick 6
5398818 Ryan Boyce GW 6 Pick 7
5398818 Ryan Boyce GW 6 Pick 8
5398818 Ryan Boyce GW 6 Pick 9
5398818 Ryan Boyce GW 6 Pick 10
5398818 Ryan Boyce GW 6 Pick 11
5398818 Ryan Boyce GW 6 Pick 12
5398818 Ryan Boyce GW 6 Pick 13
5398818 Ryan Boyce GW 6 Pick 14
5398818 Ryan Boyce GW 6 Pick 15
5398818 Ryan Boyce GW 7 Pick 1
5398818 Ryan Boyce GW 7 Pick 2
5398818 Ryan Boyce GW 7 Pick 3
5398818 Ryan Boyce GW 7 Pick 4
5398818 Ryan Boyce GW 7 Pick 5
5398818 Ryan Boyce GW 7 Pick 6
5398818 Ryan Boyce GW 7 Pick 7
5398818 Ryan Boyce GW 7 Pick 8
5398818 Ryan Boyce GW 7 Pick 9
5398818 Ryan Boyce GW 7 Pick 10
5398818 Ryan Boyce GW 7 Pick 11
5398818 Ryan Boyce GW 7 Pick 12
5398818 Ryan Boyce GW 7 Pick 13
5398818 Ryan Boyce GW 7 Pick 14
5398818 Ryan Boyce GW 7 Pick 15
5398818 Ryan Boyce GW 8 Pick 1
5398818 Ryan Boyce GW 8 Pick 2
5398818 Ryan Boyce GW 8 Pick 3
5398818 Ryan Boyce GW 8 Pick 4
5398818 Ryan Boyce GW 8 Pick 5
5398818 Ryan Boyce GW 8 Pick 6
5398818 Ryan Boyce GW 8 Pick 7
5398818 Ryan Boyce GW 8 Pick 8
5398818 Ryan Boyce GW 8 Pick 9
5398818 Ryan Boyce GW 8 Pick 10
5398818 Ryan Boyce GW 8 Pick 11
5398818 Ryan Boyce GW 8 Pick 12
5398818 Ryan Boyce GW 8 Pick 13
5398818 Ryan Boyce GW 8 Pick 14
5398818 Ryan Boyce GW 8 Pick 15
5398818 Ryan Boyce GW 9 Pick 1
5398818 Ryan Boyce GW 9 Pick 2
5398818 Ryan Boyce GW 9 Pick 3
5398818 Ryan Boyce GW 9 Pick 4
5398818 Ryan Boyce GW 9 Pick 5
5398818 Ryan Boyce GW 9 Pick 6
5398818 Ryan Boyce GW 9 Pick 7
5398818 Ryan Boyce GW 9 Pick 8
5398818 Ryan Boyce GW 9 Pick 9
5398818 Ryan Boyce GW 9 Pick 10
5398818 Ryan Boyce GW 9 Pick 11
5398818 Ryan Boyce GW 9 Pick 12
5398818 Ryan Boyce GW 9 Pick 13
5398818 Ryan Boyce GW 9 Pick 14
5398818 Ryan Boyce GW 9 Pick 15
5398818 Ryan Boyce GW 10 Pick 1
5398818 Ryan Boyce GW 10 Pick 2
5398818 Ryan Boyce GW 10 Pick 3
5398818 Ryan Boyce GW 10 Pick 4
5398818 Ryan Boyce GW 10 Pick 5
5398818 Ryan Boyce GW 10 Pick 6
5398818 Ryan Boyce GW 10 Pick 7
5398818 Ryan Boyce GW 10 Pick 8
5398818 Ryan Boyce GW 10 Pick 9
5398818 Ryan Boyce GW 10 Pick 10
5398818 Ryan Boyce GW 10 Pick 11
5398818 Ryan Boyce GW 10 Pick 12
5398818 Ryan Boyce GW 10 Pick 13
5398818 Ryan Boyce GW 10 Pick 14
5398818 Ryan Boyce GW 10 Pick 15
5398818 Ryan Boyce GW 11 Pick 1
5398818 Ryan Boyce GW 11 Pick 2
5398818 Ryan Boyce GW 11 Pick 3
5398818 Ryan Boyce GW 11 Pick 4
5398818 Ryan Boyce GW 11 Pick 5
5398818 Ryan Boyce GW 11 Pick 6
5398818 Ryan Boyce GW 11 Pick 7
5398818 Ryan Boyce GW 11 Pick 8
5398818 Ryan Boyce GW 11 Pick 9
5398818 Ryan Boyce GW 11 Pick 10
5398818 Ryan Boyce GW 11 Pick 11
5398818 Ryan Boyce GW 11 Pick 12
5398818 Ryan Boyce GW 11 Pick 13
5398818 Ryan Boyce GW 11 Pick 14
5398818 Ryan Boyce GW 11 Pick 15
5398818 Ryan Boyce GW 12 Pick 1
5398818 Ryan Boyce GW 12 Pick 2
5398818 Ryan Boyce GW 12 Pick 3
5398818 Ryan Boyce GW 12 Pick 4
5398818 Ryan Boyce GW 12 Pick 5
5398818 Ryan Boyce GW 12 Pick 6
5398818 Ryan Boyce GW 12 Pick 7
5398818 Ryan Boyce GW 12 Pick 8
5398818 Ryan Boyce GW 12 Pick 9
5398818 Ryan Boyce GW 12 Pick 10
5398818 Ryan Boyce GW 12 Pick 11
5398818 Ryan Boyce GW 12 Pick 12
5398818 Ryan Boyce GW 12 Pick 13
5398818 Ryan Boyce GW 12 Pick 14
5398818 Ryan Boyce GW 12 Pick 15
5398818 Ryan Boyce GW 13 Pick 1
5398818 Ryan Boyce GW 13 Pick 2
5398818 Ryan Boyce GW 13 Pick 3
5398818 Ryan Boyce GW 13 Pick 4
5398818 Ryan Boyce GW 13 Pick 5
5398818 Ryan Boyce GW 13 Pick 6
5398818 Ryan Boyce GW 13 Pick 7
5398818 Ryan Boyce GW 13 Pick 8
5398818 Ryan Boyce GW 13 Pick 9
5398818 Ryan Boyce GW 13 Pick 10
5398818 Ryan Boyce GW 13 Pick 11
5398818 Ryan Boyce GW 13 Pick 12
5398818 Ryan Boyce GW 13 Pick 13
5398818 Ryan Boyce GW 13 Pick 14
5398818 Ryan Boyce GW 13 Pick 15
5398818 Ryan Boyce GW 14 Pick 1
5398818 Ryan Boyce GW 14 Pick 2
5398818 Ryan Boyce GW 14 Pick 3
5398818 Ryan Boyce GW 14 Pick 4
5398818 Ryan Boyce GW 14 Pick 5
5398818 Ryan Boyce GW 14 Pick 6
5398818 Ryan Boyce GW 14 Pick 7
5398818 Ryan Boyce GW 14 Pick 8
5398818 Ryan Boyce GW 14 Pick 9
5398818 Ryan Boyce GW 14 Pick 10
5398818 Ryan Boyce GW 14 Pick 11
5398818 Ryan Boyce GW 14 Pick 12
5398818 Ryan Boyce GW 14 Pick 13
5398818 Ryan Boyce GW 14 Pick 14
5398818 Ryan Boyce GW 14 Pick 15
5398818 Ryan Boyce GW 15 Pick 1
5398818 Ryan Boyce GW 15 Pick 2
5398818 Ryan Boyce GW 15 Pick 3
5398818 Ryan Boyce GW 15 Pick 4
5398818 Ryan Boyce GW 15 Pick 5
5398818 Ryan Boyce GW 15 Pick 6
5398818 Ryan Boyce GW 15 Pick 7
5398818 Ryan Boyce GW 15 Pick 8
5398818 Ryan Boyce GW 15 Pick 9
5398818 Ryan Boyce GW 15 Pick 10
5398818 Ryan Boyce GW 15 Pick 11
5398818 Ryan Boyce GW 15 Pick 12
5398818 Ryan Boyce GW 15 Pick 13
5398818 Ryan Boyce GW 15 Pick 14
5398818 Ryan Boyce GW 15 Pick 15
5398818 Ryan Boyce GW 16 Pick 1
5398818 Ryan Boyce GW 16 Pick 2
5398818 Ryan Boyce GW 16 Pick 3
5398818 Ryan Boyce GW 16 Pick 4
5398818 Ryan Boyce GW 16 Pick 5
5398818 Ryan Boyce GW 16 Pick 6
5398818 Ryan Boyce GW 16 Pick 7
5398818 Ryan Boyce GW 16 Pick 8
5398818 Ryan Boyce GW 16 Pick 9
5398818 Ryan Boyce GW 16 Pick 10
5398818 Ryan Boyce GW 16 Pick 11
5398818 Ryan Boyce GW 16 Pick 12
5398818 Ryan Boyce GW 16 Pick 13
5398818 Ryan Boyce GW 16 Pick 14
5398818 Ryan Boyce GW 16 Pick 15
5398818 Ryan Boyce GW 17 Pick 1
5398818 Ryan Boyce GW 17 Pick 2
5398818 Ryan Boyce GW 17 Pick 3
5398818 Ryan Boyce GW 17 Pick 4
5398818 Ryan Boyce GW 17 Pick 5
5398818 Ryan Boyce GW 17 Pick 6
5398818 Ryan Boyce GW 17 Pick 7
5398818 Ryan Boyce GW 17 Pick 8
5398818 Ryan Boyce GW 17 Pick 9
5398818 Ryan Boyce GW 17 Pick 10
5398818 Ryan Boyce GW 17 Pick 11
5398818 Ryan Boyce GW 17 Pick 12
5398818 Ryan Boyce GW 17 Pick 13
5398818 Ryan Boyce GW 17 Pick 14
5398818 Ryan Boyce GW 17 Pick 15
5398818 Ryan Boyce GW 18 Pick 1
5398818 Ryan Boyce GW 18 Pick 2
5398818 Ryan Boyce GW 18 Pick 3
5398818 Ryan Boyce GW 18 Pick 4
5398818 Ryan Boyce GW 18 Pick 5
5398818 Ryan Boyce GW 18 Pick 6
5398818 Ryan Boyce GW 18 Pick 7
5398818 Ryan Boyce GW 18 Pick 8
5398818 Ryan Boyce GW 18 Pick 9
5398818 Ryan Boyce GW 18 Pick 10
5398818 Ryan Boyce GW 18 Pick 11
5398818 Ryan Boyce GW 18 Pick 12
5398818 Ryan Boyce GW 18 Pick 13
5398818 Ryan Boyce GW 18 Pick 14
5398818 Ryan Boyce GW 18 Pick 15
5398818 Ryan Boyce GW 19 Pick 1
5398818 Ryan Boyce GW 19 Pick 2
5398818 Ryan Boyce GW 19 Pick 3
5398818 Ryan Boyce GW 19 Pick 4
5398818 Ryan Boyce GW 19 Pick 5
5398818 Ryan Boyce GW 19 Pick 6
5398818 Ryan Boyce GW 19 Pick 7
5398818 Ryan Boyce GW 19 Pick 8
5398818 Ryan Boyce GW 19 Pick 9
5398818 Ryan Boyce GW 19 Pick 10
5398818 Ryan Boyce GW 19 Pick 11
5398818 Ryan Boyce GW 19 Pick 12
5398818 Ryan Boyce GW 19 Pick 13
5398818 Ryan Boyce GW 19 Pick 14
5398818 Ryan Boyce GW 19 Pick 15
5398818 Ryan Boyce GW 20 Pick 1
5398818 Ryan Boyce GW 20 Pick 2
5398818 Ryan Boyce GW 20 Pick 3
5398818 Ryan Boyce GW 20 Pick 4
5398818 Ryan Boyce GW 20 Pick 5
5398818 Ryan Boyce GW 20 Pick 6
5398818 Ryan Boyce GW 20 Pick 7
5398818 Ryan Boyce GW 20 Pick 8
5398818 Ryan Boyce GW 20 Pick 9
5398818 Ryan Boyce GW 20 Pick 10
5398818 Ryan Boyce GW 20 Pick 11
5398818 Ryan Boyce GW 20 Pick 12
5398818 Ryan Boyce GW 20 Pick 13
5398818 Ryan Boyce GW 20 Pick 14
5398818 Ryan Boyce GW 20 Pick 15
5398818 Ryan Boyce GW 21 Pick 1
5398818 Ryan Boyce GW 21 Pick 2
5398818 Ryan Boyce GW 21 Pick 3
5398818 Ryan Boyce GW 21 Pick 4
5398818 Ryan Boyce GW 21 Pick 5
5398818 Ryan Boyce GW 21 Pick 6
5398818 Ryan Boyce GW 21 Pick 7
5398818 Ryan Boyce GW 21 Pick 8
5398818 Ryan Boyce GW 21 Pick 9
5398818 Ryan Boyce GW 21 Pick 10
5398818 Ryan Boyce GW 21 Pick 11
5398818 Ryan Boyce GW 21 Pick 12
5398818 Ryan Boyce GW 21 Pick 13
5398818 Ryan Boyce GW 21 Pick 14
5398818 Ryan Boyce GW 21 Pick 15
5398818 Ryan Boyce GW 22 Pick 1
5398818 Ryan Boyce GW 22 Pick 2
5398818 Ryan Boyce GW 22 Pick 3
5398818 Ryan Boyce GW 22 Pick 4
5398818 Ryan Boyce GW 22 Pick 5
5398818 Ryan Boyce GW 22 Pick 6
5398818 Ryan Boyce GW 22 Pick 7
5398818 Ryan Boyce GW 22 Pick 8
5398818 Ryan Boyce GW 22 Pick 9
5398818 Ryan Boyce GW 22 Pick 10
5398818 Ryan Boyce GW 22 Pick 11
5398818 Ryan Boyce GW 22 Pick 12
5398818 Ryan Boyce GW 22 Pick 13
5398818 Ryan Boyce GW 22 Pick 14
5398818 Ryan Boyce GW 22 Pick 15
5398818 Ryan Boyce GW 23 Pick 1
5398818 Ryan Boyce GW 23 Pick 2
5398818 Ryan Boyce GW 23 Pick 3
5398818 Ryan Boyce GW 23 Pick 4
5398818 Ryan Boyce GW 23 Pick 5
5398818 Ryan Boyce GW 23 Pick 6
5398818 Ryan Boyce GW 23 Pick 7
5398818 Ryan Boyce GW 23 Pick 8
5398818 Ryan Boyce GW 23 Pick 9
5398818 Ryan Boyce GW 23 Pick 10
5398818 Ryan Boyce GW 23 Pick 11
5398818 Ryan Boyce GW 23 Pick 12
5398818 Ryan Boyce GW 23 Pick 13
5398818 Ryan Boyce GW 23 Pick 14
5398818 Ryan Boyce GW 23 Pick 15
5398818 Ryan Boyce GW 24 Pick 1
5398818 Ryan Boyce GW 24 Pick 2
5398818 Ryan Boyce GW 24 Pick 3
5398818 Ryan Boyce GW 24 Pick 4
5398818 Ryan Boyce GW 24 Pick 5
5398818 Ryan Boyce GW 24 Pick 6
5398818 Ryan Boyce GW 24 Pick 7
5398818 Ryan Boyce GW 24 Pick 8
5398818 Ryan Boyce GW 24 Pick 9
5398818 Ryan Boyce GW 24 Pick 10
5398818 Ryan Boyce GW 24 Pick 11
5398818 Ryan Boyce GW 24 Pick 12
5398818 Ryan Boyce GW 24 Pick 13
5398818 Ryan Boyce GW 24 Pick 14
5398818 Ryan Boyce GW 24 Pick 15
5398818 Ryan Boyce GW 25 Pick 1
5398818 Ryan Boyce GW 25 Pick 2
5398818 Ryan Boyce GW 25 Pick 3
5398818 Ryan Boyce GW 25 Pick 4
5398818 Ryan Boyce GW 25 Pick 5
5398818 Ryan Boyce GW 25 Pick 6
5398818 Ryan Boyce GW 25 Pick 7
5398818 Ryan Boyce GW 25 Pick 8
5398818 Ryan Boyce GW 25 Pick 9
5398818 Ryan Boyce GW 25 Pick 10
5398818 Ryan Boyce GW 25 Pick 11
5398818 Ryan Boyce GW 25 Pick 12
5398818 Ryan Boyce GW 25 Pick 13
5398818 Ryan Boyce GW 25 Pick 14
5398818 Ryan Boyce GW 25 Pick 15
5398818 Ryan Boyce GW 26 Pick 1
5398818 Ryan Boyce GW 26 Pick 2
5398818 Ryan Boyce GW 26 Pick 3
5398818 Ryan Boyce GW 26 Pick 4
5398818 Ryan Boyce GW 26 Pick 5
5398818 Ryan Boyce GW 26 Pick 6
5398818 Ryan Boyce GW 26 Pick 7
5398818 Ryan Boyce GW 26 Pick 8
5398818 Ryan Boyce GW 26 Pick 9
5398818 Ryan Boyce GW 26 Pick 10
5398818 Ryan Boyce GW 26 Pick 11
5398818 Ryan Boyce GW 26 Pick 12
5398818 Ryan Boyce GW 26 Pick 13
5398818 Ryan Boyce GW 26 Pick 14
5398818 Ryan Boyce GW 26 Pick 15
5398818 Ryan Boyce GW 27 Pick 1
5398818 Ryan Boyce GW 27 Pick 2
5398818 Ryan Boyce GW 27 Pick 3
5398818 Ryan Boyce GW 27 Pick 4
5398818 Ryan Boyce GW 27 Pick 5
5398818 Ryan Boyce GW 27 Pick 6
5398818 Ryan Boyce GW 27 Pick 7
5398818 Ryan Boyce GW 27 Pick 8
5398818 Ryan Boyce GW 27 Pick 9
5398818 Ryan Boyce GW 27 Pick 10
5398818 Ryan Boyce GW 27 Pick 11
5398818 Ryan Boyce GW 27 Pick 12
5398818 Ryan Boyce GW 27 Pick 13
5398818 Ryan Boyce GW 27 Pick 14
5398818 Ryan Boyce GW 27 Pick 15
5398818 Ryan Boyce GW 28 Pick 1
5398818 Ryan Boyce GW 28 Pick 2
5398818 Ryan Boyce GW 28 Pick 3
5398818 Ryan Boyce GW 28 Pick 4
5398818 Ryan Boyce GW 28 Pick 5
5398818 Ryan Boyce GW 28 Pick 6
5398818 Ryan Boyce GW 28 Pick 7
5398818 Ryan Boyce GW 28 Pick 8
5398818 Ryan Boyce GW 28 Pick 9
5398818 Ryan Boyce GW 28 Pick 10
5398818 Ryan Boyce GW 28 Pick 11
5398818 Ryan Boyce GW 28 Pick 12
5398818 Ryan Boyce GW 28 Pick 13
5398818 Ryan Boyce GW 28 Pick 14
5398818 Ryan Boyce GW 28 Pick 15
5398818 Ryan Boyce GW 29 Pick 1
5398818 Ryan Boyce GW 29 Pick 2
5398818 Ryan Boyce GW 29 Pick 3
5398818 Ryan Boyce GW 29 Pick 4
5398818 Ryan Boyce GW 29 Pick 5
5398818 Ryan Boyce GW 29 Pick 6
5398818 Ryan Boyce GW 29 Pick 7
5398818 Ryan Boyce GW 29 Pick 8
5398818 Ryan Boyce GW 29 Pick 9
5398818 Ryan Boyce GW 29 Pick 10
5398818 Ryan Boyce GW 29 Pick 11
5398818 Ryan Boyce GW 29 Pick 12
5398818 Ryan Boyce GW 29 Pick 13
5398818 Ryan Boyce GW 29 Pick 14
5398818 Ryan Boyce GW 29 Pick 15
5398818 Ryan Boyce GW 30 Pick 1
5398818 Ryan Boyce GW 30 Pick 2
5398818 Ryan Boyce GW 30 Pick 3
5398818 Ryan Boyce GW 30 Pick 4
5398818 Ryan Boyce GW 30 Pick 5
5398818 Ryan Boyce GW 30 Pick 6
5398818 Ryan Boyce GW 30 Pick 7
5398818 Ryan Boyce GW 30 Pick 8
5398818 Ryan Boyce GW 30 Pick 9
5398818 Ryan Boyce GW 30 Pick 10
5398818 Ryan Boyce GW 30 Pick 11
5398818 Ryan Boyce GW 30 Pick 12
5398818 Ryan Boyce GW 30 Pick 13
5398818 Ryan Boyce GW 30 Pick 14
5398818 Ryan Boyce GW 30 Pick 15
5398818 Ryan Boyce GW 31 Pick 1
5398818 Ryan Boyce GW 31 Pick 2
5398818 Ryan Boyce GW 31 Pick 3
5398818 Ryan Boyce GW 31 Pick 4
5398818 Ryan Boyce GW 31 Pick 5
5398818 Ryan Boyce GW 31 Pick 6
5398818 Ryan Boyce GW 31 Pick 7
5398818 Ryan Boyce GW 31 Pick 8
5398818 Ryan Boyce GW 31 Pick 9
5398818 Ryan Boyce GW 31 Pick 10
5398818 Ryan Boyce GW 31 Pick 11
5398818 Ryan Boyce GW 31 Pick 12
5398818 Ryan Boyce GW 31 Pick 13
5398818 Ryan Boyce GW 31 Pick 14
5398818 Ryan Boyce GW 31 Pick 15
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW32 to GW36

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Nico O'Reilly,a,0,DEF,Man City,1081.2,5.74,77.3,0.248,0.062,0.920
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1081.8,5.18,84.4,0.069,0.128,0.851
2,Jurriën Timber,a,0,DEF,Arsenal,1081.8,5.05,78.2,0.103,0.078,0.878
3,Bruno Borges Fernandes,a,1,MID,Man Utd,1072.5,4.98,78.8,0.228,0.228,1.197
4,Antoine Semenyo,a,0,MID,Man City,1081.2,4.90,82.5,0.245,0.173,1.051
5,Piero Hincapié,a,0,DEF,Arsenal,1081.8,4.87,72.3,0.060,0.063,0.792
6,Matheus Nunes,a,1,DEF,Man City,1081.2,4.80,84.0,0.042,0.089,0.953
7,William Saliba,a,0,DEF,Arsenal,1081.8,4.76,81.9,0.053,0.062,0.899
8,John Stones,a,0,DEF,Man City,1081.2,4.75,57.4,0.355,0.146,1.423
9,Cole Palmer,a,0,MID,Chelsea,1120.3,4.70,83.3,0.229,0.174,1.447
10,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1072.5,4.68,84.1,0.212,0.133,1.171
11,Lucas Digne,a,0,DEF,Aston Villa,990.3,4.67,75.1,0.049,0.066,0.897
12,Marc Guéhi,a,0,DEF,Man City,1081.2,4.61,84.3,0.045,0.046,0.984
13,Dominik Szoboszlai,a,1,MID,Liverpool,1079.3,4.61,86.6,0.167,0.196,1.676
14,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1049.8,4.60,84.4,0.207,0.139,1.300
15,Declan Rice,a,0,MID,Arsenal,1081.8,4.58,81.9,0.155,0.192,0.934
16,Ezri Konsa Ngoyo,a,0,DEF,Aston Villa,990.3,4.57,87.1,0.048,0.050,1.037
17,Bruno Guimarães Rodriguez Moura,d,0,MID,Newcastle,1097.2,4.57,60.2,0.456,0.180,1.526
18,Matty Cash,a,0,DEF,Aston Villa,990.3,4.56,76.8,0.045,0.055,0.932
19,Alexis Mac Allister,a,1,MID,Liverpool,1079.3,4.56,85.8,0.191,0.156,1.580
20,Pau Torres,a,0,DEF,Aston Villa,990.3,4.54,81.0,0.045,0.040,0.976
21,Carlos Henrique Casimiro,a,0,MID,Man Utd,1072.5,4.52,82.0,0.198,0.130,1.144
22,Jan Paul van Hecke,a,1,DEF,Brighton,996.2,4.51,86.5,0.043,0.051,1.048
23,Jaidon Anthony,a,0,MID,Burnley,1090.9,4.51,83.1,0.255,0.119,1.992
24,Morgan Rogers,a,0,MID,Aston Villa,990.3,4.49,82.2,0.174,0.155,1.132
25,Rúben dos Santos Gato Alves Dias,a,0,DEF,Man City,1081.2,4.49,78.4,0.053,0.050,1.030
26,Ferdi Kadıoğlu,a,0,DEF,Brighton,996.2,4.48,86.9,0.044,0.052,1.070
27,Lamare Bogarde,a,0,DEF,Aston Villa,990.3,4.45,69.4,0.041,0.060,0.925
28,Amadou Onana,a,0,MID,Aston Villa,990.3,4.45,80.9,0.177,0.149,1.105
29,Benjamin White,a,0,DEF,Arsenal,1081.8,4.44,59.5,0.265,0.061,1.222
30,Cody Gakpo,a,0,MID,Liverpool,1079.3,4.44,78.6,0.193,0.154,1.400
31,Eberechi Eze,a,0,MID,Arsenal,1081.8,4.43,73.4,0.207,0.154,0.932
32,Erling Haaland,a,0,FWD,Man City,1081.2,4.43,80.3,0.408,0.087,1.157
33,Enzo Fernández,a,0,MID,Chelsea,1120.3,4.42,83.8,0.173,0.161,1.436
34,Iliman Ndiaye,a,0,MID,Everton,1097.3,4.42,86.0,0.176,0.129,1.344
35,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,1090.0,4.42,81.3,0.420,0.071,1.439
36,Martín Zubimendi Ibáñez,a,0,MID,Arsenal,1081.8,4.41,79.8,0.155,0.148,0.965
37,Harry Wilson,a,0,MID,Fulham,1136.8,4.40,83.4,0.198,0.119,1.390
38,Diego Gómez Amarilla,a,0,MID,Brighton,996.2,4.39,80.3,0.177,0.118,1.023
39,Bukayo Saka,a,0,MID,Arsenal,1081.8,4.37,73.0,0.193,0.163,0.968
40,Anthony Gordon,a,0,MID,Newcastle,1097.2,4.36,83.4,0.180,0.123,1.267
41,Pascal Groß,a,0,MID,Brighton,996.2,4.35,84.7,0.099,0.174,1.053
42,Anton Stach,a,0,MID,Leeds,994.0,4.35,85.0,0.156,0.149,1.159
43,Mathias Jensen,a,1,MID,Brentford,1090.0,4.35,86.2,0.163,0.129,1.507
44,Florian Wirtz,a,0,MID,Liverpool,1079.3,4.34,75.3,0.166,0.195,1.359
45,Jack Hinshelwood,a,0,MID,Brighton,996.2,4.32,73.2,0.204,0.123,1.051
46,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1081.2,4.32,79.0,0.127,0.166,0.952
47,Tyrone Mings,a,1,DEF,Aston Villa,990.3,4.31,76.9,0.042,0.052,1.063
48,Alex Iwobi,a,0,MID,Fulham,1136.8,4.31,85.7,0.166,0.126,1.412
49,Abdukodir Khusanov,a,0,DEF,Man City,1081.2,4.31,66.2,0.041,0.054,0.947

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 32 and 36:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Nico O'Reilly,a,DEF,Man City,5.1,1081.2,28.88,77.3,0.248,0.062,0.920
1,Gabriel dos Santos Magalhães,a,DEF,Arsenal,7.2,1081.8,26.19,84.4,0.069,0.128,0.851
2,Jurriën Timber,a,DEF,Arsenal,6.3,1081.8,25.54,78.2,0.103,0.078,0.878
3,Bruno Borges Fernandes,a,MID,Man Utd,10.2,1072.5,24.80,78.8,0.228,0.228,1.197
4,Antoine Semenyo,a,MID,Man City,8.3,1081.2,24.66,82.5,0.245,0.173,1.051
5,Piero Hincapié,a,DEF,Arsenal,5.1,1081.8,24.39,72.3,0.060,0.063,0.792
6,Matheus Nunes,a,DEF,Man City,5.4,1081.2,24.27,84.0,0.042,0.089,0.953
7,William Saliba,a,DEF,Arsenal,6.1,1081.8,24.13,81.9,0.053,0.062,0.899
8,John Stones,a,DEF,Man City,5.4,1081.2,24.11,57.4,0.355,0.146,1.423
9,Lucas Digne,a,DEF,Aston Villa,4.5,990.3,23.67,75.1,0.049,0.066,0.897
10,Cole Palmer,a,MID,Chelsea,10.6,1120.3,23.64,83.3,0.229,0.174,1.447
11,Matheus Santos Carneiro da Cunha,a,MID,Man Utd,8.0,1072.5,23.36,84.1,0.212,0.133,1.171
12,Marc Guéhi,a,DEF,Man City,5.2,1081.2,23.27,84.3,0.045,0.046,0.984
13,Ezri Konsa Ngoyo,a,DEF,Aston Villa,4.4,990.3,23.13,87.1,0.048,0.050,1.037
14,Matty Cash,a,DEF,Aston Villa,4.7,990.3,23.09,76.8,0.045,0.055,0.932
15,Declan Rice,a,MID,Arsenal,7.4,1081.8,23.08,81.9,0.155,0.192,0.934
16,Pau Torres,a,DEF,Aston Villa,4.3,990.3,22.96,81.0,0.045,0.040,0.976
17,Bruno Guimarães Rodriguez Moura,d,MID,Newcastle,6.8,1097.2,22.92,60.2,0.456,0.180,1.526
18,Morgan Gibbs-White,a,MID,Nott'm Forest,7.4,1049.8,22.87,84.4,0.207,0.139,1.300
19,Dominik Szoboszlai,a,MID,Liverpool,7.0,1079.3,22.85,86.6,0.167,0.196,1.676

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0                 Ryan Boyce  5398818.0        1778.0
1              Bernard Chalk  1557117.0        1757.0
2         Christopher Harris    28660.0        1706.0
3          William Partridge  6588565.0        1703.0
4               Samia Shelim  6506490.0        1681.0
5               Jack Carroll  4438260.0        1675.0
6               Tommy Davies  7845816.0        1661.0
7         Christopher Harris   145486.0        1660.0
8              Ollie Carroll  5181285.0        1638.0
9                 Rhys Birdy  5810139.0        1630.0
10             Rizwan Shelim  3058994.0        1627.0
11               Nafi Shelim  4776281.0        1596.0
12            Conner Harling  3421093.0        1591.0
13             Tajwar Shelim  4773459.0        1550.0
14  Christakis Christodoulou  7474864.0        1502.0
15              Tahmid Haque  6394829.0        1458.0
16            Charlie Garner  9432680.0        1448.0
17              Will Hossack  4792527.0        1434.0
18               Simon Meech  6764382.0        1427.0
19              Holly Stower  7367977.0        1349.0
20            Rachel Aumayer  9763056.0        1186.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW32 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
213,1,5.0,Gabriel dos Santos Magalhães,a,7.2,DEF,Arsenal,37.508338,0.0,37.508338,0.000000,37.508338,0.0,37.508338,37.508338,37.508338
207,1,8.0,Jurriën Timber,a,6.3,DEF,Arsenal,36.616321,0.0,36.616321,0.000000,36.616321,0.0,36.616321,36.616321,36.616321
186,1,235.0,Cole Palmer,a,10.6,MID,Chelsea,33.466158,0.0,33.466158,0.000000,33.466158,0.0,33.466158,33.466158,33.466158
24,1,237.0,Enzo Fernández,a,6.6,MID,Chelsea,31.457024,0.0,31.457024,0.000000,31.457024,0.0,31.457024,31.457024,31.457024
441,1,384.0,Cody Gakpo,a,7.3,MID,Liverpool,30.731817,0.0,30.731817,0.000000,30.731817,0.0,30.731817,30.731817,30.731817
302,1,38.0,Ezri Konsa Ngoyo,a,4.4,DEF,Aston Villa,30.164205,0.0,30.164205,0.000000,30.164205,0.0,30.164205,30.164205,30.164205
185,1,691.0,Dominic Calvert-Lewin,a,5.6,FWD,Leeds,27.743578,0.0,27.743578,0.000000,27.743578,0.0,27.743578,27.743578,27.743578
348,1,32.0,Emiliano Martínez Romero,a,5.1,GK,Aston Villa,27.428759,0.0,27.428759,0.000000,27.428759,0.0,27.428759,27.428759,27.428759
43,1,341.0,Karl Darlow,a,3.9,GK,Leeds,26.737716,0.0,26.737716,0.000000,26.737716,0.0,26.737716,26.737716,26.737716
6,1,337.0,Raúl Jiménez Rodríguez,a,6.2,FWD,Fulham,20.617245,0.0,20.617245,0.000000,20.617245,0.0,20.617245,20.617245,20.617245
346,1,694.0,Nordi Mukiele,a,4.5,DEF,Sunderland,23.478272,20.0,18.782617,-4.695654,18.782617,0.0,14.086963,18.782617,18.782617
136,1,373.0,Virgil van Dijk,a,6.3,DEF,Liverpool,27.956977,60.0,11.182791,-16.774186,11.182791,0.0,-5.591395,11.182791,11.182791
219,1,661.0,Hugo Ekitiké,a,9.2,FWD,Liverpool,18.562303,40.0,11.137382,-7.424921,11.137382,0.0,3.712461,11.137382,11.137382
385,1,329.0,Harry Wilson,a,6.0,MID,Fulham,31.402910,80.0,6.280582,-25.122328,6.280582,0.0,-18.841746,6.280582,6.280582
339,1,449.0,Bruno Borges Fernandes,a,10.2,MID,Man Utd,34.810695,160.0,-20.886417,-55.697112,-20.886417,0.0,-76.583529,-20.886417,-20.886417

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW32 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
339,1,449.0,Bruno Borges Fernandes,a,10.2,MID,Man Utd,34.810695,160.0,-20.886417,-55.697112,-20.886417,0.000000,-76.583529,-20.886417,-20.886417
196,0,430.0,Erling Haaland,a,14.6,FWD,Man City,30.773053,60.0,12.309221,-18.463832,0.000000,-18.463832,-6.154611,-18.463832,12.309221
126,0,249.0,João Pedro Junqueira de Jesus,a,7.8,FWD,Chelsea,29.458700,60.0,11.783480,-17.675220,0.000000,-17.675220,-5.891740,-17.675220,11.783480
119,0,684.0,Malick Thiaw,a,5.1,DEF,Newcastle,27.066689,60.0,10.826675,-16.240013,0.000000,-16.240013,-5.413338,-16.240013,10.826675
9,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,26.430494,60.0,10.572197,-15.858296,0.000000,-15.858296,-5.286099,-15.858296,10.572197
440,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.3,FWD,Brentford,30.849072,40.0,18.509443,-12.339629,0.000000,-12.339629,6.169814,-12.339629,18.509443
95,0,485.0,Anthony Gordon,a,7.3,MID,Newcastle,30.797210,40.0,18.478326,-12.318884,0.000000,-12.318884,6.159442,-12.318884,18.478326
241,0,119.0,Bryan Mbeumo,a,8.6,MID,Man Utd,29.613163,40.0,17.767898,-11.845265,0.000000,-11.845265,5.922633,-11.845265,17.767898
105,0,317.0,Joachim Andersen,a,4.6,DEF,Fulham,26.384583,40.0,15.830750,-10.553833,0.000000,-10.553833,5.276917,-10.553833,15.830750
190,0,191.0,Maxime Estève,a,3.9,DEF,Burnley,21.000538,40.0,12.600323,-8.400215,0.000000,-8.400215,4.200108,-8.400215,12.600323
426,0,82.0,Antoine Semenyo,a,8.3,MID,Man City,34.410711,20.0,27.528569,-6.882142,0.000000,-6.882142,20.646427,-6.882142,27.528569
415,0,21.0,Declan Rice,a,7.4,MID,Arsenal,32.810843,20.0,26.248674,-6.562169,0.000000,-6.562169,19.686506,-6.562169,26.248674
98,0,387.0,Dominik Szoboszlai,a,7.0,MID,Liverpool,31.843592,20.0,25.474874,-6.368718,0.000000,-6.368718,19.106155,-6.368718,25.474874
343,0,457.0,Carlos Henrique Casimiro,a,5.7,MID,Man Utd,31.579742,20.0,25.263793,-6.315948,0.000000,-6.315948,18.947845,-6.315948,25.263793
272,0,16.0,Bukayo Saka,a,9.8,MID,Arsenal,31.225856,20.0,24.980685,-6.245171,0.000000,-6.245171,18.735514,-6.245171,24.980685
31,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,30.964126,20.0,24.771301,-6.192825,0.000000,-6.192825,18.578475,-6.192825,24.771301
342,0,382.0,Florian Wirtz,a,8.3,MID,Liverpool,30.097526,20.0,24.078021,-6.019505,0.000000,-6.019505,18.058515,-6.019505,24.078021
92,0,348.0,Joe Rodon,a,3.9,DEF,Leeds,29.050089,20.0,23.240071,-5.810018,0.000000,-5.810018,17.430054,-5.810018,23.240071
45,0,683.0,Omar Alderete,a,4.1,DEF,Sunderland,28.886208,20.0,23.108967,-5.777242,0.000000,-5.777242,17.331725,-5.777242,23.108967
57,0,291.0,James Tarkowski,a,5.7,DEF,Everton,28.581626,20.0,22.865301,-5.716325,0.000000,-5.716325,17.148975,-5.716325,22.865301

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW32 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
36,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,39.985607,0.0,39.985607,0.0,0.0,0.0,39.985607,0.0,39.985607
277,0,6.0,William Saliba,a,6.1,DEF,Arsenal,34.918714,0.0,34.918714,0.0,0.0,0.0,34.918714,0.0,34.918714
303,0,725.0,Piero Hincapié,a,5.1,DEF,Arsenal,34.771409,0.0,34.771409,0.0,0.0,0.0,34.771409,0.0,34.771409
166,0,409.0,John Stones,a,5.4,DEF,Man City,33.593554,0.0,33.593554,0.0,0.0,0.0,33.593554,0.0,33.593554
118,0,407.0,Matheus Nunes,a,5.4,DEF,Man City,33.479781,0.0,33.479781,0.0,0.0,0.0,33.479781,0.0,33.479781
162,0,11.0,Benjamin White,a,5.1,DEF,Arsenal,32.915887,0.0,32.915887,0.0,0.0,0.0,32.915887,0.0,32.915887
298,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,32.762265,0.0,32.762265,0.0,0.0,0.0,32.762265,0.0,32.762265
357,0,488.0,Bruno Guimarães Rodriguez Moura,d,6.8,MID,Newcastle,32.355621,0.0,32.355621,0.0,0.0,0.0,32.355621,0.0,32.355621
128,0,260.0,Marc Guéhi,a,5.2,DEF,Man City,32.152762,0.0,32.152762,0.0,0.0,0.0,32.152762,0.0,32.152762
317,0,200.0,Jaidon Anthony,a,5.0,MID,Burnley,31.830386,0.0,31.830386,0.0,0.0,0.0,31.830386,0.0,31.830386
5,0,515.0,Morgan Gibbs-White,a,7.4,MID,Nott'm Forest,31.736666,0.0,31.736666,0.0,0.0,0.0,31.736666,0.0,31.736666
392,0,26.0,Martín Zubimendi Ibáñez,a,5.2,MID,Arsenal,31.700231,0.0,31.700231,0.0,0.0,0.0,31.700231,0.0,31.700231
292,0,266.0,Eberechi Eze,a,7.2,MID,Arsenal,31.610267,0.0,31.610267,0.0,0.0,0.0,31.610267,0.0,31.610267
173,0,386.0,Alexis Mac Allister,a,6.3,MID,Liverpool,31.595664,0.0,31.595664,0.0,0.0,0.0,31.595664,0.0,31.595664
264,0,408.0,Rúben dos Santos Gato Alves Dias,a,5.5,DEF,Man City,31.425988,0.0,31.425988,0.0,0.0,0.0,31.425988,0.0,31.425988
153,0,151.0,Jan Paul van Hecke,a,4.4,DEF,Brighton,31.318266,0.0,31.318266,0.0,0.0,0.0,31.318266,0.0,31.318266
336,0,299.0,Iliman Ndiaye,a,6.2,MID,Everton,31.235900,0.0,31.235900,0.0,0.0,0.0,31.235900,0.0,31.235900
37,0,7.0,Riccardo Calafiori,a,5.6,DEF,Arsenal,30.986200,0.0,30.986200,0.0,0.0,0.0,30.986200,0.0,30.986200
150,0,148.0,Ferdi Kadıoğlu,a,4.4,DEF,Brighton,30.948723,0.0,30.948723,0.0,0.0,0.0,30.948723,0.0,30.948723
113,0,324.0,Alex Iwobi,a,6.4,MID,Fulham,30.882570,0.0,30.882570,0.0,0.0,0.0,30.882570,0.0,30.882570

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £101.5m / £102.4m
Total Weighted Expected Points: 276.61
Remaining Budget: £0.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Walter Benítez                 Crystal Palace £4.0    20.13
 ✅        Emiliano Martínez Romero       Aston Villa  £5.1    20.37

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1    28.88
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2    26.19
 ✅        Jurriën Timber                 Arsenal      £6.3    25.54
 ✅        Piero Hincapié                 Arsenal      £5.1    24.39
 ✅        Matheus Nunes                  Man City     £5.4    24.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Jaidon Anthony                 Burnley      £5.0    22.56
 ✅        Bruno Borges Fernandes         Man Utd      £10.2   24.80
 ✅        Antoine Semenyo                Man City     £8.3    24.66
 ✅        Cole Palmer                    Chelsea      £10.6   23.64
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0    23.36

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8    20.92
 🪑        Danny Welbeck                  Brighton     £6.1    20.83
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3    22.07

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £92.2m / £102.4m
Total Weighted Expected Points: 381.74
Remaining Budget: £10.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Walter Benítez                 Crystal Palace £4.0    27.47
 ✅        Bart Verbruggen                Brighton     £4.5    28.01

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1    39.99
 ✅        John Stones                    Man City     £5.4    33.59
 ✅        Jurriën Timber                 Arsenal      £6.3    36.62
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2    37.51
 ✅        William Saliba                 Arsenal      £6.1    34.92

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Morgan Gibbs-White             Nott'm Forest £7.4    31.74
 ✅        Cole Palmer                    Chelsea      £10.6   33.47
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0    32.76
 ✅        Jaidon Anthony                 Burnley      £5.0    31.83
 ✅        Bruno Guimarães Rodriguez Moura Newcastle    £6.8    32.36

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Marc Guiu Paz                  Chelsea      £4.1    27.66
 🪑        Dominic Calvert-Lewin          Leeds        £5.6    27.74
 ✅        Danny Welbeck                  Brighton     £6.1    29.23

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,34.0,Nico O'Reilly,a,DEF,Man City,Burnley,5.1,6.928933
1,37.0,Gabriel dos Santos Magalhães,a,DEF,Arsenal,Burnley,7.2,6.156369
2,34.0,Matheus Nunes,a,DEF,Man City,Burnley,5.4,6.123129
3,37.0,Jurriën Timber,a,DEF,Arsenal,Burnley,6.3,5.990774
4,37.0,William Saliba,a,DEF,Arsenal,Burnley,6.1,5.876919
5,34.0,Marc Guéhi,a,DEF,Man City,Burnley,5.2,5.793475
6,36.0,Gabriel dos Santos Magalhães,a,DEF,Arsenal,West Ham,7.2,5.699502
7,34.0,Rúben dos Santos Gato Alves Dias,a,DEF,Man City,Burnley,5.5,5.698612
8,34.0,John Stones,a,DEF,Man City,Burnley,5.4,5.665806
9,37.0,Benjamin White,a,DEF,Arsenal,Burnley,5.1,5.640199

In [17]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW32 to GW38...

Optimizing team selection for GW32...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £98.4m / £102.4m
Total Weighted Expected Points: 55.17
Remaining Budget: £4.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emiliano Martínez Romero       Aston Villa  £5.1     4.05
 ✅        Melker Ellborg                 Sunderland   £4.0     4.29

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     5.54
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.20
 ✅        Jurriën Timber                 Arsenal      £6.3     5.03
 ✅        Piero Hincapié                 Arsenal      £5.1     4.92
 ✅        John Stones                    Man City     £5.4     4.69

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Pascal Groß                    Brighton     £5.5     4.65
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    5.20
 ✅        Antoine Semenyo                Man City     £8.3     4.83
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.71
 ✅        Dominik Szoboszlai             Liverpool    £7.0     4.67

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.1     4.15
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.06
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.40

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £99.0m / £102.4m
Total Weighted Expected Points: 54.32
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Angus Gunn                     Nott'm Forest £4.0     4.09
 ✅        Bart Verbruggen                Brighton     £4.5     4.15

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     5.31
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     4.92
 ✅        Jurriën Timber                 Arsenal      £6.3     4.86
 ✅        Piero Hincapié                 Arsenal      £5.1     4.79
 ✅        Jan Paul van Hecke             Brighton     £4.4     4.68

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.67
 ✅        Morgan Gibbs-White             Nott'm Forest £7.4     5.20
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    4.81
 ✅        Cole Palmer                    Chelsea      £10.6    4.74
 ✅        Jaidon Anthony                 Burnley      £5.0     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.23
 🪑        Danny Welbeck                  Brighton     £6.1     4.14
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.44

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £100.8m / £102.4m
Total Weighted Expected Points: 58.45
Remaining Budget: £1.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Melker Ellborg                 Sunderland   £4.0     3.98
 ✅        Walter Benítez                 Crystal Palace £4.0     4.20

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     6.93
 ✅        Matheus Nunes                  Man City     £5.4     6.12
 ✅        Marc Guéhi                     Man City     £5.2     5.79
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.21
 ✅        Jurriën Timber                 Arsenal      £6.3     5.04

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Alexis Mac Allister            Liverpool    £6.3     4.63
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    4.89
 ✅        Cole Palmer                    Chelsea      £10.6    4.76
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.68
 ✅        Dominik Szoboszlai             Liverpool    £7.0     4.67

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gabriel Fernando de Jesus      Arsenal      £6.4     4.21
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.20
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.45

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £98.2m / £102.4m
Total Weighted Expected Points: 55.35
Remaining Budget: £4.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emiliano Martínez Romero       Aston Villa  £5.1     4.19
 ✅        Melker Ellborg                 Sunderland   £4.0     4.26

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Nico O'Reilly                  Man City     £5.1     5.54
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.16
 ✅        Jurriën Timber                 Arsenal      £6.3     5.09
 ✅        William Saliba                 Arsenal      £6.1     4.91
 ✅        Ezri Konsa Ngoyo               Aston Villa  £4.4     4.88

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Anton Stach                    Leeds        £4.7     4.66
 ✅        Antoine Semenyo                Man City     £8.3     4.92
 ✅        Cole Palmer                    Chelsea      £10.6    4.90
 ✅        Jaidon Anthony                 Burnley      £5.0     4.78
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    4.72

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.22
 🪑        Danny Welbeck                  Brighton     £6.1     4.20
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.46

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £100.8m / £102.4m
Total Weighted Expected Points: 57.08
Remaining Budget: £1.6m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bart Verbruggen                Brighton     £4.5     4.09
 ✅        Emiliano Martínez Romero       Aston Villa  £5.1     4.29

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.70
 ✅        Nico O'Reilly                  Man City     £5.1     5.55
 ✅        Jurriën Timber                 Arsenal      £6.3     5.51
 ✅        William Saliba                 Arsenal      £6.1     5.26
 ✅        Lucas Digne                    Aston Villa  £4.5     5.23

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.67
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    5.18
 ✅        Antoine Semenyo                Man City     £8.3     4.92
 ✅        Bruno Guimarães Rodriguez Moura Newcastle    £6.8     4.73
 ✅        Morgan Rogers                  Aston Villa  £7.5     4.68

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.20
 🪑        Danny Welbeck                  Brighton     £6.1     4.14
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.32

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £102.2m / £102.4m
Total Weighted Expected Points: 58.96
Remaining Budget: £0.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bernd Leno                     Fulham       £4.9     3.99
 ✅        Bart Verbruggen                Brighton     £4.5     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        John Stones                    Man City     £5.4     4.86
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     6.16
 ✅        Jurriën Timber                 Arsenal      £6.3     5.99
 ✅        William Saliba                 Arsenal      £6.1     5.88
 ✅        Nico O'Reilly                  Man City     £5.1     5.57

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    5.21
 ✅        Cole Palmer                    Chelsea      £10.6    5.01
 ✅        Harry Wilson                   Fulham       £6.0     4.95
 ✅        Alex Iwobi                     Fulham       £6.4     4.94
 ✅        Antoine Semenyo                Man City     £8.3     4.93

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.33
 🪑        Danny Welbeck                  Brighton     £6.1     4.20
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.44

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £102.0m / £102.4m
Total Weighted Expected Points: 54.80
Remaining Budget: £0.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Caoimhín Kelleher              Brentford    £4.8     3.96
 ✅        Robert Lynch Sánchez           Chelsea      £4.8     3.99

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matt Doherty                   Wolves       £4.4     4.63
 ✅        Nico O'Reilly                  Man City     £5.1     5.54
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.2     5.16
 ✅        Jurriën Timber                 Arsenal      £6.3     5.09
 ✅        William Saliba                 Arsenal      £6.1     4.91

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Jaidon Anthony                 Burnley      £5.0     4.96
 ✅        Antoine Semenyo                Man City     £8.3     4.82
 ✅        Cole Palmer                    Chelsea      £10.6    4.82
 ✅        Bruno Borges Fernandes         Man Utd      £10.2    4.80
 ✅        Matheus Santos Carneiro da Cunha Man Utd      £8.0     4.67

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        João Pedro Junqueira de Jesus  Chelsea      £7.8     4.21
 🪑        Danny Welbeck                  Brighton     £6.1     4.20
 ✅        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.35

================================================================================
Optimization Status: Optimal

In [18]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 37

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
59,37,Bruno Borges Fernandes,a,MID,Man Utd,Nott'm Forest,10.2,5.212862
60,37,Cole Palmer,a,MID,Chelsea,Spurs,10.6,5.014195
61,37,Harry Wilson,a,MID,Fulham,Wolves,6.0,4.952085
62,37,Alex Iwobi,a,MID,Fulham,Wolves,6.4,4.942595
63,37,Antoine Semenyo,a,MID,Man City,Bournemouth,8.3,4.926753
65,37,Bart Verbruggen,a,GK,Brighton,Leeds,4.5,4.140917
64,37,Igor Thiago Nascimento Rodrigues,a,FWD,Brentford,Crystal Palace,7.3,4.436131
55,37,Gabriel dos Santos Magalhães,a,DEF,Arsenal,Burnley,7.2,6.156369
56,37,Jurriën Timber,a,DEF,Arsenal,Burnley,6.3,5.990774
57,37,William Saliba,a,DEF,Arsenal,Burnley,6.1,5.876919
58,37,Nico O'Reilly,a,DEF,Man City,Bournemouth,5.1,5.571109

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)