In [1]:
import pandas as pd
import time
#other requirements: pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 33
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1446916"
season=20252026

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = "divx_picks"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  Riverside International League
Fetched history for Bernard Chalk (ID: 1557117)
Fetched history for Ryan Boyce (ID: 5398818)
Fetched history for Samia Shelim (ID: 6506490)
Fetched history for Christopher Harris (ID: 28660)
Fetched history for Tommy Davies (ID: 7845816)
Fetched history for William Partridge (ID: 6588565)
Fetched history for Jack Carroll (ID: 4438260)
Fetched history for Christopher Harris (ID: 145486)
Fetched history for Rhys Birdy (ID: 5810139)
Fetched history for Rizwan Shelim (ID: 3058994)
Fetched history for Ollie Carroll (ID: 5181285)
Fetched history for Nafi Shelim (ID: 4776281)
Fetched history for Conner Harling (ID: 3421093)
Fetched history for Tajwar Shelim (ID: 4773459)
Fetched history for Christakis Christodoulou (ID: 7474864)
Fetched history for Tahmid Haque (ID: 6394829)
Fetched history for Charlie Garner (ID: 9432680)
Fetched history for Will Hossack (ID: 4792527)
Fetched history for Simon Meech (ID: 6764382)
Fetched history for Holly Stower (ID: 7367977)
Fetched history for Rachel Aumayer (ID: 9763056)
Max gameweek data available for is:  34
1557117 Bernard Chalk GW 1 Pick 1
1557117 Bernard Chalk GW 1 Pick 2
1557117 Bernard Chalk GW 1 Pick 3
1557117 Bernard Chalk GW 1 Pick 4
1557117 Bernard Chalk GW 1 Pick 5
1557117 Bernard Chalk GW 1 Pick 6
1557117 Bernard Chalk GW 1 Pick 7
1557117 Bernard Chalk GW 1 Pick 8
1557117 Bernard Chalk GW 1 Pick 9
1557117 Bernard Chalk GW 1 Pick 10
1557117 Bernard Chalk GW 1 Pick 11
1557117 Bernard Chalk GW 1 Pick 12
1557117 Bernard Chalk GW 1 Pick 13
1557117 Bernard Chalk GW 1 Pick 14
1557117 Bernard Chalk GW 1 Pick 15
1557117 Bernard Chalk GW 2 Pick 1
1557117 Bernard Chalk GW 2 Pick 2
1557117 Bernard Chalk GW 2 Pick 3
1557117 Bernard Chalk GW 2 Pick 4
1557117 Bernard Chalk GW 2 Pick 5
1557117 Bernard Chalk GW 2 Pick 6
1557117 Bernard Chalk GW 2 Pick 7
1557117 Bernard Chalk GW 2 Pick 8
1557117 Bernard Chalk GW 2 Pick 9
1557117 Bernard Chalk GW 2 Pick 10
1557117 Bernard Chalk GW 2 Pick 11
1557117 Bernard Chalk GW 2 Pick 12
1557117 Bernard Chalk GW 2 Pick 13
1557117 Bernard Chalk GW 2 Pick 14
1557117 Bernard Chalk GW 2 Pick 15
1557117 Bernard Chalk GW 3 Pick 1
1557117 Bernard Chalk GW 3 Pick 2
1557117 Bernard Chalk GW 3 Pick 3
1557117 Bernard Chalk GW 3 Pick 4
1557117 Bernard Chalk GW 3 Pick 5
1557117 Bernard Chalk GW 3 Pick 6
1557117 Bernard Chalk GW 3 Pick 7
1557117 Bernard Chalk GW 3 Pick 8
1557117 Bernard Chalk GW 3 Pick 9
1557117 Bernard Chalk GW 3 Pick 10
1557117 Bernard Chalk GW 3 Pick 11
1557117 Bernard Chalk GW 3 Pick 12
1557117 Bernard Chalk GW 3 Pick 13
1557117 Bernard Chalk GW 3 Pick 14
1557117 Bernard Chalk GW 3 Pick 15
1557117 Bernard Chalk GW 4 Pick 1
1557117 Bernard Chalk GW 4 Pick 2
1557117 Bernard Chalk GW 4 Pick 3
1557117 Bernard Chalk GW 4 Pick 4
1557117 Bernard Chalk GW 4 Pick 5
1557117 Bernard Chalk GW 4 Pick 6
1557117 Bernard Chalk GW 4 Pick 7
1557117 Bernard Chalk GW 4 Pick 8
1557117 Bernard Chalk GW 4 Pick 9
1557117 Bernard Chalk GW 4 Pick 10
1557117 Bernard Chalk GW 4 Pick 11
1557117 Bernard Chalk GW 4 Pick 12
1557117 Bernard Chalk GW 4 Pick 13
1557117 Bernard Chalk GW 4 Pick 14
1557117 Bernard Chalk GW 4 Pick 15
1557117 Bernard Chalk GW 5 Pick 1
1557117 Bernard Chalk GW 5 Pick 2
1557117 Bernard Chalk GW 5 Pick 3
1557117 Bernard Chalk GW 5 Pick 4
1557117 Bernard Chalk GW 5 Pick 5
1557117 Bernard Chalk GW 5 Pick 6
1557117 Bernard Chalk GW 5 Pick 7
1557117 Bernard Chalk GW 5 Pick 8
1557117 Bernard Chalk GW 5 Pick 9
1557117 Bernard Chalk GW 5 Pick 10
1557117 Bernard Chalk GW 5 Pick 11
1557117 Bernard Chalk GW 5 Pick 12
1557117 Bernard Chalk GW 5 Pick 13
1557117 Bernard Chalk GW 5 Pick 14
1557117 Bernard Chalk GW 5 Pick 15
1557117 Bernard Chalk GW 6 Pick 1
1557117 Bernard Chalk GW 6 Pick 2
1557117 Bernard Chalk GW 6 Pick 3
1557117 Bernard Chalk GW 6 Pick 4
1557117 Bernard Chalk GW 6 Pick 5
1557117 Bernard Chalk GW 6 Pick 6
1557117 Bernard Chalk GW 6 Pick 7
1557117 Bernard Chalk GW 6 Pick 8
1557117 Bernard Chalk GW 6 Pick 9
1557117 Bernard Chalk GW 6 Pick 10
1557117 Bernard Chalk GW 6 Pick 11
1557117 Bernard Chalk GW 6 Pick 12
1557117 Bernard Chalk GW 6 Pick 13
1557117 Bernard Chalk GW 6 Pick 14
1557117 Bernard Chalk GW 6 Pick 15
1557117 Bernard Chalk GW 7 Pick 1
1557117 Bernard Chalk GW 7 Pick 2
1557117 Bernard Chalk GW 7 Pick 3
1557117 Bernard Chalk GW 7 Pick 4
1557117 Bernard Chalk GW 7 Pick 5
1557117 Bernard Chalk GW 7 Pick 6
1557117 Bernard Chalk GW 7 Pick 7
1557117 Bernard Chalk GW 7 Pick 8
1557117 Bernard Chalk GW 7 Pick 9
1557117 Bernard Chalk GW 7 Pick 10
1557117 Bernard Chalk GW 7 Pick 11
1557117 Bernard Chalk GW 7 Pick 12
1557117 Bernard Chalk GW 7 Pick 13
1557117 Bernard Chalk GW 7 Pick 14
1557117 Bernard Chalk GW 7 Pick 15
1557117 Bernard Chalk GW 8 Pick 1
1557117 Bernard Chalk GW 8 Pick 2
1557117 Bernard Chalk GW 8 Pick 3
1557117 Bernard Chalk GW 8 Pick 4
1557117 Bernard Chalk GW 8 Pick 5
1557117 Bernard Chalk GW 8 Pick 6
1557117 Bernard Chalk GW 8 Pick 7
1557117 Bernard Chalk GW 8 Pick 8
1557117 Bernard Chalk GW 8 Pick 9
1557117 Bernard Chalk GW 8 Pick 10
1557117 Bernard Chalk GW 8 Pick 11
1557117 Bernard Chalk GW 8 Pick 12
1557117 Bernard Chalk GW 8 Pick 13
1557117 Bernard Chalk GW 8 Pick 14
1557117 Bernard Chalk GW 8 Pick 15
1557117 Bernard Chalk GW 9 Pick 1
1557117 Bernard Chalk GW 9 Pick 2
1557117 Bernard Chalk GW 9 Pick 3
1557117 Bernard Chalk GW 9 Pick 4
1557117 Bernard Chalk GW 9 Pick 5
1557117 Bernard Chalk GW 9 Pick 6
1557117 Bernard Chalk GW 9 Pick 7
1557117 Bernard Chalk GW 9 Pick 8
1557117 Bernard Chalk GW 9 Pick 9
1557117 Bernard Chalk GW 9 Pick 10
1557117 Bernard Chalk GW 9 Pick 11
1557117 Bernard Chalk GW 9 Pick 12
1557117 Bernard Chalk GW 9 Pick 13
1557117 Bernard Chalk GW 9 Pick 14
1557117 Bernard Chalk GW 9 Pick 15
1557117 Bernard Chalk GW 10 Pick 1
1557117 Bernard Chalk GW 10 Pick 2
1557117 Bernard Chalk GW 10 Pick 3
1557117 Bernard Chalk GW 10 Pick 4
1557117 Bernard Chalk GW 10 Pick 5
1557117 Bernard Chalk GW 10 Pick 6
1557117 Bernard Chalk GW 10 Pick 7
1557117 Bernard Chalk GW 10 Pick 8
1557117 Bernard Chalk GW 10 Pick 9
1557117 Bernard Chalk GW 10 Pick 10
1557117 Bernard Chalk GW 10 Pick 11
1557117 Bernard Chalk GW 10 Pick 12
1557117 Bernard Chalk GW 10 Pick 13
1557117 Bernard Chalk GW 10 Pick 14
1557117 Bernard Chalk GW 10 Pick 15
1557117 Bernard Chalk GW 11 Pick 1
1557117 Bernard Chalk GW 11 Pick 2
1557117 Bernard Chalk GW 11 Pick 3
1557117 Bernard Chalk GW 11 Pick 4
1557117 Bernard Chalk GW 11 Pick 5
1557117 Bernard Chalk GW 11 Pick 6
1557117 Bernard Chalk GW 11 Pick 7
1557117 Bernard Chalk GW 11 Pick 8
1557117 Bernard Chalk GW 11 Pick 9
1557117 Bernard Chalk GW 11 Pick 10
1557117 Bernard Chalk GW 11 Pick 11
1557117 Bernard Chalk GW 11 Pick 12
1557117 Bernard Chalk GW 11 Pick 13
1557117 Bernard Chalk GW 11 Pick 14
1557117 Bernard Chalk GW 11 Pick 15
1557117 Bernard Chalk GW 12 Pick 1
1557117 Bernard Chalk GW 12 Pick 2
1557117 Bernard Chalk GW 12 Pick 3
1557117 Bernard Chalk GW 12 Pick 4
1557117 Bernard Chalk GW 12 Pick 5
1557117 Bernard Chalk GW 12 Pick 6
1557117 Bernard Chalk GW 12 Pick 7
1557117 Bernard Chalk GW 12 Pick 8
1557117 Bernard Chalk GW 12 Pick 9
1557117 Bernard Chalk GW 12 Pick 10
1557117 Bernard Chalk GW 12 Pick 11
1557117 Bernard Chalk GW 12 Pick 12
1557117 Bernard Chalk GW 12 Pick 13
1557117 Bernard Chalk GW 12 Pick 14
1557117 Bernard Chalk GW 12 Pick 15
1557117 Bernard Chalk GW 13 Pick 1
1557117 Bernard Chalk GW 13 Pick 2
1557117 Bernard Chalk GW 13 Pick 3
1557117 Bernard Chalk GW 13 Pick 4
1557117 Bernard Chalk GW 13 Pick 5
1557117 Bernard Chalk GW 13 Pick 6
1557117 Bernard Chalk GW 13 Pick 7
1557117 Bernard Chalk GW 13 Pick 8
1557117 Bernard Chalk GW 13 Pick 9
1557117 Bernard Chalk GW 13 Pick 10
1557117 Bernard Chalk GW 13 Pick 11
1557117 Bernard Chalk GW 13 Pick 12
1557117 Bernard Chalk GW 13 Pick 13
1557117 Bernard Chalk GW 13 Pick 14
1557117 Bernard Chalk GW 13 Pick 15
1557117 Bernard Chalk GW 14 Pick 1
1557117 Bernard Chalk GW 14 Pick 2
1557117 Bernard Chalk GW 14 Pick 3
1557117 Bernard Chalk GW 14 Pick 4
1557117 Bernard Chalk GW 14 Pick 5
1557117 Bernard Chalk GW 14 Pick 6
1557117 Bernard Chalk GW 14 Pick 7
1557117 Bernard Chalk GW 14 Pick 8
1557117 Bernard Chalk GW 14 Pick 9
1557117 Bernard Chalk GW 14 Pick 10
1557117 Bernard Chalk GW 14 Pick 11
1557117 Bernard Chalk GW 14 Pick 12
1557117 Bernard Chalk GW 14 Pick 13
1557117 Bernard Chalk GW 14 Pick 14
1557117 Bernard Chalk GW 14 Pick 15
1557117 Bernard Chalk GW 15 Pick 1
1557117 Bernard Chalk GW 15 Pick 2
1557117 Bernard Chalk GW 15 Pick 3
1557117 Bernard Chalk GW 15 Pick 4
1557117 Bernard Chalk GW 15 Pick 5
1557117 Bernard Chalk GW 15 Pick 6
1557117 Bernard Chalk GW 15 Pick 7
1557117 Bernard Chalk GW 15 Pick 8
1557117 Bernard Chalk GW 15 Pick 9
1557117 Bernard Chalk GW 15 Pick 10
1557117 Bernard Chalk GW 15 Pick 11
1557117 Bernard Chalk GW 15 Pick 12
1557117 Bernard Chalk GW 15 Pick 13
1557117 Bernard Chalk GW 15 Pick 14
1557117 Bernard Chalk GW 15 Pick 15
1557117 Bernard Chalk GW 16 Pick 1
1557117 Bernard Chalk GW 16 Pick 2
1557117 Bernard Chalk GW 16 Pick 3
1557117 Bernard Chalk GW 16 Pick 4
1557117 Bernard Chalk GW 16 Pick 5
1557117 Bernard Chalk GW 16 Pick 6
1557117 Bernard Chalk GW 16 Pick 7
1557117 Bernard Chalk GW 16 Pick 8
1557117 Bernard Chalk GW 16 Pick 9
1557117 Bernard Chalk GW 16 Pick 10
1557117 Bernard Chalk GW 16 Pick 11
1557117 Bernard Chalk GW 16 Pick 12
1557117 Bernard Chalk GW 16 Pick 13
1557117 Bernard Chalk GW 16 Pick 14
1557117 Bernard Chalk GW 16 Pick 15
1557117 Bernard Chalk GW 17 Pick 1
1557117 Bernard Chalk GW 17 Pick 2
1557117 Bernard Chalk GW 17 Pick 3
1557117 Bernard Chalk GW 17 Pick 4
1557117 Bernard Chalk GW 17 Pick 5
1557117 Bernard Chalk GW 17 Pick 6
1557117 Bernard Chalk GW 17 Pick 7
1557117 Bernard Chalk GW 17 Pick 8
1557117 Bernard Chalk GW 17 Pick 9
1557117 Bernard Chalk GW 17 Pick 10
1557117 Bernard Chalk GW 17 Pick 11
1557117 Bernard Chalk GW 17 Pick 12
1557117 Bernard Chalk GW 17 Pick 13
1557117 Bernard Chalk GW 17 Pick 14
1557117 Bernard Chalk GW 17 Pick 15
1557117 Bernard Chalk GW 18 Pick 1
1557117 Bernard Chalk GW 18 Pick 2
1557117 Bernard Chalk GW 18 Pick 3
1557117 Bernard Chalk GW 18 Pick 4
1557117 Bernard Chalk GW 18 Pick 5
1557117 Bernard Chalk GW 18 Pick 6
1557117 Bernard Chalk GW 18 Pick 7
1557117 Bernard Chalk GW 18 Pick 8
1557117 Bernard Chalk GW 18 Pick 9
1557117 Bernard Chalk GW 18 Pick 10
1557117 Bernard Chalk GW 18 Pick 11
1557117 Bernard Chalk GW 18 Pick 12
1557117 Bernard Chalk GW 18 Pick 13
1557117 Bernard Chalk GW 18 Pick 14
1557117 Bernard Chalk GW 18 Pick 15
1557117 Bernard Chalk GW 19 Pick 1
1557117 Bernard Chalk GW 19 Pick 2
1557117 Bernard Chalk GW 19 Pick 3
1557117 Bernard Chalk GW 19 Pick 4
1557117 Bernard Chalk GW 19 Pick 5
1557117 Bernard Chalk GW 19 Pick 6
1557117 Bernard Chalk GW 19 Pick 7
1557117 Bernard Chalk GW 19 Pick 8
1557117 Bernard Chalk GW 19 Pick 9
1557117 Bernard Chalk GW 19 Pick 10
1557117 Bernard Chalk GW 19 Pick 11
1557117 Bernard Chalk GW 19 Pick 12
1557117 Bernard Chalk GW 19 Pick 13
1557117 Bernard Chalk GW 19 Pick 14
1557117 Bernard Chalk GW 19 Pick 15
1557117 Bernard Chalk GW 20 Pick 1
1557117 Bernard Chalk GW 20 Pick 2
1557117 Bernard Chalk GW 20 Pick 3
1557117 Bernard Chalk GW 20 Pick 4
1557117 Bernard Chalk GW 20 Pick 5
1557117 Bernard Chalk GW 20 Pick 6
1557117 Bernard Chalk GW 20 Pick 7
1557117 Bernard Chalk GW 20 Pick 8
1557117 Bernard Chalk GW 20 Pick 9
1557117 Bernard Chalk GW 20 Pick 10
1557117 Bernard Chalk GW 20 Pick 11
1557117 Bernard Chalk GW 20 Pick 12
1557117 Bernard Chalk GW 20 Pick 13
1557117 Bernard Chalk GW 20 Pick 14
1557117 Bernard Chalk GW 20 Pick 15
1557117 Bernard Chalk GW 21 Pick 1
1557117 Bernard Chalk GW 21 Pick 2
1557117 Bernard Chalk GW 21 Pick 3
1557117 Bernard Chalk GW 21 Pick 4
1557117 Bernard Chalk GW 21 Pick 5
1557117 Bernard Chalk GW 21 Pick 6
1557117 Bernard Chalk GW 21 Pick 7
1557117 Bernard Chalk GW 21 Pick 8
1557117 Bernard Chalk GW 21 Pick 9
1557117 Bernard Chalk GW 21 Pick 10
1557117 Bernard Chalk GW 21 Pick 11
1557117 Bernard Chalk GW 21 Pick 12
1557117 Bernard Chalk GW 21 Pick 13
1557117 Bernard Chalk GW 21 Pick 14
1557117 Bernard Chalk GW 21 Pick 15
1557117 Bernard Chalk GW 22 Pick 1
1557117 Bernard Chalk GW 22 Pick 2
1557117 Bernard Chalk GW 22 Pick 3
1557117 Bernard Chalk GW 22 Pick 4
1557117 Bernard Chalk GW 22 Pick 5
1557117 Bernard Chalk GW 22 Pick 6
1557117 Bernard Chalk GW 22 Pick 7
1557117 Bernard Chalk GW 22 Pick 8
1557117 Bernard Chalk GW 22 Pick 9
1557117 Bernard Chalk GW 22 Pick 10
1557117 Bernard Chalk GW 22 Pick 11
1557117 Bernard Chalk GW 22 Pick 12
1557117 Bernard Chalk GW 22 Pick 13
1557117 Bernard Chalk GW 22 Pick 14
1557117 Bernard Chalk GW 22 Pick 15
1557117 Bernard Chalk GW 23 Pick 1
1557117 Bernard Chalk GW 23 Pick 2
1557117 Bernard Chalk GW 23 Pick 3
1557117 Bernard Chalk GW 23 Pick 4
1557117 Bernard Chalk GW 23 Pick 5
1557117 Bernard Chalk GW 23 Pick 6
1557117 Bernard Chalk GW 23 Pick 7
1557117 Bernard Chalk GW 23 Pick 8
1557117 Bernard Chalk GW 23 Pick 9
1557117 Bernard Chalk GW 23 Pick 10
1557117 Bernard Chalk GW 23 Pick 11
1557117 Bernard Chalk GW 23 Pick 12
1557117 Bernard Chalk GW 23 Pick 13
1557117 Bernard Chalk GW 23 Pick 14
1557117 Bernard Chalk GW 23 Pick 15
1557117 Bernard Chalk GW 24 Pick 1
1557117 Bernard Chalk GW 24 Pick 2
1557117 Bernard Chalk GW 24 Pick 3
1557117 Bernard Chalk GW 24 Pick 4
1557117 Bernard Chalk GW 24 Pick 5
1557117 Bernard Chalk GW 24 Pick 6
1557117 Bernard Chalk GW 24 Pick 7
1557117 Bernard Chalk GW 24 Pick 8
1557117 Bernard Chalk GW 24 Pick 9
1557117 Bernard Chalk GW 24 Pick 10
1557117 Bernard Chalk GW 24 Pick 11
1557117 Bernard Chalk GW 24 Pick 12
1557117 Bernard Chalk GW 24 Pick 13
1557117 Bernard Chalk GW 24 Pick 14
1557117 Bernard Chalk GW 24 Pick 15
1557117 Bernard Chalk GW 25 Pick 1
1557117 Bernard Chalk GW 25 Pick 2
1557117 Bernard Chalk GW 25 Pick 3
1557117 Bernard Chalk GW 25 Pick 4
1557117 Bernard Chalk GW 25 Pick 5
1557117 Bernard Chalk GW 25 Pick 6
1557117 Bernard Chalk GW 25 Pick 7
1557117 Bernard Chalk GW 25 Pick 8
1557117 Bernard Chalk GW 25 Pick 9
1557117 Bernard Chalk GW 25 Pick 10
1557117 Bernard Chalk GW 25 Pick 11
1557117 Bernard Chalk GW 25 Pick 12
1557117 Bernard Chalk GW 25 Pick 13
1557117 Bernard Chalk GW 25 Pick 14
1557117 Bernard Chalk GW 25 Pick 15
1557117 Bernard Chalk GW 26 Pick 1
1557117 Bernard Chalk GW 26 Pick 2
1557117 Bernard Chalk GW 26 Pick 3
1557117 Bernard Chalk GW 26 Pick 4
1557117 Bernard Chalk GW 26 Pick 5
1557117 Bernard Chalk GW 26 Pick 6
1557117 Bernard Chalk GW 26 Pick 7
1557117 Bernard Chalk GW 26 Pick 8
1557117 Bernard Chalk GW 26 Pick 9
1557117 Bernard Chalk GW 26 Pick 10
1557117 Bernard Chalk GW 26 Pick 11
1557117 Bernard Chalk GW 26 Pick 12
1557117 Bernard Chalk GW 26 Pick 13
1557117 Bernard Chalk GW 26 Pick 14
1557117 Bernard Chalk GW 26 Pick 15
1557117 Bernard Chalk GW 27 Pick 1
1557117 Bernard Chalk GW 27 Pick 2
1557117 Bernard Chalk GW 27 Pick 3
1557117 Bernard Chalk GW 27 Pick 4
1557117 Bernard Chalk GW 27 Pick 5
1557117 Bernard Chalk GW 27 Pick 6
1557117 Bernard Chalk GW 27 Pick 7
1557117 Bernard Chalk GW 27 Pick 8
1557117 Bernard Chalk GW 27 Pick 9
1557117 Bernard Chalk GW 27 Pick 10
1557117 Bernard Chalk GW 27 Pick 11
1557117 Bernard Chalk GW 27 Pick 12
1557117 Bernard Chalk GW 27 Pick 13
1557117 Bernard Chalk GW 27 Pick 14
1557117 Bernard Chalk GW 27 Pick 15
1557117 Bernard Chalk GW 28 Pick 1
1557117 Bernard Chalk GW 28 Pick 2
1557117 Bernard Chalk GW 28 Pick 3
1557117 Bernard Chalk GW 28 Pick 4
1557117 Bernard Chalk GW 28 Pick 5
1557117 Bernard Chalk GW 28 Pick 6
1557117 Bernard Chalk GW 28 Pick 7
1557117 Bernard Chalk GW 28 Pick 8
1557117 Bernard Chalk GW 28 Pick 9
1557117 Bernard Chalk GW 28 Pick 10
1557117 Bernard Chalk GW 28 Pick 11
1557117 Bernard Chalk GW 28 Pick 12
1557117 Bernard Chalk GW 28 Pick 13
1557117 Bernard Chalk GW 28 Pick 14
1557117 Bernard Chalk GW 28 Pick 15
1557117 Bernard Chalk GW 29 Pick 1
1557117 Bernard Chalk GW 29 Pick 2
1557117 Bernard Chalk GW 29 Pick 3
1557117 Bernard Chalk GW 29 Pick 4
1557117 Bernard Chalk GW 29 Pick 5
1557117 Bernard Chalk GW 29 Pick 6
1557117 Bernard Chalk GW 29 Pick 7
1557117 Bernard Chalk GW 29 Pick 8
1557117 Bernard Chalk GW 29 Pick 9
1557117 Bernard Chalk GW 29 Pick 10
1557117 Bernard Chalk GW 29 Pick 11
1557117 Bernard Chalk GW 29 Pick 12
1557117 Bernard Chalk GW 29 Pick 13
1557117 Bernard Chalk GW 29 Pick 14
1557117 Bernard Chalk GW 29 Pick 15
1557117 Bernard Chalk GW 30 Pick 1
1557117 Bernard Chalk GW 30 Pick 2
1557117 Bernard Chalk GW 30 Pick 3
1557117 Bernard Chalk GW 30 Pick 4
1557117 Bernard Chalk GW 30 Pick 5
1557117 Bernard Chalk GW 30 Pick 6
1557117 Bernard Chalk GW 30 Pick 7
1557117 Bernard Chalk GW 30 Pick 8
1557117 Bernard Chalk GW 30 Pick 9
1557117 Bernard Chalk GW 30 Pick 10
1557117 Bernard Chalk GW 30 Pick 11
1557117 Bernard Chalk GW 30 Pick 12
1557117 Bernard Chalk GW 30 Pick 13
1557117 Bernard Chalk GW 30 Pick 14
1557117 Bernard Chalk GW 30 Pick 15
1557117 Bernard Chalk GW 31 Pick 1
1557117 Bernard Chalk GW 31 Pick 2
1557117 Bernard Chalk GW 31 Pick 3
1557117 Bernard Chalk GW 31 Pick 4
1557117 Bernard Chalk GW 31 Pick 5
1557117 Bernard Chalk GW 31 Pick 6
1557117 Bernard Chalk GW 31 Pick 7
1557117 Bernard Chalk GW 31 Pick 8
1557117 Bernard Chalk GW 31 Pick 9
1557117 Bernard Chalk GW 31 Pick 10
1557117 Bernard Chalk GW 31 Pick 11
1557117 Bernard Chalk GW 31 Pick 12
1557117 Bernard Chalk GW 31 Pick 13
1557117 Bernard Chalk GW 31 Pick 14
1557117 Bernard Chalk GW 31 Pick 15
1557117 Bernard Chalk GW 32 Pick 1
1557117 Bernard Chalk GW 32 Pick 2
1557117 Bernard Chalk GW 32 Pick 3
1557117 Bernard Chalk GW 32 Pick 4
1557117 Bernard Chalk GW 32 Pick 5
1557117 Bernard Chalk GW 32 Pick 6
1557117 Bernard Chalk GW 32 Pick 7
1557117 Bernard Chalk GW 32 Pick 8
1557117 Bernard Chalk GW 32 Pick 9
1557117 Bernard Chalk GW 32 Pick 10
1557117 Bernard Chalk GW 32 Pick 11
1557117 Bernard Chalk GW 32 Pick 12
1557117 Bernard Chalk GW 32 Pick 13
1557117 Bernard Chalk GW 32 Pick 14
1557117 Bernard Chalk GW 32 Pick 15
1557117 Bernard Chalk GW 33 Pick 1
1557117 Bernard Chalk GW 33 Pick 2
1557117 Bernard Chalk GW 33 Pick 3
1557117 Bernard Chalk GW 33 Pick 4
1557117 Bernard Chalk GW 33 Pick 5
1557117 Bernard Chalk GW 33 Pick 6
1557117 Bernard Chalk GW 33 Pick 7
1557117 Bernard Chalk GW 33 Pick 8
1557117 Bernard Chalk GW 33 Pick 9
1557117 Bernard Chalk GW 33 Pick 10
1557117 Bernard Chalk GW 33 Pick 11
1557117 Bernard Chalk GW 33 Pick 12
1557117 Bernard Chalk GW 33 Pick 13
1557117 Bernard Chalk GW 33 Pick 14
1557117 Bernard Chalk GW 33 Pick 15
5398818 Ryan Boyce GW 1 Pick 1
5398818 Ryan Boyce GW 1 Pick 2
5398818 Ryan Boyce GW 1 Pick 3
5398818 Ryan Boyce GW 1 Pick 4
5398818 Ryan Boyce GW 1 Pick 5
5398818 Ryan Boyce GW 1 Pick 6
5398818 Ryan Boyce GW 1 Pick 7
5398818 Ryan Boyce GW 1 Pick 8
5398818 Ryan Boyce GW 1 Pick 9
5398818 Ryan Boyce GW 1 Pick 10
5398818 Ryan Boyce GW 1 Pick 11
5398818 Ryan Boyce GW 1 Pick 12
5398818 Ryan Boyce GW 1 Pick 13
5398818 Ryan Boyce GW 1 Pick 14
5398818 Ryan Boyce GW 1 Pick 15
5398818 Ryan Boyce GW 2 Pick 1
5398818 Ryan Boyce GW 2 Pick 2
5398818 Ryan Boyce GW 2 Pick 3
5398818 Ryan Boyce GW 2 Pick 4
5398818 Ryan Boyce GW 2 Pick 5
5398818 Ryan Boyce GW 2 Pick 6
5398818 Ryan Boyce GW 2 Pick 7
5398818 Ryan Boyce GW 2 Pick 8
5398818 Ryan Boyce GW 2 Pick 9
5398818 Ryan Boyce GW 2 Pick 10
5398818 Ryan Boyce GW 2 Pick 11
5398818 Ryan Boyce GW 2 Pick 12
5398818 Ryan Boyce GW 2 Pick 13
5398818 Ryan Boyce GW 2 Pick 14
5398818 Ryan Boyce GW 2 Pick 15
5398818 Ryan Boyce GW 3 Pick 1
5398818 Ryan Boyce GW 3 Pick 2
5398818 Ryan Boyce GW 3 Pick 3
5398818 Ryan Boyce GW 3 Pick 4
5398818 Ryan Boyce GW 3 Pick 5
5398818 Ryan Boyce GW 3 Pick 6
5398818 Ryan Boyce GW 3 Pick 7
5398818 Ryan Boyce GW 3 Pick 8
5398818 Ryan Boyce GW 3 Pick 9
5398818 Ryan Boyce GW 3 Pick 10
5398818 Ryan Boyce GW 3 Pick 11
5398818 Ryan Boyce GW 3 Pick 12
5398818 Ryan Boyce GW 3 Pick 13
5398818 Ryan Boyce GW 3 Pick 14
5398818 Ryan Boyce GW 3 Pick 15
5398818 Ryan Boyce GW 4 Pick 1
5398818 Ryan Boyce GW 4 Pick 2

In [6]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW34 to GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ollie Watkins,a,0,FWD,Aston Villa,1056.4,6.95,84.5,0.775,0.450,1.347
1,Declan Rice,a,0,MID,Arsenal,1005.9,6.04,85.3,0.347,0.359,0.837
2,Mohamed Salah,a,0,MID,Liverpool,1094.1,5.97,72.6,0.548,0.348,1.487
3,Jarrod Bowen,a,0,FWD,West Ham,1087.5,5.61,84.4,0.503,0.399,1.635
4,Harvey Barnes,a,0,MID,Newcastle,1079.1,5.35,61.8,0.635,0.316,1.693
5,Gabriel dos Santos Magalhães,a,0,DEF,Arsenal,1005.9,5.17,83.8,0.093,0.113,0.924
6,Mathias Jensen,a,0,MID,Brentford,1114.7,5.16,85.1,0.323,0.180,1.543
7,Morgan Gibbs-White,a,0,MID,Nott'm Forest,1079.1,5.06,83.2,0.229,0.338,1.530
8,Harry Wilson,a,0,MID,Fulham,1089.9,5.01,84.6,0.266,0.259,1.525
9,Eberechi Eze,a,0,MID,Arsenal,1005.9,4.99,63.2,0.355,0.350,0.851
10,Morgan Rogers,a,0,MID,Aston Villa,1056.4,4.94,82.8,0.208,0.273,1.386
11,Youri Tielemans,a,0,MID,Aston Villa,1056.4,4.91,71.0,0.281,0.329,1.323
12,Bruno Borges Fernandes,a,0,MID,Man Utd,1080.1,4.87,83.3,0.220,0.260,1.432
13,Callum Hudson-Odoi,d,0,MID,Nott'm Forest,1079.1,4.74,72.7,0.352,0.157,1.514
14,Piero Hincapié,a,0,DEF,Arsenal,1005.9,4.73,72.4,0.063,0.069,0.929
15,William Saliba,a,0,DEF,Arsenal,1005.9,4.72,86.1,0.047,0.034,0.925
16,Kiernan Dewsbury-Hall,a,0,MID,Everton,1058.7,4.72,84.9,0.195,0.228,1.433
17,Dwight McNeil,a,0,MID,Everton,1058.7,4.70,73.9,0.289,0.215,1.343
18,John McGinn,a,0,MID,Aston Villa,1056.4,4.67,73.2,0.204,0.330,1.247
19,Leandro Trossard,a,0,MID,Arsenal,1005.9,4.65,44.6,0.551,0.450,0.819
20,Igor Thiago Nascimento Rodrigues,a,0,FWD,Brentford,1114.7,4.64,84.6,0.479,0.059,1.424
21,Anthony Gordon,d,0,MID,Newcastle,1079.1,4.60,82.8,0.209,0.230,1.485
22,Matheus Santos Carneiro da Cunha,a,0,MID,Man Utd,1080.1,4.50,83.2,0.223,0.130,1.417
23,Cody Gakpo,a,0,MID,Liverpool,1094.1,4.49,82.2,0.221,0.123,1.334
24,Jurriën Timber,d,0,DEF,Arsenal,1005.9,4.46,54.5,0.110,0.141,0.919
25,Norberto Bercique Gomes Betuncal,d,0,FWD,Everton,1058.7,4.40,66.3,0.575,0.080,1.465
26,Granit Xhaka,a,0,MID,Sunderland,1045.7,4.40,75.3,0.203,0.215,1.412
27,Lucas Digne,a,0,DEF,Aston Villa,1056.4,4.40,66.6,0.092,0.289,1.447
28,Kevin Schade,a,0,MID,Brentford,1114.7,4.38,76.8,0.226,0.176,1.529
29,Ross Barkley,a,0,MID,Aston Villa,1056.4,4.37,73.1,0.236,0.145,1.297
30,Virgil van Dijk,a,0,DEF,Liverpool,1094.1,4.37,86.7,0.133,0.073,1.498
31,Bryan Mbeumo,d,0,MID,Man Utd,1080.1,4.37,71.8,0.260,0.167,1.387
32,Amadou Onana,a,0,MID,Aston Villa,1056.4,4.36,84.4,0.205,0.073,1.402
33,Benjamin White,a,0,DEF,Arsenal,1005.9,4.33,68.0,0.051,0.078,1.025
34,David Raya Martín,a,0,GK,Arsenal,1005.9,4.32,89.8,NaN,NaN,0.819
35,John Stones,a,0,DEF,Man City,1092.4,4.31,54.8,0.974,0.040,1.593
36,Alex Iwobi,d,0,MID,Fulham,1089.9,4.30,75.5,0.222,0.149,1.535
37,Dominik Szoboszlai,a,0,MID,Liverpool,1094.1,4.29,85.5,0.156,0.136,1.485
38,Conor Gallagher,a,0,MID,Spurs,1047.0,4.29,65.5,0.292,0.214,1.662
39,Cristhian Mosquera,a,0,DEF,Arsenal,1005.9,4.23,65.1,0.045,0.034,0.968
40,Habib Diarra,a,0,MID,Sunderland,1045.7,4.19,85.4,0.150,0.123,1.388
41,Iliman Ndiaye,a,0,MID,Everton,1058.7,4.15,85.3,0.153,0.087,1.399
42,Dango Ouattara,a,0,MID,Brentford,1114.7,4.13,71.1,0.190,0.179,1.538
43,Carlos Henrique Casimiro,a,0,MID,Man Utd,1080.1,4.11,83.9,0.151,0.105,1.414
44,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1092.4,4.11,81.9,0.151,0.781,1.194
45,El Hadji Malick Diouf,a,0,DEF,West Ham,1087.5,4.11,85.4,0.051,0.150,1.486
46,Riccardo Calafiori,d,0,DEF,Arsenal,1005.9,4.11,49.3,0.104,0.094,0.972
47,Mason Mount,a,0,MID,Man Utd,1080.1,4.10,25.3,0.990,0.736,2.020
48,Pau Torres,a,0,DEF,Aston Villa,1056.4,4.09,85.1,0.054,0.028,1.349
49,Crysencio Summerville,a,0,MID,West Ham,1087.5,4.09,76.4,0.227,0.071,1.535

In [7]:
print(f"\nTop 20 predicted xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        value/10 as value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
    GROUP BY player_name_id, status, position, team_name, value
    ORDER BY total_xpoints DESC
""")
next5gw_predictions.head(20)

Top 20 predicted xPoints between 34 and 38:

,player_name_id,status,position,team_name,value,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ollie Watkins,a,FWD,Aston Villa,8.5,1056.4,34.61,84.5,0.775,0.450,1.347
1,Declan Rice,a,MID,Arsenal,7.2,1005.9,30.42,85.3,0.347,0.359,0.837
2,Mohamed Salah,a,MID,Liverpool,14.0,1094.1,29.98,72.6,0.548,0.348,1.487
3,Jarrod Bowen,a,FWD,West Ham,7.6,1087.5,28.12,84.4,0.503,0.399,1.635
4,Harvey Barnes,a,MID,Newcastle,6.1,1079.1,27.19,61.8,0.635,0.316,1.693
5,Gabriel dos Santos Magalhães,a,DEF,Arsenal,7.1,1005.9,26.25,83.8,0.093,0.113,0.924
6,Mathias Jensen,a,MID,Brentford,4.9,1114.7,25.80,85.1,0.323,0.180,1.543
7,John Stones,a,DEF,Man City,5.4,1092.4,25.53,54.8,0.974,0.040,1.593
8,Morgan Gibbs-White,a,MID,Nott'm Forest,7.4,1079.1,25.48,83.2,0.229,0.338,1.530
9,Harry Wilson,a,MID,Fulham,6.0,1089.9,25.24,84.6,0.266,0.259,1.525
10,Eberechi Eze,a,MID,Arsenal,7.2,1005.9,25.14,63.2,0.355,0.350,0.851
11,Bruno Borges Fernandes,a,MID,Man Utd,10.3,1080.1,24.62,83.3,0.220,0.260,1.432
12,Morgan Rogers,a,MID,Aston Villa,7.4,1056.4,24.44,82.8,0.208,0.273,1.386
13,Youri Tielemans,a,MID,Aston Villa,5.9,1056.4,24.32,71.0,0.281,0.329,1.323
14,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,6.2,1092.4,24.23,81.9,0.151,0.781,1.194
15,William Saliba,a,DEF,Arsenal,6.1,1005.9,23.98,86.1,0.047,0.034,0.925
16,Piero Hincapié,a,DEF,Arsenal,5.1,1005.9,23.80,72.4,0.063,0.069,0.929
17,Kiernan Dewsbury-Hall,a,MID,Everton,5.1,1058.7,23.69,84.9,0.195,0.228,1.433
18,Callum Hudson-Odoi,d,MID,Nott'm Forest,5.7,1079.1,23.64,72.7,0.352,0.157,1.514
19,Dwight McNeil,a,MID,Everton,5.5,1058.7,23.58,73.9,0.289,0.215,1.343

In [8]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0              Bernard Chalk  1557117.0        1892.0
1                 Ryan Boyce  5398818.0        1882.0
2         Christopher Harris    28660.0        1821.0
3               Samia Shelim  6506490.0        1816.0
4               Tommy Davies  7845816.0        1802.0
5          William Partridge  6588565.0        1797.0
6                 Rhys Birdy  5810139.0        1785.0
7               Jack Carroll  4438260.0        1778.0
8         Christopher Harris   145486.0        1763.0
9              Rizwan Shelim  3058994.0        1763.0
10             Ollie Carroll  5181285.0        1719.0
11               Nafi Shelim  4776281.0        1686.0
12            Conner Harling  3421093.0        1677.0
13             Tajwar Shelim  4773459.0        1668.0
14  Christakis Christodoulou  7474864.0        1610.0
15              Tahmid Haque  6394829.0        1534.0
16            Charlie Garner  9432680.0        1505.0
17              Will Hossack  4792527.0        1504.0
18               Simon Meech  6764382.0        1500.0
19              Holly Stower  7367977.0        1416.0
20            Rachel Aumayer  9763056.0        1241.0

In [9]:
alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks.multiplier, 0)) AS total_points   
        FROM divx_picks
        LEFT JOIN playergw 
            ON divx_picks.element = playergw.element
            AND divx_picks.season = playergw.season
            AND divx_picks.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN (28660, 145486)
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks
        WHERE memberid = 28660
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
        FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) as total_multiplier
        FROM divx_picks
        WHERE divx_picks.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.value/10 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / (SELECT COUNT(*) FROM top_5_members) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            --MAX(ownership_ratio) AS ownership_ratio,
            MAX(ownership_ratio) * 100 AS ownership_percentage,
            SUM(xpoints) * (1 - MAX(ownership_ratio)) AS weighted_xpoints_gain,
            -1 * SUM(xpoints) * (MAX(ownership_ratio)) AS weighted_xpoints_loss,
            CASE WHEN in_my_team = 1 THEN SUM(xpoints) * (1 - MAX(ownership_ratio)) ELSE 0 
                END AS weighted_xpoints_picks_gain,
            CASE WHEN in_my_team = 0 THEN SUM(xpoints) * MAX(ownership_ratio) * -1 ELSE 0 
                END AS weighted_xpoints_team_picks_loss
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        weighted_xpoints_gain + weighted_xpoints_loss AS xpoints_net_gain,
        weighted_xpoints_picks_gain + weighted_xpoints_team_picks_loss AS xpoints_net_team_value,
        {alpha} * sum_xpoints + (1 - {alpha}) * (weighted_xpoints_gain + weighted_xpoints_loss) AS blended_score -- Not working because wighted_gain can be negative and outweigh the absolute points, need to rethink how to blend these.
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='xpoints_net_team_value', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW34 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
414,1,237.0,Enzo Fernández,a,6.5,MID,Chelsea,17.325347,0.0,17.325347,0.000000,17.325347,0.0,17.325347,17.325347,17.325347
314,1,148.0,Ferdi Kadıoğlu,a,4.4,DEF,Brighton,16.383719,0.0,16.383719,0.000000,16.383719,0.0,16.383719,16.383719,16.383719
87,1,347.0,Gabriel Gudmundsson,a,3.8,DEF,Leeds,15.921127,0.0,15.921127,0.000000,15.921127,0.0,15.921127,15.921127,15.921127
391,1,736.0,Gianluigi Donnarumma,a,5.6,GK,Man City,14.965112,0.0,14.965112,0.000000,14.965112,0.0,14.965112,14.965112,14.965112
118,1,84.0,Marcus Tavernier,a,5.4,MID,Bournemouth,17.827497,20.0,14.261998,-3.565499,14.261998,0.0,10.696498,14.261998,14.261998
376,1,342.0,Jayden Bogle,a,4.4,DEF,Leeds,15.917355,20.0,12.733884,-3.183471,12.733884,0.0,9.550413,12.733884,12.733884
368,1,807.0,Rayan Vitor Simplício Rocha,a,5.5,MID,Bournemouth,15.910187,20.0,12.728149,-3.182037,12.728149,0.0,9.546112,12.728149,12.728149
371,1,139.0,Bart Verbruggen,a,4.5,GK,Brighton,14.606499,20.0,11.685199,-2.921300,11.685199,0.0,8.763899,11.685199,11.685199
283,1,235.0,Cole Palmer,a,10.5,MID,Chelsea,19.131478,40.0,11.478887,-7.652591,11.478887,0.0,3.826296,11.478887,11.478887
390,1,691.0,Dominic Calvert-Lewin,a,5.6,FWD,Leeds,18.758880,40.0,11.255328,-7.503552,11.255328,0.0,3.751776,11.255328,11.255328
55,1,151.0,Jan Paul van Hecke,a,4.6,DEF,Brighton,16.340613,40.0,9.804368,-6.536245,9.804368,0.0,3.268123,9.804368,9.804368
5,1,72.0,Marcos Senesi Barón,a,5.2,DEF,Bournemouth,15.531654,40.0,9.318993,-6.212662,9.318993,0.0,3.106331,9.318993,9.318993
64,1,249.0,João Pedro Junqueira de Jesus,a,7.7,FWD,Chelsea,16.282933,80.0,3.256587,-13.026346,3.256587,0.0,-9.769760,3.256587,3.256587
29,1,82.0,Antoine Semenyo,a,8.2,MID,Man City,22.558254,120.0,-4.511651,-27.069905,-4.511651,0.0,-31.581556,-4.511651,-4.511651
40,1,430.0,Erling Haaland,a,14.5,FWD,Man City,19.591863,140.0,-7.836745,-27.428608,-7.836745,0.0,-35.265354,-7.836745,-7.836745

In [10]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='xpoints_net_team_value', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW34 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
418,0,329.0,Harry Wilson,a,6.0,MID,Fulham,25.244832,60.0,10.097933,-15.146899,0.000000,-15.146899,-5.048966,-15.146899,10.097933
319,0,449.0,Bruno Borges Fernandes,a,10.3,MID,Man Utd,24.621314,60.0,9.848526,-14.772789,0.000000,-14.772789,-4.924263,-14.772789,9.848526
351,0,21.0,Declan Rice,a,7.2,MID,Arsenal,30.424269,40.0,18.254562,-12.169708,0.000000,-12.169708,6.084854,-12.169708,18.254562
200,0,5.0,Gabriel dos Santos Magalhães,a,7.1,DEF,Arsenal,26.253806,40.0,15.752284,-10.501523,0.000000,-10.501523,5.250761,-10.501523,15.752284
396,0,260.0,Marc Guéhi,a,5.1,DEF,Man City,16.525598,60.0,6.610239,-9.915359,0.000000,-9.915359,-3.305120,-9.915359,6.610239
40,1,430.0,Erling Haaland,a,14.5,FWD,Man City,19.591863,140.0,-7.836745,-27.428608,-7.836745,0.000000,-35.265354,-7.836745,-7.836745
57,0,411.0,Nico O'Reilly,a,5.1,DEF,Man City,16.655692,40.0,9.993415,-6.662277,0.000000,-6.662277,3.331138,-6.662277,9.993415
41,0,224.0,Marc Cucurella Saseta,a,6.0,DEF,Chelsea,15.713764,40.0,9.428259,-6.285506,0.000000,-6.285506,3.142753,-6.285506,9.428259
301,0,341.0,Karl Darlow,a,3.9,GK,Leeds,14.620099,40.0,8.772059,-5.848040,0.000000,-5.848040,2.924020,-5.848040,8.772059
285,0,624.0,Jarrod Bowen,a,7.6,FWD,West Ham,28.124955,20.0,22.499964,-5.624991,0.000000,-5.624991,16.874973,-5.624991,22.499964
210,0,47.0,Morgan Rogers,a,7.4,MID,Aston Villa,24.444122,20.0,19.555297,-4.888824,0.000000,-4.888824,14.666473,-4.888824,19.555297
436,0,136.0,Igor Thiago Nascimento Rodrigues,a,7.3,FWD,Brentford,23.232310,20.0,18.585848,-4.646462,0.000000,-4.646462,13.939386,-4.646462,18.585848
29,1,82.0,Antoine Semenyo,a,8.2,MID,Man City,22.558254,120.0,-4.511651,-27.069905,-4.511651,0.000000,-31.581556,-4.511651,-4.511651
167,0,373.0,Virgil van Dijk,a,6.3,DEF,Liverpool,21.561434,20.0,17.249148,-4.312287,0.000000,-4.312287,12.936861,-4.312287,17.249148
386,0,387.0,Dominik Szoboszlai,a,7.1,MID,Liverpool,21.372974,20.0,17.098379,-4.274595,0.000000,-4.274595,12.823784,-4.274595,17.098379
48,0,37.0,Lucas Digne,a,4.5,DEF,Aston Villa,21.361522,20.0,17.089218,-4.272304,0.000000,-4.272304,12.816913,-4.272304,17.089218
144,0,36.0,Matty Cash,a,4.7,DEF,Aston Villa,19.604028,20.0,15.683223,-3.920806,0.000000,-3.920806,11.762417,-3.920806,15.683223
13,0,101.0,Caoimhín Kelleher,a,4.8,GK,Brentford,18.457050,20.0,14.765640,-3.691410,0.000000,-3.691410,11.074230,-3.691410,14.765640
27,0,517.0,Elliot Anderson,a,5.6,MID,Nott'm Forest,18.417245,20.0,14.733796,-3.683449,0.000000,-3.683449,11.050347,-3.683449,14.733796
335,0,110.0,Michael Kayode,a,4.6,DEF,Brentford,18.379083,20.0,14.703266,-3.675817,0.000000,-3.675817,11.027450,-3.675817,14.703266

In [11]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='xpoints_net_gain', ascending=False).head(20)

Best differential picks not in my team for GW34 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,weighted_xpoints_gain,weighted_xpoints_loss,weighted_xpoints_picks_gain,weighted_xpoints_team_picks_loss,xpoints_net_gain,xpoints_net_team_value,blended_score
142,0,64.0,Ollie Watkins,a,8.5,FWD,Aston Villa,34.607056,0.0,34.607056,0.0,0.0,0.0,34.607056,0.0,34.607056
383,0,381.0,Mohamed Salah,a,14.0,MID,Liverpool,29.977532,0.0,29.977532,0.0,0.0,0.0,29.977532,0.0,29.977532
244,0,487.0,Harvey Barnes,a,6.1,MID,Newcastle,27.191660,0.0,27.191660,0.0,0.0,0.0,27.191660,0.0,27.191660
150,0,126.0,Mathias Jensen,a,4.9,MID,Brentford,25.803150,0.0,25.803150,0.0,0.0,0.0,25.803150,0.0,25.803150
354,0,409.0,John Stones,a,5.4,DEF,Man City,25.533462,0.0,25.533462,0.0,0.0,0.0,25.533462,0.0,25.533462
11,0,515.0,Morgan Gibbs-White,a,7.4,MID,Nott'm Forest,25.478694,0.0,25.478694,0.0,0.0,0.0,25.478694,0.0,25.478694
153,0,266.0,Eberechi Eze,a,7.2,MID,Arsenal,25.139946,0.0,25.139946,0.0,0.0,0.0,25.139946,0.0,25.139946
100,0,48.0,Youri Tielemans,a,5.9,MID,Aston Villa,24.320217,0.0,24.320217,0.0,0.0,0.0,24.320217,0.0,24.320217
295,0,416.0,Bernardo Mota Veiga de Carvalho e Silva,a,6.2,MID,Man City,24.231523,0.0,24.231523,0.0,0.0,0.0,24.231523,0.0,24.231523
127,0,6.0,William Saliba,a,6.1,DEF,Arsenal,23.978935,0.0,23.978935,0.0,0.0,0.0,23.978935,0.0,23.978935
173,0,725.0,Piero Hincapié,a,5.1,DEF,Arsenal,23.795349,0.0,23.795349,0.0,0.0,0.0,23.795349,0.0,23.795349
78,0,242.0,Kiernan Dewsbury-Hall,a,5.1,MID,Everton,23.693682,0.0,23.693682,0.0,0.0,0.0,23.693682,0.0,23.693682
328,0,516.0,Callum Hudson-Odoi,d,5.7,MID,Nott'm Forest,23.641909,0.0,23.641909,0.0,0.0,0.0,23.641909,0.0,23.641909
0,0,300.0,Dwight McNeil,a,5.5,MID,Everton,23.579890,0.0,23.579890,0.0,0.0,0.0,23.579890,0.0,23.579890
280,0,20.0,Leandro Trossard,a,6.5,MID,Arsenal,23.434079,0.0,23.434079,0.0,0.0,0.0,23.434079,0.0,23.434079
357,0,54.0,John McGinn,a,5.3,MID,Aston Villa,23.249502,0.0,23.249502,0.0,0.0,0.0,23.249502,0.0,23.249502
51,0,485.0,Anthony Gordon,d,7.4,MID,Newcastle,23.185029,0.0,23.185029,0.0,0.0,0.0,23.185029,0.0,23.185029
162,0,450.0,Matheus Santos Carneiro da Cunha,a,8.0,MID,Man Utd,22.527745,0.0,22.527745,0.0,0.0,0.0,22.527745,0.0,22.527745
290,0,8.0,Jurriën Timber,d,6.2,DEF,Arsenal,22.496889,0.0,22.496889,0.0,0.0,0.0,22.496889,0.0,22.496889
169,0,384.0,Cody Gakpo,a,7.3,MID,Liverpool,22.403215,0.0,22.403215,0.0,0.0,0.0,22.403215,0.0,22.403215

In [12]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £101.7m / £102.4m
Total Weighted Expected Points: 305.25
Remaining Budget: £0.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mads Hermansen                 West Ham     £4.2    18.54
 ✅        Emiliano Martínez Romero       Aston Villa  £5.1    19.42

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Virgil van Dijk                Liverpool    £6.3    21.56
 🪑        Lucas Digne                    Aston Villa  £4.5    21.36
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1    26.25
 ✅        John Stones                    Man City     £5.4    25.53
 ✅        William Saliba                 Arsenal      £6.1    23.98

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Declan Rice                    Arsenal      £7.2    30.42
 ✅        Mohamed Salah                  Liverpool    £14.0   29.98
 ✅        Harvey Barnes                  Newcastle    £6.1    27.19
 ✅        Mathias Jensen                 Brentford    £4.9    25.80
 ✅        Morgan Gibbs-White             Nott'm Forest £7.4    25.48

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.3    23.23
 ✅        Ollie Watkins                  Aston Villa  £8.5    34.61
 ✅        Jarrod Bowen                   West Ham     £7.6    28.12

================================================================================
Optimization Status: Optimal

In [15]:
# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints_net_gain'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=102.4,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £94.5m / £102.4m
Total Weighted Expected Points: 292.59
Remaining Budget: £7.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emiliano Martínez Romero       Aston Villa  £5.1    19.42
 ✅        David Raya Martín              Arsenal      £6.0    21.80

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Reece James                    Chelsea      £5.6    20.05
 🪑        El Hadji Malick Diouf          West Ham     £4.1    20.12
 ✅        William Saliba                 Arsenal      £6.1    23.98
 ✅        Piero Hincapié                 Arsenal      £5.1    23.80
 ✅        John Stones                    Man City     £5.4    25.53

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Morgan Gibbs-White             Nott'm Forest £7.4    25.48
 ✅        Youri Tielemans                Aston Villa  £5.9    24.32
 ✅        Mathias Jensen                 Brentford    £4.9    25.80
 ✅        Harvey Barnes                  Newcastle    £6.1    27.19
 ✅        Mohamed Salah                  Liverpool    £14.0   29.98

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brian Brobbey                  Sunderland   £5.3    20.08
 ✅        Norberto Bercique Gomes Betuncal Everton      £5.0    22.14
 ✅        Ollie Watkins                  Aston Villa  £8.5    34.61

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {picks_current_gameweek+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,35.0,Ollie Watkins,a,FWD,Aston Villa,Spurs,8.5,7.397869
1,36.0,Ollie Watkins,a,FWD,Aston Villa,Burnley,8.5,7.362627
2,34.0,Ollie Watkins,a,FWD,Aston Villa,Fulham,8.5,6.658193
3,38.0,Ollie Watkins,a,FWD,Aston Villa,Man City,8.5,6.609966
4,37.0,Ollie Watkins,a,FWD,Aston Villa,Liverpool,8.5,6.578401
5,37.0,John Stones,a,DEF,Man City,Bournemouth,5.4,6.551213
6,38.0,Mohamed Salah,a,MID,Liverpool,Brentford,14.0,6.515501
7,37.0,Declan Rice,a,MID,Arsenal,Burnley,7.2,6.457361
8,35.0,John Stones,a,DEF,Man City,Everton,5.4,6.447768
9,36.0,John Stones,a,DEF,Man City,Brentford,5.4,6.407228

In [17]:
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW34 to GW38...

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.3m / £102.4m
Total Weighted Expected Points: 59.24
Remaining Budget: £3.1m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        José Malheiro de Sá            Wolves       £4.2     3.84
 ✅        David Raya Martín              Arsenal      £6.0     4.07

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Séamus Coleman                 Everton      £4.2     4.42
 🪑        El Hadji Malick Diouf          West Ham     £4.1     4.40
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     4.77
 ✅        Virgil van Dijk                Liverpool    £6.3     4.71
 ✅        Nathan Patterson               Everton      £4.4     4.49

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mohamed Salah                  Liverpool    £14.0    6.06
 ✅        Declan Rice                    Arsenal      £7.2     5.91
 ✅        Mathias Jensen                 Brentford    £4.9     5.13
 ✅        Harvey Barnes                  Newcastle    £6.1     5.07
 ✅        Morgan Gibbs-White             Nott'm Forest £7.4     5.02

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.3     4.66
 ✅        Ollie Watkins                  Aston Villa  £8.5     6.66
 ✅        Jarrod Bowen                   West Ham     £7.6     5.61

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £101.4m / £102.4m
Total Weighted Expected Points: 64.66
Remaining Budget: £1.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        David Raya Martín              Arsenal      £6.0     4.20
 ✅        Emiliano Martínez Romero       Aston Villa  £5.1     4.40

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Lucas Digne                    Aston Villa  £4.5     4.80
 🪑        Pascal Struijk                 Leeds        £4.3     4.67
 ✅        John Stones                    Man City     £5.4     6.45
 ✅        Reece James                    Chelsea      £5.6     5.04
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     4.87

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     6.24
 ✅        Declan Rice                    Arsenal      £7.2     5.94
 ✅        Mohamed Salah                  Liverpool    £14.0    5.81
 ✅        Antoine Semenyo                Man City     £8.2     5.68
 ✅        Harvey Barnes                  Newcastle    £6.1     5.36

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.6     4.88
 ✅        Ollie Watkins                  Aston Villa  £8.5     7.40
 ✅        Jarrod Bowen                   West Ham     £7.6     5.61

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £102.0m / £102.4m
Total Weighted Expected Points: 66.80
Remaining Budget: £0.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Emiliano Martínez Romero       Aston Villa  £5.1     4.58
 ✅        David Raya Martín              Arsenal      £6.0     4.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Reece James                    Chelsea      £5.6     4.59
 🪑        Olivier Boscagli               Brighton     £4.2     4.57
 ✅        John Stones                    Man City     £5.4     6.41
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     5.83
 ✅        Lucas Digne                    Aston Villa  £4.5     5.66

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     6.19
 ✅        Declan Rice                    Arsenal      £7.2     6.11
 ✅        Mohamed Salah                  Liverpool    £14.0    5.94
 ✅        Antoine Semenyo                Man City     £8.2     5.67
 ✅        Harvey Barnes                  Newcastle    £6.1     5.47

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.3     5.06
 ✅        Ollie Watkins                  Aston Villa  £8.5     7.36
 ✅        Jarrod Bowen                   West Ham     £7.6     5.51

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £101.5m / £102.4m
Total Weighted Expected Points: 66.28
Remaining Budget: £0.9m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bernd Leno                     Fulham       £4.9     3.95
 ✅        David Raya Martín              Arsenal      £6.0     4.69

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        El Hadji Malick Diouf          West Ham     £4.1     4.39
 🪑        Timothy Castagne               Fulham       £4.3     4.34
 ✅        John Stones                    Man City     £5.4     6.55
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     6.30
 ✅        Reece James                    Chelsea      £5.6     5.45

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Declan Rice                    Arsenal      £7.2     6.46
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     6.09
 ✅        Mohamed Salah                  Liverpool    £14.0    5.65
 ✅        Harvey Barnes                  Newcastle    £6.1     5.59
 ✅        Antoine Semenyo                Man City     £8.2     5.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Danny Welbeck                  Brighton     £6.3     4.78
 ✅        Ollie Watkins                  Aston Villa  £8.5     6.58
 ✅        Jarrod Bowen                   West Ham     £7.6     5.60

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £101.6m / £102.4m
Total Weighted Expected Points: 63.33
Remaining Budget: £0.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        José Malheiro de Sá            Wolves       £4.2     3.95
 ✅        David Raya Martín              Arsenal      £6.0     4.06

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Adrien Truffert                Bournemouth  £4.7     4.37
 🪑        Marcos Senesi Barón            Bournemouth  £5.2     4.20
 ✅        John Stones                    Man City     £5.4     6.13
 ✅        Reece James                    Chelsea      £5.6     4.96
 ✅        Gabriel dos Santos Magalhães   Arsenal      £7.1     4.47

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mohamed Salah                  Liverpool    £14.0    6.52
 ✅        Declan Rice                    Arsenal      £7.2     6.01
 ✅        Bernardo Mota Veiga de Carvalho e Silva Man City     £6.2     5.72
 ✅        Harvey Barnes                  Newcastle    £6.1     5.70
 ✅        Antoine Semenyo                Man City     £8.2     5.62

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Dominic Calvert-Lewin          Leeds        £5.6     4.80
 ✅        Ollie Watkins                  Aston Villa  £8.5     6.61
 ✅        Jarrod Bowen                   West Ham     £7.6     5.79

================================================================================
Optimization Status: Optimal

In [18]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 36

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
24,36,Bernardo Mota Veiga de Carvalho e Silva,a,MID,Man City,Brentford,6.2,6.185347
25,36,Declan Rice,a,MID,Arsenal,West Ham,7.2,6.110255
26,36,Mohamed Salah,a,MID,Liverpool,Chelsea,14.0,5.941173
28,36,Antoine Semenyo,a,MID,Man City,Brentford,8.2,5.672343
31,36,Harvey Barnes,a,MID,Newcastle,Nott'm Forest,6.1,5.473620
32,36,David Raya Martín,a,GK,Arsenal,West Ham,6.0,4.763374
22,36,Ollie Watkins,a,FWD,Aston Villa,Burnley,8.5,7.362627
30,36,Jarrod Bowen,a,FWD,West Ham,Arsenal,7.6,5.508972
23,36,John Stones,a,DEF,Man City,Brentford,5.4,6.407228
27,36,Gabriel dos Santos Magalhães,a,DEF,Arsenal,West Ham,7.1,5.833501
29,36,Lucas Digne,a,DEF,Aston Villa,Burnley,4.5,5.660373

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)