In [1]:
import pandas as pd
import time

# requirements: pip install pulp

In [2]:
start=time.perf_counter()

In [3]:
#add this info to a settings dict?
current_gw = 7 #predictions from gw+1
current_season = 20262027
divx_team_code = 5049406 # My 26/27 divx team code

In [4]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [5]:
from FPL_League_Data_Scraper import FPL_League_Data_Scraper

league_code = "1081956"

#Run Data Scraper for DivX league
if __name__ == "__main__":
    divx = FPL_League_Data_Scraper(league_code, current_season)
    divx_picksdf, membergw_summary = divx.scrape_picks()

#Add a new staging table & data into the database
divx_picks = divx_picksdf[['member', 'memberid','season', 'gw', 'pick', 
                 'element', 'position', 'multiplier', 
                 'is_captain', 'is_vice_captain']]

table_name = f"divx_picks_{current_season}"
if __name__ == "__main__":
    db_creator.create_staging_table_then_insert_data(table_name, data=divx_picks)
    divx_picks = db_creator.table_to_df(table_name=table_name)
    print(divx_picks.info())

Data fetched, league name:  DIV X
Fetched history for Stephen Collier (ID: 391266)
Fetched history for Joe Meader (ID: 2881244)
Fetched history for Christopher Harris (ID: 5049406)
Fetched history for Bernard Chalk (ID: 4184853)
Fetched history for Marcin Wichlinski (ID: 4010004)
Fetched history for Ollie Carroll (ID: 4913097)
Fetched history for Christopher Collier (ID: 4705527)
Fetched history for Anthony Collier (ID: 5037473)
Fetched history for Callum Harling (ID: 3081288)
Fetched history for Samia Shelim (ID: 678874)
Fetched history for Christopher Harris (ID: 4486919)
Fetched history for Luiton Fernandes (ID: 3060165)
Fetched history for Jack Carroll (ID: 4355821)
Fetched history for Ryan Boyce (ID: 4036890)
Fetched history for Tommy Davies (ID: 3340544)
Fetched history for Conner Harling (ID: 4484147)
Fetched history for Tajwar Shelim (ID: 4512122)
Fetched history for Christakis Christodoulou (ID: 5691733)
Fetched history for Omari Douglas-Rankine (ID: 8921685)
Max gameweek data available for is:  8
391266 Stephen Collier GW 1 Pick 1
391266 Stephen Collier GW 1 Pick 2
391266 Stephen Collier GW 1 Pick 3
391266 Stephen Collier GW 1 Pick 4
391266 Stephen Collier GW 1 Pick 5
391266 Stephen Collier GW 1 Pick 6
391266 Stephen Collier GW 1 Pick 7
391266 Stephen Collier GW 1 Pick 8
391266 Stephen Collier GW 1 Pick 9
391266 Stephen Collier GW 1 Pick 10
391266 Stephen Collier GW 1 Pick 11
391266 Stephen Collier GW 1 Pick 12
391266 Stephen Collier GW 1 Pick 13
391266 Stephen Collier GW 1 Pick 14
391266 Stephen Collier GW 1 Pick 15
391266 Stephen Collier GW 2 Pick 1
391266 Stephen Collier GW 2 Pick 2
391266 Stephen Collier GW 2 Pick 3
391266 Stephen Collier GW 2 Pick 4
391266 Stephen Collier GW 2 Pick 5
391266 Stephen Collier GW 2 Pick 6
391266 Stephen Collier GW 2 Pick 7
391266 Stephen Collier GW 2 Pick 8
391266 Stephen Collier GW 2 Pick 9
391266 Stephen Collier GW 2 Pick 10
391266 Stephen Collier GW 2 Pick 11
391266 Stephen Collier GW 2 Pick 12
391266 Stephen Collier GW 2 Pick 13
391266 Stephen Collier GW 2 Pick 14
391266 Stephen Collier GW 2 Pick 15
391266 Stephen Collier GW 3 Pick 1
391266 Stephen Collier GW 3 Pick 2
391266 Stephen Collier GW 3 Pick 3
391266 Stephen Collier GW 3 Pick 4
391266 Stephen Collier GW 3 Pick 5
391266 Stephen Collier GW 3 Pick 6
391266 Stephen Collier GW 3 Pick 7
391266 Stephen Collier GW 3 Pick 8
391266 Stephen Collier GW 3 Pick 9
391266 Stephen Collier GW 3 Pick 10
391266 Stephen Collier GW 3 Pick 11
391266 Stephen Collier GW 3 Pick 12
391266 Stephen Collier GW 3 Pick 13
391266 Stephen Collier GW 3 Pick 14
391266 Stephen Collier GW 3 Pick 15
391266 Stephen Collier GW 4 Pick 1
391266 Stephen Collier GW 4 Pick 2
391266 Stephen Collier GW 4 Pick 3
391266 Stephen Collier GW 4 Pick 4
391266 Stephen Collier GW 4 Pick 5
391266 Stephen Collier GW 4 Pick 6
391266 Stephen Collier GW 4 Pick 7
391266 Stephen Collier GW 4 Pick 8
391266 Stephen Collier GW 4 Pick 9
391266 Stephen Collier GW 4 Pick 10
391266 Stephen Collier GW 4 Pick 11
391266 Stephen Collier GW 4 Pick 12
391266 Stephen Collier GW 4 Pick 13
391266 Stephen Collier GW 4 Pick 14
391266 Stephen Collier GW 4 Pick 15
391266 Stephen Collier GW 5 Pick 1
391266 Stephen Collier GW 5 Pick 2
391266 Stephen Collier GW 5 Pick 3
391266 Stephen Collier GW 5 Pick 4
391266 Stephen Collier GW 5 Pick 5
391266 Stephen Collier GW 5 Pick 6
391266 Stephen Collier GW 5 Pick 7
391266 Stephen Collier GW 5 Pick 8
391266 Stephen Collier GW 5 Pick 9
391266 Stephen Collier GW 5 Pick 10
391266 Stephen Collier GW 5 Pick 11
391266 Stephen Collier GW 5 Pick 12
391266 Stephen Collier GW 5 Pick 13
391266 Stephen Collier GW 5 Pick 14
391266 Stephen Collier GW 5 Pick 15
391266 Stephen Collier GW 6 Pick 1
391266 Stephen Collier GW 6 Pick 2
391266 Stephen Collier GW 6 Pick 3
391266 Stephen Collier GW 6 Pick 4
391266 Stephen Collier GW 6 Pick 5
391266 Stephen Collier GW 6 Pick 6
391266 Stephen Collier GW 6 Pick 7
391266 Stephen Collier GW 6 Pick 8
391266 Stephen Collier GW 6 Pick 9
391266 Stephen Collier GW 6 Pick 10
391266 Stephen Collier GW 6 Pick 11
391266 Stephen Collier GW 6 Pick 12
391266 Stephen Collier GW 6 Pick 13
391266 Stephen Collier GW 6 Pick 14
391266 Stephen Collier GW 6 Pick 15
391266 Stephen Collier GW 7 Pick 1
391266 Stephen Collier GW 7 Pick 2
391266 Stephen Collier GW 7 Pick 3
391266 Stephen Collier GW 7 Pick 4
391266 Stephen Collier GW 7 Pick 5
391266 Stephen Collier GW 7 Pick 6
391266 Stephen Collier GW 7 Pick 7
391266 Stephen Collier GW 7 Pick 8
391266 Stephen Collier GW 7 Pick 9
391266 Stephen Collier GW 7 Pick 10
391266 Stephen Collier GW 7 Pick 11
391266 Stephen Collier GW 7 Pick 12
391266 Stephen Collier GW 7 Pick 13
391266 Stephen Collier GW 7 Pick 14
391266 Stephen Collier GW 7 Pick 15
2881244 Joe Meader GW 1 Pick 1
2881244 Joe Meader GW 1 Pick 2
2881244 Joe Meader GW 1 Pick 3
2881244 Joe Meader GW 1 Pick 4
2881244 Joe Meader GW 1 Pick 5
2881244 Joe Meader GW 1 Pick 6
2881244 Joe Meader GW 1 Pick 7
2881244 Joe Meader GW 1 Pick 8
2881244 Joe Meader GW 1 Pick 9
2881244 Joe Meader GW 1 Pick 10
2881244 Joe Meader GW 1 Pick 11
2881244 Joe Meader GW 1 Pick 12
2881244 Joe Meader GW 1 Pick 13
2881244 Joe Meader GW 1 Pick 14
2881244 Joe Meader GW 1 Pick 15
2881244 Joe Meader GW 2 Pick 1
2881244 Joe Meader GW 2 Pick 2
2881244 Joe Meader GW 2 Pick 3
2881244 Joe Meader GW 2 Pick 4
2881244 Joe Meader GW 2 Pick 5
2881244 Joe Meader GW 2 Pick 6
2881244 Joe Meader GW 2 Pick 7
2881244 Joe Meader GW 2 Pick 8
2881244 Joe Meader GW 2 Pick 9
2881244 Joe Meader GW 2 Pick 10
2881244 Joe Meader GW 2 Pick 11
2881244 Joe Meader GW 2 Pick 12
2881244 Joe Meader GW 2 Pick 13
2881244 Joe Meader GW 2 Pick 14
2881244 Joe Meader GW 2 Pick 15
2881244 Joe Meader GW 3 Pick 1
2881244 Joe Meader GW 3 Pick 2
2881244 Joe Meader GW 3 Pick 3
2881244 Joe Meader GW 3 Pick 4
2881244 Joe Meader GW 3 Pick 5
2881244 Joe Meader GW 3 Pick 6
2881244 Joe Meader GW 3 Pick 7
2881244 Joe Meader GW 3 Pick 8
2881244 Joe Meader GW 3 Pick 9
2881244 Joe Meader GW 3 Pick 10
2881244 Joe Meader GW 3 Pick 11
2881244 Joe Meader GW 3 Pick 12
2881244 Joe Meader GW 3 Pick 13
2881244 Joe Meader GW 3 Pick 14
2881244 Joe Meader GW 3 Pick 15
2881244 Joe Meader GW 4 Pick 1
2881244 Joe Meader GW 4 Pick 2
2881244 Joe Meader GW 4 Pick 3
2881244 Joe Meader GW 4 Pick 4
2881244 Joe Meader GW 4 Pick 5
2881244 Joe Meader GW 4 Pick 6
2881244 Joe Meader GW 4 Pick 7
2881244 Joe Meader GW 4 Pick 8
2881244 Joe Meader GW 4 Pick 9
2881244 Joe Meader GW 4 Pick 10
2881244 Joe Meader GW 4 Pick 11
2881244 Joe Meader GW 4 Pick 12
2881244 Joe Meader GW 4 Pick 13
2881244 Joe Meader GW 4 Pick 14
2881244 Joe Meader GW 4 Pick 15
2881244 Joe Meader GW 5 Pick 1
2881244 Joe Meader GW 5 Pick 2
2881244 Joe Meader GW 5 Pick 3
2881244 Joe Meader GW 5 Pick 4
2881244 Joe Meader GW 5 Pick 5
2881244 Joe Meader GW 5 Pick 6
2881244 Joe Meader GW 5 Pick 7
2881244 Joe Meader GW 5 Pick 8
2881244 Joe Meader GW 5 Pick 9
2881244 Joe Meader GW 5 Pick 10
2881244 Joe Meader GW 5 Pick 11
2881244 Joe Meader GW 5 Pick 12
2881244 Joe Meader GW 5 Pick 13
2881244 Joe Meader GW 5 Pick 14
2881244 Joe Meader GW 5 Pick 15
2881244 Joe Meader GW 6 Pick 1
2881244 Joe Meader GW 6 Pick 2
2881244 Joe Meader GW 6 Pick 3
2881244 Joe Meader GW 6 Pick 4
2881244 Joe Meader GW 6 Pick 5
2881244 Joe Meader GW 6 Pick 6
2881244 Joe Meader GW 6 Pick 7
2881244 Joe Meader GW 6 Pick 8
2881244 Joe Meader GW 6 Pick 9
2881244 Joe Meader GW 6 Pick 10
2881244 Joe Meader GW 6 Pick 11
2881244 Joe Meader GW 6 Pick 12
2881244 Joe Meader GW 6 Pick 13
2881244 Joe Meader GW 6 Pick 14
2881244 Joe Meader GW 6 Pick 15
2881244 Joe Meader GW 7 Pick 1
2881244 Joe Meader GW 7 Pick 2
2881244 Joe Meader GW 7 Pick 3
2881244 Joe Meader GW 7 Pick 4
2881244 Joe Meader GW 7 Pick 5
2881244 Joe Meader GW 7 Pick 6
2881244 Joe Meader GW 7 Pick 7
2881244 Joe Meader GW 7 Pick 8
2881244 Joe Meader GW 7 Pick 9
2881244 Joe Meader GW 7 Pick 10
2881244 Joe Meader GW 7 Pick 11
2881244 Joe Meader GW 7 Pick 12
2881244 Joe Meader GW 7 Pick 13
2881244 Joe Meader GW 7 Pick 14
2881244 Joe Meader GW 7 Pick 15
5049406 Christopher Harris GW 1 Pick 1
5049406 Christopher Harris GW 1 Pick 2
5049406 Christopher Harris GW 1 Pick 3
5049406 Christopher Harris GW 1 Pick 4
5049406 Christopher Harris GW 1 Pick 5
5049406 Christopher Harris GW 1 Pick 6
5049406 Christopher Harris GW 1 Pick 7
5049406 Christopher Harris GW 1 Pick 8
5049406 Christopher Harris GW 1 Pick 9
5049406 Christopher Harris GW 1 Pick 10
5049406 Christopher Harris GW 1 Pick 11
5049406 Christopher Harris GW 1 Pick 12
5049406 Christopher Harris GW 1 Pick 13
5049406 Christopher Harris GW 1 Pick 14
5049406 Christopher Harris GW 1 Pick 15
5049406 Christopher Harris GW 2 Pick 1
5049406 Christopher Harris GW 2 Pick 2
5049406 Christopher Harris GW 2 Pick 3
5049406 Christopher Harris GW 2 Pick 4
5049406 Christopher Harris GW 2 Pick 5
5049406 Christopher Harris GW 2 Pick 6
5049406 Christopher Harris GW 2 Pick 7
5049406 Christopher Harris GW 2 Pick 8
5049406 Christopher Harris GW 2 Pick 9
5049406 Christopher Harris GW 2 Pick 10
5049406 Christopher Harris GW 2 Pick 11
5049406 Christopher Harris GW 2 Pick 12
5049406 Christopher Harris GW 2 Pick 13
5049406 Christopher Harris GW 2 Pick 14
5049406 Christopher Harris GW 2 Pick 15
5049406 Christopher Harris GW 3 Pick 1
5049406 Christopher Harris GW 3 Pick 2
5049406 Christopher Harris GW 3 Pick 3
5049406 Christopher Harris GW 3 Pick 4
5049406 Christopher Harris GW 3 Pick 5
5049406 Christopher Harris GW 3 Pick 6
5049406 Christopher Harris GW 3 Pick 7
5049406 Christopher Harris GW 3 Pick 8
5049406 Christopher Harris GW 3 Pick 9
5049406 Christopher Harris GW 3 Pick 10
5049406 Christopher Harris GW 3 Pick 11
5049406 Christopher Harris GW 3 Pick 12
5049406 Christopher Harris GW 3 Pick 13
5049406 Christopher Harris GW 3 Pick 14
5049406 Christopher Harris GW 3 Pick 15
5049406 Christopher Harris GW 4 Pick 1
5049406 Christopher Harris GW 4 Pick 2
5049406 Christopher Harris GW 4 Pick 3
5049406 Christopher Harris GW 4 Pick 4
5049406 Christopher Harris GW 4 Pick 5
5049406 Christopher Harris GW 4 Pick 6
5049406 Christopher Harris GW 4 Pick 7
5049406 Christopher Harris GW 4 Pick 8
5049406 Christopher Harris GW 4 Pick 9
5049406 Christopher Harris GW 4 Pick 10
5049406 Christopher Harris GW 4 Pick 11
5049406 Christopher Harris GW 4 Pick 12
5049406 Christopher Harris GW 4 Pick 13
5049406 Christopher Harris GW 4 Pick 14
5049406 Christopher Harris GW 4 Pick 15
5049406 Christopher Harris GW 5 Pick 1
5049406 Christopher Harris GW 5 Pick 2
5049406 Christopher Harris GW 5 Pick 3
5049406 Christopher Harris GW 5 Pick 4
5049406 Christopher Harris GW 5 Pick 5
5049406 Christopher Harris GW 5 Pick 6
5049406 Christopher Harris GW 5 Pick 7
5049406 Christopher Harris GW 5 Pick 8
5049406 Christopher Harris GW 5 Pick 9
5049406 Christopher Harris GW 5 Pick 10
5049406 Christopher Harris GW 5 Pick 11
5049406 Christopher Harris GW 5 Pick 12
5049406 Christopher Harris GW 5 Pick 13
5049406 Christopher Harris GW 5 Pick 14
5049406 Christopher Harris GW 5 Pick 15
5049406 Christopher Harris GW 6 Pick 1
5049406 Christopher Harris GW 6 Pick 2
5049406 Christopher Harris GW 6 Pick 3
5049406 Christopher Harris GW 6 Pick 4
5049406 Christopher Harris GW 6 Pick 5
5049406 Christopher Harris GW 6 Pick 6
5049406 Christopher Harris GW 6 Pick 7
5049406 Christopher Harris GW 6 Pick 8
5049406 Christopher Harris GW 6 Pick 9
5049406 Christopher Harris GW 6 Pick 10
5049406 Christopher Harris GW 6 Pick 11
5049406 Christopher Harris GW 6 Pick 12
5049406 Christopher Harris GW 6 Pick 13
5049406 Christopher Harris GW 6 Pick 14
5049406 Christopher Harris GW 6 Pick 15
5049406 Christopher Harris GW 7 Pick 1
5049406 Christopher Harris GW 7 Pick 2
5049406 Christopher Harris GW 7 Pick 3
5049406 Christopher Harris GW 7 Pick 4
5049406 Christopher Harris GW 7 Pick 5
5049406 Christopher Harris GW 7 Pick 6
5049406 Christopher Harris GW 7 Pick 7
5049406 Christopher Harris GW 7 Pick 8
5049406 Christopher Harris GW 7 Pick 9
5049406 Christopher Harris GW 7 Pick 10
5049406 Christopher Harris GW 7 Pick 11
5049406 Christopher Harris GW 7 Pick 12
5049406 Christopher Harris GW 7 Pick 13
5049406 Christopher Harris GW 7 Pick 14
5049406 Christopher Harris GW 7 Pick 15
4184853 Bernard Chalk GW 1 Pick 1
4184853 Bernard Chalk GW 1 Pick 2
4184853 Bernard Chalk GW 1 Pick 3
4184853 Bernard Chalk GW 1 Pick 4
4184853 Bernard Chalk GW 1 Pick 5
4184853 Bernard Chalk GW 1 Pick 6
4184853 Bernard Chalk GW 1 Pick 7
4184853 Bernard Chalk GW 1 Pick 8
4184853 Bernard Chalk GW 1 Pick 9
4184853 Bernard Chalk GW 1 Pick 10
4184853 Bernard Chalk GW 1 Pick 11
4184853 Bernard Chalk GW 1 Pick 12
4184853 Bernard Chalk GW 1 Pick 13
4184853 Bernard Chalk GW 1 Pick 14
4184853 Bernard Chalk GW 1 Pick 15
4184853 Bernard Chalk GW 2 Pick 1
4184853 Bernard Chalk GW 2 Pick 2
4184853 Bernard Chalk GW 2 Pick 3
4184853 Bernard Chalk GW 2 Pick 4
4184853 Bernard Chalk GW 2 Pick 5
4184853 Bernard Chalk GW 2 Pick 6
4184853 Bernard Chalk GW 2 Pick 7
4184853 Bernard Chalk GW 2 Pick 8
4184853 Bernard Chalk GW 2 Pick 9
4184853 Bernard Chalk GW 2 Pick 10
4184853 Bernard Chalk GW 2 Pick 11
4184853 Bernard Chalk GW 2 Pick 12
4184853 Bernard Chalk GW 2 Pick 13
4184853 Bernard Chalk GW 2 Pick 14
4184853 Bernard Chalk GW 2 Pick 15
4184853 Bernard Chalk GW 3 Pick 1
4184853 Bernard Chalk GW 3 Pick 2
4184853 Bernard Chalk GW 3 Pick 3
4184853 Bernard Chalk GW 3 Pick 4
4184853 Bernard Chalk GW 3 Pick 5
4184853 Bernard Chalk GW 3 Pick 6
4184853 Bernard Chalk GW 3 Pick 7
4184853 Bernard Chalk GW 3 Pick 8
4184853 Bernard Chalk GW 3 Pick 9
4184853 Bernard Chalk GW 3 Pick 10
4184853 Bernard Chalk GW 3 Pick 11
4184853 Bernard Chalk GW 3 Pick 12
4184853 Bernard Chalk GW 3 Pick 13
4184853 Bernard Chalk GW 3 Pick 14
4184853 Bernard Chalk GW 3 Pick 15
4184853 Bernard Chalk GW 4 Pick 1
4184853 Bernard Chalk GW 4 Pick 2
4184853 Bernard Chalk GW 4 Pick 3
4184853 Bernard Chalk GW 4 Pick 4
4184853 Bernard Chalk GW 4 Pick 5
4184853 Bernard Chalk GW 4 Pick 6
4184853 Bernard Chalk GW 4 Pick 7
4184853 Bernard Chalk GW 4 Pick 8
4184853 Bernard Chalk GW 4 Pick 9
4184853 Bernard Chalk GW 4 Pick 10
4184853 Bernard Chalk GW 4 Pick 11
4184853 Bernard Chalk GW 4 Pick 12
4184853 Bernard Chalk GW 4 Pick 13
4184853 Bernard Chalk GW 4 Pick 14
4184853 Bernard Chalk GW 4 Pick 15
4184853 Bernard Chalk GW 5 Pick 1
4184853 Bernard Chalk GW 5 Pick 2
4184853 Bernard Chalk GW 5 Pick 3
4184853 Bernard Chalk GW 5 Pick 4
4184853 Bernard Chalk GW 5 Pick 5
4184853 Bernard Chalk GW 5 Pick 6
4184853 Bernard Chalk GW 5 Pick 7
4184853 Bernard Chalk GW 5 Pick 8
4184853 Bernard Chalk GW 5 Pick 9
4184853 Bernard Chalk GW 5 Pick 10
4184853 Bernard Chalk GW 5 Pick 11
4184853 Bernard Chalk GW 5 Pick 12
4184853 Bernard Chalk GW 5 Pick 13
4184853 Bernard Chalk GW 5 Pick 14
4184853 Bernard Chalk GW 5 Pick 15
4184853 Bernard Chalk GW 6 Pick 1
4184853 Bernard Chalk GW 6 Pick 2
4184853 Bernard Chalk GW 6 Pick 3
4184853 Bernard Chalk GW 6 Pick 4
4184853 Bernard Chalk GW 6 Pick 5
4184853 Bernard Chalk GW 6 Pick 6
4184853 Bernard Chalk GW 6 Pick 7
4184853 Bernard Chalk GW 6 Pick 8
4184853 Bernard Chalk GW 6 Pick 9
4184853 Bernard Chalk GW 6 Pick 10
4184853 Bernard Chalk GW 6 Pick 11
4184853 Bernard Chalk GW 6 Pick 12
4184853 Bernard Chalk GW 6 Pick 13
4184853 Bernard Chalk GW 6 Pick 14
4184853 Bernard Chalk GW 6 Pick 15
4184853 Bernard Chalk GW 7 Pick 1
4184853 Bernard Chalk GW 7 Pick 2
4184853 Bernard Chalk GW 7 Pick 3
4184853 Bernard Chalk GW 7 Pick 4
4184853 Bernard Chalk GW 7 Pick 5
4184853 Bernard Chalk GW 7 Pick 6
4184853 Bernard Chalk GW 7 Pick 7
4184853 Bernard Chalk GW 7 Pick 8
4184853 Bernard Chalk GW 7 Pick 9
4184853 Bernard Chalk GW 7 Pick 10
4184853 Bernard Chalk GW 7 Pick 11
4184853 Bernard Chalk GW 7 Pick 12
4184853 Bernard Chalk GW 7 Pick 13
4184853 Bernard Chalk GW 7 Pick 14
4184853 Bernard Chalk GW 7 Pick 15
4010004 Marcin Wichlinski GW 1 Pick 1
4010004 Marcin Wichlinski GW 1 Pick 2
4010004 Marcin Wichlinski GW 1 Pick 3
4010004 Marcin Wichlinski GW 1 Pick 4
4010004 Marcin Wichlinski GW 1 Pick 5
4010004 Marcin Wichlinski GW 1 Pick 6
4010004 Marcin Wichlinski GW 1 Pick 7
4010004 Marcin Wichlinski GW 1 Pick 8
4010004 Marcin Wichlinski GW 1 Pick 9
4010004 Marcin Wichlinski GW 1 Pick 10
4010004 Marcin Wichlinski GW 1 Pick 11
4010004 Marcin Wichlinski GW 1 Pick 12
4010004 Marcin Wichlinski GW 1 Pick 13
4010004 Marcin Wichlinski GW 1 Pick 14
4010004 Marcin Wichlinski GW 1 Pick 15
4010004 Marcin Wichlinski GW 2 Pick 1
4010004 Marcin Wichlinski GW 2 Pick 2
4010004 Marcin Wichlinski GW 2 Pick 3
4010004 Marcin Wichlinski GW 2 Pick 4
4010004 Marcin Wichlinski GW 2 Pick 5
4010004 Marcin Wichlinski GW 2 Pick 6
4010004 Marcin Wichlinski GW 2 Pick 7
4010004 Marcin Wichlinski GW 2 Pick 8
4010004 Marcin Wichlinski GW 2 Pick 9
4010004 Marcin Wichlinski GW 2 Pick 10
4010004 Marcin Wichlinski GW 2 Pick 11
4010004 Marcin Wichlinski GW 2 Pick 12
4010004 Marcin Wichlinski GW 2 Pick 13
4010004 Marcin Wichlinski GW 2 Pick 14
4010004 Marcin Wichlinski GW 2 Pick 15
4010004 Marcin Wichlinski GW 3 Pick 1
4010004 Marcin Wichlinski GW 3 Pick 2
4010004 Marcin Wichlinski GW 3 Pick 3
4010004 Marcin Wichlinski GW 3 Pick 4
4010004 Marcin Wichlinski GW 3 Pick 5
4010004 Marcin Wichlinski GW 3 Pick 6
4010004 Marcin Wichlinski GW 3 Pick 7
4010004 Marcin Wichlinski GW 3 Pick 8
4010004 Marcin Wichlinski GW 3 Pick 9
4010004 Marcin Wichlinski GW 3 Pick 10
4010004 Marcin Wichlinski GW 3 Pick 11
4010004 Marcin Wichlinski GW 3 Pick 12
4010004 Marcin Wichlinski GW 3 Pick 13
4010004 Marcin Wichlinski GW 3 Pick 14
4010004 Marcin Wichlinski GW 3 Pick 15
4010004 Marcin Wichlinski GW 4 Pick 1
4010004 Marcin Wichlinski GW 4 Pick 2
4010004 Marcin Wichlinski GW 4 Pick 3
4010004 Marcin Wichlinski GW 4 Pick 4
4010004 Marcin Wichlinski GW 4 Pick 5
4010004 Marcin Wichlinski GW 4 Pick 6
4010004 Marcin Wichlinski GW 4 Pick 7
4010004 Marcin Wichlinski GW 4 Pick 8
4010004 Marcin Wichlinski GW 4 Pick 9
4010004 Marcin Wichlinski GW 4 Pick 10
4010004 Marcin Wichlinski GW 4 Pick 11
4010004 Marcin Wichlinski GW 4 Pick 12
4010004 Marcin Wichlinski GW 4 Pick 13
4010004 Marcin Wichlinski GW 4 Pick 14
4010004 Marcin Wichlinski GW 4 Pick 15
4010004 Marcin Wichlinski GW 5 Pick 1
4010004 Marcin Wichlinski GW 5 Pick 2
4010004 Marcin Wichlinski GW 5 Pick 3
4010004 Marcin Wichlinski GW 5 Pick 4
4010004 Marcin Wichlinski GW 5 Pick 5
4010004 Marcin Wichlinski GW 5 Pick 6
4010004 Marcin Wichlinski GW 5 Pick 7
4010004 Marcin Wichlinski GW 5 Pick 8
4010004 Marcin Wichlinski GW 5 Pick 9
4010004 Marcin Wichlinski GW 5 Pick 10
4010004 Marcin Wichlinski GW 5 Pick 11
4010004 Marcin Wichlinski GW 5 Pick 12
4010004 Marcin Wichlinski GW 5 Pick 13
4010004 Marcin Wichlinski GW 5 Pick 14
4010004 Marcin Wichlinski GW 5 Pick 15
4010004 Marcin Wichlinski GW 6 Pick 1
4010004 Marcin Wichlinski GW 6 Pick 2
4010004 Marcin Wichlinski GW 6 Pick 3
4010004 Marcin Wichlinski GW 6 Pick 4
4010004 Marcin Wichlinski GW 6 Pick 5
4010004 Marcin Wichlinski GW 6 Pick 6
4010004 Marcin Wichlinski GW 6 Pick 7
4010004 Marcin Wichlinski GW 6 Pick 8
4010004 Marcin Wichlinski GW 6 Pick 9
4010004 Marcin Wichlinski GW 6 Pick 10
4010004 Marcin Wichlinski GW 6 Pick 11
4010004 Marcin Wichlinski GW 6 Pick 12
4010004 Marcin Wichlinski GW 6 Pick 13
4010004 Marcin Wichlinski GW 6 Pick 14
4010004 Marcin Wichlinski GW 6 Pick 15
4010004 Marcin Wichlinski GW 7 Pick 1
4010004 Marcin Wichlinski GW 7 Pick 2
4010004 Marcin Wichlinski GW 7 Pick 3
4010004 Marcin Wichlinski GW 7 Pick 4
4010004 Marcin Wichlinski GW 7 Pick 5
4010004 Marcin Wichlinski GW 7 Pick 6
4010004 Marcin Wichlinski GW 7 Pick 7
4010004 Marcin Wichlinski GW 7 Pick 8
4010004 Marcin Wichlinski GW 7 Pick 9
4010004 Marcin Wichlinski GW 7 Pick 10
4010004 Marcin Wichlinski GW 7 Pick 11
4010004 Marcin Wichlinski GW 7 Pick 12
4010004 Marcin Wichlinski GW 7 Pick 13
4010004 Marcin Wichlinski GW 7 Pick 14
4010004 Marcin Wichlinski GW 7 Pick 15
4913097 Ollie Carroll GW 1 Pick 1
4913097 Ollie Carroll GW 1 Pick 2
4913097 Ollie Carroll GW 1 Pick 3
4913097 Ollie Carroll GW 1 Pick 4
4913097 Ollie Carroll GW 1 Pick 5

In [6]:
view = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(
                COALESCE(playergw.total_points, 0) * COALESCE(divx_picks_{current_season}.multiplier, 0)) AS total_points   
        FROM divx_picks_{current_season}
        LEFT JOIN playergw 
            ON divx_picks_{current_season}.element = playergw.element
            AND divx_picks_{current_season}.season = playergw.season
            AND divx_picks_{current_season}.gw = playergw.event
        GROUP BY member, memberid
    )
    SELECT 
        member,
        memberid,
        total_points 
    FROM member_points
    ORDER BY total_points DESC
""")
view

                      member   memberid  total_points
0            Stephen Collier   391266.0         520.0
1                 Joe Meader  2881244.0         514.0
2         Christopher Harris  5049406.0         484.0
3              Bernard Chalk  4184853.0         478.0
4          Marcin Wichlinski  4010004.0         473.0
5              Ollie Carroll  4913097.0         467.0
6        Christopher Collier  4705527.0         466.0
7            Anthony Collier  5037473.0         461.0
8             Callum Harling  3081288.0         459.0
9               Samia Shelim   678874.0         452.0
10        Christopher Harris  4486919.0         451.0
11          Luiton Fernandes  3060165.0         448.0
12              Jack Carroll  4355821.0         424.0
13                Ryan Boyce  4036890.0         419.0
14              Tommy Davies  3340544.0         404.0
15            Conner Harling  4484147.0         393.0
16             Tajwar Shelim  4512122.0         337.0
17  Christakis Christodoulou  5691733.0         276.0
18     Omari Douglas-Rankine  8921685.0         250.0

In [7]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{current_gw+1} to GW{current_gw+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weight_sum = sum([decay_factor**i for i in range(5)])
initial_weight = 1 / weight_sum # weights add to 1

view = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        value,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {current_gw+1} THEN xpoints * {initial_weight}
                WHEN event = {current_gw+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {current_gw+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {current_gw+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {current_gw+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
        AND status IN ('a', 'd')
        --AND position IN ('DEF')
        --AND VALUE <= 44
    GROUP BY player_name_id, status, position, value, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW8 to GW12

,player_name_id,status,in_my_team,position,value,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bryan Mbeumo,a,0,MID,78.0,Man Utd,1105.0,6.26,85.4,0.571,0.218,1.454
1,Erling Haaland,a,1,FWD,157.0,Man City,1107.9,5.92,72.9,0.715,0.351,1.808
2,Bruno Borges Fernandes,a,0,MID,118.0,Man Utd,1105.0,5.54,84.9,0.324,0.336,1.480
3,Enzo Le Fée,a,0,MID,57.0,Sunderland,1042.9,5.53,84.0,0.362,0.248,1.542
4,Bukayo Saka,a,0,MID,96.0,Arsenal,1105.7,5.30,83.9,0.307,0.275,0.974
5,Morgan Rogers,a,0,MID,79.0,Chelsea,1034.1,5.26,85.2,0.291,0.269,1.337
6,Morgan Gibbs-White,d,1,MID,80.0,Nott'm Forest,1107.7,5.23,83.6,0.259,0.348,1.490
7,Declan Rice,a,0,MID,73.0,Arsenal,1105.7,5.08,82.3,0.209,0.262,0.962
8,Francisco Evanilson de Lima Barbosa,a,0,FWD,61.0,Bournemouth,1041.4,5.04,82.9,0.379,0.392,1.251
9,Martin Ødegaard,a,0,MID,68.0,Arsenal,1105.7,5.03,80.7,0.294,0.207,0.983
10,Cristhian Mosquera,a,0,DEF,52.0,Arsenal,1105.7,4.94,62.7,0.175,0.057,1.172
11,Kiernan Dewsbury-Hall,a,0,MID,66.0,Everton,1109.2,4.89,86.4,0.234,0.174,1.495
12,Riccardo Calafiori,a,1,DEF,59.0,Arsenal,1105.7,4.88,77.1,0.120,0.133,1.067
13,Benjamin White,a,0,DEF,54.0,Arsenal,1105.7,4.82,61.8,0.123,0.129,0.978
14,Harvey Barnes,a,1,MID,61.0,Newcastle,1095.3,4.77,84.8,0.293,0.146,1.527
15,Cole Palmer,a,0,MID,97.0,Chelsea,1034.1,4.77,86.1,0.241,0.201,1.306
16,Granit Xhaka,a,1,MID,54.0,Sunderland,1042.9,4.74,85.7,0.104,0.299,1.392
17,Antoine Semenyo,d,0,MID,83.0,Man City,1107.9,4.73,69.7,0.362,0.285,1.265
18,Pascal Groß,a,0,MID,61.0,Brighton,1111.6,4.72,76.1,0.263,0.240,1.460
19,Maxence Lacroix,a,0,DEF,59.0,Chelsea,1034.1,4.65,80.3,0.087,0.085,1.314
20,Marcus Tavernier,a,1,MID,61.0,Bournemouth,1041.4,4.63,75.5,0.267,0.244,1.297
21,Ezri Konsa Ngoyo,a,0,DEF,46.0,Arsenal,1105.7,4.61,82.1,0.055,0.035,1.015
22,Gonzalo García,a,0,FWD,61.0,Fulham,1103.9,4.57,79.8,0.521,0.122,1.379
23,Phil Foden,a,0,MID,68.0,Man City,1107.9,4.56,56.5,0.550,0.215,1.045
24,Gabriel dos Santos Magalhães,a,0,DEF,79.0,Arsenal,1105.7,4.55,83.9,0.067,0.053,1.172
25,Anton Stach,a,0,MID,60.0,Leeds,1035.9,4.51,84.0,0.210,0.149,1.256
26,Nordi Mukiele,a,0,DEF,54.0,Sunderland,1042.9,4.50,84.6,0.071,0.125,1.300
27,Tarik Muharemović,a,0,DEF,50.0,Leeds,1035.9,4.50,87.5,0.063,0.085,1.307
28,Alex Iwobi,a,0,MID,54.0,Fulham,1103.9,4.49,77.8,0.245,0.200,1.458
29,Enzo Fernández,a,0,MID,69.0,Man City,1107.9,4.40,69.1,0.285,0.166,1.190
30,James Justin,a,0,DEF,45.0,Leeds,1035.9,4.38,86.5,0.058,0.095,1.260
31,Pedro Lomba Neto,a,0,MID,65.0,Chelsea,1034.1,4.38,83.5,0.157,0.251,1.277
32,Dominic Calvert-Lewin,a,0,FWD,60.0,Leeds,1035.9,4.37,83.7,0.451,0.098,1.086
33,Diego Gómez Amarilla,a,0,MID,50.0,Brighton,1111.6,4.37,84.2,0.195,0.145,1.504
34,João Pedro Junqueira de Jesus,a,0,FWD,78.0,Chelsea,1034.1,4.30,79.9,0.487,0.053,1.391
35,Igor Thiago Nascimento Rodrigues,a,1,FWD,78.0,Brentford,1061.7,4.30,86.1,0.428,0.058,1.238
36,Leif Davis,a,0,DEF,40.0,Ipswich Town,1040.2,4.30,86.0,0.087,0.078,1.380
37,Yoane Wissa,a,0,FWD,62.0,Newcastle,1095.3,4.28,80.1,0.423,0.131,1.386
38,Matheus Nunes,a,1,DEF,59.0,Man City,1107.9,4.27,82.3,0.040,0.207,1.280
39,James Hill,a,0,DEF,55.0,Bournemouth,1041.4,4.27,87.2,0.038,0.053,1.364
40,Issa Diop,a,0,DEF,40.0,Ipswich Town,1040.2,4.27,87.0,0.054,0.031,1.310
41,Jayden Bogle,a,0,DEF,47.0,Leeds,1035.9,4.27,80.8,0.078,0.131,1.258
42,Jannik Schuster,d,0,DEF,45.0,Brentford,1061.7,4.27,77.2,0.041,0.145,1.358
43,Joško Gvardiol,a,0,DEF,58.0,Man City,1107.9,4.26,57.6,0.092,0.299,1.359
44,Youri Tielemans,a,0,MID,57.0,Man Utd,1105.0,4.24,79.1,0.115,0.233,1.417
45,Matheus Santos Carneiro da Cunha,a,0,MID,79.0,Man Utd,1105.0,4.24,72.5,0.247,0.225,1.438
46,Bobby Thomas,a,0,DEF,40.0,Coventry City,1031.2,4.22,84.9,0.049,0.032,1.352
47,António João Pereira de Albuquerque Tavares da...,a,0,DEF,50.0,Bournemouth,1041.4,4.22,74.6,0.074,0.064,1.456
48,Dara O'Shea,a,0,DEF,40.0,Ipswich Town,1040.2,4.21,87.8,0.050,0.042,1.357
49,Rúben dos Santos Gato Alves Dias,a,0,DEF,55.0,Man City,1107.9,4.20,86.0,0.091,0.081,1.347

In [8]:
mydivx_team_20262027 = 5049406
mydiv1_team_20262027 = 4486919

alpha = 0.5
# blending factor α (alpha) between 0 and 1, where:
# α = 0 → pure ownership-weighted (current behaviour)
# α = 1 → pure absolute points
# α = 0.5 → equal blend

ownership_weighted_predictions = db_creator.run_sql(f"""
    WITH member_points AS (
        SELECT 
            member,
            memberid,
            SUM(COALESCE(playergw.total_points, 0) * COALESCE(divx_picks_{current_season}.multiplier, 0)) AS total_points   
        FROM divx_picks_{current_season}
        LEFT JOIN playergw 
            ON divx_picks_{current_season}.element = playergw.element
            AND divx_picks_{current_season}.season = playergw.season
            AND divx_picks_{current_season}.gw = playergw.event
        GROUP BY member, memberid
    ),
    top_5_members AS (
        SELECT memberid
        FROM member_points
        WHERE memberid NOT IN ({mydivx_team_20262027}, {mydiv1_team_20262027})
        ORDER BY total_points DESC
        LIMIT 5
    ),
    my_team AS (
        SELECT DISTINCT element
        FROM divx_picks_{current_season}
        WHERE memberid = {divx_team_code}
            AND gw = {current_gw}
    ),
    latest_predictions AS (
        SELECT *
        FROM predictions
        LEFT JOIN player_status ON predictions.element = player_status.id
        WHERE prediction_timestamp = (
            SELECT MAX(prediction_timestamp)
            FROM predictions
        )
    ),
    current_divx_picks AS (
        SELECT element, SUM(multiplier) AS total_multiplier
        FROM divx_picks_{current_season}
        WHERE divx_picks_{current_season}.gw = {current_gw}
            AND memberid IN (SELECT memberid FROM top_5_members)
        GROUP BY element
    ),
    player_ownership AS (
        SELECT
            CASE WHEN mt.element IS NOT NULL THEN 1 ELSE 0 END AS in_my_team,
            p.element,
            p.player_name_id,
            p.status,
            p.now_cost / 10.0 AS value,
            p.position,
            p.team_name,
            p.event,
            p.xpoints,
            COALESCE(cdx.total_multiplier, 0)::DECIMAL / NULLIF((SELECT COUNT(*) FROM top_5_members), 0) AS ownership_ratio
        FROM latest_predictions p
        LEFT JOIN current_divx_picks cdx
            ON cdx.element = p.element
        LEFT JOIN my_team mt
            ON mt.element = p.element
        WHERE p.status IN ('a', 'd')
    ),
    aggregated_stats AS (
        SELECT 
            in_my_team,
            element, 
            player_name_id,
            status,
            value, 
            position, 
            team_name,
            SUM(xpoints) AS sum_xpoints,
            MAX(ownership_ratio) * 100.0 AS ownership_percentage,
            MAX(ownership_ratio) AS ownership_ratio,
            -- Points gained relative to top 5 if owned (0 when 100% owned, full xP when 0% owned)
            SUM(xpoints) * (1.0 - MAX(ownership_ratio)) AS differential_upside,
            -- Relative delta against rivals (-xP * O if not owned, xP * (1 - O) if owned)
            SUM(xpoints) * (in_my_team - MAX(ownership_ratio)) AS net_rank_swing
        FROM player_ownership
        WHERE event BETWEEN {current_gw + 1} AND 38
        GROUP BY in_my_team, element, player_name_id, status, value, position, team_name
    )
    SELECT 
        *,
        -- Scaled blend between raw total points and differential gain potential
        sum_xpoints * ({alpha} + (1.0 - {alpha}) * (1.0 - ownership_ratio)) AS blended_score
    FROM aggregated_stats
""")

print(f"BEST RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 1
ownership_weighted_predictions[in_my_team_filter].sort_values(by='net_rank_swing', ascending=False)

BEST RANK MOVERS! Top 15 differential picks in my team for GW8 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,ownership_ratio,differential_upside,net_rank_swing,blended_score
489,1,427.0,Bryan Mbeumo,a,7.8,MID,Man Utd,195.595096,0.0,0.0,195.595096,195.595096,195.595096
490,1,480.0,Morgan Gibbs-White,d,8.0,MID,Nott'm Forest,161.692667,20.0,0.2,129.354133,129.354133,145.523400
482,1,173.0,Bobby Thomas,a,4.0,DEF,Coventry City,122.974897,0.0,0.0,122.974897,122.974897,122.974897
491,1,497.0,Martin Dubravka,a,4.0,GK,Spurs,113.337661,0.0,0.0,113.337661,113.337661,113.337661
483,1,175.0,Milan van Ewijk,a,3.9,DEF,Coventry City,112.137709,0.0,0.0,112.137709,112.137709,112.137709
488,1,423.0,Luke Shaw,d,4.3,DEF,Man Utd,111.737970,0.0,0.0,111.737970,111.737970,111.737970
486,1,399.0,Rayan Cherki,a,8.0,MID,Man City,132.381648,20.0,0.2,105.905318,105.905318,119.143483
477,1,1.0,David Raya Martín,a,6.1,GK,Arsenal,123.664065,40.0,0.4,74.198439,74.198439,98.931252
485,1,346.0,Dominic Calvert-Lewin,a,6.0,FWD,Leeds,134.119602,60.0,0.6,53.647841,53.647841,93.883721
484,1,212.0,Will Hughes,a,4.4,MID,Crystal Palace,47.302456,0.0,0.0,47.302456,47.302456,47.302456
478,1,8.0,Riccardo Calafiori,a,6.0,DEF,Arsenal,154.137166,80.0,0.8,30.827433,30.827433,92.482300
480,1,154.0,Cole Palmer,a,9.7,MID,Chelsea,145.463859,80.0,0.8,29.092772,29.092772,87.278315
479,1,31.0,Ezri Konsa Ngoyo,a,4.6,DEF,Arsenal,145.051898,80.0,0.8,29.010380,29.010380,87.031139
481,1,165.0,João Pedro Junqueira de Jesus,a,7.8,FWD,Chelsea,131.678675,80.0,0.8,26.335735,26.335735,79.007205
487,1,411.0,Erling Haaland,a,15.7,FWD,Man City,188.124319,220.0,2.2,-225.749182,-225.749182,-18.812432

In [9]:
print(f"DONT MISS OUT! Most owned points scorers for GW{current_gw + 1} - GW38:")
ownership_weighted_predictions.sort_values(by='net_rank_swing', ascending=True).head(20)

DONT MISS OUT! Most owned points scorers for GW8 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,ownership_ratio,differential_upside,net_rank_swing,blended_score
487,1,411.0,Erling Haaland,a,15.7,FWD,Man City,188.124319,220.0,2.2,-225.749182,-225.749182,-18.812432
25,0,40.0,Morgan Rogers,a,7.9,MID,Chelsea,161.797193,60.0,0.6,64.718877,-97.078316,113.258035
91,0,124.0,Pascal Groß,a,6.1,MID,Brighton,149.952585,60.0,0.6,59.981034,-89.971551,104.966809
85,0,115.0,Maxim De Cuyper,a,5.2,DEF,Brighton,122.560206,60.0,0.6,49.024083,-73.536124,85.792144
79,0,109.0,Bart Verbruggen,a,4.6,GK,Brighton,109.029985,40.0,0.4,65.417991,-43.611994,87.223988
294,0,426.0,Bruno Borges Fernandes,a,11.8,MID,Man Utd,176.099425,20.0,0.2,140.879540,-35.219885,158.489482
369,0,542.0,Enzo Le Fée,a,5.7,MID,Sunderland,171.369524,20.0,0.2,137.095619,-34.273905,154.232571
7,0,12.0,Bukayo Saka,a,9.6,MID,Arsenal,167.689790,20.0,0.2,134.151832,-33.537958,150.920811
10,0,15.0,Martin Ødegaard,a,6.8,MID,Arsenal,157.867142,20.0,0.2,126.293714,-31.573428,142.080428
160,0,236.0,Kiernan Dewsbury-Hall,a,6.6,MID,Everton,153.557027,20.0,0.2,122.845622,-30.711405,138.201325
313,0,453.0,Harvey Barnes,a,6.1,MID,Newcastle,146.487214,20.0,0.2,117.189771,-29.297443,131.838492
2,0,4.0,Gabriel dos Santos Magalhães,a,7.9,DEF,Arsenal,142.976114,20.0,0.2,114.380891,-28.595223,128.678502
391,0,569.0,Gonzalo García,a,6.1,FWD,Fulham,141.704075,20.0,0.2,113.363260,-28.340815,127.533668
233,0,334.0,Tarik Muharemović,a,5.0,DEF,Leeds,132.388363,20.0,0.2,105.910691,-26.477673,119.149527
155,0,229.0,James Tarkowski,a,6.2,DEF,Everton,129.374445,20.0,0.2,103.499556,-25.874889,116.437001
271,0,388.0,Marc Guéhi,a,6.0,DEF,Man City,128.834929,20.0,0.2,103.067944,-25.766986,115.951436
332,0,481.0,Elliot Anderson,a,6.3,MID,Man City,124.865852,20.0,0.2,99.892682,-24.973170,112.379267
311,0,449.0,Lewis Hall,a,5.3,DEF,Newcastle,120.620929,20.0,0.2,96.496743,-24.124186,108.558836
99,0,138.0,Charalampos Kostoulas,a,5.7,FWD,Brighton,118.840237,20.0,0.2,95.072190,-23.768047,106.956214
389,0,567.0,Lukás Hornícek,a,5.0,GK,Newcastle,106.710392,20.0,0.2,85.368313,-21.342078,96.039352

In [10]:
print(f"Best differential picks not in my team for GW{current_gw + 1} - GW38:")
not_in_my_team_filter = ownership_weighted_predictions['in_my_team'] == 0
ownership_weighted_predictions[not_in_my_team_filter].sort_values(by='differential_upside', ascending=False).head(20)

Best differential picks not in my team for GW8 - GW38:

,in_my_team,element,player_name_id,status,value,position,team_name,sum_xpoints,ownership_percentage,ownership_ratio,differential_upside,net_rank_swing,blended_score
8,0,13.0,Declan Rice,a,7.3,MID,Arsenal,159.531979,0.0,0.0,159.531979,0.000000,159.531979
6,0,11.0,Cristhian Mosquera,a,5.2,DEF,Arsenal,158.067664,0.0,0.0,158.067664,0.000000,158.067664
55,0,79.0,Francisco Evanilson de Lima Barbosa,a,6.1,FWD,Bournemouth,157.280534,0.0,0.0,157.280534,0.000000,157.280534
5,0,10.0,Benjamin White,a,5.4,DEF,Arsenal,153.868004,0.0,0.0,153.868004,0.000000,153.868004
279,0,397.0,Antoine Semenyo,d,8.3,MID,Man City,150.955660,0.0,0.0,150.955660,0.000000,150.955660
371,0,544.0,Granit Xhaka,a,5.4,MID,Sunderland,145.832941,0.0,0.0,145.832941,0.000000,145.832941
280,0,398.0,Phil Foden,a,6.8,MID,Man City,144.798444,0.0,0.0,144.798444,0.000000,144.798444
46,0,68.0,Marcus Tavernier,a,6.1,MID,Bournemouth,142.937484,0.0,0.0,142.937484,0.000000,142.937484
108,0,155.0,Enzo Fernández,a,6.9,MID,Man City,141.782226,0.0,0.0,141.782226,0.000000,141.782226
294,0,426.0,Bruno Borges Fernandes,a,11.8,MID,Man Utd,176.099425,20.0,0.2,140.879540,-35.219885,158.489482
135,0,200.0,Maxence Lacroix,a,5.9,DEF,Chelsea,138.953204,0.0,0.0,138.953204,0.000000,138.953204
94,0,127.0,Diego Gómez Amarilla,a,5.0,MID,Brighton,138.328229,0.0,0.0,138.328229,0.000000,138.328229
183,0,261.0,Alex Iwobi,a,5.4,MID,Fulham,138.174135,0.0,0.0,138.174135,0.000000,138.174135
234,0,335.0,Anton Stach,a,6.0,MID,Leeds,137.398252,0.0,0.0,137.398252,0.000000,137.398252
369,0,542.0,Enzo Le Fée,a,5.7,MID,Sunderland,171.369524,20.0,0.2,137.095619,-34.273905,154.232571
363,0,533.0,Nordi Mukiele,a,5.4,DEF,Sunderland,136.925115,0.0,0.0,136.925115,0.000000,136.925115
274,0,391.0,Joško Gvardiol,a,5.8,DEF,Man City,136.615137,0.0,0.0,136.615137,0.000000,136.615137
272,0,389.0,Matheus Nunes,a,5.9,DEF,Man City,136.189134,0.0,0.0,136.189134,0.000000,136.189134
248,0,356.0,Virgil van Dijk,a,6.5,DEF,Liverpool,135.700114,0.0,0.0,135.700114,0.000000,135.700114
277,0,395.0,Rico Lewis,a,4.3,DEF,Man City,135.234416,0.0,0.0,135.234416,0.000000,135.234416

In [11]:
# print(f"BLENDED SCORE: POINTS & RANK MOVERS! Top 15 differential picks in my team for GW{current_gw + 1} - GW38:")
# ownership_weighted_predictions.sort_values(by='blended_score', ascending=False).head(20)

In [12]:
# print(f"\nTop 20 predicted xPoints between {current_gw+1} and {current_gw+5}:")
# next5gw_predictions = db_creator.run_sql(f"""
#     WITH predictions_status AS (
#     SELECT *
#     FROM predictions
#     LEFT JOIN player_status ON predictions.element = player_status.id
#     )
#     SELECT
#         player_name_id,
#         status,
#         position,
#         team_name,
#         value/10 as value,
#         ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
#         ROUND(SUM(xpoints),2) AS total_xpoints,
#         ROUND(AVG(mins_pred),1) AS avg_mins_pred,
#         ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
#         ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
#         ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
#     FROM predictions_status
#     WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
#         AND status IN ('a', 'd')
#         -- AND position = 'FWD'
#         -- AND value <= 45
#         -- AND team_name = 'Crystal Palace'
#     GROUP BY player_name_id, status, position, team_name, value
#     ORDER BY total_xpoints DESC
# """).dropna(subset=['value', 'total_xpoints'])
# next5gw_predictions.head(20)

In [13]:
from FPL_Optimizer import FPLOptimizer

In [14]:
print(f"\nPredicted Ownership Weighted xPoints between {current_gw+1} and {current_gw+5}:")
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'blended_score'
    }
    
    optimizer = FPLOptimizer(
        df=ownership_weighted_predictions,
        budget=101.0,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

Predicted Ownership Weighted xPoints between 8 and 12:
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £101.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £97.6m / £101.0m
Total Weighted Expected Points: 1735.47
Remaining Budget: £3.4m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Marcus Bettinelli              Man City     £4.4   117.79
 ✅        Marco Bizot                    Aston Villa  £4.5   119.54

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Joško Gvardiol                 Man City     £5.8   136.62
 ✅        Benjamin White                 Arsenal      £5.4   153.87
 ✅        Cristhian Mosquera             Arsenal      £5.2   158.07
 ✅        Maxence Lacroix                Chelsea      £5.9   138.95
 ✅        Nordi Mukiele                  Sunderland   £5.4   136.93

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Declan Rice                    Arsenal      £7.3   159.53
 ✅        Antoine Semenyo                Man City     £8.3   150.96
 ✅        Bruno Borges Fernandes         Man Utd      £11.8  158.49
 ✅        Enzo Le Fée                    Sunderland   £5.7   154.23
 ✅        Bryan Mbeumo                   Man Utd      £7.8   195.60

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Thiago Nascimento Rodrigues Brentford    £7.8   133.98
 🪑        Yoane Wissa                    Newcastle    £6.2   131.98
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1   157.28

================================================================================
Optimization Status: Optimal

In [15]:
print(f"\nPredicted xPoints between {current_gw+1} and {current_gw+5}:")
next5gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        player_name_id,
        status,
        position,
        team_name,
        now_cost / 10.0 AS value,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE event BETWEEN {current_gw+1} AND {current_gw+5}
        AND status IN ('a', 'd')
        -- AND position = 'FWD'
        -- AND value <= 45
        -- AND team_name = 'Crystal Palace'
    GROUP BY player_name_id, status, position, team_name, now_cost
    ORDER BY total_xpoints DESC
""").dropna(subset=['value', 'total_xpoints'])

# Usage
if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'total_xpoints'
    }
    
    optimizer = FPLOptimizer(
        df=next5gw_predictions,
        budget=101.0,
        column_mapping=custom_columns
    )
    optimizer.optimize()
    
    # Get results as DataFrames
    squad = optimizer.get_squad_dataframe()
    starting_xi = optimizer.get_starting_xi_dataframe()

Predicted xPoints between 8 and 12:
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £101.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £101.0m / £101.0m
Total Weighted Expected Points: 292.64
Remaining Budget: £-0.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Fraser Forster                 Bournemouth  £4.0    18.61
 ✅        Martin Dubravka                Spurs        £4.0    18.92

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Leif Davis                     Ipswich Town £4.0    21.62
 🪑        Issa Diop                      Ipswich Town £3.9    21.44
 ✅        Cristhian Mosquera             Arsenal      £5.2    24.22
 ✅        Riccardo Calafiori             Arsenal      £6.0    24.10
 ✅        Benjamin White                 Arsenal      £5.4    23.73

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8    31.30
 ✅        Enzo Le Fée                    Sunderland   £5.7    27.81
 ✅        Bruno Borges Fernandes         Man Utd      £11.8   27.64
 ✅        Morgan Rogers                  Chelsea      £7.9    26.25
 ✅        Morgan Gibbs-White             Nott'm Forest £8.0    25.90

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Liam Delap                     Nott'm Forest £5.5    18.51
 ✅        Erling Haaland                 Man City     £15.7   29.48
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1    25.27

================================================================================
Optimization Status: Optimal

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        event,
        player_name_id,
        status,
        position,
        team_name,
        opp_team_name,
        now_cost / 10.0 AS value,
        xpoints
    FROM predictions_status
    WHERE event BETWEEN {current_gw+1} AND 38
        AND status IN ('a', 'd')
    ORDER BY xpoints DESC
""")
print("Best week to triple captain:")
remaining_gw_predictions.head(10)

Best week to triple captain:

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
0,19.0,Erling Haaland,a,FWD,Man City,Spurs,15.7,6.624324
1,25.0,Erling Haaland,a,FWD,Man City,Spurs,15.7,6.624324
2,37.0,Bryan Mbeumo,a,MID,Man Utd,Spurs,7.8,6.586201
3,15.0,Bryan Mbeumo,a,MID,Man Utd,Crystal Palace,7.8,6.509347
4,33.0,Bryan Mbeumo,a,MID,Man Utd,Crystal Palace,7.8,6.509347
5,34.0,Bryan Mbeumo,a,MID,Man Utd,Coventry City,7.8,6.496716
6,14.0,Bryan Mbeumo,a,MID,Man Utd,Coventry City,7.8,6.496716
7,32.0,Bryan Mbeumo,a,MID,Man Utd,Ipswich Town,7.8,6.496702
8,29.0,Erling Haaland,a,FWD,Man City,Coventry City,15.7,6.479222
9,36.0,Erling Haaland,a,FWD,Man City,Ipswich Town,15.7,6.450783

In [17]:
print(f"\nOptimizing team selection for GW{current_gw+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'player_name_id',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_teams =pd.DataFrame()
    for event in range(current_gw+1, 19): #change to 39 for 2nd half of season
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=100.0,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            starting_xi = optimizer.get_starting_xi_dataframe()
            # result = optimizer.calculate_bench_boost_xpoints()
            starting_xi['event'] = event
            all_teams = pd.concat([all_teams, starting_xi], ignore_index=True)
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW8 to GW38...

Optimizing team selection for GW8...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.5m / £100.0m
Total Weighted Expected Points: 59.78
Remaining Budget: £0.5m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        John Victor Maciel Furtado     Nott'm Forest £4.4     3.80
 ✅        David Raya Martín              Arsenal      £6.1     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Jannik Schuster                Brentford    £4.5     4.54
 🪑        Bobby Thomas                   Coventry City £4.0     4.36
 ✅        Cristhian Mosquera             Arsenal      £5.2     5.10
 ✅        Riccardo Calafiori             Arsenal      £6.0     5.07
 ✅        Maxence Lacroix                Chelsea      £5.9     4.97

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.32
 ✅        Morgan Gibbs-White             Nott'm Forest £8.0     5.63
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.38
 ✅        Morgan Rogers                  Chelsea      £7.9     5.37
 ✅        Harvey Barnes                  Newcastle    £6.1     5.12

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gonzalo García                 Fulham       £6.1     4.65
 ✅        Erling Haaland                 Man City     £15.7    5.97
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     4.99

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW9...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.8m / £100.0m
Total Weighted Expected Points: 58.34
Remaining Budget: £0.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Fraser Forster                 Bournemouth  £4.0     3.91
 ✅        Marco Bizot                    Aston Villa  £4.5     4.13

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Victor Lindelöf                Aston Villa  £4.5     4.40
 🪑        Leif Davis                     Ipswich Town £4.0     4.35
 ✅        Cristhian Mosquera             Arsenal      £5.2     4.68
 ✅        Nordi Mukiele                  Sunderland   £5.4     4.62
 ✅        Taylor Harwood-Bellis          Aston Villa  £4.5     4.57

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.18
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.75
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    5.72
 ✅        Morgan Rogers                  Chelsea      £7.9     5.12
 ✅        Kiernan Dewsbury-Hall          Everton      £6.6     5.03

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Gonzalo García                 Fulham       £6.1     4.63
 ✅        Erling Haaland                 Man City     £15.7    5.76
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     5.05

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW10...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.0m / £100.0m
Total Weighted Expected Points: 60.75
Remaining Budget: £0.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Fraser Forster                 Bournemouth  £4.0     3.79
 ✅        Marcus Bettinelli              Man City     £4.4     3.95

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        James Justin                   Leeds        £4.5     4.79
 🪑        Issa Diop                      Ipswich Town £3.9     4.27
 ✅        Cristhian Mosquera             Arsenal      £5.2     5.42
 ✅        Riccardo Calafiori             Arsenal      £6.0     5.39
 ✅        Benjamin White                 Arsenal      £5.4     5.32

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.28
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    5.52
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.48
 ✅        Morgan Rogers                  Chelsea      £7.9     5.30
 ✅        Kiernan Dewsbury-Hall          Everton      £6.6     5.17

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brandon Thomas-Asante          Coventry City £5.0     3.22
 ✅        Erling Haaland                 Man City     £15.7    6.18
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     5.11

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW11...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.8m / £100.0m
Total Weighted Expected Points: 59.73
Remaining Budget: £0.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martin Dubravka                Spurs        £4.0     3.78
 ✅        Marco Bizot                    Aston Villa  £4.5     4.20

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Leif Davis                     Ipswich Town £4.0     4.46
 🪑        Issa Diop                      Ipswich Town £3.9     4.45
 ✅        Cristhian Mosquera             Arsenal      £5.2     5.21
 ✅        Benjamin White                 Arsenal      £5.4     5.09
 ✅        Riccardo Calafiori             Arsenal      £6.0     5.02

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.24
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    5.47
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.34
 ✅        Morgan Rogers                  Chelsea      £7.9     5.20
 ✅        Pascal Groß                    Brighton     £6.1     5.13

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Thierno Barry                  Everton      £5.7     4.11
 ✅        Erling Haaland                 Man City     £15.7    6.10
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     5.05

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW12...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £99.8m / £100.0m
Total Weighted Expected Points: 58.18
Remaining Budget: £0.2m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Fraser Forster                 Bournemouth  £4.0     3.88
 ✅        Marco Bizot                    Aston Villa  £4.5     4.14

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Leif Davis                     Ipswich Town £4.0     4.33
 🪑        Issa Diop                      Ipswich Town £3.9     4.23
 ✅        Nordi Mukiele                  Sunderland   £5.4     4.72
 ✅        James Hill                     Bournemouth  £5.5     4.58
 ✅        Taylor Harwood-Bellis          Aston Villa  £4.5     4.49

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.29
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.86
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    5.45
 ✅        Morgan Gibbs-White             Nott'm Forest £8.0     5.30
 ✅        Morgan Rogers                  Chelsea      £7.9     5.25

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brandon Thomas-Asante          Coventry City £5.0     3.22
 ✅        Erling Haaland                 Man City     £15.7    5.47
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     5.06

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW13...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.0m / £100.0m
Total Weighted Expected Points: 59.89
Remaining Budget: £-0.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Freddie Woodman                Liverpool    £4.0     3.86
 ✅        Marco Bizot                    Aston Villa  £4.5     4.04

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Leif Davis                     Ipswich Town £4.0     4.44
 🪑        Harry Amass                    Man Utd      £4.0     4.39
 ✅        Cristhian Mosquera             Arsenal      £5.2     5.10
 ✅        Benjamin White                 Arsenal      £5.4     4.93
 ✅        Bafodé Diakité                 Bournemouth  £4.9     4.69

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.41
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    5.89
 ✅        Morgan Gibbs-White             Nott'm Forest £8.0     5.49
 ✅        Morgan Rogers                  Chelsea      £7.9     5.42
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.41

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brandon Thomas-Asante          Coventry City £5.0     3.31
 ✅        Erling Haaland                 Man City     £15.7    5.98
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     4.94

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW14...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.0m / £100.0m
Total Weighted Expected Points: 61.32
Remaining Budget: £0.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Fraser Forster                 Bournemouth  £4.0     3.81
 ✅        Marco Bizot                    Aston Villa  £4.5     4.12

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Harry Amass                    Man Utd      £4.0     4.55
 🪑        Rico Lewis                     Man City     £4.3     4.24
 ✅        Cristhian Mosquera             Arsenal      £5.2     5.54
 ✅        Riccardo Calafiori             Arsenal      £6.0     5.45
 ✅        Benjamin White                 Arsenal      £5.4     5.39

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Bryan Mbeumo                   Man Utd      £7.8     6.50
 ✅        Bruno Borges Fernandes         Man Utd      £11.8    6.12
 ✅        Enzo Le Fée                    Sunderland   £5.7     5.49
 ✅        Morgan Rogers                  Chelsea      £7.9     5.10
 ✅        Kiernan Dewsbury-Hall          Everton      £6.6     5.02

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brandon Thomas-Asante          Coventry City £5.0     3.22
 ✅        Erling Haaland                 Man City     £15.7    5.88
 ✅        Francisco Evanilson de Lima Barbosa Bournemouth  £6.1     5.14

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW15...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £100.0m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £100.0m / £100.0m
Total Weighted Expected Points: 60.46
Remaining Budget: £-0.0m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martin Dubravka                Spurs        £4.0     3.78
 ✅        Marco Bizot                    Aston Villa  £4.5     4.10

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts

In [18]:
freehit_points = all_teams.pivot_table(index='event', values='xpoints', aggfunc='sum').sort_values(by='xpoints', ascending=False)
best_week = freehit_points.head(1)['xpoints'].index.astype(int).values[0]
print(f"Best week to freehit: {best_week}, points: {round(all_teams[all_teams['event']==best_week]['xpoints'].sum(),1)}")
all_teams[all_teams['event']==best_week].sort_values(by=['position','xpoints'], ascending=False)

Best week to freehit: 14, points: 59.7

,event,player_name_id,status,position,team_name,opp_team_name,value,xpoints
66,14,Bryan Mbeumo,a,MID,Man Utd,Coventry City,7.8,6.496716
67,14,Bruno Borges Fernandes,a,MID,Man Utd,Coventry City,11.8,6.121739
70,14,Enzo Le Fée,a,MID,Sunderland,Newcastle,5.7,5.485543
74,14,Morgan Rogers,a,MID,Chelsea,Liverpool,7.9,5.103969
75,14,Kiernan Dewsbury-Hall,a,MID,Everton,Fulham,6.6,5.017397
76,14,Marco Bizot,a,GK,Aston Villa,Crystal Palace,4.5,4.122091
68,14,Erling Haaland,a,FWD,Man City,Brentford,15.7,5.875787
73,14,Francisco Evanilson de Lima Barbosa,a,FWD,Bournemouth,Hull City,6.1,5.135099
69,14,Cristhian Mosquera,a,DEF,Arsenal,Spurs,5.2,5.542623
71,14,Riccardo Calafiori,a,DEF,Arsenal,Spurs,6.0,5.449680
72,14,Benjamin White,a,DEF,Arsenal,Spurs,5.4,5.391547

In [19]:
# finish=time.perf_counter()
# print(f'Finished in {round(((finish-start)/60),2)} minute(s)') 
# #Finished in 0.01 minute(s)

In [20]:
# Notification when file has finished running
from plyer import notification

notification.notify(
    title='Script Complete',
    message='Your file has finished running!',
    app_name='Jupyter Notebook',
    timeout=20  # notification stays for 20 seconds
)