In [6]:
import pandas as pd
import time

In [7]:
current_gw = 0
current_season = 20262027

In [8]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [9]:
print("Rest of Season Predictions")

predictions = db_creator.run_sql(f"""SELECT *
                                    FROM predictions
                                    WHERE season = {current_season}
                            """)

predictions.groupby('player_name_id')[['team_name','position','opp_team_elo','mins_pred',
                                           'xpoints', 'xpoints_mins', 'xpoints_goals', 
                                           'xpoints_assists', 'xpoints_clean_sheets', 
                                           'xpoints_shots_saved','xpoints_goals_conceded','xpoints_defcon','xpoints_bonus'
                                           ]].agg({'team_name':'first','position':'first','opp_team_elo':'mean','mins_pred':'mean','xpoints':'sum', 'xpoints_mins':'sum', 'xpoints_goals':'sum',
                                           'xpoints_assists':'sum', 'xpoints_clean_sheets':'sum',
                                           'xpoints_shots_saved':'sum','xpoints_goals_conceded':'sum','xpoints_defcon':'sum','xpoints_bonus':'sum'}
                                                  ).reset_index().sort_values(by='xpoints',ascending=False).head(10)

Rest of Season Predictions

,player_name_id,team_name,position,opp_team_elo,mins_pred,xpoints,xpoints_mins,xpoints_goals,xpoints_assists,xpoints_clean_sheets,xpoints_shots_saved,xpoints_goals_conceded,xpoints_defcon,xpoints_bonus
163,Erling Haaland,Man City,FWD,1075.192492,79.607036,201.047016,71.310981,69.385066,30.762118,0.000000,0.0,0.000000,10.218078,19.370774
71,Bruno Borges Fernandes,Man Utd,MID,1084.324182,85.698856,200.274634,73.298129,43.528942,34.270321,8.546585,0.0,0.000000,19.389159,21.241497
421,Morgan Gibbs-White,Nott'm Forest,MID,1082.540216,74.261975,197.252405,68.634658,49.257102,27.861338,9.377176,0.0,0.000000,19.389159,22.732971
73,Bryan Mbeumo,Man Utd,MID,1084.324182,68.740726,195.372356,64.812295,78.626410,8.946334,8.720883,0.0,0.000000,19.389159,14.877274
130,Declan Rice,Arsenal,MID,1074.404880,78.682083,186.257867,70.917337,34.099230,26.992017,15.175263,0.0,0.000000,19.389159,19.684861
451,Ollie Watkins,Aston Villa,FWD,1079.333859,82.993290,184.016368,72.531949,53.227263,22.677766,0.000000,0.0,0.000000,10.218078,25.361312
479,Riccardo Calafiori,Arsenal,DEF,1074.404880,64.487379,183.392147,61.191678,18.309073,10.877723,62.606174,0.0,-8.997510,20.037335,19.367674
571,William Saliba,Arsenal,DEF,1074.404880,83.482299,183.040268,72.686150,10.039270,5.556899,63.542067,0.0,-8.758768,20.037335,19.937314
374,Marcus Rashford,Man Utd,MID,1084.324182,50.431931,182.605409,48.553532,65.525792,27.900159,4.857799,0.0,0.000000,19.389159,16.378967
33,Antoine Semenyo,Man City,MID,1075.192492,67.836000,180.700997,64.085233,47.304769,19.281657,11.939658,0.0,0.000000,19.389159,18.700521

In [10]:
print("Rest of Season VORP(7)")

predictions = db_creator.run_sql(f"""
WITH preds AS (
    SELECT 
        player_name_id,
        team_name,
        position,
        SUM(xpoints) AS xpoints
    FROM predictions
    WHERE season = {current_season}
    GROUP BY player_name_id, team_name, position
),


PlayerRankings AS (
    SELECT 
        player_name_id,
        team_name,
        position,
        xpoints,
        -- Get the xpoints of the player 7 spots lower in the same position
        LEAD(xpoints, 7) OVER (
            PARTITION BY position 
            ORDER BY xpoints DESC
        ) AS replacement_xpoints
    FROM 
        preds
)
SELECT 
    player_name_id,
    team_name,
    position,
    xpoints,
    replacement_xpoints,
    -- Calculate Value Over Replacement Player
    (xpoints - replacement_xpoints) AS vorp
FROM 
    PlayerRankings
WHERE 
    replacement_xpoints IS NOT NULL
ORDER BY 
    xpoints, vorp DESC;
    """)

predictions.sort_values(by='vorp',ascending=False).head(20)

Rest of Season VORP(7)

,player_name_id,team_name,position,xpoints,replacement_xpoints,vorp
558,Erling Haaland,Man City,FWD,201.047016,138.956264,62.090752
553,Ollie Watkins,Aston Villa,FWD,184.016368,138.953932,45.062436
531,Dominic Calvert-Lewin,Leeds,FWD,163.038823,134.082358,28.956464
501,Richarlison de Andrade,Spurs,FWD,151.435862,129.343988,22.091874
484,Francisco Evanilson de Lima Barbosa,Bournemouth,FWD,147.168413,125.825040,21.343373
557,Bruno Borges Fernandes,Man Utd,MID,200.274634,179.032925,21.241709
2,Tammy Abraham,Aston Villa,FWD,89.804076,69.213360,20.590716
510,Igor Thiago Nascimento Rodrigues,Brentford,FWD,153.408439,132.913823,20.494616
551,William Saliba,Arsenal,DEF,183.040268,162.623168,20.417101
1,Georginio Rutter,Brighton,FWD,86.608192,67.783913,18.824279
446,William Osula,Newcastle,FWD,142.462837,123.682335,18.780503
556,Morgan Gibbs-White,Nott'm Forest,MID,197.252405,178.571236,18.681169
543,Virgil van Dijk,Liverpool,DEF,174.990465,156.347031,18.643433
13,Liam Delap,Chelsea,FWD,93.380161,74.939424,18.440737
396,Igor Jesus Maciel da Cruz,Nott'm Forest,FWD,138.953932,121.238079,17.715852
397,Kai Havertz,Arsenal,FWD,138.956264,121.246336,17.709928
3,Ellis Simms,Coventry City,FWD,89.845639,72.183435,17.662203
540,Benjamin White,Arsenal,DEF,173.932581,156.347031,17.585550
0,Jean-Philippe Mateta,Crystal Palace,FWD,84.098737,66.706990,17.391747
555,Bryan Mbeumo,Man Utd,MID,195.372356,178.069772,17.302583