In [19]:
import pandas as pd
import time

In [20]:
start=time.perf_counter()

In [21]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [22]:
#add this info to a settings dict?
current_gw = 32
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [23]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 33
Squad Points: 87.91

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Flemming,a,100.0,33.0,FWD,Burnley,Nott'm Forest; Man City,9.406404,155.0
1,Matheus N.,a,100.0,33.0,DEF,Man City,Arsenal; Burnley,8.793197,151.0
2,F.Kadıoğlu,a,NaN,33.0,DEF,Brighton,Spurs; Chelsea,8.059218,175.0
3,Van Hecke,a,100.0,33.0,DEF,Brighton,Spurs; Chelsea,7.941508,174.0
4,Gibbs-White,a,100.0,33.0,MID,Nott'm Forest,Burnley,5.698411,80.0
5,B.Fernandes,a,100.0,33.0,MID,Man Utd,Chelsea,4.868031,81.0
6,Mac Allister,a,100.0,33.0,MID,Liverpool,Everton,4.458805,73.0
7,Bruno G.,i,0.0,33.0,MID,Newcastle,Bournemouth,4.330265,57.0
8,Szoboszlai,a,100.0,33.0,MID,Liverpool,Everton,4.300043,87.0
9,Gabriel,a,100.0,33.0,DEF,Arsenal,Man City,3.894492,82.0
10,Mings,a,100.0,33.0,DEF,Aston Villa,Sunderland,3.824507,73.0
11,Brobbey,a,100.0,33.0,FWD,Sunderland,Aston Villa,3.609909,72.0
12,Martinez,a,100.0,33.0,GK,Aston Villa,Sunderland,3.522396,90.0
13,Raya,a,NaN,33.0,GK,Arsenal,Man City,3.150441,87.0
14,Isak,a,100.0,33.0,FWD,Liverpool,Everton,2.650956,32.0

In [24]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW33 AND 37

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1096.0,13.48,32.0,0.485,0.126,1.555
1,Emiliano Martínez Romero,1,GK,Aston Villa,1015.9,18.64,89.9,NaN,NaN,1.251
2,Brian Brobbey,1,FWD,Sunderland,1055.0,18.67,71.8,0.388,0.053,1.388
3,David Raya Martín,1,GK,Arsenal,1044.7,19.54,87.3,NaN,NaN,1.033
4,Jan Paul van Hecke,1,DEF,Brighton,1008.8,19.87,108.4,0.045,0.038,1.303
5,Tyrone Mings,1,DEF,Aston Villa,1015.9,19.97,72.9,0.072,0.051,1.308
6,Ferdi Kadıoğlu,1,DEF,Brighton,1008.8,20.23,109.1,0.046,0.047,1.294
7,Matheus Nunes,1,DEF,Man City,1073.5,20.73,89.4,0.046,0.110,1.247
8,Dominik Szoboszlai,1,MID,Liverpool,1096.0,21.23,86.5,0.155,0.145,1.683
9,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1087.9,21.38,56.4,0.319,0.346,1.645
10,Alexis Mac Allister,1,MID,Liverpool,1096.0,22.11,73.1,0.309,0.095,1.646
11,Zian Flemming,1,FWD,Burnley,1120.8,23.68,96.3,0.613,0.041,1.714
12,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1044.7,24.58,81.5,0.082,0.082,0.975
13,Bruno Borges Fernandes,1,MID,Man Utd,1080.8,24.67,80.8,0.236,0.291,1.396
14,Morgan Gibbs-White,1,MID,Nott'm Forest,1044.8,25.19,80.4,0.193,0.399,1.332

In [ ]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
    AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW33 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Chris Wood,a,0,FWD,Nott'm Forest,1051.2,28.83,33.6,1.369,0.750,1.511
1,Zian Flemming,a,1,FWD,Burnley,1084.0,28.45,92.4,0.613,0.042,1.641
2,Gabriel Fernando de Jesus,a,0,FWD,Arsenal,1045.2,26.25,29.3,1.230,0.905,1.100
3,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1071.3,25.49,68.7,0.512,0.080,1.504
4,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1056.5,23.74,80.3,0.370,0.046,1.596
5,Valentín Castellanos,a,0,FWD,West Ham,1083.8,23.62,74.8,0.394,0.054,1.399
6,Brian Brobbey,a,1,FWD,Sunderland,1064.6,22.51,71.7,0.395,0.053,1.407
7,Lorenzo Lucca,a,0,FWD,Nott'm Forest,1051.2,21.59,46.4,0.606,0.201,1.397
8,Callum Wilson,a,0,FWD,West Ham,1083.8,21.30,32.6,0.857,0.578,1.460
9,Marc Guiu Paz,a,0,FWD,Chelsea,1056.1,20.94,46.6,0.671,0.209,1.669
10,Pablo Felipe Pereira de Jesus,a,0,FWD,West Ham,1083.8,20.18,73.2,0.270,0.046,1.476
11,Jonah Kusi-Asare,a,0,FWD,Fulham,1091.4,19.29,32.1,0.685,0.238,1.698
12,Rodrigo Muniz Carvalho,a,0,FWD,Fulham,1091.4,18.06,57.5,0.334,0.047,1.440
13,Lyle Foster,a,0,FWD,Burnley,1084.0,17.95,61.8,0.482,0.034,1.808
14,Jean-Philippe Mateta,a,0,FWD,Crystal Palace,1105.1,17.92,39.0,0.551,0.170,1.610
15,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1051.2,17.79,54.0,0.273,0.167,1.410
16,Charalampos Kostoulas,a,0,FWD,Brighton,1029.5,17.76,34.4,0.672,0.222,1.262
17,Yoane Wissa,a,0,FWD,Newcastle,1080.1,17.15,25.0,0.613,0.613,1.469
18,Adam Armstrong,a,0,FWD,Wolves,1000.5,17.15,63.8,0.210,0.045,1.406
19,Raúl Jiménez Rodríguez,a,0,FWD,Fulham,1091.4,16.77,40.2,0.447,0.055,1.599
20,Lukas Nmecha,a,0,FWD,Leeds,988.6,16.53,49.3,0.449,0.063,1.313
21,Alexander Isak,a,1,FWD,Liverpool,1092.2,16.23,32.3,0.487,0.125,1.578
22,Armando Broja,a,0,FWD,Burnley,1084.0,15.63,35.9,0.756,0.031,1.717
23,Taiwo Awoniyi,a,0,FWD,Nott'm Forest,1051.2,15.61,31.7,0.663,0.029,1.367
24,Tolu Arokodare,a,0,FWD,Wolves,1000.5,14.14,36.0,0.375,0.031,1.285
25,William Osula,a,0,FWD,Newcastle,1080.1,13.86,22.9,0.507,0.049,1.399
26,Mateus Mané,a,0,FWD,Wolves,1000.5,13.84,39.3,0.297,0.039,1.494
27,Joshua Zirkzee,a,0,FWD,Man Utd,1083.6,13.07,19.3,0.515,0.066,1.296
28,Joël Piroe,a,0,FWD,Leeds,988.6,13.05,23.4,0.403,0.046,1.473
29,Tammy Abraham,a,0,FWD,Aston Villa,1051.0,12.58,22.4,0.356,0.048,1.203
30,Enes Ünal,a,0,FWD,Bournemouth,1073.2,12.37,19.7,0.521,0.050,1.653
31,Liam Delap,a,0,FWD,Chelsea,1056.1,12.34,29.7,0.300,0.037,1.394
32,Ashley Barnes,a,0,FWD,Burnley,1084.0,12.11,32.8,0.272,0.056,1.762
33,Christantus Uche,a,0,FWD,Crystal Palace,1105.1,11.73,20.2,0.272,0.041,1.552
34,Wilson Isidor,a,0,FWD,Sunderland,1064.6,11.67,15.0,0.446,0.047,1.371
35,Eliezer Mayenda Dossou,a,0,FWD,Sunderland,1064.6,11.23,19.3,0.322,0.052,1.556

In [26]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW33 AND 37

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,John Stones,d,0,DEF,Man City,1073.5,56.35,68.6,2.232,0.030,1.434
1,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,51.82,81.6,0.151,3.232,1.271
2,Mason Mount,a,0,MID,Man Utd,1080.8,45.43,20.6,4.317,2.897,1.600
3,Mats Wieffer,a,0,MID,Brighton,1008.8,35.66,101.1,0.187,1.152,1.234
4,James Ward-Prowse,a,0,MID,Burnley,1120.8,31.92,96.0,0.647,0.284,1.942
5,Harvey Barnes,a,0,MID,Newcastle,1087.9,31.45,57.7,0.846,0.533,1.518
6,Mathias Jensen,a,0,MID,Brentford,1084.8,29.33,85.7,0.505,0.111,1.559
7,Granit Xhaka,a,0,MID,Sunderland,1055.0,27.87,70.2,0.363,0.554,1.448
8,Eberechi Eze,a,0,MID,Arsenal,1044.7,26.71,66.6,0.328,0.471,0.918
9,Dwight McNeil,a,0,MID,Everton,1093.9,25.97,70.5,0.425,0.254,1.283
10,Youri Tielemans,a,0,MID,Aston Villa,1015.9,25.89,42.2,0.818,0.618,1.207
11,Michael Keane,a,0,DEF,Everton,1093.9,25.81,76.2,0.366,0.039,1.467
12,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1044.8,25.19,80.4,0.193,0.399,1.332
13,Lucas Digne,a,0,DEF,Aston Villa,1015.9,24.85,72.9,0.059,0.407,1.229
14,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.8,24.67,80.8,0.236,0.291,1.396
15,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1044.7,24.58,81.5,0.082,0.082,0.975
16,Jacob Ramsey,a,0,MID,Newcastle,1087.9,24.43,74.3,0.336,0.231,1.538
17,Kevin Schade,a,0,MID,Brentford,1084.8,24.34,73.6,0.220,0.424,1.511
18,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1044.8,24.33,57.5,0.556,0.245,1.324
19,Chris Wood,a,0,FWD,Nott'm Forest,1044.8,23.99,33.5,1.369,0.752,1.503
20,John McGinn,a,0,MID,Aston Villa,1015.9,23.97,61.6,0.224,0.600,1.191
21,Zian Flemming,a,1,FWD,Burnley,1120.8,23.68,96.3,0.613,0.041,1.714
22,Rico Lewis,a,0,DEF,Man City,1073.5,23.36,79.5,0.341,0.073,1.493
23,Marcus Tavernier,a,0,MID,Bournemouth,1086.8,22.89,100.9,0.176,0.256,1.258
24,Ross Barkley,a,0,MID,Aston Villa,1015.9,22.86,53.1,0.498,0.283,1.225
25,Ryan Sessegnon,a,0,MID,Fulham,1094.0,22.68,41.5,0.736,0.429,1.532
26,Jadon Sancho,d,0,MID,Aston Villa,1015.9,22.46,48.0,0.628,0.196,1.177
27,Jack Hinshelwood,a,0,MID,Brighton,1008.8,22.11,91.9,0.162,0.302,1.277
28,Alexis Mac Allister,a,1,MID,Liverpool,1096.0,22.11,73.1,0.309,0.095,1.646
29,Max Alleyne,a,0,DEF,Man City,1073.5,22.01,72.6,0.314,0.030,1.373
30,Gabriel Fernando de Jesus,a,0,FWD,Arsenal,1044.7,21.95,29.2,1.236,0.919,1.110
31,Rodrigo Bentancur,d,0,MID,Spurs,1052.8,21.90,49.0,0.358,0.700,2.182
32,Pascal Groß,a,0,MID,Brighton,1008.8,21.55,105.4,0.135,0.164,1.244
33,Alex Scott,a,0,MID,Bournemouth,1086.8,21.32,106.2,0.171,0.081,1.283
34,Dominik Szoboszlai,a,1,MID,Liverpool,1096.0,21.23,86.5,0.155,0.145,1.683
35,Conor Gallagher,a,0,MID,Spurs,1052.8,21.22,33.2,0.805,0.591,1.718
36,Cristhian Mosquera,a,0,DEF,Arsenal,1044.7,21.14,61.1,0.049,0.034,0.906
37,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1093.9,21.13,68.7,0.507,0.076,1.503
38,Jaidon Anthony,a,0,MID,Burnley,1120.8,21.06,105.1,0.237,0.055,2.065
39,Benjamin White,a,0,DEF,Arsenal,1044.7,20.93,63.0,0.063,0.065,1.050
40,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1080.8,20.87,83.0,0.041,0.221,1.447
41,Matheus Nunes,a,1,DEF,Man City,1073.5,20.73,89.4,0.046,0.110,1.247
42,Nordi Mukiele,a,0,DEF,Sunderland,1055.0,20.72,57.7,0.227,0.258,1.515
43,Lisandro Martínez,d,0,DEF,Man Utd,1080.8,20.72,69.2,0.243,0.048,1.632
44,Douglas Luiz Soares de Paulo,a,0,MID,Aston Villa,1015.9,20.51,50.0,0.339,0.383,1.208
45,Aaron Wan-Bissaka,a,0,DEF,West Ham,1103.7,20.51,77.2,0.045,0.207,1.406
46,Amadou Onana,a,0,MID,Aston Villa,1015.9,20.47,77.8,0.178,0.073,1.323
47,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1103.7,20.40,83.5,0.128,0.123,1.504
48,Rio Ngumoha,a,0,MID,Liverpool,1096.0,20.33,56.4,0.188,0.388,1.653
49,Habib Diarra,a,0,MID,Sunderland,1055.0,20.32,81.6,0.153,0.121,1.378

In [27]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 33 to 37

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Man City,d,John Stones,56.351896,Jan Paul van Hecke,19.872382,36.479513
1,MID,Man City,a,Bernardo Mota Veiga de Carvalho e Silva,51.817381,Dominik Szoboszlai,21.229603,30.587778
2,MID,Man Utd,a,Mason Mount,45.426925,Dominik Szoboszlai,21.229603,24.197322
3,MID,Brighton,a,Mats Wieffer,35.661160,Dominik Szoboszlai,21.229603,14.431557
4,MID,Burnley,a,James Ward-Prowse,31.916896,Dominik Szoboszlai,21.229603,10.687293
5,FWD,Nott'm Forest,a,Chris Wood,23.992331,Alexander Isak,13.475349,10.516982
6,MID,Newcastle,a,Harvey Barnes,31.447923,Dominik Szoboszlai,21.229603,10.218320
7,FWD,Arsenal,a,Gabriel Fernando de Jesus,21.951525,Alexander Isak,13.475349,8.476176
8,MID,Brentford,a,Mathias Jensen,29.329054,Dominik Szoboszlai,21.229603,8.099451
9,FWD,Everton,a,Norberto Bercique Gomes Betuncal,21.133086,Alexander Isak,13.475349,7.657738
10,MID,Sunderland,a,Granit Xhaka,27.871472,Dominik Szoboszlai,21.229603,6.641869
11,FWD,West Ham,a,Valentín Castellanos,19.511853,Alexander Isak,13.475349,6.036505
12,FWD,Spurs,a,Dominic Solanke-Mitchell,19.440826,Alexander Isak,13.475349,5.965477
13,DEF,Everton,a,Michael Keane,25.814718,Jan Paul van Hecke,19.872382,5.942336
14,MID,Arsenal,a,Eberechi Eze,26.708710,Dominik Szoboszlai,21.229603,5.479107
15,DEF,Aston Villa,a,Lucas Digne,24.847781,Jan Paul van Hecke,19.872382,4.975399
16,MID,Everton,a,Dwight McNeil,25.973175,Dominik Szoboszlai,21.229603,4.743572
17,MID,Aston Villa,a,Youri Tielemans,25.894743,Dominik Szoboszlai,21.229603,4.665139
18,FWD,Nott'm Forest,a,Lorenzo Lucca,17.989662,Alexander Isak,13.475349,4.514313
19,FWD,West Ham,a,Callum Wilson,17.300929,Alexander Isak,13.475349,3.825580

In [28]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 33 and 37:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,33.0,FWD,Man City,Arsenal; Burnley,14.4,1062.307979,12.817931,143.813609,0.699066,0.616426,1.260077
1,Erling Haaland,35.0,FWD,Man City,Everton,14.4,1075.115184,6.401834,65.664758,0.754981,0.699269,1.301899
2,Erling Haaland,36.0,FWD,Man City,Brentford,14.4,1073.538381,6.401834,65.664758,0.754981,0.699269,1.282740
3,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.4,1083.144286,6.385997,65.664758,0.749554,0.699269,1.361798

In [29]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW33 to GW37
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,John Stones,d,0,DEF,Man City,1073.5,12.38,68.6,2.232,0.030,1.434
1,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,11.38,81.6,0.151,3.232,1.271
2,Mason Mount,a,0,MID,Man Utd,1080.8,8.99,20.6,4.317,2.897,1.600
3,Mats Wieffer,a,0,MID,Brighton,1008.8,7.68,101.1,0.187,1.152,1.234
4,James Ward-Prowse,a,0,MID,Burnley,1120.8,6.94,96.0,0.647,0.284,1.942
5,Harvey Barnes,a,0,MID,Newcastle,1087.9,6.23,57.7,0.846,0.533,1.518
6,Mathias Jensen,a,0,MID,Brentford,1084.8,5.88,85.7,0.505,0.111,1.559
7,Granit Xhaka,a,0,MID,Sunderland,1055.0,5.56,70.2,0.363,0.554,1.448
8,Eberechi Eze,a,0,MID,Arsenal,1044.7,5.20,66.6,0.328,0.471,0.918
9,Dwight McNeil,a,0,MID,Everton,1093.9,5.19,70.5,0.425,0.254,1.283
10,Michael Keane,a,0,DEF,Everton,1093.9,5.16,76.2,0.366,0.039,1.467
11,Rico Lewis,a,0,DEF,Man City,1073.5,5.15,79.5,0.341,0.073,1.493
12,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1044.8,5.14,80.4,0.193,0.399,1.332
13,Youri Tielemans,a,0,MID,Aston Villa,1015.9,5.12,42.2,0.818,0.618,1.207
14,Zian Flemming,a,1,FWD,Burnley,1120.8,5.11,96.3,0.613,0.041,1.714
15,Marcus Tavernier,a,0,MID,Bournemouth,1086.8,4.98,100.9,0.176,0.256,1.258
16,Lucas Digne,a,0,DEF,Aston Villa,1015.9,4.95,72.9,0.059,0.407,1.229
17,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1044.8,4.90,57.5,0.556,0.245,1.324
18,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.8,4.90,80.8,0.236,0.291,1.396
19,Kevin Schade,a,0,MID,Brentford,1084.8,4.89,73.6,0.220,0.424,1.511
20,Jacob Ramsey,a,0,MID,Newcastle,1087.9,4.86,74.3,0.336,0.231,1.538
21,Chris Wood,a,0,FWD,Nott'm Forest,1044.8,4.85,33.5,1.369,0.752,1.503
22,Max Alleyne,a,0,DEF,Man City,1073.5,4.80,72.6,0.314,0.030,1.373
23,Jack Hinshelwood,a,0,MID,Brighton,1008.8,4.77,91.9,0.162,0.302,1.277
24,John McGinn,a,0,MID,Aston Villa,1015.9,4.76,61.6,0.224,0.600,1.191
25,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1044.7,4.65,81.5,0.082,0.082,0.975
26,Pascal Groß,a,0,MID,Brighton,1008.8,4.63,105.4,0.135,0.164,1.244
27,Alex Scott,a,0,MID,Bournemouth,1086.8,4.63,106.2,0.171,0.081,1.283
28,Matheus Nunes,a,1,DEF,Man City,1073.5,4.58,89.4,0.046,0.110,1.247
29,Jaidon Anthony,a,0,MID,Burnley,1120.8,4.57,105.1,0.237,0.055,2.065
30,Ross Barkley,a,0,MID,Aston Villa,1015.9,4.56,53.1,0.498,0.283,1.225
31,Ryan Sessegnon,a,0,MID,Fulham,1094.0,4.52,41.5,0.736,0.429,1.532
32,Jadon Sancho,d,0,MID,Aston Villa,1015.9,4.49,48.0,0.628,0.196,1.177
33,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,4.45,88.5,0.044,0.030,1.171
34,Alexis Mac Allister,a,1,MID,Liverpool,1096.0,4.44,73.1,0.309,0.095,1.646
35,Sebastiaan Bornauw,a,0,DEF,Leeds,986.7,4.43,82.6,0.232,0.024,1.507
36,Rodrigo Bentancur,d,0,MID,Spurs,1052.8,4.37,49.0,0.358,0.700,2.182
37,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1008.8,4.36,68.4,0.354,0.026,1.479
38,Ferdi Kadıoğlu,a,1,DEF,Brighton,1008.8,4.36,109.1,0.046,0.047,1.294
39,Brenden Aaronson,a,0,MID,Leeds,986.7,4.35,71.3,0.181,0.485,1.312
40,Jan Paul van Hecke,a,1,DEF,Brighton,1008.8,4.29,108.4,0.045,0.038,1.303
41,Gabriel Fernando de Jesus,a,0,FWD,Arsenal,1044.7,4.28,29.2,1.236,0.919,1.110
42,Sam Byram,a,0,DEF,Leeds,986.7,4.27,67.2,0.322,0.024,1.565
43,Olivier Boscagli,a,0,DEF,Brighton,1008.8,4.27,87.2,0.073,0.065,1.284
44,Dominik Szoboszlai,a,1,MID,Liverpool,1096.0,4.27,86.5,0.155,0.145,1.683
45,Rayan Aït-Nouri,a,0,DEF,Man City,1073.5,4.25,79.9,0.054,0.062,1.293
46,Conor Gallagher,a,0,MID,Spurs,1052.8,4.24,33.2,0.805,0.591,1.718
47,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1093.9,4.23,68.7,0.507,0.076,1.503
48,Veljko Milosavljevic,a,0,DEF,Bournemouth,1086.8,4.21,65.1,0.339,0.028,1.570
49,Jayden Bogle,a,0,DEF,Leeds,986.7,4.20,92.8,0.063,0.069,1.390

In [30]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [31]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [32]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [33]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [34]:
from FPL_Optimizer import FPLOptimizer
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW33 to GW38...

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 66.60
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.15
 ✅        Martinez                       Aston Villa  £5.1     3.52

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     3.82
 ✅        F.Kadıoğlu                     Brighton     £4.4     8.06
 ✅        Gabriel                        Arsenal      £7.2     3.89
 ✅        Van Hecke                      Brighton     £4.5     7.94
 ✅        Matheus N.                     Man City     £5.3     8.79

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.46
 ✅        B.Fernandes                    Man Utd      £10.3    4.87
 ✅        Bruno G.                       Newcastle    £6.8     4.33
 ✅        Szoboszlai                     Liverpool    £7.1     4.30
 ✅        Gibbs-White                    Nott'm Forest £7.4     5.70

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.65
 🪑        Brobbey                        Sunderland   £5.3     3.61
 ✅        Flemming                       Burnley      £5.3     9.41

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

Optimization Status: Infeasible
No valid 15-player squad found within constraints.
Error optimizing for GW34: No optimization has been run yet. Call optimize() first.

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 49.95
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.70
 ✅        Martinez                       Aston Villa  £5.1     4.09

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Van Hecke                      Brighton     £4.5     3.79
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.84
 ✅        Gabriel                        Arsenal      £7.2     4.88
 ✅        Matheus N.                     Man City     £5.3     3.99
 ✅        Mings                          Aston Villa  £4.3     4.37

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.41
 ✅        B.Fernandes                    Man Utd      £10.3    4.81
 ✅        Bruno G.                       Newcastle    £6.8     4.30
 ✅        Szoboszlai                     Liverpool    £7.1     4.21
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.86

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.66
 🪑        Brobbey                        Sunderland   £5.3     3.82
 ✅        Flemming                       Burnley      £5.3     4.78

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 51.97
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.25
 ✅        Raya                           Arsenal      £6.0     4.28

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.3     4.01
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.23
 ✅        Gabriel                        Arsenal      £7.2     5.50
 ✅        Van Hecke                      Brighton     £4.5     4.15
 ✅        Mings                          Aston Villa  £4.3     4.81

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.37
 ✅        B.Fernandes                    Man Utd      £10.3    5.02
 ✅        Bruno G.                       Newcastle    £6.8     4.35
 ✅        Szoboszlai                     Liverpool    £7.1     4.20
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.85

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.70
 🪑        Brobbey                        Sunderland   £5.3     3.71
 ✅        Flemming                       Burnley      £5.3     4.74

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 51.53
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.24
 ✅        Raya                           Arsenal      £6.0     4.83

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     3.15
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.10
 ✅        Gabriel                        Arsenal      £7.2     5.78
 ✅        Van Hecke                      Brighton     £4.5     3.99
 ✅        Matheus N.                     Man City     £5.3     3.94

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.36
 ✅        B.Fernandes                    Man Utd      £10.3    5.10
 ✅        Bruno G.                       Newcastle    £6.8     4.34
 ✅        Szoboszlai                     Liverpool    £7.1     4.17
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.89

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.72
 🪑        Brobbey                        Sunderland   £5.3     3.75
 ✅        Flemming                       Burnley      £5.3     4.75

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 49.18
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.26
 ✅        Raya                           Arsenal      £6.0     3.66

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.3     3.44
 🪑        Mings                          Aston Villa  £4.3     2.99
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.75
 ✅        Gabriel                        Arsenal      £7.2     4.79
 ✅        Van Hecke                      Brighton     £4.5     3.69

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.68
 ✅        B.Fernandes                    Man Utd      £10.3    4.99
 ✅        Bruno G.                       Newcastle    £6.8     4.36
 ✅        Szoboszlai                     Liverpool    £7.1     4.43
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.99

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.75
 ✅        Brobbey                        Sunderland   £5.3     3.84
 ✅        Flemming                       Burnley      £5.3     4.77

================================================================================
Optimization Status: Optimal

In [35]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
2     36         13.203160
1     35         12.578149
0     33         11.912232
3     37         11.574574
4     38         11.197338

In [36]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.01 minute(s)