In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
stats_current_gameweek = 13
picks_current_gameweek = 13
current_season = 20252026

In [24]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 14
Squad Points: 66.57

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,B.Fernandes,a,NaN,14.0,MID,Man Utd,West Ham,5.072422
1,Amad,a,100.0,14.0,MID,Man Utd,West Ham,4.800064
2,Lacroix,a,NaN,14.0,DEF,Crystal Palace,Burnley,4.659459
3,Matheus N.,a,NaN,14.0,DEF,Man City,Fulham,4.535678
4,Szoboszlai,a,NaN,14.0,MID,Liverpool,Sunderland,4.532242
5,Konaté,a,100.0,14.0,DEF,Liverpool,Sunderland,4.380552
6,Tarkowski,a,NaN,14.0,DEF,Everton,Bournemouth,4.365358
7,Minteh,a,NaN,14.0,MID,Brighton,Aston Villa,4.226851
8,Raya,a,NaN,14.0,GK,Arsenal,Brentford,4.062773
9,O.Dango,a,100.0,14.0,MID,Brentford,Arsenal,4.058404
10,Flemming,a,NaN,14.0,FWD,Burnley,Crystal Palace,4.015486
11,Raúl,a,100.0,14.0,FWD,Fulham,Man City,3.524491
12,Pope,d,NaN,14.0,GK,Newcastle,Spurs,3.216158
13,Gabriel,i,0.0,14.0,DEF,Arsenal,Brentford,3.199059
14,Gyökeres,a,50.0,14.0,FWD,Arsenal,Brentford,2.846788

In [13]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 14

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Gusto,a,100.0,14.0,DEF,Chelsea,Leeds,5.609646
1,Enzo,a,100.0,14.0,MID,Chelsea,Leeds,5.488385
2,Gakpo,a,NaN,14.0,MID,Liverpool,Sunderland,5.078896
3,Yeremy,a,100.0,14.0,MID,Crystal Palace,Burnley,5.052031
4,De Ligt,a,NaN,14.0,DEF,Man Utd,West Ham,4.769436
5,Anderson,a,NaN,14.0,MID,Nott'm Forest,Wolves,4.749649
6,Richards,a,100.0,14.0,DEF,Crystal Palace,Burnley,4.712602
7,Merino,a,NaN,14.0,MID,Arsenal,Brentford,4.658468
8,Shaw,a,NaN,14.0,DEF,Man Utd,West Ham,4.569866
9,Dewsbury-Hall,a,100.0,14.0,MID,Everton,Bournemouth,4.519677

In [6]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(10)

When to use first TRIPLE CAPTAIN chip (gws1-19)

           player_name_id  event position  team_name opp_team_name   xpoints
0         Ibrahima Konaté   15.0      DEF  Liverpool         Leeds  5.512817
1         Ibrahima Konaté   19.0      DEF  Liverpool         Leeds  5.512817
2         Ibrahima Konaté   18.0      DEF  Liverpool        Wolves  5.512376
3  Bruno Borges Fernandes   15.0      MID    Man Utd        Wolves  5.354371
4  Bruno Borges Fernandes   19.0      MID    Man Utd        Wolves  5.354371
5           Matheus Nunes   17.0      DEF   Man City      West Ham  5.344315
6  Bruno Borges Fernandes   14.0      MID    Man Utd      West Ham  5.072422
7         Ibrahima Konaté   17.0      DEF  Liverpool         Spurs  5.066582
8  Bruno Borges Fernandes   16.0      MID    Man Utd   Bournemouth  4.945987
9      Dominik Szoboszlai   18.0      MID  Liverpool        Wolves  4.931076

In [7]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW14 AND 18

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Cody Gakpo,0,MID,Liverpool,996.9,25.54,63.6,0.317,0.214,0.910
1,Enzo Fernández,0,MID,Chelsea,1055.9,25.42,82.9,0.265,0.172,1.163
2,Bruno Borges Fernandes,1,MID,Man Utd,1040.7,24.97,84.0,0.252,0.179,1.290
3,Ibrahima Konaté,1,DEF,Liverpool,996.9,24.72,63.8,0.064,0.049,0.909
4,Dominik Szoboszlai,1,MID,Liverpool,996.9,23.46,83.0,0.149,0.184,0.927
5,Mikel Merino Zazón,0,MID,Arsenal,1058.4,23.41,75.0,0.210,0.152,0.879
6,Matheus Nunes,1,DEF,Man City,1035.1,23.36,81.3,0.048,0.062,1.056
7,Yéremy Pino Santos,0,MID,Crystal Palace,1012.1,23.24,64.5,0.258,0.158,1.200
8,Amad Diallo,1,MID,Man Utd,1040.7,22.83,82.8,0.191,0.140,1.166
9,Marcus Tavernier,0,MID,Bournemouth,1042.7,22.60,82.7,0.183,0.147,1.284
10,Elliot Anderson,0,MID,Nott'm Forest,1045.7,22.59,83.0,0.187,0.141,1.427
11,Kiernan Dewsbury-Hall,0,MID,Everton,1073.0,22.53,82.2,0.179,0.160,1.351
12,Alexis Mac Allister,0,MID,Liverpool,996.9,22.29,68.5,0.178,0.133,0.908
13,Dango Ouattara,1,MID,Brentford,1026.7,22.17,75.4,0.213,0.115,1.298
14,Malo Gusto,0,DEF,Chelsea,1055.9,22.09,63.9,0.073,0.059,1.171
15,Carlos Henrique Casimiro,0,MID,Man Utd,1040.7,21.67,61.9,0.244,0.107,1.186
16,Yankuba Minteh,1,MID,Brighton,1120.7,21.66,81.7,0.167,0.126,1.352
17,Diego Gómez Amarilla,0,MID,Brighton,1120.7,21.66,71.2,0.218,0.106,1.328
18,Matthijs de Ligt,0,DEF,Man Utd,1040.7,21.52,83.8,0.068,0.067,1.274
19,Malick Thiaw,0,DEF,Newcastle,1027.5,21.37,82.7,0.058,0.050,1.258
20,Maxence Lacroix,1,DEF,Crystal Palace,1012.1,21.21,84.7,0.059,0.036,1.231
21,Chris Richards,0,DEF,Crystal Palace,1012.1,21.19,82.0,0.043,0.080,1.229
22,David Raya Martín,1,GK,Arsenal,1058.4,21.15,84.8,NaN,NaN,0.896
23,Ryan Gravenberch,0,MID,Liverpool,996.9,21.14,79.5,0.093,0.122,0.880
24,Martín Zubimendi Ibáñez,0,MID,Arsenal,1058.4,20.93,69.7,0.116,0.125,0.851
25,Enzo Le Fée,0,MID,Sunderland,1108.9,20.83,72.9,0.187,0.105,1.478
26,Michael Kayode,0,DEF,Brentford,1026.7,20.78,82.2,0.036,0.091,1.329
27,James Garner,0,MID,Everton,1073.0,20.70,82.4,0.121,0.116,1.371
28,Nathan Collins,0,DEF,Brentford,1026.7,20.68,84.2,0.066,0.064,1.346
29,Luke Shaw,0,DEF,Man Utd,1040.7,20.62,78.9,0.031,0.056,1.235
30,Callum Wilson,0,FWD,West Ham,1113.8,20.58,67.6,0.431,0.052,1.574
31,Sepp van den Berg,0,DEF,Brentford,1026.7,20.49,84.1,0.063,0.036,1.344
32,Harry Wilson,0,MID,Fulham,1041.3,20.46,66.0,0.188,0.098,1.367
33,Adam Wharton,0,MID,Crystal Palace,1012.1,20.35,70.3,0.082,0.186,1.203
34,Ryan Sessegnon,0,MID,Fulham,1041.3,20.30,82.4,0.126,0.098,1.384
35,Wesley Fofana,0,DEF,Chelsea,1055.9,20.29,63.0,0.051,0.027,1.155
36,James Tarkowski,1,DEF,Everton,1073.0,20.28,84.6,0.042,0.062,1.359
37,Daichi Kamada,0,MID,Crystal Palace,1012.1,20.16,73.7,0.120,0.106,1.237
38,Zian Flemming,1,FWD,Burnley,1069.7,20.07,67.9,0.378,0.061,1.830
39,Ferdi Kadıoğlu,0,DEF,Brighton,1120.7,20.07,84.5,0.054,0.062,1.401
40,Nico González Iglesias,0,MID,Man City,1035.1,20.06,70.6,0.100,0.097,0.962
41,Mikkel Damsgaard,0,MID,Brentford,1026.7,20.00,75.1,0.093,0.136,1.306
42,Michael Keane,0,DEF,Everton,1073.0,19.96,84.4,0.059,0.036,1.392
43,Adrien Truffert,0,DEF,Bournemouth,1042.7,19.93,71.2,0.038,0.053,1.299
44,Georginio Rutter,0,MID,Brighton,1120.7,19.88,65.4,0.147,0.112,1.344
45,Boubacar Kamara,0,MID,Aston Villa,1107.4,19.76,77.3,0.105,0.110,1.407
46,Jan Paul van Hecke,0,DEF,Brighton,1120.7,19.76,84.8,0.049,0.035,1.377
47,Joe Gomez,0,DEF,Liverpool,996.9,19.74,39.1,0.108,0.092,0.954
48,Vitalii Mykolenko,0,DEF,Everton,1073.0,19.71,81.4,0.035,0.063,1.345
49,Kenny Tete,0,DEF,Fulham,1041.3,19.68,81.1,0.048,0.041,1.398

In [8]:
print(f"\nBest available players to replace worst in my team over next 5 GWs: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team over next 5 GWs: 14 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,West Ham,Callum Wilson,102.996827,Viktor Gyökeres,73.255123,29.741703
1,DEF,Chelsea,Malo Gusto,106.678576,Gabriel dos Santos Magalhães,86.864932,19.813644
2,FWD,Spurs,Richarlison de Andrade,92.099594,Viktor Gyökeres,73.255123,18.844471
3,DEF,Man Utd,Matthijs de Ligt,105.501436,Gabriel dos Santos Magalhães,86.864932,18.636504
4,DEF,Brighton,Ferdi Kadıoğlu,105.109339,Gabriel dos Santos Magalhães,86.864932,18.244407
5,FWD,Wolves,Jørgen Strand Larsen,91.414285,Viktor Gyökeres,73.255123,18.159162
6,MID,Chelsea,Enzo Fernández,126.859940,Dango Ouattara,109.565151,17.294789
7,GK,Fulham,Bernd Leno,95.395326,Nick Pope,78.301222,17.094104
8,DEF,Newcastle,Malick Thiaw,103.619724,Gabriel dos Santos Magalhães,86.864932,16.754792
9,DEF,Brighton,Jan Paul van Hecke,103.420270,Gabriel dos Santos Magalhães,86.864932,16.555338
10,DEF,Brentford,Michael Kayode,102.619456,Gabriel dos Santos Magalhães,86.864932,15.754524
11,DEF,Crystal Palace,Chris Richards,101.977057,Gabriel dos Santos Magalhães,86.864932,15.112125
12,DEF,Brentford,Nathan Collins,101.878669,Gabriel dos Santos Magalhães,86.864932,15.013737
13,MID,Liverpool,Cody Gakpo,124.361558,Dango Ouattara,109.565151,14.796408
14,FWD,Nott'm Forest,Igor Jesus Maciel da Cruz,88.019871,Viktor Gyökeres,73.255123,14.764748
15,DEF,Man Utd,Luke Shaw,101.014012,Gabriel dos Santos Magalhães,86.864932,14.149080
16,DEF,Everton,Michael Keane,100.956517,Gabriel dos Santos Magalhães,86.864932,14.091585
17,DEF,Brentford,Sepp van den Berg,100.845038,Gabriel dos Santos Magalhães,86.864932,13.980106
18,GK,Nott'm Forest,Matz Sels,91.819071,Nick Pope,78.301222,13.517850
19,DEF,Aston Villa,Pau Torres,99.880058,Gabriel dos Santos Magalhães,86.864932,13.015126

In [9]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 14 and 18:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,14.0,MID,Chelsea,Leeds,6.7,915.108651,5.488385,82.731829,0.275710,0.192648,0.624988
1,Enzo Fernández,15.0,MID,Chelsea,Bournemouth,6.7,1054.800148,5.107966,82.832788,0.274725,0.174833,1.187198
2,Enzo Fernández,16.0,MID,Chelsea,Everton,6.7,1054.902805,5.107966,82.832788,0.274725,0.174833,1.187198
3,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.7,1107.974578,4.841955,82.916236,0.250352,0.160466,1.527168
4,Enzo Fernández,18.0,MID,Chelsea,Aston Villa,6.7,1146.622491,4.876450,83.019004,0.249649,0.159290,1.286676

In [10]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [11]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [12]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
#10/11/25: Finished in 0.01 minute(s)

Finished in 0.01 minute(s)