In [25]:
import pandas as pd
import time

In [26]:
start=time.perf_counter()

In [27]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [28]:
#add this info to a settings dict?
stats_current_gameweek = 12
picks_current_gameweek = 12
current_season = 20252026

In [29]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(5)

Check status of available players in GW 13

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Enzo,a,100.0,13.0,MID,Chelsea,Arsenal,5.061932
1,Kayode,a,NaN,13.0,DEF,Brentford,Burnley,4.769480
2,Collins,a,NaN,13.0,DEF,Brentford,Burnley,4.638933
3,Van den Berg,a,NaN,13.0,DEF,Brentford,Burnley,4.619713
4,Tavernier,a,NaN,13.0,MID,Bournemouth,Sunderland,4.600160

In [30]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(5)

When to use first TRIPLE CAPTAIN chip (gws1-19)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,16.0,DEF,Arsenal,Wolves,6.342217
1,Matheus Nunes,13.0,DEF,Man City,Leeds,5.532447
2,Ibrahima Konaté,18.0,DEF,Liverpool,Wolves,5.324482
3,Matheus Nunes,17.0,DEF,Man City,West Ham,5.312008
4,Ibrahima Konaté,15.0,DEF,Liverpool,Leeds,5.308150

In [39]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'FWD'
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(20)

Best players to pick for the next 5 gameweeks: GW13 AND 17

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Enzo Fernández,0,MID,Chelsea,1077.1,27.49,80.2,0.321,0.224,1.157
1,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1064.1,27.04,67.0,0.193,0.117,1.031
2,Matheus Nunes,1,DEF,Man City,1012.5,23.68,82.4,0.045,0.068,1.035
3,Marcus Tavernier,0,MID,Bournemouth,1036.2,23.67,82.8,0.223,0.164,1.303
4,Dominik Szoboszlai,1,MID,Liverpool,1008.2,23.66,78.4,0.180,0.208,1.127
5,Bruno Guimarães Rodriguez Moura,0,MID,Newcastle,1027.0,23.37,82.6,0.212,0.144,1.345
6,Bruno Borges Fernandes,1,MID,Man Utd,1043.4,23.27,70.1,0.239,0.178,1.312
7,Jacob Murphy,0,MID,Newcastle,1027.0,23.17,74.8,0.228,0.147,1.200
8,Yankuba Minteh,1,MID,Brighton,1075.4,22.62,82.7,0.182,0.146,1.244
9,Ibrahima Konaté,1,DEF,Liverpool,1008.2,22.29,64.9,0.062,0.062,1.143
10,Elliot Anderson,0,MID,Nott'm Forest,1022.8,22.29,83.1,0.162,0.141,1.301
11,Martín Zubimendi Ibáñez,0,MID,Arsenal,1064.1,22.19,77.0,0.148,0.144,0.924
12,Michael Kayode,0,DEF,Brentford,998.9,21.50,71.3,0.040,0.119,1.266
13,Amad Diallo,1,MID,Man Utd,1043.4,21.30,69.8,0.174,0.132,1.276
14,Diego Gómez Amarilla,0,MID,Brighton,1075.4,20.98,68.5,0.187,0.100,1.231
15,Nathan Collins,0,DEF,Brentford,998.9,20.98,82.9,0.041,0.070,1.258
16,Neco Williams,0,DEF,Nott'm Forest,1022.8,20.88,84.3,0.059,0.060,1.292
17,Alexis Mac Allister,0,MID,Liverpool,1008.2,20.81,63.3,0.161,0.123,1.038
18,Nicolò Savona,0,DEF,Nott'm Forest,1022.8,20.79,80.2,0.080,0.043,1.307
19,Sepp van den Berg,0,DEF,Brentford,998.9,20.79,83.7,0.060,0.039,1.338

In [32]:
print(f"\nBest available players to replace worst in my team over next 5 GWs: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team over next 5 GWs: 13 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Chelsea,Enzo Fernández,142.809077,Dango Ouattara,97.131511,45.677566
1,MID,Bournemouth,Marcus Tavernier,120.389057,Dango Ouattara,97.131511,23.257545
2,FWD,West Ham,Callum Wilson,104.365500,Viktor Gyökeres,82.444679,21.920821
3,MID,Newcastle,Jacob Murphy,118.823802,Dango Ouattara,97.131511,21.692291
4,MID,Newcastle,Bruno Guimarães Rodriguez Moura,118.687614,Dango Ouattara,97.131511,21.556103
5,MID,Arsenal,Martín Zubimendi Ibáñez,115.665521,Dango Ouattara,97.131511,18.534009
6,MID,Nott'm Forest,Elliot Anderson,113.961197,Dango Ouattara,97.131511,16.829685
7,FWD,Spurs,Richarlison de Andrade,98.588695,Viktor Gyökeres,82.444679,16.144016
8,MID,Brighton,Diego Gómez Amarilla,110.045402,Dango Ouattara,97.131511,12.913890
9,MID,Liverpool,Alexis Mac Allister,107.138519,Dango Ouattara,97.131511,10.007008
10,DEF,Brentford,Michael Kayode,108.738249,James Tarkowski,99.366084,9.372165
11,MID,Leeds,Brenden Aaronson,106.098862,Dango Ouattara,97.131511,8.967350
12,MID,Fulham,Harry Wilson,105.921119,Dango Ouattara,97.131511,8.789607
13,MID,Everton,Kiernan Dewsbury-Hall,105.397552,Dango Ouattara,97.131511,8.266041
14,MID,Liverpool,Ryan Gravenberch,105.305701,Dango Ouattara,97.131511,8.174190
15,DEF,Brentford,Nathan Collins,106.731820,James Tarkowski,99.366084,7.365736
16,MID,Everton,James Garner,104.194899,Dango Ouattara,97.131511,7.063387
17,MID,Fulham,Ryan Sessegnon,103.718612,Dango Ouattara,97.131511,6.587100
18,DEF,Brentford,Sepp van den Berg,105.883818,James Tarkowski,99.366084,6.517734
19,MID,Man Utd,Carlos Henrique Casimiro,103.594381,Dango Ouattara,97.131511,6.462870

In [33]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 13 and 17:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,13.0,MID,Chelsea,Arsenal,6.7,1248.695856,5.061932,80.482011,0.284684,0.205937,1.386719
1,Enzo Fernández,14.0,MID,Chelsea,Leeds,6.7,918.161783,5.946489,80.132231,0.373526,0.242895,0.840894
2,Enzo Fernández,15.0,MID,Chelsea,Bournemouth,6.7,1065.801289,5.566657,80.066662,0.319878,0.223629,1.058547
3,Enzo Fernández,16.0,MID,Chelsea,Everton,6.7,1053.833047,5.563366,79.828511,0.319878,0.223629,1.050748
4,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.7,1098.980975,5.349382,80.482011,0.304823,0.225996,1.448203

In [34]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [35]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [36]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
#10/11/25: Finished in 0.01 minute(s)

Finished in 0.01 minute(s)