In [16]:
import pandas as pd
import time

In [17]:
start=time.perf_counter()

In [18]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [19]:
#add this info to a settings dict?
stats_current_gameweek = 20
picks_current_gameweek = 20
current_season = 20252026

In [20]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 21
Squad Points: 58.65

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Matheus N.,a,NaN,21.0,DEF,Man City,Brighton,5.174751
1,Tarkowski,a,NaN,21.0,DEF,Everton,Wolves,4.632346
2,B.Fernandes,d,25.0,21.0,MID,Man Utd,Burnley,4.194969
3,Szoboszlai,a,100.0,21.0,MID,Liverpool,Arsenal,4.116712
4,Gibbs-White,a,100.0,21.0,MID,Nott'm Forest,West Ham,4.108797
5,Gabriel,a,100.0,21.0,DEF,Arsenal,Liverpool,3.900077
6,Konaté,a,100.0,21.0,DEF,Liverpool,Arsenal,3.721468
7,Raúl,a,100.0,21.0,FWD,Fulham,Chelsea,3.678864
8,Reijnders,a,NaN,21.0,MID,Man City,Brighton,3.441095
9,Lacroix,a,NaN,21.0,DEF,Crystal Palace,Aston Villa,3.323498
10,Raya,a,NaN,21.0,GK,Arsenal,Liverpool,3.189767
11,Martinez,a,100.0,21.0,GK,Aston Villa,Crystal Palace,2.742254
12,Gyökeres,a,100.0,21.0,FWD,Arsenal,Liverpool,2.608692
13,Minteh,d,75.0,21.0,MID,Brighton,Man City,2.562976
14,Strand Larsen,a,100.0,21.0,FWD,Wolves,Everton,2.082956

In [21]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
        -- AND position IN ('MID','FWD')
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 21

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Gravenberch,a,100.0,21.0,MID,Liverpool,Arsenal,5.905984
1,Garner,a,NaN,21.0,MID,Everton,Wolves,5.766857
2,Tavernier,a,NaN,21.0,MID,Bournemouth,Spurs,5.122015
3,Martinez,a,100.0,21.0,DEF,Man Utd,Burnley,5.062847
4,Robertson,a,NaN,21.0,DEF,Liverpool,Arsenal,4.938929
5,Dorgu,a,NaN,21.0,DEF,Man Utd,Burnley,4.897282
6,Gordon,a,100.0,21.0,MID,Newcastle,Leeds,4.837946
7,Henderson,a,100.0,21.0,MID,Brentford,Sunderland,4.825968
8,Zubimendi,a,100.0,21.0,MID,Arsenal,Liverpool,4.755781
9,Heaven,a,100.0,21.0,DEF,Man Utd,Burnley,4.744035

In [22]:
print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 38
    ORDER BY xpoints DESC
""")
view.head(10)

When to use second TRIPLE CAPTAIN chip (gws19-38)

  player_name_id  event position team_name  opp_team_name   xpoints
0  Matheus Nunes   34.0      DEF  Man City        Burnley  6.622691
1  Matheus Nunes   23.0      DEF  Man City         Wolves  6.371121
2  Matheus Nunes   28.0      DEF  Man City          Leeds  6.139806
3  Matheus Nunes   30.0      DEF  Man City       West Ham  6.016797
4  Matheus Nunes   24.0      DEF  Man City          Spurs  5.977030
5  Matheus Nunes   29.0      DEF  Man City  Nott'm Forest  5.975819
6  Matheus Nunes   35.0      DEF  Man City        Everton  5.876046
7  Matheus Nunes   37.0      DEF  Man City    Bournemouth  5.866717
8  Matheus Nunes   22.0      DEF  Man City        Man Utd  5.851860
9  Matheus Nunes   36.0      DEF  Man City      Brentford  5.851860

In [23]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW21 AND 25

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Ryan Gravenberch,0,MID,Liverpool,1101.3,30.08,79.1,0.520,0.125,1.364
1,Matheus Nunes,1,DEF,Man City,1048.8,28.39,74.8,0.099,0.149,0.776
2,James Garner,0,MID,Everton,1033.0,27.57,80.6,0.353,0.161,1.418
3,Andrew Robertson,0,DEF,Liverpool,1101.3,27.29,63.1,0.329,0.149,1.348
4,Joël Veltman,0,DEF,Brighton,1092.1,26.23,62.4,0.328,0.126,1.434
5,Marcus Tavernier,0,MID,Bournemouth,1071.9,25.23,77.5,0.345,0.105,1.421
6,Martín Zubimendi Ibáñez,0,MID,Arsenal,1057.6,24.62,75.7,0.345,0.085,1.791
7,Jordan Henderson,0,MID,Brentford,1093.0,23.98,63.7,0.227,0.363,1.466
8,Anthony Gordon,0,MID,Newcastle,1057.5,23.56,76.9,0.224,0.173,1.340
9,Enzo Le Fée,0,MID,Sunderland,1047.7,23.29,78.0,0.210,0.153,1.236
10,Ethan Ampadu,0,MID,Leeds,1096.1,23.00,74.0,0.232,0.110,1.541
11,Yéremy Pino Santos,0,MID,Crystal Palace,1090.5,22.98,73.9,0.238,0.144,1.485
12,Diego Gómez Amarilla,0,MID,Brighton,1092.1,22.88,62.7,0.311,0.140,1.375
13,Rayan Aït-Nouri,0,DEF,Man City,1048.8,22.17,50.5,0.103,0.132,0.777
14,Emile Smith Rowe,0,MID,Fulham,1058.7,22.11,75.9,0.225,0.077,1.343
15,Tim Iroegbunam,0,MID,Everton,1033.0,21.54,70.5,0.157,0.106,1.438
16,Anton Stach,0,MID,Leeds,1096.1,21.52,77.9,0.153,0.149,1.482
17,Kevin Danso,0,DEF,Spurs,1036.7,21.26,74.3,0.130,0.047,1.479
18,Yasin Ayari,0,MID,Brighton,1092.1,21.25,70.5,0.224,0.056,1.365
19,Malo Gusto,0,DEF,Chelsea,1009.0,21.22,64.3,0.101,0.117,1.463
20,Santiago Ignacio Bueno,0,DEF,Wolves,1111.3,21.19,62.0,0.235,0.122,1.848
21,Adam Wharton,0,MID,Crystal Palace,1090.5,21.19,82.0,0.121,0.133,1.503
22,Josh Laurent,0,MID,Burnley,1058.2,21.19,65.9,0.234,0.048,1.854
23,Álex Jiménez Sánchez,0,DEF,Bournemouth,1071.9,21.17,77.9,0.028,0.079,1.164
24,Dwight McNeil,0,MID,Everton,1033.0,21.16,60.8,0.174,0.124,1.483
25,Lucas Tolentino Coelho de Lima,0,MID,West Ham,1017.9,21.02,64.8,0.179,0.133,1.288
26,Dominik Szoboszlai,1,MID,Liverpool,1101.3,21.01,55.5,0.417,0.209,1.250
27,Nordi Mukiele,0,DEF,Sunderland,1047.7,20.97,85.9,0.033,0.080,1.353
28,Armando Broja,0,FWD,Burnley,1058.2,20.88,68.7,0.312,0.056,1.973
29,Nathan Aké,0,DEF,Man City,1048.8,20.86,42.3,0.078,0.084,0.804
30,Conor Bradley,0,DEF,Liverpool,1101.3,20.86,70.4,0.074,0.093,1.381
31,Morgan Gibbs-White,1,MID,Nott'm Forest,1064.5,20.74,66.4,0.190,0.124,1.350
32,John Stones,0,DEF,Man City,1048.8,20.61,40.8,0.095,0.092,0.823
33,Carlos Henrique Casimiro,0,MID,Man Utd,1088.1,20.61,70.4,0.157,0.095,1.479
34,Adrien Truffert,0,DEF,Bournemouth,1071.9,20.52,79.2,0.026,0.058,1.211
35,Lesley Ugochukwu,0,MID,Burnley,1058.2,20.49,69.7,0.207,0.074,1.779
36,Trai Hume,0,DEF,Sunderland,1047.7,20.46,77.6,0.032,0.066,1.340
37,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1048.8,20.44,74.1,0.061,0.088,0.673
38,Nicolò Savona,0,DEF,Nott'm Forest,1064.5,20.36,69.9,0.062,0.077,1.310
39,Ibrahima Konaté,1,DEF,Liverpool,1101.3,20.33,84.9,0.052,0.052,1.371
40,James Tarkowski,1,DEF,Everton,1033.0,20.28,86.1,0.052,0.057,1.375
41,Omari Hutchinson,0,MID,Nott'm Forest,1064.5,20.14,73.3,0.119,0.157,1.460
42,Omar Alderete,0,DEF,Sunderland,1047.7,20.12,85.3,0.039,0.036,1.401
43,Gabriel Gudmundsson,0,DEF,Leeds,1096.1,20.11,83.9,0.054,0.122,1.575
44,Ladislav Krejcí,0,DEF,Wolves,1111.3,20.08,65.5,0.173,0.060,1.761
45,Vitalii Mykolenko,0,DEF,Everton,1033.0,20.06,85.4,0.033,0.066,1.340
46,Patrick Dorgu,0,DEF,Man Utd,1088.1,20.03,70.8,0.072,0.075,1.414
47,Vitaly Janelt,0,MID,Brentford,1093.0,20.01,78.2,0.100,0.109,1.520
48,Dennis Cirkin,0,DEF,Sunderland,1047.7,20.00,85.0,0.057,0.066,1.491
49,Abdukodir Khusanov,0,DEF,Man City,1048.8,19.95,40.8,0.062,0.040,0.783

In [24]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW21 AND 25

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Jørgen Strand Larsen,1,FWD,Wolves,1111.3,10.42,35.8,0.295,0.060,1.768
1,Viktor Gyökeres,1,FWD,Arsenal,1057.6,13.42,53.3,0.435,0.047,1.128
2,Emiliano Martínez Romero,1,GK,Aston Villa,1064.6,13.72,70.4,NaN,NaN,1.814
3,Tijjani Reijnders,1,MID,Man City,1048.8,17.70,47.8,0.259,0.194,0.709
4,Yankuba Minteh,1,MID,Brighton,1092.1,17.71,60.2,0.089,0.096,1.342
5,David Raya Martín,1,GK,Arsenal,1057.6,17.77,85.7,NaN,NaN,1.385
6,Raúl Jiménez Rodríguez,1,FWD,Fulham,1058.7,18.59,64.1,0.333,0.048,1.323
7,Maxence Lacroix,1,DEF,Crystal Palace,1090.5,18.79,85.6,0.070,0.047,1.587
8,Bruno Borges Fernandes,1,MID,Man Utd,1088.1,19.15,49.3,0.325,0.322,1.538
9,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1057.6,19.30,59.2,0.117,0.061,1.192
10,James Tarkowski,1,DEF,Everton,1033.0,20.28,86.1,0.052,0.057,1.375
11,Ibrahima Konaté,1,DEF,Liverpool,1101.3,20.33,84.9,0.052,0.052,1.371
12,Morgan Gibbs-White,1,MID,Nott'm Forest,1064.5,20.74,66.4,0.190,0.124,1.350
13,Dominik Szoboszlai,1,MID,Liverpool,1101.3,21.01,55.5,0.417,0.209,1.250
14,Matheus Nunes,1,DEF,Man City,1048.8,28.39,74.8,0.099,0.149,0.776

In [25]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 21 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Liverpool,Ryan Gravenberch,108.539026,Tijjani Reijnders,63.407729,45.131297
1,FWD,Burnley,Armando Broja,75.599948,Jørgen Strand Larsen,37.922399,37.677549
2,MID,Everton,James Garner,98.474195,Tijjani Reijnders,63.407729,35.066466
3,DEF,Liverpool,Andrew Robertson,100.721860,James Tarkowski,70.669382,30.052478
4,FWD,Wolves,Mateus Mané,66.235577,Jørgen Strand Larsen,37.922399,28.313178
5,MID,Bournemouth,Marcus Tavernier,91.133199,Tijjani Reijnders,63.407729,27.725470
6,MID,Arsenal,Martín Zubimendi Ibáñez,88.734260,Tijjani Reijnders,63.407729,25.326531
7,DEF,Brighton,Joël Veltman,95.160055,James Tarkowski,70.669382,24.490673
8,FWD,Wolves,Tolu Arokodare,62.048455,Jørgen Strand Larsen,37.922399,24.126056
9,MID,Brentford,Jordan Henderson,87.198580,Tijjani Reijnders,63.407729,23.790850
10,FWD,Burnley,Lyle Foster,59.308265,Jørgen Strand Larsen,37.922399,21.385867
11,FWD,Burnley,Ashley Barnes,59.282629,Jørgen Strand Larsen,37.922399,21.360230
12,MID,Newcastle,Anthony Gordon,84.222916,Tijjani Reijnders,63.407729,20.815187
13,MID,Crystal Palace,Yéremy Pino Santos,83.999147,Tijjani Reijnders,63.407729,20.591418
14,MID,Brighton,Diego Gómez Amarilla,83.360678,Tijjani Reijnders,63.407729,19.952948
15,MID,Leeds,Ethan Ampadu,83.356109,Tijjani Reijnders,63.407729,19.948380
16,FWD,Newcastle,William Osula,57.428453,Jørgen Strand Larsen,37.922399,19.506054
17,MID,Sunderland,Enzo Le Fée,82.655368,Tijjani Reijnders,63.407729,19.247639
18,GK,Fulham,Bernd Leno,67.154430,Emiliano Martínez Romero,49.757546,17.396884
19,FWD,Chelsea,Marc Guiu Paz,55.171074,Jørgen Strand Larsen,37.922399,17.248675

In [26]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 21 and 25:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,21.0,MID,Chelsea,Fulham,6.4,1048.275375,4.860585,78.68596,0.214347,0.241360,1.494233
1,Enzo Fernández,22.0,MID,Chelsea,Brentford,6.4,1057.885583,4.856312,78.68596,0.214347,0.233995,1.490304
2,Enzo Fernández,23.0,MID,Chelsea,Crystal Palace,6.4,1072.933483,4.852342,78.68596,0.214824,0.233330,1.503587
3,Enzo Fernández,24.0,MID,Chelsea,West Ham,6.4,968.231321,4.940271,78.68596,0.223666,0.261939,1.577487
4,Enzo Fernández,25.0,MID,Chelsea,Wolves,6.4,897.754426,5.289646,78.68596,0.279444,0.282189,1.487584

In [27]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [28]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [29]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.01 minute(s)