In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
stats_current_gameweek = 16
picks_current_gameweek = 16
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 17
Squad Points: 67.55

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,B.Fernandes,a,NaN,17.0,MID,Man Utd,Aston Villa,6.092706
1,Matheus N.,a,NaN,17.0,DEF,Man City,West Ham,5.276641
2,Amad,n,100.0,17.0,MID,Man Utd,Aston Villa,5.246652
3,Szoboszlai,d,NaN,17.0,MID,Liverpool,Spurs,4.897114
4,Lacroix,a,NaN,17.0,DEF,Crystal Palace,Leeds,4.692987
5,Minteh,a,NaN,17.0,MID,Brighton,Sunderland,4.421449
6,Konaté,a,100.0,17.0,DEF,Liverpool,Spurs,4.336876
7,O.Dango,n,100.0,17.0,MID,Brentford,Wolves,4.194391
8,Raya,a,NaN,17.0,GK,Arsenal,Everton,3.766088
9,Gyökeres,a,100.0,17.0,FWD,Arsenal,Everton,3.633307
10,Gabriel,i,0.0,17.0,DEF,Arsenal,Everton,3.584115
11,Raúl,a,100.0,17.0,FWD,Fulham,Nott'm Forest,3.241180
12,Tarkowski,a,NaN,17.0,DEF,Everton,Arsenal,3.075313
13,Flemming,a,NaN,17.0,FWD,Burnley,Bournemouth,2.600368
14,Pope,d,25.0,17.0,GK,Newcastle,Chelsea,2.401484

In [6]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 17

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Truffert,a,NaN,17.0,DEF,Bournemouth,Burnley,5.686056
1,Rúben,a,NaN,17.0,DEF,Man City,West Ham,5.092038
2,Wilson,a,100.0,17.0,MID,Fulham,Nott'm Forest,5.017269
3,Yeremy,a,100.0,17.0,MID,Crystal Palace,Leeds,4.944666
4,Tavernier,a,NaN,17.0,MID,Bournemouth,Burnley,4.918708
5,Ballard,a,100.0,17.0,DEF,Sunderland,Brighton,4.843439
6,Mukiele,a,NaN,17.0,DEF,Sunderland,Brighton,4.823103
7,Reijnders,a,NaN,17.0,MID,Man City,West Ham,4.780447
8,Gusto,a,100.0,17.0,DEF,Chelsea,Newcastle,4.768055
9,Cullen,a,NaN,17.0,MID,Burnley,Bournemouth,4.736896

In [7]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(10)

When to use first TRIPLE CAPTAIN chip (gws1-19)

           player_name_id  event position  team_name  opp_team_name   xpoints
0  Bruno Borges Fernandes   19.0      MID    Man Utd         Wolves  7.067285
1             Amad Diallo   19.0      MID    Man Utd         Wolves  6.427795
2  Bruno Borges Fernandes   18.0      MID    Man Utd      Newcastle  6.182688
3  Bruno Borges Fernandes   17.0      MID    Man Utd    Aston Villa  6.092706
4         James Tarkowski   18.0      DEF    Everton        Burnley  5.668169
5             Amad Diallo   18.0      MID    Man Utd      Newcastle  5.384730
6           Matheus Nunes   17.0      DEF   Man City       West Ham  5.276641
7             Amad Diallo   17.0      MID    Man Utd    Aston Villa  5.246652
8      Dominik Szoboszlai   18.0      MID  Liverpool         Wolves  5.201120
9           Matheus Nunes   18.0      DEF   Man City  Nott'm Forest  5.124453

In [8]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+3}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+3}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW17 AND 19

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,1,MID,Man Utd,1057.7,19.34,69.8,0.488,0.340,2.036
1,Amad Diallo,1,MID,Man Utd,1057.7,17.06,82.2,0.378,0.204,1.587
2,Diego Gómez Amarilla,0,MID,Brighton,1090.1,15.67,61.6,0.549,0.087,1.402
3,Matheus Nunes,1,DEF,Man City,1021.3,15.33,82.0,0.061,0.118,1.045
4,Dominik Szoboszlai,1,MID,Liverpool,949.2,15.09,83.4,0.200,0.200,1.061
5,Harry Wilson,0,MID,Fulham,1037.2,15.03,75.4,0.309,0.143,1.322
6,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1021.3,14.93,86.2,0.063,0.034,0.912
7,Yéremy Pino Santos,0,MID,Crystal Palace,991.5,14.40,79.7,0.183,0.193,0.997
8,Josh Cullen,0,MID,Burnley,1070.2,14.20,81.6,0.271,0.109,1.796
9,Ibrahim Sangaré,0,MID,Nott'm Forest,1110.3,14.20,64.5,0.232,0.167,1.151
10,Malo Gusto,0,DEF,Chelsea,1106.1,14.19,63.4,0.158,0.145,1.404
11,Maxence Lacroix,1,DEF,Crystal Palace,991.5,14.01,85.9,0.029,0.053,0.970
12,Tijjani Reijnders,0,MID,Man City,1021.3,13.82,65.8,0.198,0.165,0.945
13,Samuel Chukwueze,0,MID,Fulham,1037.2,13.79,65.5,0.254,0.182,1.258
14,Calvin Bassey,0,DEF,Fulham,1037.2,13.62,63.9,0.156,0.089,1.292
15,Nathan Collins,0,DEF,Brentford,985.0,13.55,65.9,0.069,0.103,1.121
16,Omari Hutchinson,0,MID,Nott'm Forest,1110.3,13.48,65.1,0.206,0.210,1.213
17,Adam Wharton,0,MID,Crystal Palace,991.5,13.45,81.6,0.148,0.141,0.981
18,Jake O'Brien,0,DEF,Everton,1050.0,13.43,81.8,0.096,0.051,1.227
19,Yankuba Minteh,1,MID,Brighton,1090.1,13.42,81.9,0.216,0.119,1.300
20,Ibrahima Konaté,1,DEF,Liverpool,949.2,13.39,84.2,0.038,0.073,1.159
21,James Tarkowski,1,DEF,Everton,1050.0,13.37,87.0,0.078,0.072,1.241
22,Marcus Tavernier,0,MID,Bournemouth,1018.6,13.35,74.0,0.185,0.162,1.376
23,Sepp van den Berg,0,DEF,Brentford,985.0,13.24,86.8,0.078,0.015,1.115
24,Rayan Cherki,0,MID,Man City,1021.3,13.23,52.1,0.388,0.288,1.082
25,Mats Wieffer,0,MID,Brighton,1090.1,13.16,83.4,0.170,0.100,1.341
26,Adrien Truffert,0,DEF,Bournemouth,1018.6,13.15,86.1,0.090,0.070,1.294
27,Emile Smith Rowe,0,MID,Fulham,1037.2,13.12,62.4,0.248,0.089,1.092
28,Nordi Mukiele,0,DEF,Sunderland,1088.7,13.08,86.6,0.024,0.093,1.137
29,Vitalii Mykolenko,0,DEF,Everton,1050.0,13.05,86.9,0.075,0.042,1.246
30,Kenny Tete,0,DEF,Fulham,1037.2,13.04,73.7,0.061,0.056,1.184
31,Mohammed Kudus,0,MID,Spurs,1111.3,13.00,79.8,0.173,0.143,1.382
32,Virgil van Dijk,0,DEF,Liverpool,949.2,12.94,86.9,0.066,0.024,1.187
33,Daniel Ballard,0,DEF,Sunderland,1088.7,12.92,79.6,0.047,0.063,1.178
34,Michael Kayode,0,DEF,Brentford,985.0,12.92,80.1,0.041,0.053,1.124
35,Anton Stach,0,MID,Leeds,1114.4,12.83,74.2,0.170,0.103,1.170
36,Dan Burn,0,DEF,Newcastle,1024.5,12.79,64.4,0.090,0.026,1.243
37,Georginio Rutter,0,MID,Brighton,1090.1,12.78,70.5,0.190,0.111,1.367
38,Jayden Bogle,0,DEF,Leeds,1114.4,12.77,84.6,0.037,0.093,1.105
39,Bruno Guimarães Rodriguez Moura,0,MID,Newcastle,1024.5,12.76,69.6,0.141,0.156,1.345
40,Carlos Henrique Casimiro,0,MID,Man Utd,1057.7,12.71,78.0,0.185,0.078,1.536
41,Pascal Struijk,0,DEF,Leeds,1114.4,12.40,85.9,0.057,0.039,1.159
42,Dango Ouattara,1,MID,Brentford,985.0,12.40,78.1,0.177,0.059,1.203
43,Gabriel Gudmundsson,0,DEF,Leeds,1114.4,12.37,75.6,0.040,0.057,1.129
44,Michael Keane,0,DEF,Everton,1050.0,12.34,76.2,0.108,0.014,1.352
45,Conor Bradley,0,DEF,Liverpool,949.2,12.30,43.9,0.064,0.127,0.890
46,Jaka Bijol,0,DEF,Leeds,1114.4,12.25,69.9,0.045,0.028,1.114
47,Tanaka Ao,0,MID,Leeds,1114.4,12.24,66.8,0.141,0.117,1.224
48,Enzo Le Fée,0,MID,Sunderland,1088.7,12.17,71.5,0.156,0.092,1.228
49,Curtis Jones,0,MID,Liverpool,949.2,12.13,61.3,0.104,0.103,0.990

In [9]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 17 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,GK,Crystal Palace,Dean Henderson,82.413484,Nick Pope,53.431481,28.982003
1,GK,Liverpool,Alisson Becker,81.943114,Nick Pope,53.431481,28.511633
2,DEF,Man City,Rúben dos Santos Gato Alves Dias,108.622343,Gabriel dos Santos Magalhães,80.519255,28.103088
3,DEF,Chelsea,Malo Gusto,108.509488,Gabriel dos Santos Magalhães,80.519255,27.990233
4,FWD,Nott'm Forest,Igor Jesus Maciel da Cruz,84.724368,Zian Flemming,57.368564,27.355804
5,MID,Brighton,Diego Gómez Amarilla,114.351900,Dango Ouattara,90.050651,24.301250
6,FWD,West Ham,Jarrod Bowen,81.618493,Zian Flemming,57.368564,24.249928
7,GK,Bournemouth,Đorđe Petrović,77.483278,Nick Pope,53.431481,24.051797
8,GK,Aston Villa,Marco Bizot,77.409664,Nick Pope,53.431481,23.978183
9,GK,West Ham,Alphonse Areola,75.154936,Nick Pope,53.431481,21.723455
10,MID,Fulham,Harry Wilson,110.499017,Dango Ouattara,90.050651,20.448366
11,GK,Nott'm Forest,Matz Sels,73.716949,Nick Pope,53.431481,20.285468
12,FWD,Crystal Palace,Jean-Philippe Mateta,77.579075,Zian Flemming,57.368564,20.210510
13,GK,Newcastle,Aaron Ramsdale,73.438010,Nick Pope,53.431481,20.006529
14,DEF,Sunderland,Nordi Mukiele,98.403204,Gabriel dos Santos Magalhães,80.519255,17.883949
15,DEF,Leeds,Jayden Bogle,97.965846,Gabriel dos Santos Magalhães,80.519255,17.446591
16,DEF,Sunderland,Daniel Ballard,97.595347,Gabriel dos Santos Magalhães,80.519255,17.076092
17,DEF,Fulham,Calvin Bassey,95.965253,Gabriel dos Santos Magalhães,80.519255,15.445998
18,DEF,Leeds,Pascal Struijk,95.369993,Gabriel dos Santos Magalhães,80.519255,14.850738
19,DEF,Leeds,Gabriel Gudmundsson,94.968172,Gabriel dos Santos Magalhães,80.519255,14.448917

In [10]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 17 and 21:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.6,1097.420086,4.678789,80.073727,0.219794,0.153535,1.439194
1,Enzo Fernández,18.0,MID,Chelsea,Aston Villa,6.6,1173.335624,4.639995,80.073727,0.230241,0.146131,1.565142
2,Enzo Fernández,19.0,MID,Chelsea,Bournemouth,6.6,1047.663673,4.798028,80.073727,0.219794,0.168172,1.327445
3,Enzo Fernández,20.0,MID,Chelsea,Man City,6.6,1236.029561,4.603676,80.073727,0.230241,0.146131,1.677612
4,Enzo Fernández,21.0,MID,Chelsea,Fulham,6.6,1029.261205,4.853895,80.073727,0.223891,0.169536,1.370442

In [11]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [12]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [15]:
view = db_creator.run_sql(f"""
    SELECT *
    FROM fpl_picks2
""")
view.head(10)

ProgrammingError: (psycopg2.errors.UndefinedTable) relation "fpl_picks2" does not exist
LINE 3:     FROM fpl_picks2
                 ^

[SQL:
    SELECT *
    FROM fpl_picks2
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [13]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.01 minute(s)