In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
stats_current_gameweek = 12
picks_current_gameweek = 12
current_season = 20252026

In [5]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(5)

Check status of available players in GW 13

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Enzo,a,100.0,13.0,MID,Chelsea,Arsenal,5.344600
1,Kayode,a,NaN,13.0,DEF,Brentford,Burnley,4.952589
2,Van den Berg,a,NaN,13.0,DEF,Brentford,Burnley,4.927085
3,Collins,a,NaN,13.0,DEF,Brentford,Burnley,4.863596
4,Tavernier,a,NaN,13.0,MID,Bournemouth,Sunderland,4.713850

In [13]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(10)

When to use first TRIPLE CAPTAIN chip (gws1-19)

,player_name_id,event,position,team_name,opp_team_name,xpoints
0,Gabriel dos Santos Magalhães,16.0,DEF,Arsenal,Wolves,6.396964
1,Matheus Nunes,13.0,DEF,Man City,Leeds,5.717532
2,Ibrahima Konaté,15.0,DEF,Liverpool,Leeds,5.473267
3,Ibrahima Konaté,19.0,DEF,Liverpool,Leeds,5.473267
4,Ibrahima Konaté,18.0,DEF,Liverpool,Wolves,5.473267
5,Matheus Nunes,17.0,DEF,Man City,West Ham,5.341799
6,Bruno Borges Fernandes,19.0,MID,Man Utd,Wolves,5.266036
7,Bruno Borges Fernandes,15.0,MID,Man Utd,Wolves,5.266036
8,Gabriel dos Santos Magalhães,18.0,DEF,Arsenal,Brighton,5.198117
9,Gabriel dos Santos Magalhães,14.0,DEF,Arsenal,Brentford,5.195599

In [25]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW13 AND 17

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Enzo Fernández,0,MID,Chelsea,1079.1,27.82,78.6,0.335,0.229,1.190
1,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1066.1,27.05,71.1,0.136,0.119,0.951
2,Bruno Borges Fernandes,1,MID,Man Utd,1043.4,24.40,83.5,0.229,0.195,1.370
3,Matheus Nunes,1,DEF,Man City,1012.5,23.93,81.4,0.049,0.067,1.014
4,Marcus Tavernier,0,MID,Bournemouth,1036.2,23.91,83.4,0.239,0.151,1.338
5,Bruno Guimarães Rodriguez Moura,0,MID,Newcastle,1029.0,23.49,82.7,0.228,0.133,1.382
6,Jacob Murphy,0,MID,Newcastle,1029.0,23.36,76.6,0.236,0.143,1.209
7,Ibrahima Konaté,1,DEF,Liverpool,1008.2,22.95,65.6,0.076,0.076,1.147
8,Dominik Szoboszlai,1,MID,Liverpool,1008.2,22.74,82.1,0.141,0.200,1.201
9,Yankuba Minteh,1,MID,Brighton,1075.4,22.45,81.9,0.181,0.146,1.255
10,Yéremy Pino Santos,0,MID,Crystal Palace,1020.5,22.34,62.5,0.213,0.171,1.152
11,Sepp van den Berg,0,DEF,Brentford,998.9,22.27,82.6,0.083,0.044,1.237
12,Amad Diallo,1,MID,Man Utd,1043.4,22.12,82.7,0.158,0.153,1.250
13,Martín Zubimendi Ibáñez,0,MID,Arsenal,1066.1,22.09,78.6,0.137,0.134,0.889
14,Michael Kayode,0,DEF,Brentford,998.9,21.91,72.1,0.041,0.111,1.235
15,Elliot Anderson,0,MID,Nott'm Forest,1024.8,21.82,84.0,0.154,0.131,1.350
16,Alexis Mac Allister,0,MID,Liverpool,1008.2,21.75,67.7,0.180,0.139,1.071
17,Nathan Collins,0,DEF,Brentford,998.9,21.66,83.5,0.042,0.071,1.216
18,Dango Ouattara,1,MID,Brentford,998.9,21.33,62.4,0.235,0.090,1.185
19,David Raya Martín,1,GK,Arsenal,1066.1,21.25,84.8,NaN,NaN,0.854
20,Maxence Lacroix,1,DEF,Crystal Palace,1020.5,21.10,85.0,0.047,0.043,1.237
21,Diego Gómez Amarilla,0,MID,Brighton,1075.4,21.10,70.8,0.189,0.101,1.202
22,Neco Williams,0,DEF,Nott'm Forest,1024.8,20.85,84.1,0.059,0.060,1.316
23,Adrien Truffert,0,DEF,Bournemouth,1036.2,20.70,68.9,0.037,0.062,1.216
24,Kiernan Dewsbury-Hall,0,MID,Everton,1118.6,20.69,77.9,0.125,0.154,1.438
25,Carlos Henrique Casimiro,0,MID,Man Utd,1043.4,20.69,70.7,0.179,0.090,1.254
26,Ryan Gravenberch,0,MID,Liverpool,1008.2,20.46,79.1,0.094,0.125,1.074
27,Ferdi Kadıoğlu,0,DEF,Brighton,1075.4,20.32,83.1,0.044,0.065,1.320
28,Luke Shaw,0,DEF,Man Utd,1043.4,20.28,80.0,0.033,0.061,1.259
29,Daichi Kamada,0,MID,Crystal Palace,1020.5,20.11,75.5,0.107,0.116,1.236
30,Dan Ndoye,0,MID,Nott'm Forest,1024.8,20.06,78.3,0.112,0.115,1.239
31,Adam Smith,0,DEF,Bournemouth,1036.2,19.96,14.8,0.009,0.011,0.654
32,Nicolò Savona,0,DEF,Nott'm Forest,1024.8,19.94,80.7,0.073,0.043,1.441
33,Mikkel Damsgaard,0,MID,Brentford,998.9,19.90,67.2,0.095,0.149,1.178
34,Nico González Iglesias,0,MID,Man City,1012.5,19.87,68.1,0.083,0.110,0.894
35,Harry Wilson,0,MID,Fulham,1052.4,19.84,66.5,0.160,0.090,1.324
36,Nikola Milenković,0,DEF,Nott'm Forest,1024.8,19.84,84.3,0.051,0.041,1.327
37,Callum Wilson,0,FWD,West Ham,1138.8,19.82,66.6,0.409,0.055,1.727
38,Ryan Sessegnon,0,MID,Fulham,1052.4,19.72,81.9,0.109,0.087,1.381
39,Nick Pope,1,GK,Newcastle,1029.0,19.67,71.9,NaN,NaN,1.229
40,Georginio Rutter,0,MID,Brighton,1075.4,19.64,73.4,0.100,0.111,1.186
41,Yasin Ayari,0,MID,Brighton,1075.4,19.63,79.9,0.107,0.077,1.220
42,Dan Burn,0,DEF,Newcastle,1029.0,19.58,48.2,0.252,0.168,1.373
43,James Garner,0,MID,Everton,1118.6,19.56,81.8,0.102,0.101,1.519
44,Jordan Henderson,0,MID,Brentford,998.9,19.53,80.5,0.061,0.126,1.186
45,Sandro Tonali,0,MID,Newcastle,1029.0,19.47,75.9,0.081,0.107,1.240
46,Nathaniel Clyne,0,DEF,Crystal Palace,1020.5,19.45,3.7,0.063,0.023,0.715
47,Lewis Dunk,0,DEF,Brighton,1075.4,19.45,65.4,0.053,0.026,1.342
48,Pau Torres,0,DEF,Aston Villa,1059.9,19.43,68.2,0.036,0.027,1.343
49,Bernardo Mota Veiga de Carvalho e Silva,0,MID,Man City,1012.5,19.37,65.6,0.052,0.127,0.913

In [8]:
print(f"\nBest available players to replace worst in my team over next 5 GWs: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team over next 5 GWs: 13 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Chelsea,Enzo Fernández,145.051644,Dango Ouattara,107.862234,37.189410
1,FWD,West Ham,Callum Wilson,105.158176,Viktor Gyökeres,86.274830,18.883346
2,MID,Bournemouth,Marcus Tavernier,121.588063,Dango Ouattara,107.862234,13.725829
3,FWD,Fulham,Raúl Jiménez Rodríguez,99.780537,Viktor Gyökeres,86.274830,13.505707
4,MID,Newcastle,Jacob Murphy,119.819273,Dango Ouattara,107.862234,11.957039
5,FWD,Spurs,Richarlison de Andrade,97.568598,Viktor Gyökeres,86.274830,11.293768
6,MID,Newcastle,Bruno Guimarães Rodriguez Moura,119.126743,Dango Ouattara,107.862234,11.264509
7,DEF,Brentford,Sepp van den Berg,112.324649,James Tarkowski,104.907076,7.417572
8,MID,Arsenal,Martín Zubimendi Ibáñez,115.058666,Dango Ouattara,107.862234,7.196433
9,MID,Crystal Palace,Yéremy Pino Santos,114.025935,Dango Ouattara,107.862234,6.163701
10,DEF,Brentford,Michael Kayode,110.206899,James Tarkowski,104.907076,5.299823
11,MID,Nott'm Forest,Elliot Anderson,111.857571,Dango Ouattara,107.862234,3.995338
12,MID,Liverpool,Alexis Mac Allister,111.528226,Dango Ouattara,107.862234,3.665992
13,DEF,Brentford,Nathan Collins,107.779240,James Tarkowski,104.907076,2.872164
14,MID,Everton,Kiernan Dewsbury-Hall,110.325329,Dango Ouattara,107.862234,2.463095
15,MID,Brighton,Diego Gómez Amarilla,109.928379,Dango Ouattara,107.862234,2.066145
16,DEF,Brighton,Ferdi Kadıoğlu,105.925268,James Tarkowski,104.907076,1.018192
17,DEF,Nott'm Forest,Neco Williams,104.517380,James Tarkowski,104.907076,-0.389697
18,DEF,Bournemouth,Adrien Truffert,104.507786,James Tarkowski,104.907076,-0.399290
19,DEF,Everton,Michael Keane,104.499337,James Tarkowski,104.907076,-0.407739

In [9]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 13 and 17:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,13.0,MID,Chelsea,Arsenal,6.7,1248.695856,5.344600,79.363356,0.320070,0.215751,1.340773
1,Enzo Fernández,14.0,MID,Chelsea,Leeds,6.7,918.161783,6.014766,77.378930,0.375826,0.261320,0.764965
2,Enzo Fernández,15.0,MID,Chelsea,Bournemouth,6.7,1065.801289,5.510428,78.452444,0.326668,0.216737,1.175059
3,Enzo Fernández,16.0,MID,Chelsea,Everton,6.7,1063.896408,5.509289,78.407557,0.326668,0.216737,1.175059
4,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.7,1098.980975,5.436159,79.309153,0.324767,0.232260,1.494184

In [10]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [11]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [12]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
#10/11/25: Finished in 0.01 minute(s)

Finished in 0.01 minute(s)