In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 32
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 33
Squad Points: 91.84

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,33.0,DEF,Man City,Arsenal; Burnley,11.206146,173.0
1,Flemming,a,100.0,33.0,FWD,Burnley,Nott'm Forest; Man City,8.235576,144.0
2,F.Kadıoğlu,a,NaN,33.0,DEF,Brighton,Spurs; Chelsea,8.038036,175.0
3,Van Hecke,a,100.0,33.0,DEF,Brighton,Spurs; Chelsea,7.959091,173.0
4,Bruno G.,i,0.0,33.0,MID,Newcastle,Bournemouth,5.343626,60.0
5,Gibbs-White,a,100.0,33.0,MID,Nott'm Forest,Burnley,5.277031,84.0
6,B.Fernandes,a,100.0,33.0,MID,Man Utd,Chelsea,4.665258,81.0
7,Szoboszlai,a,100.0,33.0,MID,Liverpool,Everton,4.334788,86.0
8,Gabriel,a,100.0,33.0,DEF,Arsenal,Man City,4.334743,84.0
9,Mac Allister,a,100.0,33.0,MID,Liverpool,Everton,4.074164,71.0
10,Brobbey,a,100.0,33.0,FWD,Sunderland,Aston Villa,3.953466,83.0
11,Mings,d,100.0,33.0,DEF,Aston Villa,Sunderland,3.899190,71.0
12,Martinez,d,100.0,33.0,GK,Aston Villa,Sunderland,3.474340,89.0
13,Raya,a,NaN,33.0,GK,Arsenal,Man City,3.106594,89.0
14,Isak,a,100.0,33.0,FWD,Liverpool,Everton,2.735578,30.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW33 AND 37

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1093.4,13.62,29.6,0.531,0.081,1.593
1,Emiliano Martínez Romero,1,GK,Aston Villa,1015.9,18.68,88.9,NaN,NaN,1.294
2,Jan Paul van Hecke,1,DEF,Brighton,1007.7,19.73,108.1,0.052,0.036,1.351
3,Ferdi Kadıoğlu,1,DEF,Brighton,1007.7,20.06,109.3,0.050,0.049,1.337
4,Tyrone Mings,1,DEF,Aston Villa,1015.9,20.17,71.2,0.077,0.085,1.320
5,Alexis Mac Allister,1,MID,Liverpool,1093.4,20.26,71.1,0.236,0.101,1.694
6,David Raya Martín,1,GK,Arsenal,1043.9,20.39,89.1,NaN,NaN,0.955
7,Brian Brobbey,1,FWD,Sunderland,1052.3,20.40,83.5,0.386,0.040,1.357
8,Zian Flemming,1,FWD,Burnley,1124.6,20.78,89.7,0.524,0.046,1.752
9,Dominik Szoboszlai,1,MID,Liverpool,1093.4,21.37,85.7,0.157,0.162,1.681
10,Morgan Gibbs-White,1,MID,Nott'm Forest,1040.1,23.64,83.8,0.209,0.220,1.337
11,Bruno Borges Fernandes,1,MID,Man Utd,1081.6,23.94,80.3,0.226,0.224,1.409
12,Matheus Nunes,1,DEF,Man City,1073.5,26.58,108.0,0.048,0.305,1.092
13,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1088.5,26.74,59.9,0.545,0.395,1.677
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1043.9,27.25,83.3,0.073,0.142,0.821

In [8]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
    AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW33 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Zian Flemming,a,1,FWD,Burnley,1087.1,25.10,86.3,1.000,0.527,1.000,0.046,1.694
1,Brian Brobbey,a,1,FWD,Sunderland,1061.2,24.51,83.2,1.000,0.390,1.000,0.040,1.363
2,Valentín Castellanos,a,0,FWD,West Ham,1086.1,23.42,75.1,1.000,0.376,1.000,0.064,1.346
3,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1057.1,23.09,83.1,1.000,0.315,1.000,0.051,1.520
4,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1074.3,22.63,59.3,1.000,0.510,1.000,0.076,1.525
5,Marc Guiu Paz,a,0,FWD,Chelsea,1055.4,21.11,53.2,1.000,0.592,1.000,0.135,1.536
6,Lorenzo Lucca,a,0,FWD,Nott'm Forest,1047.3,20.92,43.5,1.000,0.611,1.000,0.178,1.462
7,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1047.3,20.81,74.0,1.000,0.270,1.000,0.059,1.463
8,Gabriel Fernando de Jesus,a,0,FWD,Arsenal,1046.3,20.32,29.3,1.751,0.926,4.115,0.300,1.097
9,William Osula,a,0,FWD,Newcastle,1080.7,20.05,48.8,1.000,0.548,1.000,0.054,1.504
10,Pablo Felipe Pereira de Jesus,a,0,FWD,West Ham,1086.1,19.60,71.0,1.000,0.269,1.000,0.044,1.511
11,Lyle Foster,a,0,FWD,Burnley,1087.1,19.20,68.3,1.000,0.460,1.000,0.036,1.851
12,Jonah Kusi-Asare,a,0,FWD,Fulham,1089.0,19.18,34.5,1.000,0.650,1.000,0.137,1.793
13,Chris Wood,a,0,FWD,Nott'm Forest,1047.3,18.32,31.4,1.594,0.830,1.956,0.079,1.423
14,Adam Armstrong,a,0,FWD,Wolves,1002.7,18.30,67.2,1.000,0.233,1.000,0.036,1.405
15,Charalampos Kostoulas,a,0,FWD,Brighton,1025.8,17.86,38.2,1.000,0.618,1.000,0.146,1.410
16,Rodrigo Muniz Carvalho,a,0,FWD,Fulham,1089.0,17.70,54.4,1.000,0.338,1.000,0.042,1.379
17,Jean-Philippe Mateta,a,0,FWD,Crystal Palace,1105.1,16.97,53.3,1.000,0.326,1.704,0.086,1.533
18,Alexander Isak,a,1,FWD,Liverpool,1090.1,16.46,29.8,1.000,0.536,1.496,0.081,1.594
19,Lukas Nmecha,a,0,FWD,Leeds,987.0,16.36,48.2,1.000,0.424,1.000,0.102,1.334
20,Raúl Jiménez Rodríguez,a,0,FWD,Fulham,1089.0,16.19,40.5,1.000,0.391,1.000,0.087,1.576
21,Mateus Mané,a,0,FWD,Wolves,1002.7,15.55,47.9,1.000,0.309,1.000,0.036,1.576
22,Taiwo Awoniyi,a,0,FWD,Nott'm Forest,1047.3,14.52,31.7,1.377,0.524,1.000,0.032,1.383
23,Tolu Arokodare,a,0,FWD,Wolves,1002.7,14.31,36.5,1.000,0.401,1.000,0.036,1.474
24,Yoane Wissa,a,0,FWD,Newcastle,1080.7,14.29,16.7,1.224,0.503,2.343,0.338,1.488
25,Callum Wilson,a,0,FWD,West Ham,1086.1,14.00,28.0,1.696,0.462,4.430,0.152,1.509
26,Armando Broja,a,0,FWD,Burnley,1087.1,13.93,37.6,1.671,0.491,1.000,0.034,1.743
27,Joël Piroe,a,0,FWD,Leeds,987.0,13.64,25.1,1.000,0.409,1.000,0.042,1.414
28,Joshua Zirkzee,a,0,FWD,Man Utd,1084.2,13.37,19.4,1.000,0.468,1.000,0.071,1.428
29,Enes Ünal,a,0,FWD,Bournemouth,1077.6,13.36,21.7,1.000,0.505,1.000,0.068,1.530
30,Christantus Uche,a,0,FWD,Crystal Palace,1105.1,12.71,21.1,1.000,0.324,1.000,0.046,1.574
31,Tammy Abraham,a,0,FWD,Aston Villa,1052.2,12.60,20.1,1.000,0.381,1.000,0.052,1.218
32,Ashley Barnes,a,0,FWD,Burnley,1087.1,12.54,35.5,1.000,0.263,1.000,0.054,1.722
33,Liam Delap,a,0,FWD,Chelsea,1055.4,12.03,23.8,1.000,0.351,1.000,0.042,1.388
34,Wilson Isidor,a,0,FWD,Sunderland,1061.2,11.84,11.6,1.000,0.455,1.000,0.069,1.465
35,Eliezer Mayenda Dossou,a,0,FWD,Sunderland,1061.2,10.91,13.5,1.000,0.323,1.000,0.034,1.525

In [20]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW33 AND 37

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xg_overperf_factor,avg_xgcp90_pred
0,John Stones,d,0,DEF,Man City,1073.5,31.18,72.7,0.773,3.160,0.063,3.160,1.444
1,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,28.85,100.1,0.152,1.000,0.719,1.000,1.220
2,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1043.9,27.25,83.3,0.073,1.000,0.142,1.000,0.821
3,Matheus Nunes,a,1,DEF,Man City,1073.5,26.58,108.0,0.048,1.000,0.305,1.000,1.092
4,Mats Wieffer,a,0,MID,Brighton,1007.7,25.46,104.0,0.172,1.000,0.407,1.000,1.279
5,Harvey Barnes,a,0,MID,Newcastle,1088.5,25.24,56.3,0.639,1.787,0.275,1.787,1.634
6,Mason Mount,a,0,MID,Man Utd,1081.6,24.51,21.2,1.953,3.345,0.678,3.345,1.576
7,Bruno Borges Fernandes,a,1,MID,Man Utd,1081.6,23.94,80.3,0.226,1.000,0.224,1.000,1.409
8,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1040.1,23.64,83.8,0.209,1.000,0.220,1.000,1.337
9,Max Alleyne,a,0,DEF,Man City,1073.5,23.17,78.1,0.298,1.000,0.061,1.000,1.401
10,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1040.1,23.11,77.5,0.279,1.975,0.145,1.975,1.342
11,Mathias Jensen,a,0,MID,Brentford,1085.7,22.51,84.8,0.234,1.731,0.101,1.731,1.532
12,Lucas Digne,a,0,DEF,Aston Villa,1015.9,22.11,76.1,0.054,1.000,0.197,1.000,1.267
13,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,22.08,104.4,0.048,1.000,0.031,1.000,1.126
14,Marcus Tavernier,a,0,MID,Bournemouth,1091.6,22.06,100.2,0.178,1.000,0.218,1.000,1.407
15,Dwight McNeil,a,0,MID,Everton,1099.0,22.00,71.6,0.266,1.615,0.183,1.615,1.401
16,James Ward-Prowse,a,0,MID,Burnley,1124.6,21.97,90.2,0.278,2.173,0.211,2.173,2.155
17,Ross Barkley,a,0,MID,Aston Villa,1015.9,21.87,72.7,0.227,1.819,0.164,1.819,1.262
18,Rico Lewis,a,0,DEF,Man City,1073.5,21.82,75.1,0.287,1.000,0.107,1.000,1.531
19,Youri Tielemans,a,0,MID,Aston Villa,1015.9,21.78,63.6,0.259,2.326,0.285,2.326,1.224
20,Pascal Groß,a,0,MID,Brighton,1007.7,21.73,107.7,0.137,1.000,0.162,1.000,1.247
21,Eberechi Eze,a,0,MID,Arsenal,1043.9,21.38,56.4,0.301,1.278,0.268,1.278,0.899
22,Dominik Szoboszlai,a,1,MID,Liverpool,1093.4,21.37,85.7,0.157,1.000,0.162,1.000,1.681
23,Cristhian Mosquera,a,0,DEF,Arsenal,1043.9,21.34,61.1,0.046,1.000,0.037,1.000,0.899
24,Benjamin White,a,0,DEF,Arsenal,1043.9,21.29,68.6,0.056,1.000,0.071,1.000,1.058
25,Granit Xhaka,a,0,MID,Sunderland,1052.3,21.23,77.5,0.178,2.049,0.185,2.049,1.398
26,Rodrigo Bentancur,d,0,MID,Spurs,1053.5,21.12,57.5,0.341,1.000,0.337,1.000,2.084
27,Pascal Struijk,a,0,DEF,Leeds,984.7,21.10,108.5,0.079,1.000,0.045,1.000,1.271
28,Amadou Onana,a,0,MID,Aston Villa,1015.9,21.07,83.8,0.170,1.000,0.083,1.000,1.270
29,Michael Keane,a,0,DEF,Everton,1099.0,20.85,81.2,0.166,2.512,0.033,2.512,1.542
30,Zian Flemming,a,1,FWD,Burnley,1124.6,20.78,89.7,0.524,1.000,0.046,1.000,1.752
31,Jayden Bogle,a,0,DEF,Leeds,984.7,20.78,97.0,0.074,1.000,0.066,1.000,1.250
32,Pau Torres,a,0,DEF,Aston Villa,1015.9,20.72,86.1,0.051,1.000,0.030,1.000,1.237
33,John McGinn,a,0,MID,Aston Villa,1015.9,20.64,66.8,0.153,1.000,0.286,1.000,1.209
34,Riccardo Calafiori,d,0,DEF,Arsenal,1043.9,20.61,47.6,0.109,1.000,0.119,1.000,0.956
35,Jack Hinshelwood,a,0,MID,Brighton,1007.7,20.41,89.9,0.157,1.000,0.190,1.000,1.280
36,Brian Brobbey,a,1,FWD,Sunderland,1052.3,20.40,83.5,0.386,1.000,0.040,1.000,1.357
37,David Raya Martín,a,1,GK,Arsenal,1043.9,20.39,89.1,NaN,1.000,NaN,1.000,0.955
38,Kevin Schade,a,0,MID,Brentford,1085.7,20.38,71.6,0.185,1.000,0.185,1.000,1.521
39,James Justin,a,0,DEF,Leeds,984.7,20.37,107.5,0.042,1.000,0.058,1.000,1.245
40,Tomáš Souček,a,0,MID,West Ham,1103.7,20.27,82.0,0.185,1.000,0.065,1.000,1.544
41,Alexis Mac Allister,a,1,MID,Liverpool,1093.4,20.26,71.1,0.236,1.353,0.101,1.353,1.694
42,Alex Scott,a,0,MID,Bournemouth,1091.6,20.21,102.5,0.144,1.000,0.093,1.000,1.416
43,Tyrone Mings,d,1,DEF,Aston Villa,1015.9,20.17,71.2,0.077,1.000,0.085,1.000,1.320
44,Justin Devenny,a,0,MID,Crystal Palace,1077.3,20.13,55.1,0.466,1.000,0.129,1.000,2.014
45,Habib Diarra,a,0,MID,Sunderland,1052.3,20.13,81.3,0.147,1.000,0.116,1.000,1.369
46,Brenden Aaronson,a,0,MID,Leeds,984.7,20.09,85.7,0.138,1.000,0.249,1.000,1.147
47,Ferdi Kadıoğlu,a,1,DEF,Brighton,1007.7,20.06,109.3,0.050,1.000,0.049,1.000,1.337
48,Sebastiaan Bornauw,a,0,DEF,Leeds,984.7,19.97,80.2,0.216,1.000,0.026,1.000,1.443
49,Konstantinos Mavropanos,a,0,DEF,West Ham,1103.7,19.82,77.0,0.135,1.000,0.039,1.000,1.593

In [10]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 33 to 37

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,DEF,Man City,d,John Stones,31.180681,Jan Paul van Hecke,19.730722,11.449959
1,MID,Man City,a,Bernardo Mota Veiga de Carvalho e Silva,28.848195,Alexis Mac Allister,20.264178,8.584017
2,FWD,West Ham,a,Valentín Castellanos,19.340512,Alexander Isak,13.624425,5.716087
3,FWD,Spurs,a,Dominic Solanke-Mitchell,19.094833,Alexander Isak,13.624425,5.470408
4,FWD,Everton,a,Norberto Bercique Gomes Betuncal,18.820462,Alexander Isak,13.624425,5.196037
5,MID,Brighton,a,Mats Wieffer,25.456294,Alexis Mac Allister,20.264178,5.192115
6,MID,Newcastle,a,Harvey Barnes,25.235482,Alexis Mac Allister,20.264178,4.971303
7,MID,Man Utd,a,Mason Mount,24.506251,Alexis Mac Allister,20.264178,4.242072
8,FWD,Chelsea,a,Marc Guiu Paz,17.485449,Alexander Isak,13.624425,3.861024
9,FWD,Nott'm Forest,a,Lorenzo Lucca,17.458009,Alexander Isak,13.624425,3.833585
10,FWD,Nott'm Forest,a,Igor Jesus Maciel da Cruz,17.398531,Alexander Isak,13.624425,3.774106
11,DEF,Man City,a,Max Alleyne,23.167744,Jan Paul van Hecke,19.730722,3.437021
12,FWD,Arsenal,a,Gabriel Fernando de Jesus,16.957539,Alexander Isak,13.624425,3.333115
13,FWD,Newcastle,a,William Osula,16.701152,Alexander Isak,13.624425,3.076728
14,MID,Nott'm Forest,a,Callum Hudson-Odoi,23.111530,Alexis Mac Allister,20.264178,2.847351
15,DEF,Aston Villa,a,Lucas Digne,22.112209,Jan Paul van Hecke,19.730722,2.381487
16,DEF,Man City,a,Abdukodir Khusanov,22.084658,Jan Paul van Hecke,19.730722,2.353936
17,FWD,Fulham,a,Jonah Kusi-Asare,15.969470,Alexander Isak,13.624425,2.345045
18,MID,Brentford,a,Mathias Jensen,22.506830,Alexis Mac Allister,20.264178,2.242651
19,FWD,West Ham,a,Pablo Felipe Pereira de Jesus,15.834721,Alexander Isak,13.624425,2.210296

In [11]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 33 and 37:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,33.0,FWD,Man City,Arsenal; Burnley,14.4,1062.307979,10.077303,160.272246,0.485980,0.195358,1.400768
1,Erling Haaland,35.0,FWD,Man City,Everton,14.4,1075.115184,4.936333,81.035027,0.474397,0.186844,1.339329
2,Erling Haaland,36.0,FWD,Man City,Brentford,14.4,1073.538381,4.977157,81.035027,0.481419,0.186844,1.336522
3,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.4,1083.144286,4.976294,81.035027,0.480523,0.187718,1.302923

In [ ]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW33 to GW37
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,John Stones,d,0,DEF,Man City,1073.5,6.91,72.7,0.773,0.063,1.444
1,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,6.22,100.1,0.152,0.719,1.220
2,Matheus Nunes,a,1,DEF,Man City,1073.5,5.86,108.0,0.048,0.305,1.092
3,Mats Wieffer,a,0,MID,Brighton,1007.7,5.45,104.0,0.172,0.407,1.279
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1043.9,5.17,83.3,0.073,0.142,0.821
5,Max Alleyne,a,0,DEF,Man City,1073.5,5.10,78.1,0.298,0.061,1.401
6,Harvey Barnes,a,0,MID,Newcastle,1088.5,5.00,56.3,0.639,0.275,1.634
7,Mason Mount,a,0,MID,Man Utd,1081.6,4.89,21.2,1.953,0.678,1.576
8,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,4.89,104.4,0.048,0.031,1.126
9,Rico Lewis,a,0,DEF,Man City,1073.5,4.84,75.1,0.287,0.107,1.531
10,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1040.1,4.82,83.8,0.209,0.220,1.337
11,Marcus Tavernier,a,0,MID,Bournemouth,1091.6,4.80,100.2,0.178,0.218,1.407
12,James Ward-Prowse,a,0,MID,Burnley,1124.6,4.79,90.2,0.278,0.211,2.155
13,Bruno Borges Fernandes,a,1,MID,Man Utd,1081.6,4.73,80.3,0.226,0.224,1.409
14,Callum Hudson-Odoi,a,0,MID,Nott'm Forest,1040.1,4.71,77.5,0.279,0.145,1.342
15,Pascal Groß,a,0,MID,Brighton,1007.7,4.69,107.7,0.137,0.162,1.247
16,Pascal Struijk,a,0,DEF,Leeds,984.7,4.57,108.5,0.079,0.045,1.271
17,Mathias Jensen,a,0,MID,Brentford,1085.7,4.52,84.8,0.234,0.101,1.532
18,Jayden Bogle,a,0,DEF,Leeds,984.7,4.51,97.0,0.074,0.066,1.250
19,Zian Flemming,a,1,FWD,Burnley,1124.6,4.49,89.7,0.524,0.046,1.752
20,James Justin,a,0,DEF,Leeds,984.7,4.42,107.5,0.042,0.058,1.245
21,Jack Hinshelwood,a,0,MID,Brighton,1007.7,4.41,89.9,0.157,0.190,1.280
22,Alex Scott,a,0,MID,Bournemouth,1091.6,4.40,102.5,0.144,0.093,1.416
23,Lucas Digne,a,0,DEF,Aston Villa,1015.9,4.40,76.1,0.054,0.197,1.267
24,Dwight McNeil,a,0,MID,Everton,1099.0,4.40,71.6,0.266,0.183,1.401
25,Ross Barkley,a,0,MID,Aston Villa,1015.9,4.36,72.7,0.227,0.164,1.262
26,Sebastiaan Bornauw,a,0,DEF,Leeds,984.7,4.35,80.2,0.216,0.026,1.443
27,Youri Tielemans,a,0,MID,Aston Villa,1015.9,4.34,63.6,0.259,0.285,1.224
28,Ferdi Kadıoğlu,a,1,DEF,Brighton,1007.7,4.33,109.3,0.050,0.049,1.337
29,Brenden Aaronson,a,0,MID,Leeds,984.7,4.32,85.7,0.138,0.249,1.147
30,Dominik Szoboszlai,a,1,MID,Liverpool,1093.4,4.30,85.7,0.157,0.162,1.681
31,Jan Paul van Hecke,a,1,DEF,Brighton,1007.7,4.27,108.1,0.052,0.036,1.351
32,Rayan Aït-Nouri,a,0,DEF,Man City,1073.5,4.26,78.0,0.047,0.061,1.290
33,Michael Keane,a,0,DEF,Everton,1099.0,4.23,81.2,0.166,0.033,1.542
34,Rodrigo Bentancur,d,0,MID,Spurs,1053.5,4.23,57.5,0.341,0.337,2.084
35,Granit Xhaka,a,0,MID,Sunderland,1052.3,4.23,77.5,0.178,0.185,1.398
36,Rodrigo 'Rodri' Hernandez Cascante,a,0,MID,Man City,1073.5,4.22,106.9,0.075,0.087,1.210
37,Eberechi Eze,a,0,MID,Arsenal,1043.9,4.21,56.4,0.301,0.268,0.899
38,Jaidon Anthony,a,0,MID,Burnley,1124.6,4.21,100.7,0.182,0.071,2.203
39,Amadou Onana,a,0,MID,Aston Villa,1015.9,4.19,83.8,0.170,0.083,1.270
40,Pau Torres,a,0,DEF,Aston Villa,1015.9,4.15,86.1,0.051,0.030,1.237
41,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1007.7,4.13,67.8,0.267,0.051,1.473
42,Jaka Bijol,a,0,DEF,Leeds,984.7,4.11,83.5,0.047,0.066,1.238
43,John McGinn,a,0,MID,Aston Villa,1015.9,4.10,66.8,0.153,0.286,1.209
44,Kevin Schade,a,0,MID,Brentford,1085.7,4.10,71.6,0.185,0.185,1.521
45,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1057.3,4.08,77.7,0.227,0.031,1.578
46,Tomáš Souček,a,0,MID,West Ham,1103.7,4.07,82.0,0.185,0.065,1.544
47,Benjamin White,a,0,DEF,Arsenal,1043.9,4.06,68.6,0.056,0.071,1.058
48,Brian Brobbey,a,1,FWD,Sunderland,1052.3,4.06,83.5,0.386,0.040,1.357
49,Alexis Mac Allister,a,1,MID,Liverpool,1093.4,4.06,71.1,0.236,0.101,1.694

In [13]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [14]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [15]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [16]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [17]:
from FPL_Optimizer import FPLOptimizer
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW33 to GW38...

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 68.31
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.11
 ✅        Martinez                       Aston Villa  £5.1     3.47

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     3.90
 ✅        F.Kadıoğlu                     Brighton     £4.4     8.04
 ✅        Gabriel                        Arsenal      £7.2     4.33
 ✅        Van Hecke                      Brighton     £4.5     7.96
 ✅        Matheus N.                     Man City     £5.3    11.21

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.07
 ✅        B.Fernandes                    Man Utd      £10.3    4.67
 ✅        Bruno G.                       Newcastle    £6.8     5.34
 ✅        Szoboszlai                     Liverpool    £7.1     4.33
 ✅        Gibbs-White                    Nott'm Forest £7.4     5.28

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.74
 🪑        Brobbey                        Sunderland   £5.3     3.95
 ✅        Flemming                       Burnley      £5.3     8.24

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

Optimization Status: Infeasible
No valid 15-player squad found within constraints.
Error optimizing for GW34: No optimization has been run yet. Call optimize() first.

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 51.78
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.11
 ✅        Raya                           Arsenal      £6.0     4.13

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        F.Kadıoğlu                     Brighton     £4.4     3.72
 🪑        Van Hecke                      Brighton     £4.5     3.70
 ✅        Gabriel                        Arsenal      £7.2     5.27
 ✅        Matheus N.                     Man City     £5.3     5.19
 ✅        Mings                          Aston Villa  £4.3     4.30

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.05
 ✅        B.Fernandes                    Man Utd      £10.3    4.65
 ✅        Bruno G.                       Newcastle    £6.8     5.33
 ✅        Szoboszlai                     Liverpool    £7.1     4.27
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.60

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.70
 ✅        Brobbey                        Sunderland   £5.3     4.25
 ✅        Flemming                       Burnley      £5.3     4.31

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 52.94
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.32
 ✅        Raya                           Arsenal      £6.0     4.53

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.18
 ✅        Gabriel                        Arsenal      £7.2     5.81
 ✅        Van Hecke                      Brighton     £4.5     4.05
 ✅        Matheus N.                     Man City     £5.3     5.12
 ✅        Mings                          Aston Villa  £4.3     4.62

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mac Allister                   Liverpool    £6.3     4.03
 ✅        B.Fernandes                    Man Utd      £10.3    4.74
 ✅        Bruno G.                       Newcastle    £6.8     5.46
 ✅        Szoboszlai                     Liverpool    £7.1     4.23
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.56

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.73
 🪑        Brobbey                        Sunderland   £5.3     4.03
 ✅        Flemming                       Burnley      £5.3     4.14

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 53.48
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.25
 ✅        Raya                           Arsenal      £6.0     4.73

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Van Hecke                      Brighton     £4.5     4.03
 🪑        Mings                          Aston Villa  £4.3     3.36
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.12
 ✅        Gabriel                        Arsenal      £7.2     6.59
 ✅        Matheus N.                     Man City     £5.3     5.07

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.04
 ✅        B.Fernandes                    Man Utd      £10.3    5.20
 ✅        Bruno G.                       Newcastle    £6.8     5.42
 ✅        Szoboszlai                     Liverpool    £7.1     4.20
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.61

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.71
 ✅        Brobbey                        Sunderland   £5.3     4.08
 ✅        Flemming                       Burnley      £5.3     4.09

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 50.93
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.32
 ✅        Raya                           Arsenal      £6.0     3.99

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Van Hecke                      Brighton     £4.5     3.60
 🪑        Mings                          Aston Villa  £4.3     3.30
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.62
 ✅        Gabriel                        Arsenal      £7.2     5.18
 ✅        Matheus N.                     Man City     £5.3     4.76

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.16
 ✅        B.Fernandes                    Man Utd      £10.3    4.96
 ✅        Bruno G.                       Newcastle    £6.8     5.37
 ✅        Szoboszlai                     Liverpool    £7.1     4.45
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.71

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.84
 ✅        Brobbey                        Sunderland   £5.3     4.11
 ✅        Flemming                       Burnley      £5.3     4.32

================================================================================
Optimization Status: Optimal

In [18]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
2     36         13.603101
1     35         12.802138
0     33         12.325345
3     37         12.004916
4     38         11.755638

In [19]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 1.37 minute(s)