In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 30
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 31
Squad Points: 56.24

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,B.Fernandes,a,100.0,31.0,MID,Man Utd,Bournemouth,5.076736,81.0
1,Mac Allister,a,100.0,31.0,MID,Liverpool,Brighton,4.825747,85.0
2,Mings,a,100.0,31.0,DEF,Aston Villa,West Ham,4.765329,77.0
3,Gibbs-White,a,100.0,31.0,MID,Nott'm Forest,Spurs,4.763485,82.0
4,Szoboszlai,a,100.0,31.0,MID,Liverpool,Brighton,4.669425,86.0
5,Jensen,a,NaN,31.0,MID,Brentford,Leeds,4.449502,83.0
6,Maatsen,a,NaN,31.0,DEF,Aston Villa,West Ham,4.236240,54.0
7,Konaté,a,100.0,31.0,DEF,Liverpool,Brighton,4.150222,85.0
8,Martinez,a,100.0,31.0,GK,Aston Villa,West Ham,4.005608,90.0
9,Raúl,a,100.0,31.0,FWD,Fulham,Burnley,3.646057,68.0
10,Brobbey,a,75.0,31.0,FWD,Sunderland,Newcastle,3.427209,67.0
11,Igor Jesus,a,100.0,31.0,FWD,Nott'm Forest,Spurs,3.145043,71.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW31 AND 35

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Igor Jesus Maciel da Cruz,1,FWD,Nott'm Forest,1027.5,15.60,70.6,0.199,0.049,1.276
1,David Raya Martín,1,GK,Arsenal,1106.6,15.89,89.9,NaN,NaN,1.099
2,Raúl Jiménez Rodríguez,1,FWD,Fulham,1103.2,16.85,66.5,0.322,0.049,1.360
3,Brian Brobbey,1,FWD,Sunderland,1027.8,17.21,67.4,0.333,0.060,1.215
4,Matheus Nunes,1,DEF,Man City,1084.5,18.82,86.1,0.044,0.070,1.010
5,Emiliano Martínez Romero,1,GK,Aston Villa,1008.4,19.16,89.7,NaN,NaN,1.214
6,Ian Maatsen,1,DEF,Aston Villa,1008.4,19.46,53.8,0.043,0.066,1.033
7,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1106.6,19.53,84.4,0.060,0.072,0.933
8,Ibrahima Konaté,1,DEF,Liverpool,1069.5,20.89,84.5,0.042,0.045,1.207
9,Mathias Jensen,1,MID,Brentford,1039.0,21.51,83.1,0.157,0.138,1.398
10,Tyrone Mings,1,DEF,Aston Villa,1008.4,22.71,77.2,0.045,0.068,1.030
11,Dominik Szoboszlai,1,MID,Liverpool,1069.5,23.29,86.4,0.183,0.190,1.490
12,Morgan Gibbs-White,1,MID,Nott'm Forest,1027.5,23.43,81.6,0.228,0.156,1.221
13,Alexis Mac Allister,1,MID,Liverpool,1069.5,24.06,84.6,0.224,0.172,1.351
14,Bruno Borges Fernandes,1,MID,Man Utd,1082.6,25.03,80.9,0.206,0.266,1.342

In [7]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW31 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1066.5,40.32,80.9,0.206,0.270,1.315
1,Alexis Mac Allister,a,1,MID,Liverpool,1084.3,37.96,84.6,0.222,0.162,1.422
2,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1051.0,37.17,81.6,0.229,0.151,1.322
3,Dominik Szoboszlai,a,1,MID,Liverpool,1084.3,36.77,86.4,0.181,0.181,1.553
4,Lucas Digne,a,0,DEF,Aston Villa,1040.5,35.89,73.4,0.051,0.073,1.051
5,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1051.3,35.68,84.4,0.060,0.081,0.854
6,Anton Stach,a,0,MID,Leeds,1016.8,35.37,85.5,0.149,0.175,1.182
7,Diego Gómez Amarilla,a,0,MID,Brighton,1034.7,34.96,80.1,0.196,0.115,1.127
8,Lamare Bogarde,a,0,DEF,Aston Villa,1040.5,34.90,63.8,0.037,0.057,0.917
9,Tyrone Mings,a,1,DEF,Aston Villa,1040.5,34.64,77.3,0.045,0.065,1.138
10,Pascal Struijk,a,0,DEF,Leeds,1016.8,34.54,86.3,0.047,0.048,1.118
11,Marc Guiu Paz,a,0,FWD,Chelsea,1081.7,34.54,46.6,0.855,0.251,1.550
12,Amadou Onana,a,0,MID,Aston Villa,1040.5,34.35,81.5,0.163,0.142,1.263
13,Lewis Dunk,a,0,DEF,Brighton,1034.7,34.30,86.5,0.042,0.044,1.143
14,Pascal Groß,a,0,MID,Brighton,1034.7,34.14,86.0,0.104,0.161,1.087
15,Ferdi Kadıoğlu,a,0,DEF,Brighton,1034.7,34.13,86.6,0.039,0.048,1.136
16,Jan Paul van Hecke,a,0,DEF,Brighton,1034.7,33.94,84.9,0.041,0.049,1.154
17,Mathias Jensen,a,1,MID,Brentford,1079.1,33.88,83.2,0.157,0.131,1.532
18,Habib Diarra,a,0,MID,Sunderland,1055.0,33.70,85.0,0.162,0.097,1.156
19,Joe Rodon,a,0,DEF,Leeds,1016.8,33.64,86.3,0.038,0.045,1.149
20,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1073.7,33.43,84.7,0.119,0.130,1.360
21,Tomáš Souček,a,0,MID,West Ham,1073.7,33.42,82.7,0.146,0.134,1.365
22,James Justin,a,0,DEF,Leeds,1016.8,33.34,83.1,0.037,0.046,1.152
23,Ibrahima Konaté,a,1,DEF,Liverpool,1084.3,33.11,84.5,0.041,0.045,1.215
24,Alex Scott,a,0,MID,Bournemouth,1096.4,33.03,81.9,0.143,0.111,1.241
25,Dwight McNeil,a,0,MID,Everton,1078.6,33.02,79.9,0.159,0.119,1.343
26,Pau Torres,a,0,DEF,Aston Villa,1040.5,33.01,77.3,0.038,0.041,1.192
27,Estêvão Almeida de Oliveira Gonçalves,a,0,MID,Chelsea,1081.7,32.92,49.0,0.429,0.270,1.640
28,Ethan Pinnock,a,0,DEF,Brentford,1079.1,32.70,66.2,0.227,0.051,1.565
29,Jayden Bogle,a,0,DEF,Leeds,1016.8,32.66,74.6,0.053,0.047,1.160
30,Jaidon Anthony,a,0,MID,Burnley,1084.0,32.58,83.9,0.168,0.104,1.897
31,Nikola Milenković,a,0,DEF,Nott'm Forest,1051.0,32.51,85.8,0.046,0.041,1.240
32,Ola Aina,a,0,DEF,Nott'm Forest,1051.0,32.46,86.7,0.037,0.041,1.225
33,Marcus Tavernier,a,0,MID,Bournemouth,1096.4,32.46,77.1,0.165,0.105,1.300
34,Matheus Nunes,a,1,DEF,Man City,1086.7,32.40,86.1,0.044,0.066,1.045
35,Enzo Le Fée,d,0,MID,Sunderland,1055.0,32.36,83.3,0.120,0.103,1.204
36,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1051.0,32.17,86.5,0.036,0.040,1.240
37,Aaron Wan-Bissaka,a,0,DEF,West Ham,1073.7,31.67,86.4,0.036,0.042,1.267
38,Cristian Romero,d,0,DEF,Spurs,1045.0,31.64,64.9,0.195,0.056,1.545
39,Moisés Caicedo Corozo,a,0,MID,Chelsea,1081.7,31.56,76.3,0.093,0.162,1.325
40,Axel Disasi,a,0,DEF,West Ham,1073.7,31.55,86.0,0.036,0.039,1.272
41,El Hadji Malick Diouf,a,0,DEF,West Ham,1073.7,31.22,78.5,0.036,0.041,1.249
42,James Tarkowski,a,0,DEF,Everton,1078.6,31.14,86.4,0.059,0.042,1.409
43,Zian Flemming,a,0,FWD,Burnley,1084.0,31.13,71.9,0.443,0.043,1.613
44,João Maria Lobo Alves Palhares Costa Palhinha ...,d,0,MID,Spurs,1045.0,31.06,77.5,0.127,0.114,1.339
45,Hákon Rafn Valdimarsson,a,0,GK,Brentford,1079.1,31.06,86.2,NaN,NaN,1.365
46,Rodrigo 'Rodri' Hernandez Cascante,a,0,MID,Man City,1086.7,30.97,84.3,0.077,0.238,0.984
47,Trai Hume,a,0,DEF,Sunderland,1055.0,30.97,83.9,0.041,0.041,1.301
48,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1066.5,30.96,79.1,0.039,0.064,1.316
49,Jack Hinshelwood,a,0,MID,Brighton,1034.7,30.95,65.0,0.187,0.121,1.118

In [8]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW31 AND 35

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1082.6,25.03,80.9,0.206,0.266,1.342
1,Alexis Mac Allister,a,1,MID,Liverpool,1069.5,24.06,84.6,0.224,0.172,1.351
2,Lucas Digne,a,0,DEF,Aston Villa,1008.4,23.59,73.5,0.050,0.077,0.907
3,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1027.5,23.43,81.6,0.228,0.156,1.221
4,Dominik Szoboszlai,a,1,MID,Liverpool,1069.5,23.29,86.4,0.183,0.190,1.490
5,Lamare Bogarde,a,0,DEF,Aston Villa,1008.4,22.97,63.6,0.038,0.058,0.796
6,Tyrone Mings,a,1,DEF,Aston Villa,1008.4,22.71,77.2,0.045,0.068,1.030
7,Anton Stach,a,0,MID,Leeds,1018.7,22.19,85.5,0.154,0.177,1.229
8,Pau Torres,a,0,DEF,Aston Villa,1008.4,21.83,77.4,0.039,0.043,1.048
9,Amadou Onana,a,0,MID,Aston Villa,1008.4,21.83,81.5,0.165,0.152,1.155
10,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,21.73,80.0,0.196,0.110,1.145
11,Mathias Jensen,a,1,MID,Brentford,1039.0,21.51,83.1,0.157,0.138,1.398
12,Marc Guiu Paz,a,0,FWD,Chelsea,1098.7,21.49,46.5,0.860,0.241,1.575
13,Pascal Struijk,a,0,DEF,Leeds,1018.7,21.41,86.3,0.048,0.048,1.144
14,Habib Diarra,a,0,MID,Sunderland,1027.8,21.35,85.0,0.163,0.103,1.091
15,Pascal Groß,a,0,MID,Brighton,1047.4,21.23,86.0,0.103,0.159,1.104
16,Lewis Dunk,a,0,DEF,Brighton,1047.4,21.19,86.5,0.042,0.043,1.166
17,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,21.14,86.6,0.039,0.047,1.158
18,Ethan Pinnock,a,0,DEF,Brentford,1039.0,21.05,66.3,0.225,0.052,1.479
19,Nikola Milenković,a,0,DEF,Nott'm Forest,1027.5,21.05,85.8,0.047,0.042,1.168
20,Tomáš Souček,a,0,MID,West Ham,1051.8,21.02,82.7,0.146,0.138,1.299
21,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1051.8,21.02,84.8,0.121,0.132,1.291
22,Ola Aina,a,0,DEF,Nott'm Forest,1027.5,20.98,86.7,0.037,0.042,1.151
23,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,20.92,84.9,0.041,0.048,1.185
24,Ibrahima Konaté,a,1,DEF,Liverpool,1069.5,20.89,84.5,0.042,0.045,1.207
25,Joe Rodon,a,0,DEF,Leeds,1018.7,20.78,86.3,0.039,0.045,1.183
26,James Justin,a,0,DEF,Leeds,1018.7,20.66,83.1,0.038,0.045,1.174
27,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1027.5,20.65,86.5,0.036,0.041,1.185
28,Alex Scott,a,0,MID,Bournemouth,1098.3,20.65,81.9,0.143,0.110,1.233
29,Aaron Wan-Bissaka,a,0,DEF,West Ham,1051.8,20.50,86.4,0.036,0.042,1.177
30,Estêvão Almeida de Oliveira Gonçalves,a,0,MID,Chelsea,1098.7,20.48,49.1,0.425,0.282,1.751
31,Enzo Le Fée,d,0,MID,Sunderland,1027.8,20.47,83.3,0.121,0.109,1.143
32,Jaidon Anthony,a,0,MID,Burnley,1068.3,20.40,83.9,0.164,0.106,1.787
33,Marcus Tavernier,a,0,MID,Bournemouth,1098.3,20.34,77.1,0.165,0.104,1.280
34,Axel Disasi,a,0,DEF,West Ham,1051.8,20.32,86.0,0.036,0.039,1.195
35,Dwight McNeil,a,0,MID,Everton,1117.0,20.29,79.8,0.156,0.110,1.414
36,Trai Hume,a,0,DEF,Sunderland,1027.8,20.10,83.9,0.042,0.043,1.230
37,Jayden Bogle,a,0,DEF,Leeds,1018.7,20.04,74.6,0.055,0.047,1.222
38,El Hadji Malick Diouf,a,0,DEF,West Ham,1051.8,20.00,78.6,0.036,0.042,1.186
39,Jean-Clair Todibo,a,0,DEF,West Ham,1051.8,19.77,85.5,0.039,0.039,1.275
40,Sepp van den Berg,a,0,DEF,Brentford,1039.0,19.66,83.3,0.044,0.051,1.361
41,Cristian Romero,d,0,DEF,Spurs,1038.1,19.63,64.7,0.195,0.057,1.560
42,Moisés Caicedo Corozo,a,0,MID,Chelsea,1098.7,19.63,76.4,0.092,0.163,1.380
43,Victor Lindelöf,a,0,DEF,Aston Villa,1008.4,19.63,32.4,0.075,0.065,0.835
44,Zian Flemming,a,0,FWD,Burnley,1068.3,19.60,72.4,0.445,0.043,1.574
45,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1106.6,19.53,84.4,0.060,0.072,0.933
46,Kevin Schade,a,0,MID,Brentford,1039.0,19.50,67.3,0.190,0.123,1.362
47,Ian Maatsen,a,1,DEF,Aston Villa,1008.4,19.46,53.8,0.043,0.066,1.033
48,João Maria Lobo Alves Palhares Costa Palhinha ...,d,0,MID,Spurs,1038.1,19.46,77.5,0.127,0.116,1.330
49,Luke O'Nien,a,0,DEF,Sunderland,1027.8,19.45,74.1,0.034,0.045,1.228

In [9]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 31 to 35

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Chelsea,a,Marc Guiu Paz,21.494149,Igor Jesus Maciel da Cruz,15.595407,5.898742
1,DEF,Aston Villa,a,Lucas Digne,23.589532,Matheus Nunes,18.819180,4.770352
2,DEF,Aston Villa,a,Lamare Bogarde,22.972713,Matheus Nunes,18.819180,4.153533
3,FWD,Burnley,a,Zian Flemming,19.599135,Igor Jesus Maciel da Cruz,15.595407,4.003727
4,FWD,Brighton,a,Danny Welbeck,18.785336,Igor Jesus Maciel da Cruz,15.595407,3.189929
5,GK,Brentford,a,Hákon Rafn Valdimarsson,19.046665,David Raya Martín,15.892005,3.154659
6,DEF,Aston Villa,a,Pau Torres,21.832419,Matheus Nunes,18.819180,3.013239
7,GK,Sunderland,a,Melker Ellborg,18.838694,David Raya Martín,15.892005,2.946689
8,GK,West Ham,a,Mads Hermansen,18.780398,David Raya Martín,15.892005,2.888392
9,FWD,Spurs,a,Dominic Solanke-Mitchell,18.374266,Igor Jesus Maciel da Cruz,15.595407,2.778859
10,GK,Leeds,a,Lucas Estella Perri,18.604082,David Raya Martín,15.892005,2.712077
11,DEF,Leeds,a,Pascal Struijk,21.409306,Matheus Nunes,18.819180,2.590126
12,DEF,Brighton,a,Lewis Dunk,21.189727,Matheus Nunes,18.819180,2.370547
13,GK,Nott'm Forest,d,Stefan Ortega Moreno,18.218269,David Raya Martín,15.892005,2.326264
14,DEF,Brighton,a,Ferdi Kadıoğlu,21.142765,Matheus Nunes,18.819180,2.323585
15,DEF,Brentford,a,Ethan Pinnock,21.051662,Matheus Nunes,18.819180,2.232482
16,DEF,Nott'm Forest,a,Nikola Milenković,21.047048,Matheus Nunes,18.819180,2.227868
17,DEF,Nott'm Forest,a,Ola Aina,20.984140,Matheus Nunes,18.819180,2.164960
18,GK,Leeds,a,Karl Darlow,18.012983,David Raya Martín,15.892005,2.120977
19,DEF,Brighton,a,Jan Paul van Hecke,20.920749,Matheus Nunes,18.819180,2.101569

In [10]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Leandro Trossard'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 31 and 35:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Leandro Trossard,32.0,MID,Arsenal,Bournemouth,6.6,1066.816076,3.882950,59.590889,0.198490,0.129993,0.863796
1,Leandro Trossard,33.0,MID,Arsenal,Man City,6.6,1226.620831,3.564536,59.916946,0.167430,0.107506,1.288878
2,Leandro Trossard,34.0,MID,Arsenal,Newcastle,6.6,1090.007827,3.822385,59.590889,0.191638,0.131769,0.932761
3,Leandro Trossard,35.0,MID,Arsenal,Fulham,6.6,1042.769745,3.959437,59.465175,0.198490,0.129993,0.763105

In [11]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW31 to GW35
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,a,1,MID,Man Utd,1082.6,5.05,80.9,0.206,0.266,1.342
1,Alexis Mac Allister,a,1,MID,Liverpool,1069.5,4.83,84.6,0.224,0.172,1.351
2,Lucas Digne,a,0,DEF,Aston Villa,1008.4,4.74,73.5,0.050,0.077,0.907
3,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1027.5,4.70,81.6,0.228,0.156,1.221
4,Dominik Szoboszlai,a,1,MID,Liverpool,1069.5,4.67,86.4,0.183,0.190,1.490
5,Lamare Bogarde,a,0,DEF,Aston Villa,1008.4,4.60,63.6,0.038,0.058,0.796
6,Tyrone Mings,a,1,DEF,Aston Villa,1008.4,4.56,77.2,0.045,0.068,1.030
7,Pau Torres,a,0,DEF,Aston Villa,1008.4,4.41,77.4,0.039,0.043,1.048
8,Anton Stach,a,0,MID,Leeds,1018.7,4.38,85.5,0.154,0.177,1.229
9,Amadou Onana,a,0,MID,Aston Villa,1008.4,4.37,81.5,0.165,0.152,1.155
10,Diego Gómez Amarilla,a,0,MID,Brighton,1047.4,4.35,80.0,0.196,0.110,1.145
11,Mathias Jensen,a,1,MID,Brentford,1039.0,4.31,83.1,0.157,0.138,1.398
12,Nikola Milenković,a,0,DEF,Nott'm Forest,1027.5,4.28,85.8,0.047,0.042,1.168
13,Marc Guiu Paz,a,0,FWD,Chelsea,1098.7,4.27,46.5,0.860,0.241,1.575
14,Lewis Dunk,a,0,DEF,Brighton,1047.4,4.27,86.5,0.042,0.043,1.166
15,Ferdi Kadıoğlu,a,0,DEF,Brighton,1047.4,4.25,86.6,0.039,0.047,1.158
16,Ola Aina,a,0,DEF,Nott'm Forest,1027.5,4.25,86.7,0.037,0.042,1.151
17,Pascal Groß,a,0,MID,Brighton,1047.4,4.25,86.0,0.103,0.159,1.104
18,Habib Diarra,a,0,MID,Sunderland,1027.8,4.24,85.0,0.163,0.103,1.091
19,Ethan Pinnock,a,0,DEF,Brentford,1039.0,4.23,66.3,0.225,0.052,1.479
20,Jan Paul van Hecke,a,0,DEF,Brighton,1047.4,4.21,84.9,0.041,0.048,1.185
21,Tomáš Souček,a,0,MID,West Ham,1051.8,4.20,82.7,0.146,0.138,1.299
22,Pascal Struijk,a,0,DEF,Leeds,1018.7,4.20,86.3,0.048,0.048,1.144
23,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1051.8,4.19,84.8,0.121,0.132,1.291
24,Murillo Costa dos Santos,a,0,DEF,Nott'm Forest,1027.5,4.19,86.5,0.036,0.041,1.185
25,Ibrahima Konaté,a,1,DEF,Liverpool,1069.5,4.18,84.5,0.042,0.045,1.207
26,Aaron Wan-Bissaka,a,0,DEF,West Ham,1051.8,4.10,86.4,0.036,0.042,1.177
27,Alex Scott,a,0,MID,Bournemouth,1098.3,4.10,81.9,0.143,0.110,1.233
28,Joe Rodon,a,0,DEF,Leeds,1018.7,4.09,86.3,0.039,0.045,1.183
29,Axel Disasi,a,0,DEF,West Ham,1051.8,4.08,86.0,0.036,0.039,1.195
30,Jaidon Anthony,a,0,MID,Burnley,1068.3,4.08,83.9,0.164,0.106,1.787
31,Enzo Le Fée,d,0,MID,Sunderland,1027.8,4.07,83.3,0.121,0.109,1.143
32,Estêvão Almeida de Oliveira Gonçalves,a,0,MID,Chelsea,1098.7,4.07,49.1,0.425,0.282,1.751
33,James Justin,a,0,DEF,Leeds,1018.7,4.06,83.1,0.038,0.045,1.174
34,Dwight McNeil,a,0,MID,Everton,1117.0,4.06,79.8,0.156,0.110,1.414
35,Marcus Tavernier,a,0,MID,Bournemouth,1098.3,4.04,77.1,0.165,0.104,1.280
36,El Hadji Malick Diouf,a,0,DEF,West Ham,1051.8,4.02,78.6,0.036,0.042,1.186
37,Jean-Clair Todibo,a,0,DEF,West Ham,1051.8,3.96,85.5,0.039,0.039,1.275
38,Sepp van den Berg,a,0,DEF,Brentford,1039.0,3.95,83.3,0.044,0.051,1.361
39,Trai Hume,a,0,DEF,Sunderland,1027.8,3.94,83.9,0.042,0.043,1.230
40,Ian Maatsen,a,1,DEF,Aston Villa,1008.4,3.93,53.8,0.043,0.066,1.033
41,Cristian Romero,d,0,DEF,Spurs,1038.1,3.93,64.7,0.195,0.057,1.560
42,Zian Flemming,a,0,FWD,Burnley,1068.3,3.93,72.4,0.445,0.043,1.574
43,Victor Lindelöf,a,0,DEF,Aston Villa,1008.4,3.93,32.4,0.075,0.065,0.835
44,Moisés Caicedo Corozo,a,0,MID,Chelsea,1098.7,3.91,76.4,0.092,0.163,1.380
45,Antonee Robinson,a,0,DEF,Fulham,1103.2,3.91,79.2,0.036,0.034,1.359
46,Kevin Schade,a,0,MID,Brentford,1039.0,3.91,67.3,0.190,0.123,1.362
47,João Maria Lobo Alves Palhares Costa Palhinha ...,d,0,MID,Spurs,1038.1,3.91,77.5,0.127,0.116,1.330
48,Ibrahim Sangaré,a,0,MID,Nott'm Forest,1027.5,3.90,84.8,0.109,0.066,1.195
49,Jayden Bogle,a,0,DEF,Leeds,1018.7,3.90,74.6,0.055,0.047,1.222

In [12]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [13]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [14]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [ ]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

Squad Points: GW 31 - GW38

In [16]:
from FPL_Optimizer import FPLOptimizer
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW31 to GW38...

Optimizing team selection for GW31...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

Optimization Status: Infeasible
No valid 15-player squad found within constraints.
Error optimizing for GW31: No optimization has been run yet. Call optimize() first.

Optimizing team selection for GW32...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 51.01
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.95
 ✅        Raya                           Arsenal      £6.0     4.08

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Maatsen                        Aston Villa  £4.2     3.98
 ✅        Gabriel                        Arsenal      £7.2     4.98
 ✅        Konaté                         Liverpool    £5.5     4.28
 ✅        Matheus N.                     Man City     £5.4     4.46
 ✅        Mings                          Aston Villa  £4.3     4.56

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.88
 ✅        B.Fernandes                    Man Utd      £10.1    5.35
 ✅        Szoboszlai                     Liverpool    £7.0     4.70
 ✅        Jensen                         Brentford    £4.9     4.25
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.59

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.03
 🪑        Raúl                           Fulham       £6.2     3.27
 ✅        Brobbey                        Sunderland   £5.3     3.45

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 49.05
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.54
 ✅        Raya                           Arsenal      £6.0     3.67

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Maatsen                        Aston Villa  £4.2     3.42
 ✅        Gabriel                        Arsenal      £7.2     4.63
 ✅        Konaté                         Liverpool    £5.5     4.15
 ✅        Matheus N.                     Man City     £5.4     4.19
 ✅        Mings                          Aston Villa  £4.3     4.27

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.84
 ✅        B.Fernandes                    Man Utd      £10.1    4.79
 ✅        Szoboszlai                     Liverpool    £7.0     4.68
 ✅        Jensen                         Brentford    £4.9     4.20
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.83

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.28
 🪑        Raúl                           Fulham       £6.2     3.39
 ✅        Brobbey                        Sunderland   £5.3     3.43

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 51.14
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.49
 ✅        Raya                           Arsenal      £6.0     4.00

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Maatsen                        Aston Villa  £4.2     3.44
 ✅        Gabriel                        Arsenal      £7.2     4.95
 ✅        Konaté                         Liverpool    £5.5     4.22
 ✅        Matheus N.                     Man City     £5.4     5.56
 ✅        Mings                          Aston Villa  £4.3     4.26

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.87
 ✅        B.Fernandes                    Man Utd      £10.1    4.98
 ✅        Szoboszlai                     Liverpool    £7.0     4.70
 ✅        Jensen                         Brentford    £4.9     4.17
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.64

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.11
 🪑        Raúl                           Fulham       £6.2     3.36
 ✅        Brobbey                        Sunderland   £5.3     3.43

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 50.95
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     4.14
 ✅        Martinez                       Aston Villa  £5.1     4.18

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Konaté                         Liverpool    £5.5     4.09
 ✅        Gabriel                        Arsenal      £7.2     4.96
 ✅        Maatsen                        Aston Villa  £4.2     4.38
 ✅        Matheus N.                     Man City     £5.4     4.60
 ✅        Mings                          Aston Villa  £4.3     4.86

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.63
 ✅        B.Fernandes                    Man Utd      £10.1    4.83
 ✅        Szoboszlai                     Liverpool    £7.0     4.54
 ✅        Jensen                         Brentford    £4.9     4.45
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.61

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.03
 🪑        Raúl                           Fulham       £6.2     3.19
 ✅        Brobbey                        Sunderland   £5.3     3.47

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-4-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 51.93
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.41
 ✅        Raya                           Arsenal      £6.0     4.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Gabriel                        Arsenal      £7.2     5.43
 ✅        Maatsen                        Aston Villa  £4.2     4.60
 ✅        Konaté                         Liverpool    £5.5     4.04
 ✅        Matheus N.                     Man City     £5.4     4.55
 ✅        Mings                          Aston Villa  £4.3     5.05

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Jensen                         Brentford    £4.9     4.02
 ✅        Mac Allister                   Liverpool    £6.3     4.55
 ✅        B.Fernandes                    Man Utd      £10.1    5.15
 ✅        Szoboszlai                     Liverpool    £7.0     4.41
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.09
 🪑        Raúl                           Fulham       £6.2     3.39
 ✅        Brobbey                        Sunderland   £5.3     3.46

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 50.55
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.35
 ✅        Raya                           Arsenal      £6.0     4.69

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Maatsen                        Aston Villa  £4.2     2.73
 ✅        Gabriel                        Arsenal      £7.2     5.81
 ✅        Konaté                         Liverpool    £5.5     4.03
 ✅        Matheus N.                     Man City     £5.4     4.58
 ✅        Mings                          Aston Villa  £4.3     3.80

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.52
 ✅        B.Fernandes                    Man Utd      £10.1    5.20
 ✅        Szoboszlai                     Liverpool    £7.0     4.39
 ✅        Jensen                         Brentford    £4.9     4.23
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Brobbey                        Sunderland   £5.3     3.41
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.03
 ✅        Raúl                           Fulham       £6.2     3.46

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £90.7m / £102.4m
Total Weighted Expected Points: 48.79
Remaining Budget: £11.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.44
 ✅        Raya                           Arsenal      £6.0     4.10

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Maatsen                        Aston Villa  £4.2     2.14
 🪑        Mings                          Aston Villa  £4.3     3.08
 ✅        Gabriel                        Arsenal      £7.2     4.92
 ✅        Konaté                         Liverpool    £5.5     4.15
 ✅        Matheus N.                     Man City     £5.4     4.46

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.83
 ✅        B.Fernandes                    Man Utd      £10.1    4.95
 ✅        Szoboszlai                     Liverpool    £7.0     4.67
 ✅        Jensen                         Brentford    £4.9     4.12
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.58

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Igor Jesus                     Nott'm Forest £5.8     3.10
 ✅        Brobbey                        Sunderland   £5.3     3.43
 ✅        Raúl                           Fulham       £6.2     3.41

================================================================================
Optimization Status: Optimal

In [17]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
4     36         13.420369
3     35         12.999947
0     32         12.809717
1     33         12.265438
2     34         12.056176
5     37         11.272844
6     38         10.579465

In [18]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.07 minute(s)