In [33]:
import pandas as pd
import time

In [34]:
start=time.perf_counter()

In [35]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [36]:
#add this info to a settings dict?
stats_current_gameweek = 16
picks_current_gameweek = 16
current_season = 20252026

In [37]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 17
Squad Points: 65.67

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,B.Fernandes,a,NaN,17.0,MID,Man Utd,Aston Villa,5.439767
1,Matheus N.,a,NaN,17.0,DEF,Man City,West Ham,5.107653
2,Szoboszlai,d,NaN,17.0,MID,Liverpool,Spurs,5.083805
3,O.Dango,n,100.0,17.0,MID,Brentford,Wolves,4.779860
4,Lacroix,a,NaN,17.0,DEF,Crystal Palace,Leeds,4.449044
5,Konaté,a,100.0,17.0,DEF,Liverpool,Spurs,4.423751
6,Minteh,a,NaN,17.0,MID,Brighton,Sunderland,4.292959
7,Amad,n,100.0,17.0,MID,Man Utd,Aston Villa,3.905072
8,Gabriel,i,0.0,17.0,DEF,Arsenal,Everton,3.847522
9,Gyökeres,a,100.0,17.0,FWD,Arsenal,Everton,3.794882
10,Raya,a,NaN,17.0,GK,Arsenal,Everton,3.759593
11,Raúl,a,100.0,17.0,FWD,Fulham,Nott'm Forest,3.221873
12,Tarkowski,a,NaN,17.0,DEF,Everton,Arsenal,2.999445
13,Pope,d,25.0,17.0,GK,Newcastle,Chelsea,2.594351
14,Flemming,a,NaN,17.0,FWD,Burnley,Bournemouth,2.535174

In [38]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 17

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Yeremy,a,100.0,17.0,MID,Crystal Palace,Leeds,5.512001
1,Rúben,a,NaN,17.0,DEF,Man City,West Ham,5.253795
2,Wilson,a,100.0,17.0,MID,Fulham,Nott'm Forest,5.112844
3,Mukiele,a,NaN,17.0,DEF,Sunderland,Brighton,5.029976
4,Milenković,a,NaN,17.0,DEF,Nott'm Forest,Fulham,4.950362
5,Cherki,a,100.0,17.0,MID,Man City,West Ham,4.835410
6,Truffert,a,NaN,17.0,DEF,Bournemouth,Burnley,4.823920
7,Savona,a,NaN,17.0,DEF,Nott'm Forest,Fulham,4.793748
8,Gusto,a,100.0,17.0,DEF,Chelsea,Newcastle,4.769626
9,Reijnders,a,NaN,17.0,MID,Man City,West Ham,4.764414

In [39]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(10)

When to use first TRIPLE CAPTAIN chip (gws1-19)

           player_name_id  event position  team_name  opp_team_name   xpoints
0  Bruno Borges Fernandes   19.0      MID    Man Utd         Wolves  5.773624
1      Dominik Szoboszlai   18.0      MID  Liverpool         Wolves  5.563219
2  Bruno Borges Fernandes   18.0      MID    Man Utd      Newcastle  5.546151
3  Bruno Borges Fernandes   17.0      MID    Man Utd    Aston Villa  5.439767
4      Dominik Szoboszlai   19.0      MID  Liverpool          Leeds  5.213580
5           Matheus Nunes   17.0      DEF   Man City       West Ham  5.107653
6      Dominik Szoboszlai   17.0      MID  Liverpool          Spurs  5.083805
7           Matheus Nunes   18.0      DEF   Man City  Nott'm Forest  4.948414
8         Ibrahima Konaté   18.0      DEF  Liverpool         Wolves  4.948315
9         James Tarkowski   18.0      DEF    Everton        Burnley  4.881906

In [40]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+3}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+3}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW17 AND 19

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Bruno Borges Fernandes,1,MID,Man Utd,1065.1,16.76,59.8,0.500,0.324,1.480
1,Yéremy Pino Santos,0,MID,Crystal Palace,998.8,15.96,77.3,0.295,0.238,1.085
2,Dominik Szoboszlai,1,MID,Liverpool,956.4,15.86,79.5,0.262,0.200,0.939
3,Diego Gómez Amarilla,0,MID,Brighton,1107.4,15.54,63.4,0.479,0.120,1.279
4,Harry Wilson,0,MID,Fulham,1044.5,15.51,63.8,0.361,0.212,1.206
5,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1038.4,15.28,85.3,0.088,0.032,0.944
6,Matheus Nunes,1,DEF,Man City,1038.4,14.80,84.2,0.069,0.080,1.027
7,Calvin Bassey,0,DEF,Fulham,1044.5,14.30,64.6,0.169,0.076,1.201
8,Virgil van Dijk,0,DEF,Liverpool,956.4,14.28,87.0,0.051,0.024,0.967
9,Rayan Cherki,0,MID,Man City,1038.4,14.21,53.2,0.399,0.375,1.131
10,Nordi Mukiele,0,DEF,Sunderland,1096.5,14.15,85.9,0.031,0.060,0.962
11,Bruno Guimarães Rodriguez Moura,0,MID,Newcastle,1032.2,14.09,72.1,0.208,0.176,1.050
12,Malo Gusto,0,DEF,Chelsea,1113.5,14.09,63.1,0.134,0.164,1.298
13,Mats Wieffer,0,MID,Brighton,1107.4,13.95,82.3,0.251,0.078,1.319
14,Ibrahima Konaté,1,DEF,Liverpool,956.4,13.92,85.0,0.086,0.063,1.177
15,Tijjani Reijnders,0,MID,Man City,1038.4,13.78,67.0,0.230,0.116,0.901
16,Dan Burn,0,DEF,Newcastle,1032.2,13.76,63.7,0.029,0.031,0.929
17,Wesley Fofana,0,DEF,Chelsea,1113.5,13.69,63.7,0.105,0.027,1.132
18,Adam Wharton,0,MID,Crystal Palace,998.8,13.67,83.4,0.146,0.155,1.031
19,Dango Ouattara,1,MID,Brentford,991.8,13.52,73.6,0.265,0.060,1.101
20,Daniel Ballard,0,DEF,Sunderland,1096.5,13.42,81.9,0.051,0.027,1.068
21,Mohammed Kudus,0,MID,Spurs,1119.1,13.31,76.3,0.189,0.177,1.410
22,Omari Hutchinson,0,MID,Nott'm Forest,1118.0,13.21,67.5,0.207,0.133,1.081
23,Yankuba Minteh,1,MID,Brighton,1107.4,13.10,82.0,0.184,0.118,1.292
24,Maxence Lacroix,1,DEF,Crystal Palace,998.8,13.10,86.5,0.038,0.046,1.132
25,Ibrahim Sangaré,0,MID,Nott'm Forest,1118.0,13.01,72.1,0.146,0.150,1.113
26,Gabriel Gudmundsson,0,DEF,Leeds,1131.8,12.96,71.5,0.042,0.082,1.085
27,Adrien Truffert,0,DEF,Bournemouth,1026.2,12.88,70.6,0.029,0.078,1.160
28,Anton Stach,0,MID,Leeds,1131.8,12.81,77.2,0.179,0.113,1.123
29,Dean Henderson,0,GK,Crystal Palace,998.8,12.77,89.9,NaN,NaN,1.049
30,Vitalii Mykolenko,0,DEF,Everton,1057.9,12.69,87.1,0.019,0.063,1.191
31,Jayden Bogle,0,DEF,Leeds,1131.8,12.63,79.0,0.026,0.081,1.106
32,Alex Iwobi,0,MID,Fulham,1044.5,12.58,81.3,0.145,0.087,1.241
33,Jarrod Bowen,0,FWD,West Ham,1125.8,12.56,82.7,0.282,0.031,1.245
34,James Tarkowski,1,DEF,Everton,1057.9,12.53,87.2,0.027,0.079,1.265
35,Pascal Struijk,0,DEF,Leeds,1131.8,12.53,81.9,0.055,0.024,1.138
36,Josh Cullen,0,MID,Burnley,1077.4,12.52,82.3,0.136,0.128,1.750
37,Daichi Kamada,0,MID,Crystal Palace,998.8,12.46,80.6,0.079,0.130,1.011
38,Alisson Becker,0,GK,Liverpool,956.4,12.43,80.2,NaN,NaN,1.063
39,Nicolò Savona,0,DEF,Nott'm Forest,1118.0,12.42,79.1,0.033,0.054,1.292
40,Nikola Milenković,0,DEF,Nott'm Forest,1118.0,12.39,86.2,0.030,0.027,1.234
41,Nathan Collins,0,DEF,Brentford,991.8,12.38,61.1,0.047,0.066,1.015
42,Trai Hume,0,DEF,Sunderland,1096.5,12.31,65.8,0.026,0.057,1.199
43,Michael Kayode,0,DEF,Brentford,991.8,12.29,80.4,0.027,0.048,1.219
44,Sepp van den Berg,0,DEF,Brentford,991.8,12.26,87.1,0.064,0.016,1.277
45,Michael Keane,0,DEF,Everton,1057.9,12.23,73.5,0.029,0.019,1.217
46,Georginio Rutter,0,MID,Brighton,1107.4,12.23,68.4,0.138,0.127,1.268
47,Fabian Schär,0,DEF,Newcastle,1032.2,12.14,47.1,0.186,0.300,1.243
48,Richarlison de Andrade,0,FWD,Spurs,1119.1,11.97,72.0,0.327,0.026,1.309
49,Ryan Gravenberch,0,MID,Liverpool,956.4,11.97,84.3,0.076,0.064,0.903

In [41]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 17 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Sunderland,Brian Brobbey,92.477371,Zian Flemming,55.820109,36.657262
1,FWD,West Ham,Jarrod Bowen,91.993728,Zian Flemming,55.820109,36.173619
2,GK,Crystal Palace,Dean Henderson,90.006149,Nick Pope,55.462490,34.543659
3,GK,Liverpool,Alisson Becker,89.716234,Nick Pope,55.462490,34.253744
4,FWD,Spurs,Richarlison de Andrade,87.615487,Zian Flemming,55.820109,31.795377
5,FWD,Nott'm Forest,Igor Jesus Maciel da Cruz,85.565610,Zian Flemming,55.820109,29.745501
6,DEF,Man City,Rúben dos Santos Gato Alves Dias,112.322475,Gabriel dos Santos Magalhães,84.563062,27.759414
7,MID,Brighton,Diego Gómez Amarilla,116.054036,Amad Diallo,88.552453,27.501583
8,GK,West Ham,Alphonse Areola,81.288607,Nick Pope,55.462490,25.826117
9,MID,Fulham,Harry Wilson,114.329364,Amad Diallo,88.552453,25.776911
10,FWD,Burnley,Armando Broja,80.758015,Zian Flemming,55.820109,24.937906
11,MID,Crystal Palace,Yéremy Pino Santos,112.691985,Amad Diallo,88.552453,24.139532
12,GK,Bournemouth,Đorđe Petrović,79.013251,Nick Pope,55.462490,23.550761
13,DEF,Sunderland,Nordi Mukiele,107.938661,Gabriel dos Santos Magalhães,84.563062,23.375599
14,GK,Nott'm Forest,Matz Sels,77.550712,Nick Pope,55.462490,22.088222
15,GK,Newcastle,Aaron Ramsdale,77.176234,Nick Pope,55.462490,21.713744
16,DEF,Chelsea,Malo Gusto,104.210543,Gabriel dos Santos Magalhães,84.563062,19.647482
17,GK,Wolves,Sam Johnstone,72.930419,Nick Pope,55.462490,17.467930
18,DEF,Liverpool,Virgil van Dijk,101.908978,Gabriel dos Santos Magalhães,84.563062,17.345917
19,DEF,Fulham,Calvin Bassey,101.625079,Gabriel dos Santos Magalhães,84.563062,17.062017

In [42]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 17 and 21:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.6,1104.948985,4.922787,77.533994,0.229755,0.254982,1.371387
1,Enzo Fernández,18.0,MID,Chelsea,Aston Villa,6.6,1180.983956,4.904149,77.553188,0.225109,0.254382,1.327219
2,Enzo Fernández,19.0,MID,Chelsea,Bournemouth,6.6,1054.494175,5.152573,75.527648,0.247936,0.277214,1.125220
3,Enzo Fernández,20.0,MID,Chelsea,Man City,6.6,1244.963275,4.885855,77.553188,0.229709,0.254382,1.477507
4,Enzo Fernández,21.0,MID,Chelsea,Fulham,6.6,1036.365466,5.215680,75.527648,0.258955,0.287687,1.134217

In [43]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [44]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [45]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.02 minute(s)