In [20]:
import pandas as pd
import time

In [21]:
start=time.perf_counter()

In [22]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [23]:
#add this info to a settings dict?
current_gw = 32
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [24]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 33
Squad Points: 87.85

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Matheus N.,a,100.0,33.0,DEF,Man City,Arsenal; Burnley,9.281474,149.0
1,Flemming,a,100.0,33.0,FWD,Burnley,Nott'm Forest; Man City,9.109203,159.0
2,Van Hecke,a,100.0,33.0,DEF,Brighton,Spurs; Chelsea,8.096057,172.0
3,F.Kadıoğlu,a,NaN,33.0,DEF,Brighton,Chelsea; Spurs,8.012377,174.0
4,B.Fernandes,a,100.0,33.0,MID,Man Utd,Chelsea,4.877100,85.0
5,Gibbs-White,a,100.0,33.0,MID,Nott'm Forest,Burnley,4.630308,78.0
6,Bruno G.,i,0.0,33.0,MID,Newcastle,Bournemouth,4.570927,60.0
7,Szoboszlai,a,100.0,33.0,MID,Liverpool,Everton,4.476583,87.0
8,Gabriel,a,100.0,33.0,DEF,Arsenal,Man City,4.199586,85.0
9,Mac Allister,a,100.0,33.0,MID,Liverpool,Everton,4.172321,71.0
10,Brobbey,a,100.0,33.0,FWD,Sunderland,Aston Villa,3.745404,74.0
11,Mings,a,100.0,33.0,DEF,Aston Villa,Sunderland,3.689512,76.0
12,Martinez,a,100.0,33.0,GK,Aston Villa,Sunderland,3.558407,90.0
13,Raya,a,NaN,33.0,GK,Arsenal,Man City,3.476843,85.0
14,Isak,a,100.0,33.0,FWD,Liverpool,Everton,2.669970,30.0

In [25]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW33 AND 37

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1096.0,13.70,31.7,0.507,0.133,1.626
1,Emiliano Martínez Romero,1,GK,Aston Villa,1015.9,18.92,89.8,NaN,NaN,1.201
2,Brian Brobbey,1,FWD,Sunderland,1055.0,19.04,74.1,0.356,0.077,1.311
3,Tyrone Mings,1,DEF,Aston Villa,1015.9,19.84,75.6,0.044,0.063,1.324
4,Ferdi Kadıoğlu,1,DEF,Brighton,1008.8,19.99,108.2,0.048,0.050,1.349
5,Jan Paul van Hecke,1,DEF,Brighton,1008.8,20.22,107.0,0.048,0.053,1.314
6,David Raya Martín,1,GK,Arsenal,1044.7,20.65,84.5,NaN,NaN,0.906
7,Alexis Mac Allister,1,MID,Liverpool,1096.0,20.77,71.4,0.198,0.168,1.646
8,Matheus Nunes,1,DEF,Man City,1073.5,21.35,85.0,0.048,0.108,1.145
9,Morgan Gibbs-White,1,MID,Nott'm Forest,1044.8,22.02,79.0,0.194,0.147,1.332
10,Dominik Szoboszlai,1,MID,Liverpool,1096.0,22.21,86.6,0.149,0.189,1.710
11,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1087.9,22.39,59.1,0.360,0.277,1.631
12,Zian Flemming,1,FWD,Burnley,1120.8,23.12,99.1,0.549,0.052,1.876
13,Bruno Borges Fernandes,1,MID,Man Utd,1080.8,24.75,84.4,0.204,0.228,1.419
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1044.7,25.88,84.5,0.077,0.123,0.951

In [26]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    in_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (in_any_team = 0 OR in_my_team = 1)
    AND status IN ('a','d')
    AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, in_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW33 AND GW38

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Zian Flemming,a,1,FWD,Burnley,1084.0,28.02,95.1,0.560,0.054,1.786
1,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1071.3,25.98,66.0,0.532,0.101,1.490
2,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1056.5,23.80,81.3,0.350,0.061,1.646
3,Valentín Castellanos,a,0,FWD,West Ham,1083.8,23.49,75.3,0.371,0.061,1.469
4,Brian Brobbey,a,1,FWD,Sunderland,1064.6,22.83,74.1,0.356,0.080,1.340
5,Marc Guiu Paz,a,0,FWD,Chelsea,1056.1,22.71,49.2,0.640,0.359,1.597
6,Lorenzo Lucca,a,0,FWD,Nott'm Forest,1051.2,22.27,45.2,0.631,0.229,1.492
7,Chris Wood,a,0,FWD,Nott'm Forest,1051.2,21.77,40.2,0.658,0.327,1.589
8,Jonah Kusi-Asare,a,0,FWD,Fulham,1091.4,20.23,31.9,0.644,0.296,1.984
9,Rodrigo Muniz Carvalho,a,0,FWD,Fulham,1091.4,19.58,60.3,0.352,0.048,1.533
10,Charalampos Kostoulas,a,0,FWD,Brighton,1029.5,19.32,39.4,0.636,0.243,1.469
11,Pablo Felipe Pereira de Jesus,a,0,FWD,West Ham,1083.8,19.13,70.0,0.223,0.048,1.490
12,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1051.2,18.61,58.8,0.295,0.097,1.406
13,Lyle Foster,a,0,FWD,Burnley,1084.0,18.54,66.5,0.428,0.038,1.838
14,Adam Armstrong,a,0,FWD,Wolves,1000.5,18.48,67.9,0.211,0.052,1.328
15,Lukas Nmecha,a,0,FWD,Leeds,988.6,16.84,49.1,0.405,0.074,1.346
16,Alexander Isak,a,1,FWD,Liverpool,1092.2,16.51,31.9,0.511,0.133,1.645
17,Raúl Jiménez Rodríguez,a,0,FWD,Fulham,1091.4,16.46,40.0,0.413,0.064,1.437
18,Jean-Philippe Mateta,a,0,FWD,Crystal Palace,1105.1,16.45,34.8,0.519,0.091,1.627
19,Mateus Mané,a,0,FWD,Wolves,1000.5,15.63,45.8,0.286,0.054,1.403
20,Gabriel Fernando de Jesus,a,0,FWD,Arsenal,1045.2,15.02,29.3,0.366,0.070,1.023
21,William Osula,a,0,FWD,Newcastle,1080.1,14.82,21.2,0.534,0.053,1.464
22,Tolu Arokodare,a,0,FWD,Wolves,1000.5,14.29,36.2,0.362,0.037,1.456
23,Joshua Zirkzee,a,0,FWD,Man Utd,1083.6,14.03,20.7,0.469,0.092,1.452
24,Yoane Wissa,a,0,FWD,Newcastle,1080.1,13.95,25.4,0.413,0.135,1.561
25,Taiwo Awoniyi,a,0,FWD,Nott'm Forest,1051.2,13.87,33.0,0.392,0.039,1.395
26,Tammy Abraham,a,0,FWD,Aston Villa,1051.0,13.81,26.6,0.340,0.074,1.324
27,Joël Piroe,a,0,FWD,Leeds,988.6,13.69,25.0,0.398,0.079,1.491
28,Ashley Barnes,a,0,FWD,Burnley,1084.0,13.25,35.0,0.361,0.086,1.831
29,Liam Delap,a,0,FWD,Chelsea,1056.1,12.93,30.1,0.316,0.045,1.423
30,Wilson Isidor,a,0,FWD,Sunderland,1064.6,12.64,15.0,0.489,0.079,1.377
31,Armando Broja,a,0,FWD,Burnley,1084.0,12.60,37.5,0.353,0.038,1.748
32,Christantus Uche,a,0,FWD,Crystal Palace,1105.1,12.56,19.6,0.286,0.055,1.588
33,Enes Ünal,a,0,FWD,Bournemouth,1073.2,12.51,21.5,0.515,0.049,1.585
34,Callum Wilson,a,0,FWD,West Ham,1083.8,12.30,28.0,0.279,0.033,1.497
35,Eliezer Mayenda Dossou,a,0,FWD,Sunderland,1064.6,11.18,17.6,0.284,0.040,1.527

In [27]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.in_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xap90_pred,
        p.xgcp90_pred,
        p.event,
        p.in_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW33 AND 37

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1044.7,25.88,84.5,0.077,0.123,0.951
1,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.8,24.75,84.4,0.204,0.228,1.419
2,Mats Wieffer,a,0,MID,Brighton,1008.8,23.69,105.0,0.179,0.233,1.270
3,Jaidon Anthony,a,0,MID,Burnley,1120.8,23.24,106.6,0.285,0.105,2.099
4,Zian Flemming,a,1,FWD,Burnley,1120.8,23.12,99.1,0.549,0.052,1.876
5,Max Alleyne,a,0,DEF,Man City,1073.5,23.12,79.7,0.285,0.054,1.382
6,Pascal Groß,a,0,MID,Brighton,1008.8,22.65,106.3,0.132,0.211,1.257
7,Alex Scott,a,0,MID,Bournemouth,1086.8,22.61,102.3,0.199,0.140,1.295
8,Mathias Jensen,a,0,MID,Brentford,1084.8,22.33,85.5,0.168,0.149,1.515
9,Dominik Szoboszlai,a,1,MID,Liverpool,1096.0,22.21,86.6,0.149,0.189,1.710
10,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1044.8,22.02,79.0,0.194,0.147,1.332
11,Benjamin White,a,0,DEF,Arsenal,1044.7,21.93,64.4,0.057,0.075,0.975
12,Jack Hinshelwood,a,0,MID,Brighton,1008.8,21.69,96.6,0.192,0.143,1.292
13,Matheus Nunes,a,1,DEF,Man City,1073.5,21.35,85.0,0.048,0.108,1.145
14,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1093.9,21.34,66.0,0.513,0.095,1.487
15,Rico Lewis,a,0,DEF,Man City,1073.5,21.30,73.4,0.285,0.065,1.465
16,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1008.8,21.27,77.9,0.300,0.054,1.517
17,Kevin Schade,a,0,MID,Brentford,1084.8,21.18,74.9,0.230,0.113,1.520
18,Konstantinos Mavropanos,a,0,DEF,West Ham,1103.7,21.17,76.5,0.176,0.070,1.560
19,Amadou Onana,a,0,MID,Aston Villa,1015.9,21.17,77.7,0.165,0.132,1.263
20,Sebastiaan Bornauw,a,0,DEF,Leeds,986.7,21.16,88.2,0.219,0.051,1.529
21,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,21.00,89.9,0.047,0.050,1.152
22,Lucas Digne,a,0,DEF,Aston Villa,1015.9,20.85,73.7,0.052,0.073,1.205
23,Alexis Mac Allister,a,1,MID,Liverpool,1096.0,20.77,71.4,0.198,0.168,1.646
24,John Stones,d,0,DEF,Man City,1073.5,20.75,66.5,0.229,0.116,1.336
25,Marcus Tavernier,a,0,MID,Bournemouth,1086.8,20.71,98.9,0.157,0.129,1.300
26,David Raya Martín,a,1,GK,Arsenal,1044.7,20.65,84.5,NaN,NaN,0.906
27,Chemsdine Talbi,a,0,MID,Sunderland,1055.0,20.61,76.9,0.181,0.124,1.445
28,Tomáš Souček,a,0,MID,West Ham,1103.7,20.46,83.1,0.147,0.114,1.471
29,Myles Lewis-Skelly,a,0,DEF,Arsenal,1044.7,20.34,68.4,0.059,0.053,1.156
30,Habib Diarra,a,0,MID,Sunderland,1055.0,20.34,81.3,0.148,0.113,1.371
31,Riccardo Calafiori,d,0,DEF,Arsenal,1044.7,20.34,50.5,0.076,0.085,0.947
32,Cristhian Mosquera,a,0,DEF,Arsenal,1044.7,20.31,54.0,0.049,0.065,0.943
33,Rayan Aït-Nouri,a,0,DEF,Man City,1073.5,20.31,72.2,0.047,0.151,1.162
34,Jan Paul van Hecke,a,1,DEF,Brighton,1008.8,20.22,107.0,0.048,0.053,1.314
35,Rio Ngumoha,a,0,MID,Liverpool,1096.0,20.22,58.2,0.220,0.262,1.534
36,Eberechi Eze,a,0,MID,Arsenal,1044.7,20.16,60.3,0.221,0.160,0.894
37,Pau Torres,a,0,DEF,Aston Villa,1015.9,20.15,76.7,0.048,0.041,1.256
38,Lisandro Martínez,d,0,DEF,Man Utd,1080.8,20.12,63.8,0.229,0.085,1.590
39,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1103.7,20.08,83.4,0.124,0.094,1.474
40,Justin Devenny,a,0,MID,Crystal Palace,1077.3,20.08,48.0,0.518,0.198,1.973
41,Ferdi Kadıoğlu,a,1,DEF,Brighton,1008.8,19.99,108.2,0.048,0.050,1.349
42,Rodrigo Bentancur,d,0,MID,Spurs,1052.8,19.92,52.5,0.312,0.251,2.230
43,Tyrone Mings,a,1,DEF,Aston Villa,1015.9,19.84,75.6,0.044,0.063,1.324
44,Sam Byram,a,0,DEF,Leeds,986.7,19.81,65.8,0.295,0.052,1.475
45,Idrissa Gana Gueye,a,0,MID,Everton,1093.9,19.75,81.2,0.109,0.089,1.309
46,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1052.8,19.75,81.3,0.345,0.060,1.599
47,Dwight McNeil,a,0,MID,Everton,1093.9,19.74,73.4,0.152,0.130,1.294
48,Ryan Christie,a,0,MID,Bournemouth,1086.8,19.65,90.1,0.163,0.114,1.307
49,Yankuba Minteh,a,0,MID,Brighton,1008.8,19.62,85.7,0.162,0.138,1.301

In [28]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 33 to 37

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,Everton,a,Norberto Bercique Gomes Betuncal,21.335538,Alexander Isak,13.697256,7.638281
1,FWD,Spurs,a,Dominic Solanke-Mitchell,19.749214,Alexander Isak,13.697256,6.051958
2,FWD,West Ham,a,Valentín Castellanos,19.477843,Alexander Isak,13.697256,5.780586
3,FWD,Chelsea,a,Marc Guiu Paz,18.844550,Alexander Isak,13.697256,5.147293
4,FWD,Nott'm Forest,a,Lorenzo Lucca,18.582504,Alexander Isak,13.697256,4.885248
5,FWD,Nott'm Forest,a,Chris Wood,18.147088,Alexander Isak,13.697256,4.449831
6,DEF,Man City,a,Max Alleyne,23.115345,Tyrone Mings,19.835484,3.279861
7,FWD,Fulham,a,Jonah Kusi-Asare,16.841378,Alexander Isak,13.697256,3.144121
8,MID,Brighton,a,Mats Wieffer,23.692327,Alexis Mac Allister,20.765767,2.926559
9,FWD,Fulham,a,Rodrigo Muniz Carvalho,16.222549,Alexander Isak,13.697256,2.525292
10,FWD,Brighton,a,Charalampos Kostoulas,16.213789,Alexander Isak,13.697256,2.516532
11,MID,Burnley,a,Jaidon Anthony,23.240879,Alexis Mac Allister,20.765767,2.475112
12,DEF,Arsenal,a,Benjamin White,21.934657,Tyrone Mings,19.835484,2.099173
13,FWD,West Ham,a,Pablo Felipe Pereira de Jesus,15.666787,Alexander Isak,13.697256,1.969531
14,MID,Brighton,a,Pascal Groß,22.654576,Alexis Mac Allister,20.765767,1.888809
15,FWD,Nott'm Forest,a,Igor Jesus Maciel da Cruz,15.566308,Alexander Isak,13.697256,1.869052
16,MID,Bournemouth,a,Alex Scott,22.608095,Alexis Mac Allister,20.765767,1.842327
17,FWD,Burnley,a,Lyle Foster,15.272879,Alexander Isak,13.697256,1.575622
18,MID,Brentford,a,Mathias Jensen,22.333239,Alexis Mac Allister,20.765767,1.567472
19,DEF,Man City,a,Rico Lewis,21.300606,Tyrone Mings,19.835484,1.465122

In [29]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 33 and 37:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,33.0,FWD,Man City,Arsenal; Burnley,14.4,1062.307979,9.546220,146.553788,0.522412,0.110178,1.209973
1,Erling Haaland,35.0,FWD,Man City,Everton,14.4,1075.115184,4.530548,67.105473,0.580364,0.104259,1.179886
2,Erling Haaland,36.0,FWD,Man City,Brentford,14.4,1073.538381,4.541402,67.105473,0.583984,0.104310,1.177148
3,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.4,1083.144286,4.540090,67.027140,0.582833,0.104303,1.236276

In [30]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.in_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.in_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, in_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW33 to GW37
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Mats Wieffer,a,0,MID,Brighton,1008.8,5.09,105.0,0.179,0.233,1.270
1,Max Alleyne,a,0,DEF,Man City,1073.5,5.07,79.7,0.285,0.054,1.382
2,Jaidon Anthony,a,0,MID,Burnley,1120.8,5.03,106.6,0.285,0.105,2.099
3,Zian Flemming,a,1,FWD,Burnley,1120.8,4.98,99.1,0.549,0.052,1.876
4,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1044.7,4.92,84.5,0.077,0.123,0.951
5,Alex Scott,a,0,MID,Bournemouth,1086.8,4.92,102.3,0.199,0.140,1.295
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.8,4.92,84.4,0.204,0.228,1.419
7,Pascal Groß,a,0,MID,Brighton,1008.8,4.86,106.3,0.132,0.211,1.257
8,Matheus Nunes,a,1,DEF,Man City,1073.5,4.76,85.0,0.048,0.108,1.145
9,Rico Lewis,a,0,DEF,Man City,1073.5,4.70,73.4,0.285,0.065,1.465
10,Jack Hinshelwood,a,0,MID,Brighton,1008.8,4.68,96.6,0.192,0.143,1.292
11,Sebastiaan Bornauw,a,0,DEF,Leeds,986.7,4.67,88.2,0.219,0.051,1.529
12,Igor Julio dos Santos de Paulo,a,0,DEF,Brighton,1008.8,4.59,77.9,0.300,0.054,1.517
13,Abdukodir Khusanov,a,0,DEF,Man City,1073.5,4.58,89.9,0.047,0.050,1.152
14,John Stones,d,0,DEF,Man City,1073.5,4.52,66.5,0.229,0.116,1.336
15,Marcus Tavernier,a,0,MID,Bournemouth,1086.8,4.51,98.9,0.157,0.129,1.300
16,Rayan Aït-Nouri,a,0,DEF,Man City,1073.5,4.49,72.2,0.047,0.151,1.162
17,Mathias Jensen,a,0,MID,Brentford,1084.8,4.49,85.5,0.168,0.149,1.515
18,Dominik Szoboszlai,a,1,MID,Liverpool,1096.0,4.46,86.6,0.149,0.189,1.710
19,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1044.8,4.44,79.0,0.194,0.147,1.332
20,Sam Byram,a,0,DEF,Leeds,986.7,4.37,65.8,0.295,0.052,1.475
21,Jan Paul van Hecke,a,1,DEF,Brighton,1008.8,4.37,107.0,0.048,0.053,1.314
22,Ferdi Kadıoğlu,a,1,DEF,Brighton,1008.8,4.33,108.2,0.048,0.050,1.349
23,Konstantinos Mavropanos,a,0,DEF,West Ham,1103.7,4.31,76.5,0.176,0.070,1.560
24,Norberto Bercique Gomes Betuncal,a,0,FWD,Everton,1093.9,4.27,66.0,0.513,0.095,1.487
25,Ryan Christie,a,0,MID,Bournemouth,1086.8,4.26,90.1,0.163,0.114,1.307
26,Kevin Schade,a,0,MID,Brentford,1084.8,4.25,74.9,0.230,0.113,1.520
27,Yankuba Minteh,a,0,MID,Brighton,1008.8,4.22,85.7,0.162,0.138,1.301
28,Amadou Onana,a,0,MID,Aston Villa,1015.9,4.22,77.7,0.165,0.132,1.263
29,Alexis Mac Allister,a,1,MID,Liverpool,1096.0,4.17,71.4,0.198,0.168,1.646
30,Lucas Digne,a,0,DEF,Aston Villa,1015.9,4.15,73.7,0.052,0.073,1.205
31,Benjamin White,a,0,DEF,Arsenal,1044.7,4.14,64.4,0.057,0.075,0.975
32,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1073.5,4.14,76.4,0.141,0.202,1.183
33,Jayden Bogle,a,0,DEF,Leeds,986.7,4.13,89.7,0.053,0.050,1.374
34,James Justin,a,0,DEF,Leeds,986.7,4.13,90.9,0.042,0.056,1.382
35,Rio Ngumoha,a,0,MID,Liverpool,1096.0,4.13,58.2,0.220,0.262,1.534
36,Chemsdine Talbi,a,0,MID,Sunderland,1055.0,4.12,76.9,0.181,0.124,1.445
37,Tomáš Souček,a,0,MID,West Ham,1103.7,4.12,83.1,0.147,0.114,1.471
38,Habib Diarra,a,0,MID,Sunderland,1055.0,4.05,81.3,0.148,0.113,1.371
39,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1103.7,4.04,83.4,0.124,0.094,1.474
40,Pascal Struijk,a,0,DEF,Leeds,986.7,4.04,86.8,0.046,0.070,1.401
41,Marc Guiu Paz,a,0,FWD,Chelsea,1060.1,4.04,50.9,0.642,0.360,1.561
42,Benoît Badiashile Mukinayi,a,0,DEF,Chelsea,1060.1,4.04,77.9,0.238,0.046,1.695
43,Pau Torres,a,0,DEF,Aston Villa,1015.9,4.04,76.7,0.048,0.041,1.256
44,Julio Soler Barreto,a,0,DEF,Bournemouth,1086.8,4.03,67.1,0.307,0.057,1.726
45,Justin Devenny,a,0,MID,Crystal Palace,1077.3,4.03,48.0,0.518,0.198,1.973
46,Lisandro Martínez,d,0,DEF,Man Utd,1080.8,4.03,63.8,0.229,0.085,1.590
47,Olivier Boscagli,a,0,DEF,Brighton,1008.8,3.99,80.7,0.063,0.061,1.329
48,Rodrigo Bentancur,d,0,MID,Spurs,1052.8,3.99,52.5,0.312,0.251,2.230
49,Aaron Hickey,d,0,DEF,Brentford,1084.8,3.98,68.3,0.221,0.047,1.725

In [31]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [32]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [33]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [34]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE in_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [35]:
from FPL_Optimizer import FPLOptimizer
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW33 to GW38...

Optimizing team selection for GW33...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 66.34
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.48
 ✅        Martinez                       Aston Villa  £5.1     3.56

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     3.69
 ✅        F.Kadıoğlu                     Brighton     £4.4     8.01
 ✅        Gabriel                        Arsenal      £7.2     4.20
 ✅        Van Hecke                      Brighton     £4.5     8.10
 ✅        Matheus N.                     Man City     £5.3     9.28

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.17
 ✅        B.Fernandes                    Man Utd      £10.3    4.88
 ✅        Bruno G.                       Newcastle    £6.8     4.57
 ✅        Szoboszlai                     Liverpool    £7.1     4.48
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.63

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.67
 🪑        Brobbey                        Sunderland   £5.3     3.75
 ✅        Flemming                       Burnley      £5.3     9.11

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

Optimization Status: Infeasible
No valid 15-player squad found within constraints.
Error optimizing for GW34: No optimization has been run yet. Call optimize() first.

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 50.07
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     3.96
 ✅        Martinez                       Aston Villa  £5.1     4.12

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        F.Kadıoğlu                     Brighton     £4.4     3.85
 🪑        Van Hecke                      Brighton     £4.5     3.82
 ✅        Gabriel                        Arsenal      £7.2     5.08
 ✅        Matheus N.                     Man City     £5.3     4.01
 ✅        Mings                          Aston Villa  £4.3     4.59

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.12
 ✅        B.Fernandes                    Man Utd      £10.3    4.88
 ✅        Bruno G.                       Newcastle    £6.8     4.45
 ✅        Szoboszlai                     Liverpool    £7.1     4.41
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.36

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.72
 ✅        Brobbey                        Sunderland   £5.3     3.94
 ✅        Flemming                       Burnley      £5.3     4.69

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-5-1
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 52.34
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.29
 ✅        Raya                           Arsenal      £6.0     4.64

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.3     4.07
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.29
 ✅        Gabriel                        Arsenal      £7.2     5.55
 ✅        Van Hecke                      Brighton     £4.5     4.41
 ✅        Mings                          Aston Villa  £4.3     4.87

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.09
 ✅        B.Fernandes                    Man Utd      £10.3    5.04
 ✅        Bruno G.                       Newcastle    £6.8     4.60
 ✅        Szoboszlai                     Liverpool    £7.1     4.41
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.32

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.75
 🪑        Brobbey                        Sunderland   £5.3     3.74
 ✅        Flemming                       Burnley      £5.3     4.65

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 51.05
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.40
 ✅        Raya                           Arsenal      £6.0     4.69

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        F.Kadıoğlu                     Brighton     £4.4     3.84
 🪑        Mings                          Aston Villa  £4.3     2.98
 ✅        Gabriel                        Arsenal      £7.2     6.18
 ✅        Van Hecke                      Brighton     £4.5     3.90
 ✅        Matheus N.                     Man City     £5.3     3.98

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.09
 ✅        B.Fernandes                    Man Utd      £10.3    5.07
 ✅        Bruno G.                       Newcastle    £6.8     4.57
 ✅        Szoboszlai                     Liverpool    £7.1     4.35
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.39

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.79
 ✅        Brobbey                        Sunderland   £5.3     3.85
 ✅        Flemming                       Burnley      £5.3     4.68

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 3-5-2
Total Squad Cost: £95.6m / £102.4m
Total Weighted Expected Points: 49.63
Remaining Budget: £6.8m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.44
 ✅        Raya                           Arsenal      £6.0     3.93

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Matheus N.                     Man City     £5.3     3.42
 🪑        Mings                          Aston Villa  £4.3     2.87
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.79
 ✅        Gabriel                        Arsenal      £7.2     5.17
 ✅        Van Hecke                      Brighton     £4.5     3.84

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mac Allister                   Liverpool    £6.3     4.31
 ✅        B.Fernandes                    Man Utd      £10.3    4.90
 ✅        Bruno G.                       Newcastle    £6.8     4.66
 ✅        Szoboszlai                     Liverpool    £7.1     4.60
 ✅        Gibbs-White                    Nott'm Forest £7.4     4.49

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.81
 ✅        Brobbey                        Sunderland   £5.3     3.78
 ✅        Flemming                       Burnley      £5.3     4.90

================================================================================
Optimization Status: Optimal

In [36]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
2     36         13.360185
1     35         12.913116
0     33         12.223556
3     37         11.706537
4     38         11.279502

In [37]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.03 minute(s)