In [16]:
import pandas as pd
import time

In [17]:
start=time.perf_counter()

In [18]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [ ]:
#add this info to a settings dict?
stats_current_gameweek = 17
picks_current_gameweek = 17
current_season = 20252026

In [20]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 1
        -- AND in_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 17
Squad Points: 58.47

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Matheus N.,a,NaN,17.0,DEF,Man City,West Ham,5.030890
1,Raya,a,NaN,17.0,GK,Arsenal,Everton,4.977404
2,Szoboszlai,s,75.0,17.0,MID,Liverpool,Spurs,4.515798
3,Gabriel,d,25.0,17.0,DEF,Arsenal,Everton,4.455341
4,B.Fernandes,d,NaN,17.0,MID,Man Utd,Aston Villa,4.308979
5,Konaté,a,100.0,17.0,DEF,Liverpool,Spurs,4.079866
6,Minteh,a,NaN,17.0,MID,Brighton,Sunderland,4.043694
7,Gyökeres,a,100.0,17.0,FWD,Arsenal,Everton,3.839057
8,Amad,n,0.0,17.0,MID,Man Utd,Aston Villa,3.118473
9,O.Dango,n,0.0,17.0,MID,Brentford,Wolves,2.847949
10,Tarkowski,a,NaN,17.0,DEF,Everton,Arsenal,2.838882
11,Lacroix,a,NaN,17.0,DEF,Crystal Palace,Leeds,2.818829
12,Pope,d,75.0,17.0,GK,Newcastle,Chelsea,2.528728
13,Flemming,a,NaN,17.0,FWD,Burnley,Bournemouth,2.159498
14,Raúl,a,100.0,17.0,FWD,Fulham,Nott'm Forest,1.874546

In [21]:
print(f"Check status of available players in GW {picks_current_gameweek+1}")
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions_status
    WHERE in_my_team = 0
        AND in_any_team = 0
        AND event = {picks_current_gameweek+1}
        AND status = 'a'
    ORDER BY xpoints DESC
""")
view.head(10)

Check status of available players in GW 17

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints
0,Lewis-Potter,a,NaN,17.0,DEF,Brentford,Wolves,6.414250
1,Cherki,a,100.0,17.0,MID,Man City,West Ham,5.822071
2,Truffert,a,NaN,17.0,DEF,Bournemouth,Burnley,5.588669
3,Senesi,a,100.0,17.0,DEF,Bournemouth,Burnley,5.541604
4,Struijk,a,100.0,17.0,DEF,Leeds,Crystal Palace,5.434644
5,Bogle,a,100.0,17.0,DEF,Leeds,Crystal Palace,5.234979
6,Cook,a,100.0,17.0,MID,Bournemouth,Burnley,5.174392
7,Collins,a,NaN,17.0,DEF,Brentford,Wolves,5.075511
8,Gudmundsson,a,100.0,17.0,DEF,Leeds,Crystal Palace,5.066664
9,Rúben,a,NaN,17.0,DEF,Man City,West Ham,5.030944

In [22]:
print("When to use first TRIPLE CAPTAIN chip (gws1-19)")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints
    FROM predictions
    WHERE in_my_team = 1
      AND event BETWEEN {picks_current_gameweek} AND 19
    ORDER BY xpoints DESC
""")
view.head(10)

When to use first TRIPLE CAPTAIN chip (gws1-19)

           player_name_id  event position  team_name  opp_team_name   xpoints
0             Amad Diallo   19.0      MID    Man Utd         Wolves  5.648058
1         James Tarkowski   18.0      DEF    Everton        Burnley  5.610780
2  Bruno Borges Fernandes   19.0      MID    Man Utd         Wolves  5.160420
3             Amad Diallo   18.0      MID    Man Utd      Newcastle  5.143240
4      Dominik Szoboszlai   18.0      MID  Liverpool         Wolves  5.126808
5         Viktor Gyökeres   18.0      FWD    Arsenal       Brighton  5.079567
6           Matheus Nunes   17.0      DEF   Man City       West Ham  5.030890
7       David Raya Martín   17.0       GK    Arsenal        Everton  4.977404
8         Viktor Gyökeres   19.0      FWD    Arsenal    Aston Villa  4.969733
9           Matheus Nunes   18.0      DEF   Man City  Nott'm Forest  4.966458

In [37]:
print(f"Best players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        in_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE (in_any_team = 0 OR in_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, in_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the next 5 gameweeks: GW17 AND 21

,player_name_id,in_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xap90_pred,avg_xgcp90_pred
0,Daniel Ballard,0,DEF,Sunderland,1074.4,25.64,85.0,0.074,0.107,0.978
1,Rúben dos Santos Gato Alves Dias,0,DEF,Man City,1071.2,25.50,80.1,0.121,0.052,1.016
2,Amad Diallo,1,MID,Man Utd,1008.2,25.05,62.8,0.392,0.202,1.203
3,Harry Wilson,0,MID,Fulham,1092.8,24.17,61.1,0.307,0.188,1.431
4,Anton Stach,0,MID,Leeds,1113.8,24.05,79.4,0.205,0.215,1.404
5,Viktor Gyökeres,1,FWD,Arsenal,1122.2,23.99,63.6,0.543,0.068,1.233
6,Dominik Szoboszlai,1,MID,Liverpool,1033.8,23.98,83.8,0.204,0.184,1.202
7,Bruno Borges Fernandes,1,MID,Man Utd,1008.2,23.88,55.2,0.365,0.412,1.541
8,James Tarkowski,1,DEF,Everton,1027.7,23.73,87.1,0.066,0.061,1.079
9,Nordi Mukiele,0,DEF,Sunderland,1074.4,23.65,86.8,0.031,0.057,0.960
10,Matheus Nunes,1,DEF,Man City,1071.2,23.65,66.2,0.081,0.122,1.185
11,Yéremy Pino Santos,0,MID,Crystal Palace,1057.2,23.62,77.1,0.257,0.139,1.510
12,Rayan Cherki,0,MID,Man City,1071.2,23.30,50.8,0.194,0.582,0.982
13,Pascal Struijk,0,DEF,Leeds,1113.8,23.28,79.9,0.234,0.036,1.422
14,Tijjani Reijnders,0,MID,Man City,1071.2,23.24,62.0,0.233,0.182,1.009
15,David Raya Martín,1,GK,Arsenal,1122.2,23.18,80.3,NaN,NaN,0.745
16,Jake O'Brien,0,DEF,Everton,1027.7,23.12,72.6,0.086,0.045,1.084
17,Sepp van den Berg,0,DEF,Brentford,1024.7,22.99,87.1,0.093,0.019,1.124
18,Nathan Collins,0,DEF,Brentford,1024.7,22.96,76.3,0.111,0.067,1.179
19,Michael Keane,0,DEF,Everton,1027.7,22.84,86.3,0.083,0.021,1.156
20,Omar Alderete,0,DEF,Sunderland,1074.4,22.82,86.8,0.103,0.035,1.226
21,Vitalii Mykolenko,0,DEF,Everton,1027.7,22.80,87.0,0.053,0.053,1.111
22,Enzo Le Fée,0,MID,Sunderland,1074.4,22.40,71.6,0.206,0.173,1.139
23,Adam Wharton,0,MID,Crystal Palace,1057.2,21.90,79.8,0.144,0.168,1.534
24,Adrien Truffert,0,DEF,Bournemouth,1068.9,21.86,84.9,0.039,0.066,1.180
25,Malo Gusto,0,DEF,Chelsea,1125.7,21.81,66.5,0.109,0.143,1.485
26,Georginio Rutter,0,MID,Brighton,1092.1,21.77,75.9,0.185,0.129,1.328
27,Bruno Guimarães Rodriguez Moura,0,MID,Newcastle,1030.2,21.68,78.5,0.149,0.129,1.313
28,Virgil van Dijk,0,DEF,Liverpool,1033.8,21.60,86.6,0.061,0.024,1.165
29,Trai Hume,0,DEF,Sunderland,1074.4,21.59,74.8,0.054,0.080,1.266
30,Jarrod Bowen,0,FWD,West Ham,1064.5,21.53,86.7,0.380,0.052,1.570
31,Marcus Tavernier,0,MID,Bournemouth,1068.9,21.36,76.3,0.184,0.102,1.321
32,Michael Kayode,0,DEF,Brentford,1024.7,21.35,79.7,0.026,0.079,1.180
33,Marcos Senesi Barón,0,DEF,Bournemouth,1068.9,21.19,58.2,0.127,0.253,1.244
34,Yankuba Minteh,1,MID,Brighton,1092.1,20.99,76.3,0.136,0.149,1.349
35,Diogo Dalot Teixeira,0,DEF,Man Utd,1008.2,20.87,82.1,0.066,0.090,1.375
36,Mats Wieffer,0,MID,Brighton,1092.1,20.82,68.7,0.178,0.106,1.392
37,Josh Cullen,0,MID,Burnley,1077.2,20.69,82.1,0.124,0.118,1.427
38,Luke Shaw,0,DEF,Man Utd,1008.2,20.62,84.5,0.045,0.068,1.267
39,Ibrahima Konaté,1,DEF,Liverpool,1033.8,20.40,86.3,0.042,0.041,1.228
40,Abdukodir Khusanov,0,DEF,Man City,1071.2,20.37,17.8,0.058,0.041,0.669
41,Nico González Iglesias,0,MID,Man City,1071.2,20.34,73.1,0.098,0.118,0.971
42,Lewis Miley,0,MID,Newcastle,1030.2,20.34,68.7,0.102,0.139,1.115
43,Lucas Tolentino Coelho de Lima,0,MID,West Ham,1064.5,20.26,70.0,0.085,0.163,1.252
44,Benjamin White,0,DEF,Arsenal,1122.2,20.18,45.5,0.041,0.064,0.771
45,Myles Lewis-Skelly,0,DEF,Arsenal,1122.2,19.98,35.8,0.117,0.100,0.886
46,Maxence Lacroix,1,DEF,Crystal Palace,1057.2,19.93,85.6,0.074,0.055,1.504
47,Youri Tielemans,0,MID,Aston Villa,1120.6,19.93,79.8,0.092,0.103,1.273
48,Martín Zubimendi Ibáñez,0,MID,Arsenal,1122.2,19.93,69.6,0.082,0.063,0.640
49,Mohammed Kudus,0,MID,Spurs,1097.9,19.88,70.9,0.140,0.108,1.287

In [38]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to 38")#{picks_current_gameweek + 5}
view = db_creator.run_sql(f"""
    WITH 
    summed AS (
        SELECT 
            player_name_id,
            team_name,
            position,
            in_my_team,
            in_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions
        WHERE event BETWEEN {picks_current_gameweek+1} AND 38 --{picks_current_gameweek + 5}
        GROUP BY player_name_id, team_name, position, in_my_team, in_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, total_xpoints AS xpoints, in_my_team, position
        FROM summed
        WHERE in_any_team = 0
          AND in_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b
    CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b
    CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b
    CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b
    CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")

view.head(20)

Best available players to replace worst in my team: 17 to 38

,position,best_team,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,FWD,West Ham,Jarrod Bowen,94.365197,Raúl Jiménez Rodríguez,46.564429,47.800768
1,FWD,Crystal Palace,Jean-Philippe Mateta,86.980086,Raúl Jiménez Rodríguez,46.564429,40.415657
2,MID,Leeds,Anton Stach,107.238101,Dango Ouattara,67.988647,39.249453
3,MID,Fulham,Harry Wilson,106.790000,Dango Ouattara,67.988647,38.801353
4,MID,Crystal Palace,Yéremy Pino Santos,106.630449,Dango Ouattara,67.988647,38.641802
5,FWD,Spurs,Richarlison de Andrade,85.008264,Raúl Jiménez Rodríguez,46.564429,38.443834
6,GK,Crystal Palace,Dean Henderson,82.314182,Nick Pope,51.260751,31.053431
7,MID,Sunderland,Enzo Le Fée,98.991589,Dango Ouattara,67.988647,31.002942
8,GK,Liverpool,Alisson Becker,81.845437,Nick Pope,51.260751,30.584686
9,MID,Man City,Tijjani Reijnders,98.570208,Dango Ouattara,67.988647,30.581561
10,MID,Man City,Rayan Cherki,98.310015,Dango Ouattara,67.988647,30.321368
11,MID,Crystal Palace,Adam Wharton,97.554006,Dango Ouattara,67.988647,29.565359
12,GK,Bournemouth,Đorđe Petrović,80.291935,Nick Pope,51.260751,29.031184
13,MID,Brighton,Georginio Rutter,95.287328,Dango Ouattara,67.988647,27.298680
14,MID,Bournemouth,Marcus Tavernier,94.483979,Dango Ouattara,67.988647,26.495332
15,MID,Newcastle,Bruno Guimarães Rodriguez Moura,94.119430,Dango Ouattara,67.988647,26.130782
16,DEF,Sunderland,Daniel Ballard,115.354760,Ibrahima Konaté,89.496582,25.858178
17,DEF,Man City,Rúben dos Santos Gato Alves Dias,114.880635,Ibrahima Konaté,89.496582,25.384053
18,GK,Aston Villa,Emiliano Martínez Romero,76.280765,Nick Pope,51.260751,25.020014
19,GK,Newcastle,Aaron Ramsdale,74.927825,Nick Pope,51.260751,23.667074

In [39]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Enzo Fernández'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 17 and 21:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Enzo Fernández,17.0,MID,Chelsea,Newcastle,6.5,1104.995921,4.903485,65.194523,0.321140,0.213594,1.671256
1,Enzo Fernández,18.0,MID,Chelsea,Aston Villa,6.5,1187.909037,4.928403,70.040871,0.333854,0.176092,1.452377
2,Enzo Fernández,19.0,MID,Chelsea,Bournemouth,6.5,1050.319497,5.152748,70.040871,0.342987,0.186001,1.124906
3,Enzo Fernández,20.0,MID,Chelsea,Man City,6.5,1248.652906,4.852567,69.365769,0.333854,0.176092,1.654845
4,Enzo Fernández,21.0,MID,Chelsea,Fulham,6.5,1036.411749,5.186279,70.040871,0.344701,0.195492,1.111757

In [40]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [41]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

In [42]:
view = db_creator.run_sql(f"""
    SELECT *
    FROM fpl_picks_2
""")
view.head(10)

,member,memberid,season,gw,pick,element,position,multiplier,is_captain,is_vice_captain,div
0,Rhys Birdy,4899844.0,2526.0,1.0,1.0,366.0,1.0,1.0,False,False,2.0
1,Rhys Birdy,4899844.0,2526.0,1.0,2.0,6.0,2.0,1.0,False,False,2.0
2,Rhys Birdy,4899844.0,2526.0,1.0,3.0,402.0,3.0,1.0,False,False,2.0
3,Rhys Birdy,4899844.0,2526.0,1.0,4.0,508.0,4.0,1.0,False,False,2.0
4,Rhys Birdy,4899844.0,2526.0,1.0,5.0,21.0,5.0,1.0,False,False,2.0
5,Rhys Birdy,4899844.0,2526.0,1.0,6.0,381.0,6.0,2.0,True,False,2.0
6,Rhys Birdy,4899844.0,2526.0,1.0,7.0,16.0,7.0,1.0,False,True,2.0
7,Rhys Birdy,4899844.0,2526.0,1.0,8.0,119.0,8.0,1.0,False,False,2.0
8,Rhys Birdy,4899844.0,2526.0,1.0,9.0,417.0,9.0,1.0,False,False,2.0
9,Rhys Birdy,4899844.0,2526.0,1.0,10.0,596.0,10.0,1.0,False,False,2.0

In [43]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 41.08 minute(s)