In [1]:
import pandas as pd
import time

In [2]:
start=time.perf_counter()

In [3]:
from DatabaseCreator import DatabaseCreator
import CJDH_local_settings

#Run Database Creator
if __name__ == "__main__":
    db_creator = DatabaseCreator(db_settings=CJDH_local_settings.local_settings['FPL_Points_Predictor'])
    fpl_engine = db_creator.get_engine_for("fpl_data_analysis")

In [4]:
#add this info to a settings dict?
current_gw = 33
stats_current_gameweek = current_gw
picks_current_gameweek = current_gw
current_season = 20252026

In [5]:
print(f"Team Selection - GW {picks_current_gameweek+1}")
## latest_my_team and in_my_team differ because the former adjusts to freehits by setting the latest team to the previous gw
view = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        -- AND latest_any_team = 1
        AND event = {picks_current_gameweek+1}
        -- AND status = 'a'
    ORDER BY xpoints DESC
""")
print(f"Squad Points: {round(view['xpoints'].sum()+view['xpoints'][0],2)}") #including captain points
view.head(15)

Team Selection - GW 34
Squad Points: 49.13

,web_name,status,chance_of_playing_this_round,event,position,team_name,opp_team_name,xpoints,mins_pred
0,Gibbs-White,a,100.0,34.0,MID,Nott'm Forest,Sunderland,5.019851,84.0
1,B.Fernandes,a,100.0,34.0,MID,Man Utd,Brentford,4.775803,84.0
2,Gabriel,a,100.0,34.0,DEF,Arsenal,Newcastle,4.773438,84.0
3,Szoboszlai,a,100.0,34.0,MID,Liverpool,Crystal Palace,4.371677,86.0
4,Raya,a,NaN,34.0,GK,Arsenal,Newcastle,4.074805,90.0
5,Brobbey,a,100.0,34.0,FWD,Sunderland,Nott'm Forest,3.975334,83.0
6,Mac Allister,a,100.0,34.0,MID,Liverpool,Crystal Palace,3.662590,56.0
7,Martinez,a,100.0,34.0,GK,Aston Villa,Fulham,3.599380,90.0
8,Mings,a,100.0,34.0,DEF,Aston Villa,Fulham,3.594072,77.0
9,Bruno G.,a,75.0,34.0,MID,Newcastle,Arsenal,3.237036,52.0
10,Isak,a,100.0,34.0,FWD,Liverpool,Crystal Palace,3.025133,50.0

In [6]:
print(f"Best players to transfer out for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions
    WHERE latest_my_team = 1
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      -- AND position = 'DEF'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, position, team_name, latest_my_team
    ORDER BY total_xpoints ASC
""")
view.head(50)

Best players to transfer out for the next 5 gameweeks: GW34 AND 38

,player_name_id,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Alexander Isak,1,FWD,Liverpool,1094.1,15.06,50.6,0.376,1.000,0.065,1.596,1.390
1,Zian Flemming,1,FWD,Burnley,1076.3,15.64,76.4,0.394,1.000,0.046,1.000,1.864
2,Jan Paul van Hecke,1,DEF,Brighton,1025.4,16.34,86.5,0.051,1.000,0.042,1.000,1.246
3,Ferdi Kadıoğlu,1,DEF,Brighton,1025.4,16.38,86.8,0.050,1.000,0.045,1.000,1.256
4,Bruno Guimarães Rodriguez Moura,1,MID,Newcastle,1079.1,16.97,53.4,0.218,1.000,0.153,1.000,1.515
5,Alexis Mac Allister,1,MID,Liverpool,1094.1,17.91,55.7,0.269,1.458,0.096,1.000,1.518
6,Matheus Nunes,1,DEF,Man City,1092.4,18.00,82.3,0.046,1.000,0.292,2.833,1.468
7,Tyrone Mings,1,DEF,Aston Villa,1056.4,18.62,77.0,0.050,1.000,0.047,1.000,1.468
8,Emiliano Martínez Romero,1,GK,Aston Villa,1056.4,19.42,89.7,NaN,1.000,NaN,1.000,1.267
9,Brian Brobbey,1,FWD,Sunderland,1045.7,20.08,82.5,0.369,1.000,0.041,1.000,1.336
10,Dominik Szoboszlai,1,MID,Liverpool,1094.1,21.37,85.5,0.156,1.000,0.136,1.000,1.485
11,David Raya Martín,1,GK,Arsenal,1005.9,21.80,89.8,NaN,1.000,NaN,1.000,0.819
12,Bruno Borges Fernandes,1,MID,Man Utd,1080.1,24.62,83.3,0.220,1.000,0.260,1.334,1.432
13,Morgan Gibbs-White,1,MID,Nott'm Forest,1079.1,25.48,83.2,0.229,1.000,0.338,1.986,1.530
14,Gabriel dos Santos Magalhães,1,DEF,Arsenal,1005.9,26.25,83.8,0.093,1.000,0.113,1.000,0.924

In [7]:
print(f"Best players to pick for the rest of the season: GW{picks_current_gameweek+1} AND GW38")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
    player_name_id,
    status,
    latest_my_team,
    position,
    team_name,
    ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
    ROUND(SUM(xpoints),2) AS total_xpoints,
    ROUND(AVG(mins_pred),1) AS avg_mins_pred,
    ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
    ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
    ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
    ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
    ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
FROM predictions_status
WHERE (latest_any_team = 0 OR latest_my_team = 1)
    AND status IN ('a','d')
    -- AND position IN ('FWD')
    --AND team_name = 'Liverpool'
  AND event BETWEEN {picks_current_gameweek+1} AND 38
GROUP BY player_name_id, status, position, team_name, latest_my_team
ORDER BY total_xpoints DESC
""")
view.head(50)

Best players to pick for the rest of the season: GW34 AND GW38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xg_overperf_factor,avg_xgp90_pred,avg_xa_overperf_factor,avg_xap90_pred,avg_xgcp90_pred
0,Harvey Barnes,a,0,MID,Newcastle,1079.1,27.19,61.8,1.988,0.635,2.467,0.316,1.693
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1005.9,26.25,83.8,1.000,0.093,1.000,0.113,0.924
2,Mathias Jensen,a,0,MID,Brentford,1114.7,25.80,85.1,1.911,0.323,1.000,0.180,1.543
3,John Stones,a,0,DEF,Man City,1092.4,25.53,54.8,3.577,0.974,1.000,0.040,1.593
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1079.1,25.48,83.2,1.000,0.229,1.986,0.338,1.530
5,Eberechi Eze,a,0,MID,Arsenal,1005.9,25.14,63.2,1.353,0.355,1.972,0.350,0.851
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.1,24.62,83.3,1.000,0.220,1.334,0.260,1.432
7,Youri Tielemans,a,0,MID,Aston Villa,1056.4,24.32,71.0,2.733,0.281,2.302,0.329,1.323
8,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1092.4,24.23,81.9,1.000,0.151,4.780,0.781,1.194
9,Callum Hudson-Odoi,d,0,MID,Nott'm Forest,1079.1,23.64,72.7,2.189,0.352,1.948,0.157,1.514
10,Dwight McNeil,a,0,MID,Everton,1058.7,23.58,73.9,1.781,0.289,1.645,0.215,1.343
11,Leandro Trossard,a,0,MID,Arsenal,1005.9,23.43,44.6,1.982,0.551,2.533,0.450,0.819
12,John McGinn,a,0,MID,Aston Villa,1056.4,23.25,73.2,1.000,0.204,2.046,0.330,1.247
13,Benjamin White,a,0,DEF,Arsenal,1005.9,21.90,68.0,1.000,0.051,1.000,0.078,1.025
14,Granit Xhaka,a,0,MID,Sunderland,1045.7,21.87,75.3,2.320,0.203,3.169,0.215,1.412
15,Kevin Schade,a,0,MID,Brentford,1114.7,21.85,76.8,1.000,0.226,2.065,0.176,1.529
16,David Raya Martín,a,1,GK,Arsenal,1005.9,21.80,89.8,1.000,NaN,1.000,NaN,0.819
17,Ross Barkley,a,0,MID,Aston Villa,1056.4,21.64,73.1,1.922,0.236,1.888,0.145,1.297
18,Amadou Onana,a,0,MID,Aston Villa,1056.4,21.62,84.4,1.000,0.205,1.000,0.073,1.402
19,Dominik Szoboszlai,a,1,MID,Liverpool,1094.1,21.37,85.5,1.000,0.156,1.000,0.136,1.485
20,Lucas Digne,a,0,DEF,Aston Villa,1056.4,21.36,66.6,1.000,0.092,2.217,0.289,1.447
21,Cristhian Mosquera,a,0,DEF,Arsenal,1005.9,21.33,65.1,1.000,0.045,1.000,0.034,0.968
22,Conor Gallagher,a,0,MID,Spurs,1047.0,21.25,65.5,2.507,0.292,3.352,0.214,1.662
23,Habib Diarra,a,0,MID,Sunderland,1045.7,20.86,85.4,1.000,0.150,1.000,0.123,1.388
24,Riccardo Calafiori,d,0,DEF,Arsenal,1005.9,20.63,49.3,1.000,0.104,1.000,0.094,0.972
25,Mason Mount,a,0,MID,Man Utd,1080.1,20.53,25.3,3.906,0.990,5.301,0.736,2.020
26,Tomáš Souček,a,0,MID,West Ham,1087.5,20.43,84.0,1.000,0.189,1.000,0.063,1.532
27,Myles Lewis-Skelly,a,0,DEF,Arsenal,1005.9,20.20,61.5,1.000,0.052,1.000,0.031,1.022
28,El Hadji Malick Diouf,a,0,DEF,West Ham,1087.5,20.12,85.4,1.000,0.051,2.255,0.150,1.486
29,Brian Brobbey,a,1,FWD,Sunderland,1045.7,20.08,82.5,1.000,0.369,1.000,0.041,1.336
30,Noni Madueke,a,0,MID,Arsenal,1005.9,20.08,59.5,1.000,0.258,1.000,0.096,0.851
31,Reece James,d,0,DEF,Chelsea,1047.3,20.05,60.3,4.135,0.211,2.957,0.575,1.445
32,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1087.5,19.98,85.0,1.000,0.123,1.000,0.102,1.513
33,Pau Torres,a,0,DEF,Aston Villa,1056.4,19.97,85.1,1.000,0.054,1.000,0.028,1.349
34,James Ward-Prowse,a,0,MID,Burnley,1076.3,19.71,76.1,2.532,0.360,1.778,0.217,1.999
35,Andrew Robertson,a,0,DEF,Liverpool,1094.1,19.71,74.5,1.000,0.048,1.986,0.182,1.472
36,Nathan Patterson,a,0,DEF,Everton,1058.7,19.57,49.4,1.000,0.236,1.000,0.398,1.600
37,Mats Wieffer,a,0,MID,Brighton,1025.4,19.51,84.5,1.000,0.144,2.463,0.369,1.304
38,Emiliano Martínez Romero,a,1,GK,Aston Villa,1056.4,19.42,89.7,1.000,NaN,1.000,NaN,1.267
39,Séamus Coleman,a,0,DEF,Everton,1058.7,19.29,51.8,1.000,0.366,1.000,0.037,1.596
40,Idrissa Gana Gueye,a,0,MID,Everton,1058.7,19.28,81.5,1.000,0.099,1.000,0.090,1.384
41,Jacob Ramsey,a,0,MID,Newcastle,1079.1,19.20,62.5,1.708,0.228,2.029,0.175,1.622
42,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1047.0,19.01,84.9,1.000,0.302,1.000,0.044,1.437
43,Jake O'Brien,a,0,DEF,Everton,1058.7,18.85,85.2,1.000,0.044,1.000,0.046,1.411
44,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1080.1,18.84,80.6,1.000,0.042,1.861,0.112,1.479
45,Vitalii Mykolenko,a,0,DEF,Everton,1058.7,18.80,86.0,1.000,0.044,1.000,0.039,1.413
46,Marco Bizot,a,0,GK,Aston Villa,1056.4,18.77,89.7,1.000,NaN,1.000,NaN,1.490
47,Lewis Miley,a,0,MID,Newcastle,1079.1,18.76,78.6,1.000,0.129,1.000,0.079,1.565
48,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1079.1,18.76,73.1,1.000,0.361,1.000,0.063,1.399
49,Ibrahima Konaté,a,0,DEF,Liverpool,1094.1,18.76,86.1,1.000,0.046,1.000,0.042,1.466

In [8]:
print(f"Best available players to pick for the next 5 gameweeks: GW{picks_current_gameweek+1} AND {picks_current_gameweek+5}")
view = db_creator.run_sql(f"""
WITH predictions_status AS (
    SELECT 
        p.player_name_id,
        p.element,
        ps.status,
        p.latest_my_team,
        p.position,
        p.team_name,
        p.opp_team_elo,
        p.xpoints,
        p.mins_pred,
        p.xgp90_pred,
        p.xg_overperf_factor,
        p.xap90_pred,
        p.xa_overperf_factor,
        p.xgcp90_pred,
        p.event,
        p.latest_any_team
    FROM predictions p
    LEFT JOIN player_status ps ON p.element = ps.id
)  
SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(AVG(opp_team_elo),1) AS avg_opp_team_elo,
        ROUND(SUM(xpoints),2) AS total_xpoints,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'FWD'
      -- AND team_name IN ('Arsenal','Man United','Nottm Forest','Brentford','Brighton','Chelsea')
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints DESC
""")
view.head(50)

Best available players to pick for the next 5 gameweeks: GW34 AND 38

,player_name_id,status,latest_my_team,position,team_name,avg_opp_team_elo,total_xpoints,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Harvey Barnes,a,0,MID,Newcastle,1079.1,27.19,61.8,0.635,1.988,0.316,2.467,1.693
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1005.9,26.25,83.8,0.093,1.000,0.113,1.000,0.924
2,Mathias Jensen,a,0,MID,Brentford,1114.7,25.80,85.1,0.323,1.911,0.180,1.000,1.543
3,John Stones,a,0,DEF,Man City,1092.4,25.53,54.8,0.974,3.577,0.040,1.000,1.593
4,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1079.1,25.48,83.2,0.229,1.000,0.338,1.986,1.530
5,Eberechi Eze,a,0,MID,Arsenal,1005.9,25.14,63.2,0.355,1.353,0.350,1.972,0.851
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1080.1,24.62,83.3,0.220,1.000,0.260,1.334,1.432
7,Youri Tielemans,a,0,MID,Aston Villa,1056.4,24.32,71.0,0.281,2.733,0.329,2.302,1.323
8,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,1092.4,24.23,81.9,0.151,1.000,0.781,4.780,1.194
9,Callum Hudson-Odoi,d,0,MID,Nott'm Forest,1079.1,23.64,72.7,0.352,2.189,0.157,1.948,1.514
10,Dwight McNeil,a,0,MID,Everton,1058.7,23.58,73.9,0.289,1.781,0.215,1.645,1.343
11,Leandro Trossard,a,0,MID,Arsenal,1005.9,23.43,44.6,0.551,1.982,0.450,2.533,0.819
12,John McGinn,a,0,MID,Aston Villa,1056.4,23.25,73.2,0.204,1.000,0.330,2.046,1.247
13,Benjamin White,a,0,DEF,Arsenal,1005.9,21.90,68.0,0.051,1.000,0.078,1.000,1.025
14,Granit Xhaka,a,0,MID,Sunderland,1045.7,21.87,75.3,0.203,2.320,0.215,3.169,1.412
15,Kevin Schade,a,0,MID,Brentford,1114.7,21.85,76.8,0.226,1.000,0.176,2.065,1.529
16,David Raya Martín,a,1,GK,Arsenal,1005.9,21.80,89.8,NaN,1.000,NaN,1.000,0.819
17,Ross Barkley,a,0,MID,Aston Villa,1056.4,21.64,73.1,0.236,1.922,0.145,1.888,1.297
18,Amadou Onana,a,0,MID,Aston Villa,1056.4,21.62,84.4,0.205,1.000,0.073,1.000,1.402
19,Dominik Szoboszlai,a,1,MID,Liverpool,1094.1,21.37,85.5,0.156,1.000,0.136,1.000,1.485
20,Lucas Digne,a,0,DEF,Aston Villa,1056.4,21.36,66.6,0.092,1.000,0.289,2.217,1.447
21,Cristhian Mosquera,a,0,DEF,Arsenal,1005.9,21.33,65.1,0.045,1.000,0.034,1.000,0.968
22,Conor Gallagher,a,0,MID,Spurs,1047.0,21.25,65.5,0.292,2.507,0.214,3.352,1.662
23,Habib Diarra,a,0,MID,Sunderland,1045.7,20.86,85.4,0.150,1.000,0.123,1.000,1.388
24,Riccardo Calafiori,d,0,DEF,Arsenal,1005.9,20.63,49.3,0.104,1.000,0.094,1.000,0.972
25,Mason Mount,a,0,MID,Man Utd,1080.1,20.53,25.3,0.990,3.906,0.736,5.301,2.020
26,Tomáš Souček,a,0,MID,West Ham,1087.5,20.43,84.0,0.189,1.000,0.063,1.000,1.532
27,Myles Lewis-Skelly,a,0,DEF,Arsenal,1005.9,20.20,61.5,0.052,1.000,0.031,1.000,1.022
28,El Hadji Malick Diouf,a,0,DEF,West Ham,1087.5,20.12,85.4,0.051,1.000,0.150,2.255,1.486
29,Brian Brobbey,a,1,FWD,Sunderland,1045.7,20.08,82.5,0.369,1.000,0.041,1.000,1.336
30,Noni Madueke,a,0,MID,Arsenal,1005.9,20.08,59.5,0.258,1.000,0.096,1.000,0.851
31,Reece James,d,0,DEF,Chelsea,1047.3,20.05,60.3,0.211,4.135,0.575,2.957,1.445
32,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1087.5,19.98,85.0,0.123,1.000,0.102,1.000,1.513
33,Pau Torres,a,0,DEF,Aston Villa,1056.4,19.97,85.1,0.054,1.000,0.028,1.000,1.349
34,James Ward-Prowse,a,0,MID,Burnley,1076.3,19.71,76.1,0.360,2.532,0.217,1.778,1.999
35,Andrew Robertson,a,0,DEF,Liverpool,1094.1,19.71,74.5,0.048,1.000,0.182,1.986,1.472
36,Nathan Patterson,a,0,DEF,Everton,1058.7,19.57,49.4,0.236,1.000,0.398,1.000,1.600
37,Mats Wieffer,a,0,MID,Brighton,1025.4,19.51,84.5,0.144,1.000,0.369,2.463,1.304
38,Emiliano Martínez Romero,a,1,GK,Aston Villa,1056.4,19.42,89.7,NaN,1.000,NaN,1.000,1.267
39,Séamus Coleman,a,0,DEF,Everton,1058.7,19.29,51.8,0.366,1.000,0.037,1.000,1.596
40,Idrissa Gana Gueye,a,0,MID,Everton,1058.7,19.28,81.5,0.099,1.000,0.090,1.000,1.384
41,Jacob Ramsey,a,0,MID,Newcastle,1079.1,19.20,62.5,0.228,1.708,0.175,2.029,1.622
42,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1047.0,19.01,84.9,0.302,1.000,0.044,1.000,1.437
43,Jake O'Brien,a,0,DEF,Everton,1058.7,18.85,85.2,0.044,1.000,0.046,1.000,1.411
44,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1080.1,18.84,80.6,0.042,1.000,0.112,1.861,1.479
45,Vitalii Mykolenko,a,0,DEF,Everton,1058.7,18.80,86.0,0.044,1.000,0.039,1.000,1.413
46,Marco Bizot,a,0,GK,Aston Villa,1056.4,18.77,89.7,NaN,1.000,NaN,1.000,1.490
47,Lewis Miley,a,0,MID,Newcastle,1079.1,18.76,78.6,0.129,1.000,0.079,1.000,1.565
48,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1079.1,18.76,73.1,0.361,1.000,0.063,1.000,1.399
49,Ibrahima Konaté,a,0,DEF,Liverpool,1094.1,18.76,86.1,0.046,1.000,0.042,1.000,1.466

In [9]:
print(f"\nBest available players to replace worst in my team: {picks_current_gameweek+1} to {picks_current_gameweek+5}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xap90_pred,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    ),

    summed AS (
        SELECT 
            player_name_id,
            team_name,
                          status,
            position,
            latest_my_team,
            latest_any_team,
            SUM(xpoints) AS total_xpoints
        FROM predictions_status
        WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
          AND status IN ('a', 'd')
        GROUP BY player_name_id, team_name, status, position, latest_my_team, latest_any_team
    ),

    worst_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'GK'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_gk AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'GK'
    ),

    worst_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'DEF'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_def AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'DEF'
    ),

    worst_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'MID'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_mid AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'MID'
    ),

    worst_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_my_team = 1
          AND position = 'FWD'
        ORDER BY total_xpoints ASC
        LIMIT 1
    ),
    best_fwd AS (
        SELECT player_name_id, team_name, status, total_xpoints AS xpoints, latest_my_team, position
        FROM summed
        WHERE latest_any_team = 0
          AND latest_my_team = 0
          AND position = 'FWD'
    )

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_gk b CROSS JOIN worst_gk w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_def b CROSS JOIN worst_def w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status, 
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_mid b CROSS JOIN worst_mid w

    UNION ALL

    SELECT 
        b.position,
        b.team_name AS best_team,
        b.status AS status,
        b.player_name_id AS best_player_id,
        b.xpoints AS best_xpoints,
        w.player_name_id AS worst_player_id,
        w.xpoints AS worst_xpoints,
        (b.xpoints - w.xpoints) AS xpoints_diff
    FROM best_fwd b CROSS JOIN worst_fwd w
    ORDER BY xpoints_diff DESC
""")
view.head(20)

Best available players to replace worst in my team: 34 to 38

,position,best_team,status,best_player_id,best_xpoints,worst_player_id,worst_xpoints,xpoints_diff
0,MID,Newcastle,a,Harvey Barnes,27.191660,Bruno Guimarães Rodriguez Moura,16.971313,10.220347
1,DEF,Man City,a,John Stones,25.533462,Jan Paul van Hecke,16.340613,9.192848
2,MID,Brentford,a,Mathias Jensen,25.803150,Bruno Guimarães Rodriguez Moura,16.971313,8.831837
3,MID,Arsenal,a,Eberechi Eze,25.139946,Bruno Guimarães Rodriguez Moura,16.971313,8.168633
4,MID,Aston Villa,a,Youri Tielemans,24.320217,Bruno Guimarães Rodriguez Moura,16.971313,7.348904
5,MID,Man City,a,Bernardo Mota Veiga de Carvalho e Silva,24.231523,Bruno Guimarães Rodriguez Moura,16.971313,7.260210
6,MID,Nott'm Forest,d,Callum Hudson-Odoi,23.641909,Bruno Guimarães Rodriguez Moura,16.971313,6.670596
7,MID,Everton,a,Dwight McNeil,23.579890,Bruno Guimarães Rodriguez Moura,16.971313,6.608577
8,MID,Arsenal,a,Leandro Trossard,23.434079,Bruno Guimarães Rodriguez Moura,16.971313,6.462766
9,MID,Aston Villa,a,John McGinn,23.249502,Bruno Guimarães Rodriguez Moura,16.971313,6.278189
10,DEF,Arsenal,a,Benjamin White,21.899713,Jan Paul van Hecke,16.340613,5.559099
11,DEF,Aston Villa,a,Lucas Digne,21.361522,Jan Paul van Hecke,16.340613,5.020909
12,DEF,Arsenal,a,Cristhian Mosquera,21.329682,Jan Paul van Hecke,16.340613,4.989068
13,MID,Sunderland,a,Granit Xhaka,21.872636,Bruno Guimarães Rodriguez Moura,16.971313,4.901323
14,MID,Brentford,a,Kevin Schade,21.846764,Bruno Guimarães Rodriguez Moura,16.971313,4.875451
15,MID,Aston Villa,a,Ross Barkley,21.644982,Bruno Guimarães Rodriguez Moura,16.971313,4.673669
16,MID,Aston Villa,a,Amadou Onana,21.622792,Bruno Guimarães Rodriguez Moura,16.971313,4.651479
17,DEF,Arsenal,d,Riccardo Calafiori,20.626960,Jan Paul van Hecke,16.340613,4.286347
18,MID,Spurs,a,Conor Gallagher,21.246166,Bruno Guimarães Rodriguez Moura,16.971313,4.274853
19,FWD,Spurs,a,Dominic Solanke-Mitchell,19.008362,Alexander Isak,15.059352,3.949010

In [10]:
print(f"\n Player xPoints between {picks_current_gameweek+1} and {picks_current_gameweek+5}:")
view = db_creator.run_sql(f"""
    SELECT
        player_name_id,
        event,
        position,
        team_name,
        opp_team_name,
        value/10 as value,
        opp_team_elo,
        xpoints,
        mins_pred,
        xgp90_pred,
        xap90_pred,
        xgcp90_pred
    FROM predictions
    WHERE event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
        AND player_name_id = 'Erling Haaland'
        -- AND value <= 48
    ORDER BY event ASC
""")
view.head(20)

 Player xPoints between 34 and 38:

,player_name_id,event,position,team_name,opp_team_name,value,opp_team_elo,xpoints,mins_pred,xgp90_pred,xap90_pred,xgcp90_pred
0,Erling Haaland,35.0,FWD,Man City,Everton,14.5,1067.473132,4.836949,86.220221,0.440414,0.171741,1.065977
1,Erling Haaland,36.0,FWD,Man City,Brentford,14.5,1072.620018,4.875217,86.220221,0.450400,0.171741,1.094076
2,Erling Haaland,37.0,FWD,Man City,Bournemouth,14.5,1092.690932,4.945996,86.220221,0.468911,0.172158,1.258062
3,Erling Haaland,38.0,FWD,Man City,Aston Villa,14.5,1136.729368,4.933701,85.400221,0.472060,0.179560,1.326526

In [20]:
print(f"Best players for next 5 gameweeks with exponential decay (normalized): GW{picks_current_gameweek+1} to GW{picks_current_gameweek+5}")

# For weights to sum to 1 with decay_factor d and initial weight w:
# w * (1 + d + d^2 + d^3 + d^4) = 1
# So w = 1 / (1 + d + d^2 + d^3 + d^4)

decay_factor = 0.75 #  lower decay factor means more emphasis on nearer gws, 1 is equal weights.
weights = [decay_factor**i for i in range(5)]
weight_sum = sum(weights)
initial_weight = 1 / weight_sum # weights add to 1
print(f"Decay factor: {decay_factor}, Weights: {[round((w/weight_sum),2) for w in weights]}")

view = db_creator.run_sql(f"""
    WITH 
    predictions_status AS (
        SELECT 
            p.player_name_id,
            p.element,
            ps.status,
            p.latest_my_team,
            p.position,
            p.team_name,
            p.opp_team_elo,
            p.xpoints,
            p.mins_pred,
            p.xgp90_pred,
            p.xg_overperf_factor,
            p.xap90_pred,
            p.xa_overperf_factor,
            p.xgcp90_pred,
            p.event,
            p.latest_any_team
        FROM predictions p
        LEFT JOIN player_status ps ON p.element = ps.id
    )
                                         
    SELECT
        player_name_id,
        status,
        latest_my_team,
        position,
        team_name,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN opp_team_elo * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN opp_team_elo * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN opp_team_elo * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN opp_team_elo * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN opp_team_elo * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 1) AS avg_elo_decayed,
        ROUND(SUM(
            CASE 
                WHEN event = {picks_current_gameweek+1} THEN xpoints * {initial_weight}
                WHEN event = {picks_current_gameweek+2} THEN xpoints * {initial_weight * decay_factor}
                WHEN event = {picks_current_gameweek+3} THEN xpoints * {initial_weight * decay_factor**2}
                WHEN event = {picks_current_gameweek+4} THEN xpoints * {initial_weight * decay_factor**3}
                WHEN event = {picks_current_gameweek+5} THEN xpoints * {initial_weight * decay_factor**4}
                ELSE 0
            END
        ), 2) AS total_xpoints_decayed,
        ROUND(AVG(mins_pred),1) AS avg_mins_pred,
        ROUND(AVG(xgp90_pred),3) AS avg_xgp90_pred,
        ROUND(AVG(xg_overperf_factor),3) AS avg_xg_overperf_factor,
        ROUND(AVG(xap90_pred),3) AS avg_xap90_pred,
        ROUND(AVG(xa_overperf_factor),3) AS avg_xa_overperf_factor,
        ROUND(AVG(xgcp90_pred),3) AS avg_xgcp90_pred
    FROM predictions_status
    WHERE (latest_any_team = 0 OR latest_my_team = 1)
      AND event BETWEEN {picks_current_gameweek+1} AND {picks_current_gameweek+5}
      AND status IN ('a','d')
      -- AND position = 'MID'
    GROUP BY player_name_id, status, position, team_name, latest_my_team
    ORDER BY total_xpoints_decayed DESC
""")
view.head(50)

Best players for next 5 gameweeks with exponential decay (normalized): GW34 to GW38
Decay factor: 0.75, Weights: [0.33, 0.25, 0.18, 0.14, 0.1]

,player_name_id,status,latest_my_team,position,team_name,avg_elo_decayed,total_xpoints_decayed,avg_mins_pred,avg_xgp90_pred,avg_xg_overperf_factor,avg_xap90_pred,avg_xa_overperf_factor,avg_xgcp90_pred
0,Harvey Barnes,a,0,MID,Newcastle,1108.8,5.35,61.8,0.635,1.988,0.316,2.467,1.693
1,Gabriel dos Santos Magalhães,a,1,DEF,Arsenal,1017.6,5.17,83.8,0.093,1.000,0.113,1.000,0.924
2,Mathias Jensen,a,0,MID,Brentford,1105.2,5.16,85.1,0.323,1.911,0.180,1.000,1.543
3,Morgan Gibbs-White,a,1,MID,Nott'm Forest,1072.1,5.06,83.2,0.229,1.000,0.338,1.986,1.530
4,Eberechi Eze,a,0,MID,Arsenal,1017.6,4.99,63.2,0.355,1.353,0.350,1.972,0.851
5,Youri Tielemans,a,0,MID,Aston Villa,1027.9,4.91,71.0,0.281,2.733,0.329,2.302,1.323
6,Bruno Borges Fernandes,a,1,MID,Man Utd,1085.7,4.87,83.3,0.220,1.000,0.260,1.334,1.432
7,Callum Hudson-Odoi,d,0,MID,Nott'm Forest,1072.1,4.74,72.7,0.352,2.189,0.157,1.948,1.514
8,Dwight McNeil,a,0,MID,Everton,1070.6,4.70,73.9,0.289,1.781,0.215,1.645,1.343
9,John McGinn,a,0,MID,Aston Villa,1027.9,4.67,73.2,0.204,1.000,0.330,2.046,1.247
10,Leandro Trossard,a,0,MID,Arsenal,1017.6,4.65,44.6,0.551,1.982,0.450,2.533,0.819
11,Granit Xhaka,a,0,MID,Sunderland,1031.0,4.40,75.3,0.203,2.320,0.215,3.169,1.412
12,Lucas Digne,a,0,DEF,Aston Villa,1027.9,4.40,66.6,0.092,1.000,0.289,2.217,1.447
13,Kevin Schade,a,0,MID,Brentford,1105.2,4.38,76.8,0.226,1.000,0.176,2.065,1.529
14,Ross Barkley,a,0,MID,Aston Villa,1027.9,4.37,73.1,0.236,1.922,0.145,1.888,1.297
15,Amadou Onana,a,0,MID,Aston Villa,1027.9,4.36,84.4,0.205,1.000,0.073,1.000,1.402
16,Benjamin White,a,0,DEF,Arsenal,1017.6,4.33,68.0,0.051,1.000,0.078,1.000,1.025
17,David Raya Martín,a,1,GK,Arsenal,1017.6,4.32,89.8,NaN,1.000,NaN,1.000,0.819
18,John Stones,a,0,DEF,Man City,729.2,4.31,54.8,0.974,3.577,0.040,1.000,1.593
19,Dominik Szoboszlai,a,1,MID,Liverpool,1089.4,4.29,85.5,0.156,1.000,0.136,1.000,1.485
20,Conor Gallagher,a,0,MID,Spurs,1031.7,4.29,65.5,0.292,2.507,0.214,3.352,1.662
21,Cristhian Mosquera,a,0,DEF,Arsenal,1017.6,4.23,65.1,0.045,1.000,0.034,1.000,0.968
22,Habib Diarra,a,0,MID,Sunderland,1031.0,4.19,85.4,0.150,1.000,0.123,1.000,1.388
23,El Hadji Malick Diouf,a,0,DEF,West Ham,1091.7,4.11,85.4,0.051,1.000,0.150,2.255,1.486
24,Bernardo Mota Veiga de Carvalho e Silva,a,0,MID,Man City,729.2,4.11,81.9,0.151,1.000,0.781,4.780,1.194
25,Riccardo Calafiori,d,0,DEF,Arsenal,1017.6,4.11,49.3,0.104,1.000,0.094,1.000,0.972
26,Mason Mount,a,0,MID,Man Utd,1085.7,4.10,25.3,0.990,3.906,0.736,5.301,2.020
27,Pau Torres,a,0,DEF,Aston Villa,1027.9,4.09,85.1,0.054,1.000,0.028,1.000,1.349
28,Tomáš Souček,a,0,MID,West Ham,1091.7,4.08,84.0,0.189,1.000,0.063,1.000,1.532
29,Myles Lewis-Skelly,a,0,DEF,Arsenal,1017.6,4.02,61.5,0.052,1.000,0.031,1.000,1.022
30,Andrew Robertson,a,0,DEF,Liverpool,1089.4,4.01,74.5,0.048,1.000,0.182,1.986,1.472
31,Brian Brobbey,a,1,FWD,Sunderland,1031.0,4.01,82.5,0.369,1.000,0.041,1.000,1.336
32,Noni Madueke,a,0,MID,Arsenal,1017.6,3.99,59.5,0.258,1.000,0.096,1.000,0.851
33,Mateus Gonçalo Espanha Fernandes,a,0,MID,West Ham,1091.7,3.99,85.0,0.123,1.000,0.102,1.000,1.513
34,Nathan Patterson,a,0,DEF,Everton,1070.6,3.96,49.4,0.236,1.000,0.398,1.000,1.600
35,Emiliano Martínez Romero,a,1,GK,Aston Villa,1027.9,3.93,89.7,NaN,1.000,NaN,1.000,1.267
36,Séamus Coleman,a,0,DEF,Everton,1070.6,3.88,51.8,0.366,1.000,0.037,1.000,1.596
37,Tyrone Mings,a,1,DEF,Aston Villa,1027.9,3.85,77.0,0.050,1.000,0.047,1.000,1.468
38,Idrissa Gana Gueye,a,0,MID,Everton,1070.6,3.84,81.5,0.099,1.000,0.090,1.000,1.384
39,Ibrahima Konaté,a,0,DEF,Liverpool,1089.4,3.81,86.1,0.046,1.000,0.042,1.000,1.466
40,Victor Lindelöf,a,0,DEF,Aston Villa,1027.9,3.80,66.2,0.077,1.000,0.054,1.000,1.407
41,Marco Bizot,a,0,GK,Aston Villa,1027.9,3.79,89.7,NaN,1.000,NaN,1.000,1.490
42,Dominic Solanke-Mitchell,a,0,FWD,Spurs,1031.7,3.79,84.9,0.302,1.000,0.044,1.000,1.437
43,Jacob Ramsey,a,0,MID,Newcastle,1108.8,3.79,62.5,0.228,1.708,0.175,2.029,1.622
44,Konstantinos Mavropanos,a,0,DEF,West Ham,1091.7,3.78,80.7,0.098,1.000,0.047,1.000,1.606
45,Jake O'Brien,a,0,DEF,Everton,1070.6,3.78,85.2,0.044,1.000,0.046,1.000,1.411
46,Vitalii Mykolenko,a,0,DEF,Everton,1070.6,3.77,86.0,0.044,1.000,0.039,1.000,1.413
47,Igor Jesus Maciel da Cruz,a,0,FWD,Nott'm Forest,1072.1,3.75,73.1,0.361,1.000,0.063,1.000,1.399
48,Michael Keane,a,0,DEF,Everton,1070.6,3.74,65.8,0.168,2.912,0.037,1.000,1.618
49,Diogo Dalot Teixeira,a,0,DEF,Man Utd,1085.7,3.74,80.6,0.042,1.000,0.112,1.861,1.479

In [12]:
# #Gt member player codes from the latest GW
# query = """
#         WITH
#         currentgw AS (
#             SELECT MAX(gw) as max_gw
#             FROM playergw)
#         SELECT *
#         FROM playergw
#         WHERE gw = currentgw
#         ;
#         """
# with fpl_engine.connect() as conn:
#     viewdf = pd.read_sql_query(query, conn)
# print(viewdf.shape)

In [13]:
# #Query gets only player details from the latest GW
# query = """
#         ALTER TABLE player_details
#             RENAME COLUMN total_points TO total_points_gw;

#         WITH playergw AS (
#             SELECT *,
#             ROW_NUMBER() OVER(
#                     PARTITION BY
#                         season,
#                         code,
#                         event,
#                         fixture_id --Only one record per GW
#                     ORDER BY 
#                         now_datetime_utc DESC) as rn --Only select the latest date
#         FROM playergw
#         ),
#         currentgw AS (
#             SELECT MAX(current_gw) as max_gw
#             FROM playergw
#         )
        
#         SELECT *
#         FROM player_details
#         LEFT JOIN playergw
#             ON player_details.element = playergw.id
#             AND player_details.round = playergw.current_gw
#         CROSS JOIN currentgw
#         WHERE player_details.round = currentgw.max_gw
#             AND playergw.rn = 1    
#         ;
#         """
# with engine.connect() as conn:
#     playerdf = pd.read_sql_query(query, conn)
# print(playerdf.shape)

# pd.pivot_table(playerdf, index=['id','web_name','team_name','round'],values='total_points_gw',aggfunc=np.sum).sort_values(by='total_points_gw', ascending=False)

# Chip Decisions

### Triple Captain

In [14]:
# print("When to use second TRIPLE CAPTAIN chip (gws19-38)")
# view = db_creator.run_sql(f"""
#     SELECT
#         player_name_id,
#         event,
#         position,
#         team_name,
#         opp_team_name,
#         xpoints
#     FROM predictions
#     WHERE in_my_team = 1
#       AND event BETWEEN {picks_current_gameweek} AND 38
#     ORDER BY xpoints DESC
# """)
# view.head(10)

### Bench Boost

In [15]:
remaining_gw_predictions = db_creator.run_sql(f"""
    
    WITH predictions_status AS (
    SELECT *
    FROM predictions
    LEFT JOIN player_status ON predictions.element = player_status.id
    )
    SELECT
        web_name,
        status,
        now_cost/10 as value,
        chance_of_playing_this_round,
        event,
        position,
        team_name,
        opp_team_name,
        xpoints,
        ROUND(mins_pred) as mins_pred
    FROM predictions_status
    WHERE latest_my_team = 1
        AND event BETWEEN {picks_current_gameweek+1} AND 38
""")

In [16]:
from FPL_Optimizer import FPLOptimizer
print(f"\nOptimizing team selection for GW{picks_current_gameweek+1} to GW38...")

if __name__ == "__main__":
    custom_columns = {
        'player_name': 'web_name',
        'team_name': 'team_name',
        'position': 'position',
        'value': 'value',
        'xpoints': 'xpoints'
    }
    all_results =[]
    for event in range(picks_current_gameweek+1, 39):
        print(f"\nOptimizing team selection for GW{event}...")
        try:
            optimizer = FPLOptimizer(
                df=remaining_gw_predictions[remaining_gw_predictions['event']==event],
                budget=102.4,
                column_mapping=custom_columns
            )
            optimizer.optimize()
        
            # Get results as DataFrames
            # squad = optimizer.get_squad_dataframe()
            # starting_xi = optimizer.get_starting_xi_dataframe()
            result = optimizer.calculate_bench_boost_xpoints()
            result['event'] = event
            # Append just the relevant keys as a dict
            all_results.append({
                'event': result['event'],
                'bench_boost_gain': result['bench_boost_gain']
            })
        except Exception as e:
            print(f"Error optimizing for GW{event}: {e}")

Optimizing team selection for GW34 to GW38...

Optimizing team selection for GW34...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

Optimization Status: Infeasible
No valid 15-player squad found within constraints.
Error optimizing for GW34: No optimization has been run yet. Call optimize() first.

Optimizing team selection for GW35...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 49.21
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Raya                           Arsenal      £6.0     4.20
 ✅        Martinez                       Aston Villa  £5.1     4.40

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mings                          Aston Villa  £4.3     4.33
 ✅        Gabriel                        Arsenal      £7.1     4.87
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.78
 ✅        Van Hecke                      Brighton     £4.6     3.80
 ✅        Matheus N.                     Man City     £5.3     4.62

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mac Allister                   Liverpool    £6.3     3.56
 🪑        Bruno G.                       Newcastle    £6.8     3.41
 ✅        B.Fernandes                    Man Utd      £10.3    4.74
 ✅        Szoboszlai                     Liverpool    £7.1     4.26
 ✅        Gibbs-White                    Nott'm Forest £7.5     5.02

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    2.97
 ✅        Brobbey                        Sunderland   £5.3     4.06
 ✅        Flemming                       Burnley      £5.3     3.91

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW36...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 5-3-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 52.60
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     4.58
 ✅        Raya                           Arsenal      £6.0     4.76

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 ✅        Mings                          Aston Villa  £4.3     4.94
 ✅        Gabriel                        Arsenal      £7.1     5.83
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.49
 ✅        Van Hecke                      Brighton     £4.6     4.48
 ✅        Matheus N.                     Man City     £5.3     4.59

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mac Allister                   Liverpool    £6.3     3.61
 🪑        Bruno G.                       Newcastle    £6.8     3.45
 ✅        Szoboszlai                     Liverpool    £7.1     4.29
 ✅        Gibbs-White                    Nott'm Forest £7.5     4.98
 ✅        B.Fernandes                    Man Utd      £10.3    4.92

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.02
 ✅        Brobbey                        Sunderland   £5.3     3.93
 ✅        Flemming                       Burnley      £5.3     3.90

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW37...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 51.16
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.38
 ✅        Raya                           Arsenal      £6.0     4.69

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     2.96
 ✅        Gabriel                        Arsenal      £7.1     6.30
 ✅        F.Kadıoğlu                     Brighton     £4.4     4.30
 ✅        Van Hecke                      Brighton     £4.6     4.31
 ✅        Matheus N.                     Man City     £5.3     4.50

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.43
 ✅        Szoboszlai                     Liverpool    £7.1     4.15
 ✅        Gibbs-White                    Nott'm Forest £7.5     5.16
 ✅        Mac Allister                   Liverpool    £6.3     3.49
 ✅        B.Fernandes                    Man Utd      £10.3    5.16

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.02
 ✅        Brobbey                        Sunderland   £5.3     3.99
 ✅        Flemming                       Burnley      £5.3     3.82

================================================================================
Optimization Status: Optimal

Optimizing team selection for GW38...
================================================================================
FPL TEAM OPTIMIZER (Linear Programming)
================================================================================

Budget for 15-Player Squad: £102.4m

Solving optimization problem...

================================================================================
OPTIMAL 15-PLAYER SQUAD
================================================================================
Starting XI Formation: 4-4-2
Total Squad Cost: £95.7m / £102.4m
Total Weighted Expected Points: 48.00
Remaining Budget: £6.7m

--------------------------------GOALKEEPERS (2)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Martinez                       Aston Villa  £5.1     3.46
 ✅        Raya                           Arsenal      £6.0     4.06

---------------------------------DEFENDERS (5)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Mings                          Aston Villa  £4.3     2.79
 ✅        Gabriel                        Arsenal      £7.1     4.47
 ✅        F.Kadıoğlu                     Brighton     £4.4     3.81
 ✅        Van Hecke                      Brighton     £4.6     3.76
 ✅        Matheus N.                     Man City     £5.3     4.29

--------------------------------MIDFIELDERS (5)---------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Bruno G.                       Newcastle    £6.8     3.45
 ✅        Mac Allister                   Liverpool    £6.3     3.58
 ✅        Gibbs-White                    Nott'm Forest £7.5     5.30
 ✅        B.Fernandes                    Man Utd      £10.3    5.01
 ✅        Szoboszlai                     Liverpool    £7.1     4.30

----------------------------------FORWARDS (3)----------------------------------
 Starter  Player Name                    Team         Cost     xPts
--------------------------------------------------------------------------------
 🪑        Isak                           Liverpool    £10.3    3.02
 ✅        Brobbey                        Sunderland   £5.3     4.13
 ✅        Flemming                       Burnley      £5.3     4.01

================================================================================
Optimization Status: Optimal

In [17]:
print("Best weeks to Bench Boost:")
all_results_df = pd.DataFrame(all_results).sort_values(by='bench_boost_gain', ascending=False, inplace=False)
all_results_df

Best weeks to Bench Boost:

   event  bench_boost_gain
1     36         13.194832
0     35         12.729564
2     37         11.517134
3     38         11.443050

In [18]:
finish=time.perf_counter()
print(f'Finished in {round(((finish-start)/60),2)} minute(s)')
# Finished in 0.01 minute(s)

Finished in 0.03 minute(s)